Universal server idle timeout
applitools/eyes.sdk.javascript1 pull request #1011
Opened 2022-07-08 22:44 UTC by SophieDePaula

[Trello card](https://trello.com/c/1KtpPXqD/1442-infogrid-cypress-universal-server-idle-timeout)

2022-07-11 05:25 UTC, kyryloonufriiev requested changes

2022-07-11 05:25 UTC, kyryloonufriiev commented on js/packages/eyes-universal/src/universal-server.ts
> +  detached?: boolean
It shouldn't be here because you never use it here. This is clearly an option of `makeServerProcess`.

2022-07-11 05:25 UTC, kyryloonufriiev commented on js/packages/eyes-universal/src/universal-server-process.ts
>  export function makeServerProcess(options: ServerOptions): Promise<{port: number; close: () => void}> {
```suggestion
export function makeServerProcess(options: ServerOptions & {detached?: boolean}): Promise<{port: number; close: () => void}> {
```

2022-07-11 05:25 UTC, kyryloonufriiev commented on js/packages/eyes-universal/src/universal-server.ts
> +    }
You don't have to even set the timeout if it is 0

2022-07-11 23:21 UTC, SophieDePaula commented on js/packages/eyes-universal/src/universal-server.ts
> +    }
@kyryloonufriiev I thought this is cleaner than to ask everywhere if timeout > 0 call `clearTimeout`.

2022-07-12 09:29 UTC, kyryloonufriiev commented on js/packages/eyes-universal/src/universal-server.ts
> +    }
You will have two if statements the same as you have now, but you will not call `setTimeout` when you don't care about it.

2022-07-12 16:22 UTC, SophieDePaula commented on js/packages/eyes-universal/src/universal-server.ts
> +  }
@kyryloonufriiev fyi

2022-07-13 04:32 UTC, kyryloonufriiev approved these changes

2022-07-13 21:52 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Close the universal server when cypress process is finished
@benbabayoff8

2022-07-14 15:53 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Close the universal server when cypress process is finished
@SophieDePaula The user shouldn't care that we have a "Universal Server". 
I would consider it as a bug fix and write something like: "Internal architecture fixes".
@amitzur @kyryloonufriiev What do you think?

2022-07-15 16:29 UTC, merged