support adding 'userTestId' to eyes.open config
applitools/eyes.sdk.javascript1 pull request #1024
Opened 2022-07-19 11:59 UTC by chaim-aharonson-applitools

2022-07-19 12:39 UTC, chaim-aharonson-applitools commented
change-log already approved by Ben

2022-07-19 12:59 UTC, kyryloonufriiev commented
@chaim-aharonson-applitools What about classic eyes? We should have it there as well.

2022-07-19 14:43 UTC, chaim-aharonson-applitools commented
> @chaim-aharonson-applitools What about classic eyes? We should have it there as well.

Ben said we don't have to support it there

2022-07-20 07:01 UTC, kyryloonufriiev commented
I think we should we have to be consistent. Please add this feature to classic as well.

2022-07-20 08:15 UTC, chaim-aharonson-applitools commented
> I think we should we have to be consistent. Please add this feature to classic as well.

done. also fixed the 'types' package.json

2022-07-20 09:15 UTC, kyryloonufriiev requested changes
I don't see two important tests, userTestId being added in the TestResults object. And `userTestId` being added in TestResultsContainer object.

2022-07-20 09:15 UTC, kyryloonufriiev commented on js/packages/types/package.json
> +    "@applitools/scripts": "1.1.0"
Please put it in devDeps

2022-07-20 12:18 UTC, skhalymon commented on js/packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +    if (!this._configuration.getUserTestId()) {
If a single Eyes instance would be used for multiple `eyes.open/close` on the first step, we set `usertTestId` and on the second call of `eyes.open` it will use previous  `usertTestId` value.

2022-07-20 15:15 UTC, chaim-aharonson-applitools commented on js/packages/types/package.json
> +    "@applitools/scripts": "1.1.0"
done

2022-07-21 04:16 UTC, kyryloonufriiev approved these changes
@chaim-aharonson-applitools Looks good to me:) Sorry for the confusion around this feature.

2022-07-21 06:21 UTC, merged