Cypress region id elements
applitools/eyes.sdk.javascript1 pull request #1045
Opened 2022-07-24 14:07 UTC by SophieDePaula

2022-07-24 18:00 UTC, kyryloonufriiev commented on .github/workflows/test.yml
> -          Xvfb -ac $DISPLAY -screen 0 1280x1024x16 &
What is wrong with that?

2022-07-25 06:24 UTC, SophieDePaula commented on .github/workflows/test.yml
> -          Xvfb -ac $DISPLAY -screen 0 1280x1024x16 &
@kyryloonufriiev when I run the `test` workflow, I see this error message: ` [2571:0724/141402.139934:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY`. I thought removing this line will help, but it didn't so I'll undo this

2022-07-25 06:45 UTC, kyryloonufriiev commented on js/packages/eyes-cypress/src/browser/eyesCheckMapping.js
> +      if (region.element || isHTMLElement(region) || region.jquery) {
what `region.jquery` means?

2022-07-25 06:49 UTC, kyryloonufriiev approved these changes

2022-07-25 06:54 UTC, kyryloonufriiev requested changes

2022-07-25 06:54 UTC, kyryloonufriiev commented on js/packages/eyes-cypress/src/browser/eyesCheckMapping.js
> +          }
`regionId` and `padding` could be specified todether.

2022-07-25 07:02 UTC, SophieDePaula commented
@kyryloonufriiev I added some changes, so please have a look and if it's all good I'll merge it.

2022-07-25 07:04 UTC, kyryloonufriiev commented
@SophieDePaula ☝🏼 Do you see the comment I left before?

2022-07-25 07:20 UTC, SophieDePaula commented
> @SophieDePaula ☝🏼 Do you see the comment I left before?
@kyryloonufriiev I see my last commit, thanks.

2022-07-25 10:43 UTC, kyryloonufriiev commented on js/packages/eyes-cypress/src/browser/eyesCheckMapping.js
> +            }
```suggestion
            if (region.padding) {
              curr.padding = region.padding;
            }
            if (region.regionId) {
              curr.regionId = region.regionId;
            }
```

2022-07-25 10:43 UTC, kyryloonufriiev approved these changes

2022-07-25 10:50 UTC, merged