[universal] Remove settings update
applitools/eyes.sdk.javascript1 pull request #1048
Opened 2022-07-25 14:54 UTC by kyryloonufriiev

2022-07-25 16:55 UTC, tourdedave requested changes
@kyryloonufriiev This came up during release testing for the NMG. It was a necessary fix to overcome cases where the SDK would fail to locate the necessary elements to perform VHS extraction. I was asked to make it so the server handled it implicitly (rather than have the customer specify the capability to set it). To remove it, we would require testing from @Yarden-Ingber's team to verify we don't introduce any regressions.

So the action item here, is to have a broader discussion.

2022-07-25 16:56 UTC, tourdedave commented on js/packages/eyes-universal/package.json
> +    "setup": "yarn docker:setup",
IIRC, having `setup` like this causes issues in the build/test pipeline

2022-07-26 12:42 UTC, kyryloonufriiev commented on js/packages/eyes-universal/package.json
> +    "setup": "yarn docker:setup",
Without it doesn't work at all. I had added the mocha hook to the relevant test to wait for docker to start.

2022-07-26 13:13 UTC, tourdedave commented
We'll also need to document (somewhere, for the field at least) what the capability is for the user to set this since it's an obscure appium specific capability. It's `'settings[allowInvisibleElements]': true`

2022-07-26 16:27 UTC, kyryloonufriiev commented
@tourdedave Customer also can update settings in runtime as we do it - https://appium.io/docs/en/advanced-concepts/settings/

2022-07-27 13:03 UTC, tourdedave commented
One other thought I had was to present a helpful error to users when they reach a situation where they need to change this setting (e.g., when running with NMG on Android and the SDK is unable to find the necessary element). The error message should contain details about how to set the setting (or a link to some sort of documentation about it). What do you think?

2022-07-27 14:10 UTC, kyryloonufriiev commented
The thing is that we don't know if they don't have our library at all, or if they have it but we are just not able to find it due to this issue. 
Of course, we could include both, I think it would be great and very helpful.

2022-08-23 14:37 UTC, tourdedave commented
Per [Trello](https://trello.com/c/9L9JC09L/1495-biogen-appium-universal-allowinvisibleelements-breaks-xpath#comment-62fa2de20e0f0067571d5f53), merging/releasing.

2022-08-23 14:37 UTC, merged