add robotframework sdk to the list of supported sdks
applitools/eyes.sdk.javascript1 pull request #1052
Opened 2022-07-27 14:44 UTC by Artem-applitools

2022-07-27 14:46 UTC, kyryloonufriiev approved these changes
LGTM

2022-07-27 15:29 UTC, kyryloonufriiev requested changes

2022-07-27 15:29 UTC, kyryloonufriiev commented on pending-changes.yaml
> +    -
@Artem-applitools Please remove it. There is no need for a changelog for something else than SDK. This is an internal tooling package so we don't maintain changelog for them

2022-07-28 08:37 UTC, Artem-applitools commented on pending-changes.yaml
> +    -
@kyryloonufriiev Removed

2022-07-28 10:01 UTC, Artem-applitools commented
@kyryloonufriiev Pls merge the PR when you will be publishing new package version

2022-07-28 12:54 UTC, merged