add hover tests
applitools/eyes.sdk.javascript1 pull request #1057
Opened 2022-08-02 15:12 UTC by zamboney

Add test to cover `hover` for `web`

## on the way add more stuff:
- Add ignored files to `.gitignore`
- Add explain on where the images save once tests fails

2022-08-02 15:23 UTC, kyryloonufriiev requested changes

2022-08-02 15:23 UTC, kyryloonufriiev commented on .gitignore
> +node_modules
I'm not sure I understand why we need it here.

2022-08-02 15:23 UTC, kyryloonufriiev commented on js/packages/screenshoter/test/e2e/e2e.js
> +      pixelmatch(actual.data, expected.data, null, expected.width, expected.height),
I love the message. But sometimes it is important to know the reason why it failed. There might be different image sizes or pixel differences. Can you include this information?

2022-08-02 15:23 UTC, kyryloonufriiev commented on js/packages/screenshoter/test/e2e/web/hover-element.spec.js
> +  it('take element in frame screenshot with hover element', async () => {
I would rather call it
```suggestion
  it('take hovered element screenshot', async () => {
```

2022-08-02 15:23 UTC, kyryloonufriiev commented on js/packages/screenshoter/test/e2e/web/hover-element.spec.js
> +      tag: 'hover-element',
The convention here is 
```
`${what's on the screenshot (page | frame | element)}-${fully or not}-${what's special about it}`
```

```suggestion
      tag: 'element-hovered',
```

2022-08-02 15:23 UTC, kyryloonufriiev commented on js/packages/screenshoter/test/e2e/web/hover-element.spec.js
> +      tag: 'hover-element',
The same for file name

2022-08-02 16:00 UTC, zamboney commented on .gitignore
> +node_modules
`.DB_Store` i will remove but `node_modules` should not be added to the repo

2022-08-02 16:06 UTC, zamboney commented on js/packages/screenshoter/test/e2e/e2e.js
> +      pixelmatch(actual.data, expected.data, null, expected.width, expected.height),
np

2022-08-02 16:16 UTC, zamboney commented on .gitignore
> +node_modules
the `.DB_Store` was [before](https://github.com/applitools/eyes.sdk.javascript1/blob/f07a743710fda3590eb6d0014e41855586a07b8e/.gitignore#L4) this pr

2022-08-02 17:03 UTC, kyryloonufriiev commented on .gitignore
> +node_modules
I was talking about `node_modules`. It wasn't there and it wasn't a problem, so I don't see why we should add it.

2022-08-02 17:45 UTC, zamboney commented on .gitignore
> +node_modules
I don't understand why the `node_moudles` are ignore right now but this will make sure it will ignore in the future.

And, unless you want to keep the `node_moudles`, it doesn't do anything.

2022-08-02 18:05 UTC, kyryloonufriiev commented on .gitignore
> +node_modules
We need to understand how it will affect us first, before doing it. Especially in cases like this, when there are no real problem solved. I actually did the check why we don't have node_modules included in the repo, and why we didn't have node_modules ignored here. To clarify it for your self you have to look at /js/.gitignore file.

2022-08-02 18:28 UTC, tourdedave commented on .gitignore
> +node_modules
Put another way - this repo is a monorepo of multiple programming languages (right now just Python and JS, but soon to also include Java, C#, and Ruby). The .gitignore in the `js` directory already handles `node_modules`. The top-level .gitignore for the repo does not need this since all languages do not need this.

2022-08-03 06:32 UTC, zamboney commented on .gitignore
> +node_modules
ok, i will remove it

2022-08-03 07:16 UTC, kyryloonufriiev commented
Looks good to merge. Make sure you use the "Squash and merge" button

2022-08-03 07:16 UTC, kyryloonufriiev approved these changes

2022-08-03 07:25 UTC, merged