Add `typesVersions` and `exports` to the `package.json`
applitools/eyes.sdk.javascript1 pull request #1059
Opened 2022-08-03 11:38 UTC by zamboney

Now to `import` the new `SDK` (a.k.a not `index-legacy`) with all of the types inside it all needed to do is `import` from  `@applitools/eyes-testcafe/next`

For example `BatchClose`:

```
import { BatchClose } from "@applitools/eyes-testcafe/next";
```

2022-08-03 13:57 UTC, kyryloonufriiev commented
@zamboney It comes to me that if the customer uses node < 16 they will not be able to run `import {BatchClose} from '@applitools/eyes-testcafe/next'`, even if types are recognized. Because node < 16 will not respect the `exports` configuration, so it will think that `./next` is an actual file or dir in the package. 
In order to help customers with node < 16, we should help typescript understand where the types live when they will import from `@applitools/eyes-testcafe/dist/index`. This could be done with `typesVersions` i believe.

2022-08-03 14:00 UTC, kyryloonufriiev commented
@zamboney in order to solve the `Verify changelog` check, you should add a changelog entry in `pending-changes.yml` file at the root of the repo. Obviously, you should add it to `eyes-testcafe` only, I think you will get it.

2022-08-03 14:09 UTC, zamboney commented
> @zamboney It comes to me that if the customer uses node < 16 they will not be able to run `import {BatchClose} from '@applitools/eyes-testcafe/next'`, even if types are recognized. Because node < 16 will not respect the `exports` configuration, so it will think that `./next` is an actual file or dir in the package. In order to help customers with node < 16, we should help typescript understand where the types live when they will import from `@applitools/eyes-testcafe/dist/index`. This could be done with `typesVersions` i believe.

yes of course that's why I added both `typesVersions` and `exports`.

2022-08-03 15:37 UTC, kyryloonufriiev commented
You added `typesVersions` for `next`, and node < 16 doesn't know what `@applitools/eyes-testcafe/next` is, it thinks that there should be a file/dir with name `next`. But there are not. This is why customers who use node < 16 should use our directory structure instead of this fancy `next` sub-module.

2022-08-03 15:40 UTC, kyryloonufriiev requested changes

2022-08-03 16:03 UTC, zamboney commented
@kyryloonufriiev I tested it on `node@14`, and it works. I understand what you are saying about the file structure and how it's worked for customers before this change, but i don't understand why they should use it after this change if it works fine with `typesVersions` (as long as they use `ts@<3.1` [link](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions)). of course they can keep work with the file/dir as before.

2022-08-03 17:27 UTC, kyryloonufriiev commented
@zamboney I have no doubt that TS works, but I don't think that JS will actually work. Because node < 16 will throw when you try to import/require `eyes-testcafe/next`.

2022-08-03 17:50 UTC, zamboney commented
@kyryloonufriiev good point, but what is the difference from what it was before? It will just work for `node@16` and above

But for sure this solution does not cover `node@14`

If you want to cover `node@14` I can add a `next` folder that `expose` `dist/index.js`.

This will make the whole solution as a setup for the upcoming deprecation of `node@14` in April 23

Does it sound good?

2022-08-03 18:11 UTC, kyryloonufriiev commented
I don't want a directory next in the file system. This is just a work around for the user. If they have node 16 the work around will be nicer, if not then you should deal with a file system.

2022-08-03 18:40 UTC, zamboney commented
So you can approve this PR 🧑‍🎤?

2022-08-03 19:27 UTC, kyryloonufriiev commented
I cannot approve. We need to support `@applitools/eyes-testcafe/dist` for customers with node < 16

2022-08-04 05:09 UTC, zamboney commented
But isn't the `dist` folder already created by `tsc`?

2022-08-04 07:51 UTC, zamboney commented
@kyryloonufriiev I think i figure it out

check the video below

[![asciicast](https://asciinema.org/a/tsLlN3RMCb28hXE6mM34DrByM.svg)](https://asciinema.org/a/tsLlN3RMCb28hXE6mM34DrByM)

It looks like everything is working as expected!

I will add the `dist` export after you approve that this is what you had in mind.

2022-08-04 10:10 UTC, kyryloonufriiev requested changes

2022-08-04 10:10 UTC, kyryloonufriiev commented on js/packages/eyes-testcafe/package.json
> +    }
What about all of this but in a `typesVesions`? because it still doesn't solve the problem for node < 16?

2022-08-04 10:10 UTC, kyryloonufriiev commented on js/packages/eyes-testcafe/package.json
> +    },
Also, I would allow importing any file from `dist`.
```suggestion
    "./dist/*": {
        "types": "./types/*.d.ts",
        "default": "./dist/*.js"
    },
```

2022-08-04 10:13 UTC, zamboney commented on js/packages/eyes-testcafe/package.json
> +    }
isn't `typeVersions` for `typesctipt` only use?

2022-08-04 10:23 UTC, kyryloonufriiev commented on js/packages/eyes-testcafe/package.json
> +    }
No, how it node resolves modules and how typescript resolves types are two completely different topics. You can try it out, `import {Eyes} from '@applitools/eyes-testcafe/dist'` will not resolve types in node < 16, without tsconfig's `"moduleResolution": "node16"`.

2022-08-04 10:32 UTC, zamboney commented on js/packages/eyes-testcafe/package.json
> +    }
Ok good to know! i will add it to the `typeVersions`

2022-08-04 11:45 UTC, kyryloonufriiev approved these changes

2022-08-04 11:50 UTC, merged