Pull makeImage into its own package (from screenshoter)
applitools/eyes.sdk.javascript1 pull request #1061
Opened 2022-08-04 19:33 UTC by tourdedave

- [x] pull it into its own package
- [x] convert it to TS (e.g., no build errors and tests passing)
- [ ] specify concrete types (not just any)
- [ ] update screenshoter to use the new package

2022-08-05 14:57 UTC, kyryloonufriiev requested changes
Looks good to me. One small thing that is maybe more about esthetic is I wouldn't put the whole implementation in the index file, but rather create an `image.ts` file with the implementation of the image logic. And the same for test `index.d.ts` is not informative enough as for me.

2022-08-05 14:57 UTC, kyryloonufriiev commented on js/packages/image/src/index.ts
> +export = makeImage
It would be better to use named export.

2022-08-05 14:57 UTC, kyryloonufriiev commented on js/packages/image/src/index.ts
> +type Image = {
I would specify it as an `interface`, not `type`. There is no big difference, but I usually use `type` to specify the shape of a data object, and `interfaces` to specify a functional object as we have here.

2022-08-08 09:34 UTC, kyryloonufriiev commented on js/packages/image/src/image.ts
> +interface Image {
This should be exported, so we can use the time in other packages
```suggestion
export interface Image {
```

2022-08-08 09:35 UTC, kyryloonufriiev requested changes
Looks good to me, the only missing point is a dedicated github action to publish this pacakge.

2022-08-08 14:43 UTC, tourdedave commented
> Looks good to me, there are a few missing points:
> 
> * Dedicated github action to publish `image` package.
> * Add `@applitools/scripts` to the `screenshoter` as a dev dependency.
> * Add `test:sanity` command to the `image`, it could run all of the tests, since they are fast.

`@applitools/scripts` is already a dev dep in `screenshoter`. The other items are done.

2022-08-08 15:03 UTC, kyryloonufriiev requested changes
If after merging my proposed change all tests are passing in the PR, feel free to merge.

2022-08-08 15:03 UTC, kyryloonufriiev commented on js/packages/image/package.json
> +  ],
Aha. I see what confused me. We use the first alias as the name of the job, so it says that `screenshoter` doesn't have `scripts` dependency when the `image` is the one that doesn't have it. 
```suggestion
  "aliases": [
    "image"
  ],
```

2022-08-08 16:09 UTC, kyryloonufriiev approved these changes
Great, let's merge and release it!

2022-08-08 17:42 UTC, merged