Fix `selectorOrElement` is both `Selector` and `Element`
applitools/eyes.sdk.javascript1 pull request #1067
Opened 2022-08-10 09:27 UTC by zamboney

There are cases (`testcafe` for example) that  the `selectorOrElement` is both `Selector` and `Element`.

This Change will make the make sure that if `selectorOrElement` is both `Selector` and `Element`, it will choose to use the `Selector` logic instead of the `Element` logic.

|`isSelector`|`isElement`| logic |
|-|-|-|
|false|false| throw an `Error`|
|false|true| `Element` logic|
|true|false| `Selector` logic|
|true|true| `Selector` logic|

2022-08-10 09:29 UTC, kyryloonufriiev commented on js/packages/driver/src/context.ts
> +    selectorOrElement: TElement | types.Selector<TSelector>,
Not important at all, I just like it to be consistent :)
```suggestion
    selectorOrElement: types.Selector<TSelector> | TElement,
```

2022-08-10 09:30 UTC, kyryloonufriiev reviewed
The PR looks great as we discussed, nice description! Let's have a dedicated discussion about testing.

2022-08-18 16:58 UTC, kyryloonufriiev requested changes

2022-08-18 16:58 UTC, kyryloonufriiev commented on js/packages/driver/test/unit/element-selector-same.spec.ts
> +  it('should return single element if the `isElement` return `true` and `isSelector` return `false`', async () => {
I would put those tests in `context`, because it is where we testing it

2022-08-21 06:35 UTC, zamboney commented on pending-changes.yaml
> +      'fix selector issue in `testcafe`, the selector and the element are the same and once there are multi selector the it's only peak the element'
np i will remove it

2022-08-21 06:35 UTC, zamboney commented on js/packages/driver/test/unit/element-selector-same.spec.ts
> +    } catch (_) {
np i will remove it

2022-08-21 06:36 UTC, zamboney commented on js/packages/driver/test/unit/element-selector-same.spec.ts
> +    }
for the 1st state, `isSelector` and `isElement` return `false`

2022-08-21 06:37 UTC, zamboney commented on js/packages/driver/test/unit/element-selector-same.spec.ts
> +  it('should return single element if the `isElement` return `true` and `isSelector` return `false`', async () => {
np

2022-08-24 07:01 UTC, kyryloonufriiev approved these changes
Let's merge it

2022-08-24 08:29 UTC, merged