move toCheckSettings logic to screenshoter and add tests
applitools/eyes.sdk.javascript1 pull request #1069
Opened 2022-08-13 01:19 UTC by SophieDePaula

I still need to add tests for `toBaseCheckSettings`

2022-08-15 07:38 UTC, kyryloonufriiev commented
@SophieDePaula I think you can merge your PR directly in master. This way we can already start taking advantage of this.

2022-08-15 15:41 UTC, SophieDePaula commented
> @SophieDePaula I think you can merge your PR directly in master. This way we can already start taking advantage of this.

@kyryloonufriiev I branched out of Dave's NML branch, so I also have his changes here

2022-08-16 00:34 UTC, SophieDePaula commented on js/packages/eyes-sdk-core/lib/sdk/CheckSettingsUtils.js
> +  const regionTypes = ['ignore', 'layout', 'strict', 'content', 'floating', 'accessibility']
@kyryloonufriiev notice that I had to make a few changes to this function.

2022-08-16 00:35 UTC, SophieDePaula commented
@kyryloonufriiev this PR is ready for review.

2022-08-16 09:18 UTC, kyryloonufriiev requested changes

2022-08-16 09:18 UTC, kyryloonufriiev commented on js/packages/utils/src/general.ts
> +}
this function shouldn't be in the utils package containing general utilities, and this is an applitools specific one. You could feel it when you put `any` in argument type. Because you don't have access to `types`.

2022-08-16 09:18 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/take-screenshot.js
> +      const {region, ...options} = codedRegion.region ? codedRegion : {region: codedRegion}
In this line, I see that you exposed the check settings sub-structure to `screenshoter`. The idea was to avoid it, but passing just elements/selectors and not the whole object of coded region with unnecessary metadata.

2022-08-16 09:18 UTC, kyryloonufriiev commented on js/packages/screenshoter/test/e2e/e2e.js
> +        regionId: r.regionId,
Same here. You shouldn't test coded region structure, since this is not the feature of screenshoter.

2022-08-16 21:27 UTC, SophieDePaula commented on js/packages/utils/src/general.ts
> +}
@kyryloonufriiev we use this function in both `core` and `screenshoter`, where would be the appropriate place to put it?

2022-08-16 22:17 UTC, SophieDePaula commented on js/packages/screenshoter/src/take-screenshot.js
> +      const {region, ...options} = codedRegion.region ? codedRegion : {region: codedRegion}
@kyryloonufriiev this info about the region such as `regionId` and `padding` is needed in `screenshoter` as there we also add the padding to the coordinates we find and calculate the `regionId`.

2022-08-16 22:21 UTC, SophieDePaula commented on js/packages/screenshoter/src/take-screenshot.js
> +      const {region, ...options} = codedRegion.region ? codedRegion : {region: codedRegion}
did you want the logic around `padding` and `regionId` to be separated from extracting the coordinates? Today it's calculated together:

```
        const elementRegion = utils.geometry.withPadding(await element.getRegion(), options.padding)
        const region = utils.geometry.offset(elementRegion, contextLocationInViewport)
        const scaledRegion = utils.geometry.scale(
          {
            x: Math.max(0, region.x - screenshot.region.x),
            y: Math.max(0, region.y - screenshot.region.y),
            width: region.width,
            height: region.height,
          },
          context.driver.viewportScale,
        )
```

2022-08-17 10:20 UTC, kyryloonufriiev commented on js/packages/utils/src/general.ts
> +}
This shouldn't be used in `screenshoter` in the first place

2022-08-17 10:25 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/take-screenshot.js
> +      const {region, ...options} = codedRegion.region ? codedRegion : {region: codedRegion}
@SophieDePaula Exactly, I want this logic to be spreaded. I understand that it might look like an unnecessary complication, but I believe that this is a unification, because 1 - this is something that already happening when we are working with ufg, and 2 this is what going to happen when we will work with nml.

2022-08-18 21:46 UTC, SophieDePaula commented
@kyryloonufriiev please take another look at this PR and also the note I added to the description.
Thanks!

2022-08-29 16:49 UTC, kyryloonufriiev requested changes

2022-08-29 16:49 UTC, kyryloonufriiev commented on js/packages/eyes-sdk-core/lib/sdk/CheckSettingsUtils.js
> +    })
1. Don't use `map` / `flatMap` if you don't care about the outcome.
2. How it could be undefined if you explicitly set there at least `[]`

2022-08-29 16:49 UTC, kyryloonufriiev commented on js/packages/eyes-sdk-core/lib/sdk/CheckSettingsUtils.js
> +      for (const region of transformedSettings[`${regionType}Regions`]) {
if the point of this is just to have something to use in `for`, then better do this 
```suggestion
      for (const region of transformedSettings[`${regionType}Regions`] || []) {
```

2022-08-29 16:49 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/take-screenshot.js
> +    return {screenshot, codedRegionsByCoordinates}
I wouldn't call it "coded regions", because this way you merge eyes terminology and low-level screenshoter terminology. As I see it it is just "region" / "caltulatedRegions". Coded regions have their own features and types, and this is not what you return here.

2022-08-29 16:49 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/take-screenshot.js
> +      }
I think this deserves its own file, and separate integration test

2022-08-29 23:20 UTC, SophieDePaula commented on js/packages/eyes-sdk-core/lib/sdk/CheckSettingsUtils.js
> +    })
@kyryloonufriiev , what do you mean if I don't care about the outcome? I do care, I want all the regions in each type to not have nested arrays.
I actually had a bug here, but now if I can't find an element in `take-screenshot`, I return an array with `{regions:[]}`, and I set `undefined` in `enrichRegion` in `getBaseCheckSettings` as a place holder.

2022-08-29 23:39 UTC, SophieDePaula commented on js/packages/screenshoter/src/take-screenshot.js
> +      }
I separated this logic to a new file. I already have `e2e` tests for this logic, so I don't think we need integration tests as well.

2022-08-30 16:22 UTC, kyryloonufriiev requested changes

2022-08-30 16:22 UTC, kyryloonufriiev commented on js/packages/eyes-sdk-core/lib/sdk/CheckSettingsUtils.js
> +    })
Ok, my first question why do you use `flatMap` here? Why not just `map`?
Both of them do not make sense here, because those methods construct some new value out of the array, but you don't use the value it returns, so you shouldn't use this method in the first place. Maybe `forEach` is what you need.

But even if you get this, there is a bigger question why do you need to do the second iteration over all of the region is you could do this during the first itteration.

2022-08-30 17:15 UTC, merged