universal e2e tests client
applitools/eyes.sdk.javascript1 pull request #1078
Opened 2022-08-21 14:23 UTC by zamboney

In order to test the communication between the `eyes-universal` and other platform (like `Python` or `Ruby` for example) this `client` will test the communication between `eyes-universal` (a.k.a. server) and a `client` (a.k.a. `nodejs` client).

This change is here to replace [this close](https://github.com/applitools/eyes.sdk.javascript1/pull/1010) pr that try to make this `client` as a standalone package.

Also adding a `stress tests` that use this `client` test.

2022-08-24 11:48 UTC, kyryloonufriiev requested changes

2022-08-24 11:48 UTC, kyryloonufriiev commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +export type Driver = Selenium.WebDriver & {__serverUrl?: string} & {__applitoolsBrand?: never}
This should not be here in the type. Because it is user-facing thing

2022-08-24 12:18 UTC, zamboney commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +export type Driver = Selenium.WebDriver & {__serverUrl?: string} & {__applitoolsBrand?: never}
ok so where it's should be? without it `tsc` break

2022-08-24 12:30 UTC, kyryloonufriiev commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +export type Driver = Selenium.WebDriver & {__serverUrl?: string} & {__applitoolsBrand?: never}
You can skip declaring it because this is already a hack. So no need to pretend it is a real thing.
BTW if you really want to declare it you can declare it in the return value of the build function.

2022-08-25 13:32 UTC, zamboney commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +  Object.defineProperty(driver, '__serverUrl', {get: () => url})
@kyryloonufriiev
return the `serverUrl` value in the `build` function, meaning passing this value through the `nodejs` client. I think it's overhead and it makes the code less readable (IMO).
I think using `Object.defineProperty` to bind to the `driver` the `serverUrl` is a hacky solution but not as hacky as changing the `Driver` type.
WTYT.

2022-08-26 05:57 UTC, kyryloonufriiev commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +  Object.defineProperty(driver, '__serverUrl', {get: () => url})
I was thinking about something else. instead of return `[Driver, () => void]` - return `[Driver & {__serverUrl: string}, () => void]`. This way you don't change the user-facing `Driver` type and have all of the declarations you need during testing.

2022-08-26 09:15 UTC, zamboney commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +  Object.defineProperty(driver, '__serverUrl', {get: () => url})
Np will do on Sunday 😎

2022-08-29 13:54 UTC, zamboney commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +export type Driver = Selenium.WebDriver & {__serverUrl?: string} & {__applitoolsBrand?: never}
@kyryloonufriiev done please take a look

2022-08-29 13:55 UTC, zamboney commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +  Object.defineProperty(driver, '__serverUrl', {get: () => url})
@kyryloonufriiev done please take a look, 10x

2022-08-30 11:08 UTC, zamboney commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +  Object.defineProperty(driver, '__serverUrl', {get: () => url})
my bad i will remove it

2022-08-30 11:10 UTC, zamboney commented on js/packages/spec-driver-selenium/src/spec-driver.ts
> +export async function build({selenium, ...env}: any): Promise<[DriverWithServerUrl | Driver, () => Promise<void>]> {
will do

2022-09-14 13:35 UTC, kyryloonufriiev approved these changes
Looks good to me!

2022-09-14 13:35 UTC, kyryloonufriiev commented on js/packages/eyes-universal/src/socket.ts
> +  }
If you do this, that makes sense, you would probably want to remove  `if (!ws) return` from the `attach` function.

2022-09-14 13:35 UTC, kyryloonufriiev commented on js/packages/eyes-universal/test/stress/run.sh
> +echo "stress test done"
It is hard for me to understand what exactly it is doing. Why did you choose to do it with bash and not js/ts?

2022-09-15 11:49 UTC, merged