Allow viewport size to be greater than the screen size in `UFG`.
applitools/eyes.sdk.javascript1 pull request #1081
Opened 2022-08-23 14:27 UTC by zamboney

Before this change, the test fails if the viewport is set to be greater than the window size both in `classic` and `UFG`.

This fix allows the viewport to be greater than the screen in `UFG` (but less than the `UFG` limitation).

2022-08-23 17:48 UTC, amitzur requested changes
The core e2e test is :100: 
I think the implementation should be more minimal. I don't see a reason to do any change to `setViewportSize`.

2022-08-23 17:48 UTC, amitzur commented on js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +      const error = await this.setViewportSize(vsFromConfiguration, false)
I recommend to just `try/catch` instead of changing the API of `setViewportSize`.

2022-08-23 17:48 UTC, amitzur commented on pending-changes.yaml
> +    - Allow viewport size greater than the screen size in `UFG`.
```suggestion
    - Don't fail `eyes.open` when there is a failure to set viewport size in `UFG`.
```

2022-08-23 18:05 UTC, amitzur commented on js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +      const error = await this.setViewportSize(vsFromConfiguration, false)
Not sure I understand. I mean doing something like this:

```
if (this._configuration.getViewportSize()) {
  const vs = this._configuration.getViewportSize()
  try {
    await this.setViewportSize(vs)
  } catch(err) {
    this._logger.warn(`Failed to "setViewportSize" to ${vsFromConfiguration}, but still continue with the test`)
  }
}
```

Do you see anything wrong with it?

2022-08-23 18:11 UTC, zamboney commented on js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +      const error = await this.setViewportSize(vsFromConfiguration, false)
Without my change [this error](https://github.com/applitools/eyes.sdk.javascript1/blob/17d2b6d3aac364636b92493669bd1fc3486130ac/js/packages/eyes-sdk-core/lib/sdk/EyesCore.js#L245) will thrown no matter if it's catch the `error` or not

2022-08-24 04:06 UTC, amitzur commented on js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +      const error = await this.setViewportSize(vsFromConfiguration, false)
IMO it's more important to keep the API as clean as possible. It makes things easier to reason about. In this case, I would change that place from `logger.error` to `logger.log`. Because you will call `logger.warn` here anyway.

2022-08-24 04:32 UTC, amitzur requested changes
There's another comment about the test. I was running this in docker and wasn't successful in getting the `setViewportSize` to fail, even though it is NOT headless. Only on my local machine's chrome I was able to verify it.
So a verification of the actual viewport size is very important in the test.

2022-08-24 04:32 UTC, amitzur commented on js/packages/eyes-sdk-core/test/e2e/viewportSizeFallback.e2e.spec.js
> +            headless: false,
This does nothing, it can be removed.

2022-08-24 04:32 UTC, amitzur commented on js/packages/eyes-sdk-core/test/e2e/viewportSizeFallback.e2e.spec.js
> +  })
I would add the following at the end:

```
const actualViewportSize = await driver.executeScript(getViewportSize)
expect(actualViewportSize.width).to.be.lessThan(UFG_MAX_WIDTH_HEIGHT_SIZE - 1)
expect(actualViewportSize.height).to.be.lessThan(UFG_MAX_WIDTH_HEIGHT_SIZE - 1)
```
It's important to verify that the conditions you assume happen in the test, actually happened

2022-08-24 04:32 UTC, amitzur commented on js/packages/eyes-sdk-core/test/e2e/viewportSizeFallback.e2e.spec.js
> +  })
This requires adding at the top:
```
const {expect} = require('chai')
const {getViewportSize} = require('@applitools/snippets')
```

2022-08-24 06:35 UTC, zamboney commented on js/packages/eyes-sdk-core/test/e2e/viewportSizeFallback.e2e.spec.js
> +            headless: false,
About the `headless` you're right, but about the other properties, I'm not sure. You can see in the [eyes test](https://eyes.applitools.com/app/test-results/00000251740978189603/00000251740978189447/steps/1?accountId=UAujt6tHnEKUivQXIz7G6A~~&mode=step-editor) that the width and height are set as expected...
![image](https://user-images.githubusercontent.com/7997259/186347486-d0c3c1e7-2f38-4535-9cba-6e61188646ef.png)

2022-08-24 08:21 UTC, zamboney commented
@amitzur, I change all your request on the running code
On the test side, I understand what you saying about the way I tested it, and I moved the tests to `it` tests, and now it's testing the code as expected (you can remove my `try catch` [code](https://github.com/applitools/eyes.sdk.javascript1/blob/34987ecaa28a7d759b5212dcf5bdce430c8c5e71/js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js#L123-L129) and the test will fail.

2022-08-24 08:22 UTC, zamboney commented on js/packages/eyes-sdk-core/test/e2e/viewportSizeFallback.e2e.spec.js
> +  })
@amitzur  i remove this test and create a new one in `it`

2022-08-24 08:22 UTC, zamboney commented on js/packages/eyes-sdk-core/test/e2e/viewportSizeFallback.e2e.spec.js
> +            headless: false,
i see what i miss and remove this test

2022-08-24 09:33 UTC, amitzur commented on js/packages/eyes-sdk-core/test/e2e/viewportSizeFallback.e2e.spec.js
> +            headless: false,
I only referred to the `headless: false`

2022-08-24 09:38 UTC, amitzur requested changes
In addition to the inline comment about the `error instanceof EyesError`, I have a comment about the test.
I liked that it was an e2e test. Kyrylo is working on core redesign and I would like this test to stay the same even after his work.
I don't like the integration tests that check `EyesVisualGrid` because that class is not how I would like core to be designed in the first place. This is why we are doing the final redesign now :)
The only comment I have about that e2e test is that the test should also verify the assumption that the viewport size was NOT set to what was asked.

2022-08-24 09:38 UTC, amitzur commented on js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +        if (error instanceof EyesError)
I don't think this is needed. The contract is that `setViewportSize` throws if it fails. No need to look into **what** it throws.

2022-08-24 10:02 UTC, zamboney commented
The `e2e` test I did don't really test anything ,you can remove the code I change and everything stay the same.

I think it's because the `selenium` `docker ` image using a VM like env that not really have a screen size, but I'm not sure.

I can keep the `e2e` test just for a `UFG` smoke test but I didn't figure out a way to test my changes using it

2022-08-24 10:05 UTC, zamboney commented on js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +        if (error instanceof EyesError)
This is for safety measure, what happens if there is a `property undefined` error? If I didn't `catch` the type of the `error` it would continue

2022-08-24 10:13 UTC, amitzur commented on js/packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +        if (error instanceof EyesError)
Fair enough

2022-08-24 10:17 UTC, amitzur commented
@zamboney the e2e does test what it needs, it's the docker that's "misbehaving".

I would keep the e2e with the assertion that I suggested, in addition to your good integration test.
I would skip the e2e test and then release this. After that we should insist on understanding how to make the test behave well in docker.

2022-08-24 11:31 UTC, zamboney commented
@amitzur i added the `e2e` test as a `smoke test`. the changes you suggested do not work. the value of the `width` and `height` remained the same.

2022-08-24 11:43 UTC, kyryloonufriiev commented
@zamboney did you try this - https://github.com/SeleniumHQ/docker-selenium#setting-screen-resolution?

2022-08-24 12:07 UTC, zamboney commented
As @amitzur suggested, I added the `e2e` test that tests this change but `skip` it. I will continue investigating this issue

2022-08-24 12:23 UTC, zamboney commented
> @zamboney did you try this - https://github.com/SeleniumHQ/docker-selenium#setting-screen-resolution?
@kyryloonufriiev  its not working 😢 i will investigate more

2022-08-24 13:02 UTC, kyryloonufriiev reviewed
@zamboney Let's fix the changelog and merge it today.

2022-08-24 13:02 UTC, kyryloonufriiev commented on pending-changes.yaml
> +    - Don't fail `eyes.open` when there is a failure to set viewport size in `UFG`.
This is relevant for all of the sdks except storybook, not only universal.

2022-08-24 14:07 UTC, zamboney commented on pending-changes.yaml
> +    - Don't fail `eyes.open` when there is a failure to set viewport size in `UFG`.
done

2022-08-24 14:25 UTC, merged