WebView support
applitools/eyes.sdk.javascript1 pull request #1105
Opened 2022-09-19 18:35 UTC by tourdedave

[Trello](https://trello.com/c/uEWiEF5s)

2022-09-23 18:13 UTC, tourdedave commented on pending-changes.yaml
> +    - Added support for webview switching in classic execution
@benbabayoff8 ☝️

2022-09-23 18:30 UTC, tourdedave commented on pending-changes.yaml
> +    - Added support for webview switching in classic execution
Ben approved this offline

2022-09-26 08:07 UTC, kyryloonufriiev reviewed
Looks really great, I like the simplicity. There is one important comment regarding the spec-driver, let's discuss it.
I also think we should handle this case - if the user switched to the webview, and asks for a viewport screenshot it should get the whole viewport, not just the webview. This is how it works with frames. I believe we should be consistent here.

2022-09-26 08:07 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/take-screenshot.js
> +    else await driver.refresh()
I'm not sure that the driver should ever be reinitialized in screenshoter. Since one of the requirements of the screenshoter package is that driver is already initialized and the state of the driver is correct.

2022-09-26 13:46 UTC, tourdedave commented on js/packages/screenshoter/src/take-screenshot.js
> +    else await driver.refresh()
Okay. But isn't there a case where this could happen with webviews? Like when `driver.init()` has been called, then a user switches to a webview, and then they perform a check? This is the case that presented when testing e2e in screenshoter. `refresh` only reinitializes in this case ([link](https://github.com/applitools/eyes.sdk.javascript1/blob/js/feat/webview-support/js/packages/driver/src/driver.ts#L324-L333)).

2022-09-26 13:50 UTC, tourdedave commented
> if the user switched to the webview, and asks for a viewport screenshot it should get the whole viewport, not just the webview. This is how it works with frames.

@kyryloonufriiev Just to make sure I understand - you mean if the user specifies something like `Target.window().webview()`? Can you point me to an example e2e test for frames that does something similar for reference?

2022-09-26 14:33 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/take-screenshot.js
> +    else await driver.refresh()
`driver.init()` will be performed in check, so `screenshoter` will always get a driver with an actual state. And this is not a coincidence this is the requirement of the `screenshoter` package.

2022-09-26 16:25 UTC, tourdedave commented on js/packages/screenshoter/src/take-screenshot.js
> +    else await driver.refresh()
Okay. This requirement was not clear to me. Is it written down somewhere? Seems like a helpful thing to put in a readme.

2022-09-26 16:33 UTC, tourdedave commented
> @tourdedave I had this case in mind.
> 
> ```js
> await driver.switchContext('webview')
> await eyes.check(Target.window())
> ```
> 
> I think we don't have a test for such case. But you can see this very clear in screenshoter when we calculate a `window` value.

@kyryloonufriiev Are you saying we don't have a test that demonstrates what you're describing for frames (but it's something we support for frames)?

I wanted a test so I could see what the final image looks like in the case of frames (since you said it's similar behavior). It should be a viewport screenshot which contains the contents of the webview, right?

What's the desired outcome of doing what I described (`Target.window().webview()`)?

2022-09-26 18:25 UTC, kyryloonufriiev commented
@tourdedave 
- There is nothing special about it - `Target.window().webview()`, same as `Target.webview()`.
- Yes, there is no test for taking a viewport screenshot after manual switch to a frame.

When the user doing `Target.window()` it shouldn't matter where the user is in webview or frame. It is always the topmost context or world for that matter. `Target.window().fully()` will take a full screenshot of the native world. BTW speaking of full screenshots, there is a way to specify the scroll root element for a target context and the main context separately. I think we should give it some thought in the context of webviews.

2022-09-26 19:15 UTC, tourdedave commented
@kyryloonufriiev

So, to put into my own words.

For the implicit case (where a user switches into a webview before calling check), we currently support:

```
await driver.switchContext('webview')
await eyes.check()
```

Which gets us just the webview. And we also want to support:

```
await driver.switchContext('webview')
await eyes.check(Target.window())
```

Which would get us the viewport (not just the webview). Is that right?

> there is a way to specify the scroll root element for a target context and the main context separately. I think we should give it some thought in the context of webviews.

Okay, but I committed to shipping webview support by Wednesday. If we're looking to increase the scope further then I think we should save this functionality for a follow-on version. What do you think?

2022-09-26 19:26 UTC, kyryloonufriiev commented
Ok. I'm fine with not implementing scroll root thing.

The examples you gave have no difference. `Target.window()` is the same as passing nothing. What I was saying is that if you are going to check WINDOW it should be topmost world, doesn't matter what is the current state of the driver. But if you are going to check region or frame, it should be related to the current state of the driver.
Here is the example
`Target.window()` - is `cd /` 
`Targer.region('bla')` or `Target.frame('bla') is `cd ./bla`

2022-09-26 19:44 UTC, tourdedave commented
> The examples you gave have no difference. `Target.window()` is the same as passing nothing. What I was saying is that if you are going to check WINDOW it should be topmost world, doesn't matter what is the current state of the driver. But if you are going to check region or frame, it should be related to the current state of the driver. Here is the example `Target.window()` - is `cd /` `Targer.region('bla')` or `Target.frame('bla') is `cd ./bla`

I thought that the implicit use case we wanted to support was preserving the driver state that the user switched to. Did I misunderstand? That's what is tested [here](https://github.com/applitools/eyes.sdk.javascript1/blob/js/feat/webview-support/js/packages/core/test/e2e/classic/webview.spec.ts#L42-L62) which gets [this result Eyes](https://eyes.applitools.com/app/test-results/00000251738079447364/00000251738079447177/steps/1?accountId=xIpd7EWjhU6cjJzDGrMcUw~~&display=details&fb=eyJkYXRlUmFuZ2UiOnsiZnJvbURhdGUiOiIyMDIyLTA5LTI2VDA0OjAwOjAwLjAwMFoiLCJ0b0RhdGUiOiIyMDIyLTA5LTI2VDA0OjAwOjAwLjAwMFoifSwidGV4dFNlYXJjaCI6IndlYnZpZXcifQ%3D%3D&mode=step-editor&top=00000251738079447364%2816%29).

If there is still confusion, then let's hop on a call tomorrow to discuss.

2022-09-26 19:50 UTC, kyryloonufriiev commented
As I said state is important when you are checking "not a window". Because window is special – it always means root.

2022-09-26 19:53 UTC, tourdedave commented
I feel like we're talking past each other. I'll sync up with you tomorrow.

2022-09-28 14:24 UTC, kyryloonufriiev requested changes

2022-09-28 14:34 UTC, tourdedave commented on pending-changes.yaml
> +    - Added support for webview switching in classic execution
We'll need to add it at some point (not for this release). We should keep track of this in the Trello card. I'll note it there.

2022-09-28 17:30 UTC, merged