WIP - support coded region in region
applitools/eyes.sdk.javascript1 pull request #1129
Opened 2022-10-11 17:16 UTC by tourdedave

[Trello](https://trello.com/c/Bhsdn014)

2022-10-22 01:16 UTC, tourdedave commented on pending-changes.yaml
> +    - Fix calculation for determining coded region positions when they are inside of a check region
@benbabayoff8 ☝️

2022-10-23 07:44 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Fix calculation for determining coded region positions when they are inside of a check region
looks good.

2022-10-24 09:06 UTC, kyryloonufriiev requested changes
I've briefly reviewed it, without deep dive into the solution. Does this PR complete?

2022-10-24 09:06 UTC, kyryloonufriiev commented on js/packages/core/src/automation/locate.ts
> +    const screenshot = await takeScreenshot({driver, settings, logger, regionsToCalculate: []})
I beliave this meant to be in settings

2022-10-24 09:06 UTC, kyryloonufriiev commented on js/packages/core/src/automation/types.ts
> +  regionsToCalculate?: []
It could not be here. Because this would mean that `eyes.check`, could also accept it

2022-10-24 14:30 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/extract-coodinates-for-selectors-and-elements.js
> +          }
How is it possible that only one coordinate has to be compensated?

2022-10-24 14:30 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/take-screenshot.js
> +    compensateCoordinatesRelativeToParentRegion: !!region && driver.isWeb,
Isn't compensation also needed for native apps?

2022-10-24 14:35 UTC, kyryloonufriiev commented on js/packages/core-base/src/types.ts
> +
Having it here would also mean that it will go to `CheckSettings`. I meant that this property is not coming from the outside, and is always calculated internally. So it should be declared in an appropriate location. If `screenshoter` had ts this definitely would be the place, but today instead of `screenshoter` ts package we have this `take-screenshot.ts` file in the `core`, that wraps `screenshoter` package.

2022-10-24 15:18 UTC, tourdedave commented on js/packages/core-base/src/types.ts
> +
Yes, I know. This is where I added it. It was originally as a new argument to this function. Your recommendation was to consolidate it into settings. My intention was *not* to expose this property externally, but to address type/build errors I was getting. I'll try again.

2022-10-24 15:21 UTC, tourdedave commented on js/packages/screenshoter/src/take-screenshot.js
> +    compensateCoordinatesRelativeToParentRegion: !!region && driver.isWeb,
Likely, yes. For the current issue this PR addresses, no. When opening it up to native apps there a few GCT failures that need to be reviewed to determine if the test needs to be updated or if the implementation is missing something.

2022-10-24 15:24 UTC, tourdedave commented on js/packages/screenshoter/src/extract-coodinates-for-selectors-and-elements.js
> +          }
It seems likely that `y` would also need to be included in this, but it's not something I tested for. I was focused on the user reported issue.

2022-10-24 15:27 UTC, tourdedave commented
> @tourdedave I'm sure, I wasn't sure if the PR is fully completed, but I already saw your comment on the trello. So I left a full review.

I took it out of draft, removed the `WIP` tag, and marked you as a reviewer. When I do that, it's complete (a.k.a. ready for review) -- although I reserve the word "complete" for when something has been reviewed/tested/released. So... 🤷‍♂️

2022-10-24 15:39 UTC, kyryloonufriiev commented
@tourdedave Yes, I agree. Sorry about that.

2022-10-24 17:03 UTC, tourdedave commented on js/packages/screenshoter/src/take-screenshot.js
> +    compensateCoordinatesRelativeToParentRegion: !!region && driver.isWeb,
There were two native mobile GCT tests I think (I can't remember if there were others):

```
test/generic/AppiumIOSCheckRegionWithIgnoreRegion.spec.js
test/generic/AppiumAndroidCheckRegionWithIgnoreRegion.spec.js
```

For the first one, it seems like we already do the right thing. It's handled as part of the scaling logic in `extract-coordinates-for-selectors-and-elements`

```
driver    | 2022-10-24T16:48:57.091Z [INFO ] Extracted region { x: 131, y: 333, width: 113, height: 65 }
screenshoter| 2022-10-24T16:48:57.091Z [INFO ] scaled region { x: 115, y: 35, width: 113, height: 65 }
```

Makes me wonder why this isn't working for web as-is. Taking a closer look.

2022-10-24 18:17 UTC, tourdedave commented on js/packages/screenshoter/src/take-screenshot.js
> +    compensateCoordinatesRelativeToParentRegion: !!region && driver.isWeb,
The main difference I see so far is that a region screenshot on native mobile uses `takeSimpleScreenshot` and web uses `takeStitchedScreenshot`. For the web test I'm using (`core/test/e2e/classic/coded-regions.spec.ts`) it looks like the crop region that's calculated does not contain the correct `x`/`y` coordinates. If that's true, then I'd rather fix that then add compensation. I'll keep digging.

2022-10-25 10:11 UTC, kyryloonufriiev commented on js/packages/screenshoter/src/extract-coodinates-for-selectors-and-elements.js
> +          }
I would really prefer to spend more time to have a proper solution for the problem, not just a solution for the card.

2022-10-26 18:27 UTC, tourdedave commented on js/packages/screenshoter/src/extract-coodinates-for-selectors-and-elements.js
> +          }
We don't need this new compensation. The issue was coming from `calculate-screenshot-region.js`.

2022-10-26 18:28 UTC, tourdedave commented on js/packages/screenshoter/src/take-screenshot.js
> +    compensateCoordinatesRelativeToParentRegion: !!region && driver.isWeb,
The issue was coming from `calculate-screenshot-region.js`. Fixed in https://github.com/applitools/eyes.sdk.javascript1/pull/1129/commits/e1f2081ab62b978ee845fdeb4e37adec4a6cd879

2022-10-27 14:37 UTC, kyryloonufriiev approved these changes
I'm really glad we get to the bottom of the issue.

2022-10-27 15:13 UTC, tourdedave commented
I'll wait until https://github.com/applitools/sdk.coverage.tests/pull/168 is approved before merging, since they are intertwined.

2022-10-28 10:05 UTC, merged