Get `contentSize` without `Helper` in `IOS`
applitools/eyes.sdk.javascript1 pull request #1131
Opened 2022-10-13 12:48 UTC by zamboney

On older version of the SDK once there was no `Helper` there was a fallback for calculate the size of the element ([ref](https://github.com/applitools/eyes.sdk.javascript1/blob/9c6cb79c7eb048a04e64a09c5ec1c7173aaeaa9a/packages/driver/src/element.ts#L169-L179)).

This PR just restore this and add test for `IOS` to make sure that if there are no `Helper` the `contentSize` can be measure

2022-10-14 05:18 UTC, kyryloonufriiev requested changes

2022-10-14 05:18 UTC, kyryloonufriiev commented on js/packages/driver/src/element.ts
> +    }
What is the point of `switch` here if only one case exists? So it should be `if` here.

2022-10-14 05:18 UTC, kyryloonufriiev commented on js/packages/driver/src/element.ts
> +        })
Can you explain this comment better?

2022-10-14 08:10 UTC, zamboney commented on js/packages/driver/src/element.ts
> +    }
Np will do

2022-10-14 08:27 UTC, zamboney commented on js/packages/driver/src/element.ts
> +        })
The layout is arranged like it and this is how you need to get it.

Also this is how it's done in the [past](https://github.com/applitools/eyes.sdk.javascript1/blob/9c6cb79c7eb048a04e64a09c5ec1c7173aaeaa9a/packages/driver/src/element.ts#L173)

2022-10-16 17:20 UTC, kyryloonufriiev commented on js/packages/driver/src/element.ts
> +        })
I was asking about the comment in the code. I also don't understand in what exact case it should work. I know that this was implemented like this in Java, but I want to understand what is so special about this case. And couldn't it be solved in a more flexible way?

2022-10-18 11:33 UTC, merged