[driver] Add fallback and child selectors support
applitools/eyes.sdk.javascript1 pull request #1145
Opened 2022-11-01 14:53 UTC by kyryloonufriiev

[Trello](https://trello.com/c/ZYQdtJQN)

New selector formats:
A selector to look for elements within other elements (child selector):
```
{
  "type": "id",
  "selector": "my_id",
  "child": {
    "type": "class name",
    "selector": "my_class_name",
    "child": {
      "type": "xpath",
      "selector: "//my/xpath" 
    }
  }
}
```
A selector that looks for elements with fallback if they were not found (fallback selector):
```
{
  "type": "id",
  "selector": "my_id",
  "fallback": {
    "type": "class name",
    "selector": "my_class_name",
    "fallback": {
      "type": "xpath",
      "selector: "//my/xpath" 
    }
  }
}
```

Just an example of how a common selector could look like with all new capabilities:
```
{
  selector: 'frame1',
  frame: {
    selector: 'frame1-shadow1',
    shadow: {
      selector: 'frame1-shadow1-child1',
      child: {
        selector: 'frame1-shadow1-child1-frame1',
        frame: {
          selector: 'frame1-shadow1-child1-child1',
          fallback: {
            selector: 'frame1-shadow1-child1-frame1',
            frame: 'frame1-shadow1-child1-frame1-child1'
          }
        },
        fallback: 'frame1-shadow1-child1-child1'
      },
      fallback: {
        selector: 'frame1-shadow1-shadow1',
        shadow: {
          selector: 'frame1-shadow1-shadow1-child1',
          fallback: 'frame1-shadow1-shadow1-child2'
        },
        fallback: 'frame1-shadow1-child1'
      }
    },
    fallback: {
      selector: 'frame1-shadow2',
      shadow: {
        selector: 'frame1-shadow1-child1',
        child: {
          selector: 'frame1-shadow1-child1-frame1',
          frame: {
            selector: 'frame1-shadow1-child1-child1',
            fallback: {
              selector: 'frame1-shadow1-child1-frame1',
              frame: 'frame1-shadow1-child1-frame1-child1'
            }
          },
          fallback: 'frame1-shadow1-child1-child1'
        },
      },
    }
  },
  fallback: 'child1'
}
```

2022-11-01 17:43 UTC, tourdedave requested changes
Looks good overall. But how are we planning to test this e2e? Is it just for Java or are other languages include too (like dotnet)? A GCT that's just for affected languages maybe? Let me know what you think.

Also, you're missing a pending changes entry.

2022-11-01 17:43 UTC, tourdedave commented on js/packages/driver/src/context.ts
> +    } else if (all) {
Do we want to support when `wait` && `all` are both provided?

2022-11-02 08:41 UTC, kyryloonufriiev commented on js/packages/driver/src/context.ts
> +    } else if (all) {
`waitFor` method always returns only one element.

2022-11-02 09:35 UTC, kyryloonufriiev commented
I don't think the generic test is worth the effort if it is available only in Java.

2022-11-02 09:35 UTC, merged

2022-11-02 13:40 UTC, tourdedave commented
> I don't think the generic test is worth the effort if it is available only in Java.

Okay, but are they writing a test to verify that this works?

2022-11-02 13:47 UTC, tourdedave commented on js/packages/driver/src/context.ts
> +    } else if (all) {
What `waitFor` method? Do you mean `waitForSelector`? I don't see it implemented on any of the specs, so the fallback condition is likely used, which is a hand-rolled wait that, and yes, it returns just one element but I don't see how that's a relevant detail to what I was thinking. Isn't there a case where we would need to wait for a selector to be present before performing a `findElements`?

2022-11-02 13:48 UTC, IdosApplitools commented
> > I don't think the generic test is worth the effort if it is available only in Java.
> 
> Okay, but are they (@IdosApplitools & @danielputerman) writing a test to verify that this works?

Yes, I am currently working on adding e2e tests for that on our end :)