Handle reduced user agent
applitools/eyes.sdk.javascript1 pull request #1147
Opened 2022-11-03 19:10 UTC by kyryloonufriiev

2022-11-03 23:05 UTC, SophieDePaula reviewed
The changes around the `userAgent` vs the client hints make sense to me.
One question, why did you change executePoll?
Also, it would have helped me if you would have added a description of what you changed and why (even a few words about every change would have been helpful).

2022-11-04 01:42 UTC, tourdedave requested changes
+1 on @SophieDePaula's comments.

Also, I'm surprised to see that there isn't test coverage in snippets for `getBrowserInfo` to cover the different browser/OS combinations and each of the code paths.

2022-11-04 15:23 UTC, kyryloonufriiev commented
> One question, why did you change executePoll?
@SophieDePaula Because I need this to get browser info, so since we don't really want to implement `executeAsync` (which would mean a new spec method), our polling interface should be standardized in the driver package, and this is what I did.

2022-11-04 22:12 UTC, SophieDePaula commented on js/packages/driver/src/context.ts
> +        response = deserialize(await this.execute(pollScript, pollArg))
@kyryloonufriiev what happens if no `pollScript` is sent to `executePoll` like with `lazyLoading` and the `executionTimeOut` is not up?

2022-11-04 22:19 UTC, SophieDePaula reviewed
@kyryloonufriiev I left one comment, other than that, it looks good to me.

2022-11-05 09:33 UTC, kyryloonufriiev commented on js/packages/driver/src/context.ts
> +        response = deserialize(await this.execute(pollScript, pollArg))
You can see it from the implementation, you specified just one script which will be the user from both operations start and polling. Previously you always had to provide two scripts implicitly so in the case of lazyLoad we had to pass the same script for both operations. In huge scripts like dom-snapshot it made sense to create a separate script for polling to make requests smaller. But as we saw with Dave while he was implementing the lazy load feature for small scripts it makes no sense to do something like that.

2022-11-05 21:57 UTC, SophieDePaula approved these changes

2022-11-07 06:54 UTC, kyryloonufriiev commented on pending-changes.yaml
> +    - Use user agent metadata to improve browser environment detection logic
@benbabayoff8

2022-11-07 08:46 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Use user agent metadata to improve browser environment detection logic
@kyryloonufriiev Looks good.

2022-11-09 08:05 UTC, merged