coded regions, replace selector with region
applitools/eyes.sdk.javascript1 pull request #1153
Opened 2022-11-08 16:45 UTC by SophieDePaula

[Trello card](https://trello.com/c/uZxC9grz/1615-autodesk-incorrect-region-placement)
This PR purpose is to simplify the experience around coded regions. Currently, we support sending`selectore` and `region` properties, however, we support other options like `padding` and `regionId` only with `region` which is confusing for the customer.

TODO:
- [ ] look at accessibility and floating regions
- [ ] Make sure we have tests to cover the changes and the added secnarios

2022-11-09 08:04 UTC, kyryloonufriiev requested changes

2022-11-09 08:04 UTC, kyryloonufriiev commented on js/packages/driver/src/element.ts
> +    } else if (typeof this._selector === 'string') {
use `utils.types.isString(...)`

2022-11-15 07:21 UTC, kyryloonufriiev commented on js/packages/eyes-cypress/test/coverage/generic/package.json
> +    "cypress": "^10.0.0",
You can return the `latest` here after our solution for cypress@11 right?

2022-11-15 16:56 UTC, SophieDePaula commented on js/packages/eyes-cypress/test/coverage/generic/package.json
> +    "cypress": "^10.0.0",
@kyryloonufriiev I noticed that I get a webpack error when I try to run our tests with Cypress 11 that I need to investigate and I didn't want to delay the release of this and the other PR I am working on.
I'll upgrade our tests to run with cypress 11 after this is done.

2022-11-15 22:29 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Add support for regionId and padding for accessibility and floating regions
@benbabayoff8

2022-11-16 00:35 UTC, SophieDePaula commented on js/packages/eyes-cypress/test/coverage/generic/package.json
> +    "cypress": "^10.0.0",
@kyryloonufriiev it seems that the webpack error no longer occurs with cypress 11.1.0

2022-11-16 07:39 UTC, kyryloonufriiev approved these changes
Looks good to me

2022-11-16 16:33 UTC, merged