[eyes-cypress] add type definition for eyes plugin
applitools/eyes.sdk.javascript1 pull request #1171
Opened 2022-11-20 14:17 UTC by zamboney

This change will stop throwing error for the code below

```typescript

import eyes from '@applitools/eyes-cypress'
import { defineConfig } from 'cypress'
const config = defineConfig({
  fixturesFolder: false,
  video: false,
})
eyes(config) // Error, This expression is not callable.  Type 'typeof import("@applitools/eyes-cypress/index")' has no call signatures.

```

2022-11-21 07:41 UTC, amitzur requested changes
Please add e2e test.
Also, I'm not familiar with this syntax: `export = _exports`. Can you explain it or share a link to TS docs? Is it a feature of TS or just ESM?

2022-11-21 07:41 UTC, amitzur commented on pending-changes.yaml
> +    - Add typescript definition for eyes plugin
I would move this from `bug-fix` to `feature` and write `Support ESM and TypeScript in Applitools' config file`. I hope this is indeed the nature of this PR.

2022-11-21 08:20 UTC, zamboney commented on pending-changes.yaml
> +    - Add typescript definition for eyes plugin
done

2022-11-21 08:36 UTC, zamboney commented
> Please add e2e test.

not sure how to add `e2e` test but i will change the `test/e2e/ts/cypress/plugin/index.js` to `test/e2e/ts/cypress/index.ts` 

>  Also, I'm not familiar with this syntax: `export = _exports`. Can you explain it or share a link to TS docs? Is it a feature of TS or just ESM?

the syntax is what auto-generated by `tsc --declaration --allowJs --emitDeclarationOnly --outDir types`. i just took the product of `types/plugin/startPlugin.d.ts` and put it in `index.d.ts` so it will not throw a `typescript` error once using typescript

2022-11-21 13:09 UTC, amitzur commented
@zamboney an e2e test for this is taking the snippet you put in the description, and actually running it in an automated test. This is how to prove that the code actually solves this case.
I think it's important to add such a test and not just change `index.js` to `index.ts`.

2022-11-21 13:13 UTC, zamboney commented
@amitzur this is what i did, i changed the `plugin.js` to `plugin.ts` and changed the code so it will support the new type definitions

2022-11-21 18:36 UTC, kyryloonufriiev commented
I don't think this is the right solution in general. Why would we have to wrap the whole config object if we want to modify just one property of it?

2022-11-21 18:40 UTC, kyryloonufriiev commented
This is a random cypress plugin that I found by googling "cypress plugins" - https://github.com/Shelex/cypress-allure-plugin. It has a more clear forward setup logic, I think this is what we have to provide for the people who wanna take a manual step to setup applitools.

2022-11-21 19:25 UTC, zamboney commented
@kyryloonufriiev I'm not sure what exactly you want me to change?
It's just for the setting of the plugin, not for the `eyes` usage, all the customer wants, in the ticket is to be able to set the plugin in `typescript` without the right definition and without using `@ts-ignore`.
If you understand it differently please care to explain

2022-11-21 19:30 UTC, kyryloonufriiev commented
Do you see how plugins setup works in this package I shared? We should do the same. Because this is more transparent and clearer API for the end user.

2022-12-05 15:06 UTC, kyryloonufriiev requested changes
I think the current implementation is trying to make something work on top of what we have. While deeper understanding is definitely required here. I see that the `eyesPlugin` method still has the logic that works with `module.exports` stuff, this could not be right. The `eyesPlugin` should do only what is required to do - run the universal server/setup hooks/modify cypress config, and that's it everything else (module.exports) related to a different function wrapper that is created around this function to work with the module object.

2022-12-05 15:29 UTC, zamboney reviewed
@kyryloonufriiev i don't want to make a huge change base on a ticket of something else.

i sure that there is a task on it and once we will have time to do it we will. in the meanwhile we are not fix a typescript error that just look bad...

2022-12-05 15:29 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
it's should not be populated. this is for the `setupNodeEvents`. if there is  a `e2e` or `component` then it will use the `setupNodeEvents` directly like so 

```typescript
import { defineConfig } from 'cypress'
import { eyesPlugin } from 'eyes-cypress'

export default defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
       eyesPlugin(on, config)
    }
  }
})
```

2022-12-06 07:55 UTC, kyryloonufriiev commented
If we would wait for tickets for everything we do we would be in a much worse position. I think we should be in a mindset of improving everything we touch, not just rush with addressing exactly what bothering this particular customer. Tomorrow there will be another one that would want to use it with esm and it won't be possible.
I see this card as an opportunity to improve the plugin setup process that we have, so not just address an issue but improve the area around it.

2022-12-06 07:56 UTC, kyryloonufriiev commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
If I do what you wrote in the example it still will not be populated. Or am I missing something?

2022-12-06 09:16 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
I just tested it, and it's working (you need to add the eyes `command`, just like in the example your share)

But it still needs small changes


```js
import { defineConfig } from 'cypress'
import { eyesPlugin } from 'eyes-cypress'

export default defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
       const eyesConfig = await eyesPlugin(on, config);
       return { ...config, ...eyesConfig};
    }
  }
})
```

i think that this is a great approach @amitzur what do you think?

2022-12-06 10:12 UTC, kyryloonufriiev commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
I wasn't saying it is not going to work, but did you check if `pluginExportsE2E`/`pluginExportsComponent` were populated? I think they didn't and this is correct, but this raise a question for me, should it even be written in the place it is right now?
Feel free to correct me if I am missing something.

2022-12-06 10:53 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
if you are not passing the `pluginExports` then of course it will not populate in the configuration above. but way it should be? if you use the configuration above then you are not using the old `require('@applitools/eyes-cypress')(module)` and therefor you need to setup each `e2e` and `component` on his own

2022-12-08 11:47 UTC, kyryloonufriiev commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
If it will not be used then why should it be there? My point is that if I use `eyesPlugin(on, config)`, then I don't need this code, which means this code should not even be there.

2022-12-08 13:35 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
i could not figure out an easy way to remove it without breaking everything... i think in this point of the pr is ok to leave it like so

2022-12-12 09:57 UTC, amitzur commented
> > Please add e2e test.
> 
> not sure how to add `e2e` test but i will change the `test/e2e/ts/cypress/plugin/index.js` to `test/e2e/ts/cypress/index.ts`
> 
> > Also, I'm not familiar with this syntax: `export = _exports`. Can you explain it or share a link to TS docs? Is it a feature of TS or just ESM?
> 
> the syntax is what auto-generated by `tsc --declaration --allowJs --emitDeclarationOnly --outDir types`. i just took the product of `types/plugin/startPlugin.d.ts` and put it in `index.d.ts` so it will not throw a `typescript` error once using typescript

I was looking for this reference:
https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

2022-12-13 07:16 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/pluginExport.js
> +        config.testingType === 'e2e' ? pluginExportsE2E : pluginExportsComponent;
@kyryloonufriiev can you please replay

2022-12-13 10:17 UTC, amitzur commented
@zamboney @kyryloonufriiev Let me try to do some order in the next steps:

1. Let's just make it clear what scenarios we wish to support.
2. Let's decide what we want to cover in this PR. IMO if we're already working on it, we should just support all the possible scenarios (there shouldn't be too much) and be done with it.
3. We should cover all these scenarios in e2e tests.
4. Understand the implications on `eyes-setup`, and do adjustments if necessary (including tests)
5. Make sure all scenarios are documented properly.
6. Ship it!


So, here are the scenarios I see and would like to support, and the proposition of how to support them:

1. `pluginsFile` in CJS
```
module.exports = (on, config) => {
  // ...
}
require('@applitools/eyes-cypress')(module)
```

2. `cypress.config.js` in CJS
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});

require('@applitools/eyes-cypress')(module)
```

3. `cypress.config.ts` or `cypress.config.mjs` (ESM)
```
import {defineConfig} from 'cypress';
import {eyesPlugin} from '@applitools/eyes-cypress';

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      eyesPlugin(on, config)
    },
  },
});
```

4. `pluginsFile` in ESM
```
import {eyesPlugin} from '@applitools/eyes-cypress';
export default (on, config) => {
  // ...
  eyesPlugin(on, config)
}
```

In short, the new thing we aim to provide in this PR is a new API for ESM (and TS, wow so many acronyms...).
Since the proposed ESM support is harder to generate automatically in the `eyes-setup` script, we need to instruct the user to do it manually, preferably by detecting this situation in `eyes-setup` and then recommending the manual solution to the user.

I hope this makes it clearer, and also that my proposition makes sense to you.

2022-12-14 08:31 UTC, amitzur commented
@zamboney yep

2022-12-14 09:02 UTC, amitzur commented
@kyryloonufriiev @zamboney I tend to agree. In my words - the `pluginExport.js` file has become a little monster, much more than it was planned, with patches added to it over time. I tend to agree that we have already spent a lot digging into this PR, so now it's a good time to sort it out.

To put it in technical terms - I would refactor it into TS, and separate wrapper function (which is what `pluginExport.js` was meant to be) with the actual **plugin** (currently named `setupNodeEvents`). This way we could also unit test many scenarios without the need for e2e for **all** combinations (e.g. both `e2e` and `component`, AND each of them alone). I do think that e2e tests should exist for all 4 scenarios that I described above.

@zamboney - are you good with this?

2023-01-11 08:46 UTC, amitzur reviewed
I reviewed about 30% of the PR so far. I thought I would sumbit a review and then continue.
See my inline comments, and also `yarn test:e2e` doesn't even run because of the missing `@applitools/test-server` depenedency. Did you verify that all tests pass?

2023-01-11 08:46 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.json
> +    "esModuleInterop": true
Does it mean that our users need to have `esModuleInterop:true` and `allowSyntheticDefaultImports:true` in their tsconfig.json as well?

2023-01-11 11:44 UTC, zamboney commented on js/packages/eyes-cypress/test/fixtures/testAppCypress10/cypress.config.js
> +const {defineConfig} = require('./node_modules/cypress');
I had an issue with typescript, i solve it without using `./node_modules` but i forgot to remove this line. I will remove it. Thanks for the feedback

2023-01-11 11:44 UTC, zamboney commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.json
> +    "esModuleInterop": true
I'm not sure how it's work before before my changes but this isn't work now without it... we need to mention it and maybe upgrade a major version?

2023-01-11 11:44 UTC, zamboney commented on js/packages/eyes-cypress/README.md
> - Add the following code to your `cypress.config.js` file after `module.exports`:
but this explain in the section above? isn't it enough?

2023-01-11 11:49 UTC, zamboney commented
@amitzur about verify that it's work [this action](https://github.com/applitools/eyes.sdk.javascript1/actions/runs/3817382577) run on this branch and pass

2023-01-19 10:43 UTC, amitzur requested changes
General notes:
1. Most of the code that was changed from JS to TS has types that are just `any`. I think it's fine not to add all types right now, but then let's not call it "refactor JS to TS", since there is no added value in it. So we should be aware that there is a task waiting to actually write types in the Eyes-Cypress SDK codebase.
2. I think the solution with the `ttsc` is clever and valid. Although I am curious to know how to fix `api-extractor`, I will hold my curiousity in favor of focusing on what matters :)
3. I haven't gone over the CI files yet. Those are the only ones left for me to review.

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/config.ts
> +import {type EyesConfig} from './../expose'
no need for `./../`, just `../`

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/pluginExport.ts
> +import {type EyesConfig} from './../expose'
no need for `./../`, just `../`

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/setupNodeEvents.ts
> +import {type EyesConfig} from './../expose'
no need for `./../`, just `../`

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/index.ts
> +import {type EyesConfig} from '../expose' // eslint-disable-line @typescript-eslint/no-unused-vars
You can also define the type and export it from here, instead of in `expose.ts`. It will do the same thing. I would leave the comment, though, it's great.
I would also add to the comment that the absolute path is added because TS (or api-extractor?) goes over the `eyesPlugin` declaration before it goes over the `EyesConfig` definition, and this is why it's importat to reverse the order.

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/setupNodeEvents.ts
> +  return async function (origOn: Cypress.PluginEvents, cypressConfig: Cypress.PluginConfigOptions): Promise<EyesConfig> {
The parameter name is important here, since it shows up to the user. So I would change `origOn` to `on` and `cypressConfig` to `config`. And add a comment about why the parameter names are important :)

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/setupNodeEvents.ts
> +import makeGlobalRunHooks from './hooks'
I would rename this file from `setupNodeEvents` to something like `eyesPlugin` or `startPlugin`. And I would have a named export called `makeEyesPlugin`, because that's essentially what it's doing.

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/setupNodeEvents.ts
> +    if (eyesConfig.eyesIsGlobalHooksSupported) {
This will never be true, because `eyesIsGlobalHooksSupported` is assigned a value in `pluginExport`. I would like this bug to be covered in a test. This is exactly the type of regressions we keep having in Cypress because this is a fragile area that is sensitive to how the user uses the SDK.

The test should check that the functionality that is done in the global hooks is actually performed when using the `eyesPlugin` directly.

I can also argue that this if statement is not necessary at all, because this is the new way to do things, and only new Cypress versions would use it.

2023-01-19 10:43 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/pluginExport.ts
> +      const globalHooks: any = makeGlobalRunHooks({
It's a shame that we can't call the code in `setupNodeEvents` (which I think should be renamed) here. There's risky code duplication here. I understand why, and I don't have a solution for it :(

2023-01-19 15:34 UTC, zamboney reviewed
@amitzur thank you for the great review 🎉
i still need to test the `eyesIsGlobalHooksSupported` issue but i think remove it is the good approach and so i did

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/setupNodeEvents.ts
> +  return async function (origOn: Cypress.PluginEvents, cypressConfig: Cypress.PluginConfigOptions): Promise<EyesConfig> {
done

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/setupNodeEvents.ts
> +import {type EyesConfig} from './../expose'
done

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/setupNodeEvents.ts
> +    if (eyesConfig.eyesIsGlobalHooksSupported) {
you right i miss that 🤦, i will add a test for that

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/webSocket.ts
> +    // @ts-ignore
i will 10x

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/webSocket.ts
> +    // @ts-ignore
i will 10x

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/test/e2e/ts/cypress-12.config.ts
> +import {defineConfig} from 'cypress12'
you think that but you need to `import` the right `cypress` version and then `export` this `defineConfig`. it can be done if you create the `cypress.config.ts` dynamically is it worth it? I think it's better to have 3 files than to have a dynamic file.

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/test/e2e/ts/cypress-12.config.ts
> +import {defineConfig} from 'cypress12'
you think that but you need to `import` the right `cypress` version and then `export` this `defineConfig`. it can be done if you create the `cypress.config.ts` dynamically is it worth it? I think it's better to have 3 files than to have a dynamic file.

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/test/e2e/ts/cypress/plugins/index.js
> -module.exports = (_on, _config) => {}
no... its used for testing

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/test/fixtures/cypressConfig-global-hooks-overrides-config-file.js
> +const {defineConfig} = require('./node_modules/cypress');
sure fixed

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/types/index.d.ts
> +/// <reference types="cypress" />
`cypress` browser commands definitions read `types/index.d.ts` by default

2023-01-19 15:34 UTC, zamboney commented on js/packages/eyes-cypress/types/index.d.ts
> +import {eyesPlugin} from './expose'
done

2023-01-22 08:13 UTC, amitzur commented on js/packages/eyes-cypress/src/browser/spec-driver.ts
> +export function getViewportSize(): any {
@zamboney ping

2023-01-22 08:16 UTC, amitzur commented on js/packages/eyes-cypress/README.md
> + ##### `cypress.config.js`
Good point. Well, they have this interactive widget that makes it easier to see the difference. I respect your approach :)

2023-01-22 08:18 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/errorDigest.ts
> +function stringifyTestResults(testResults: any) {
I guess using `noImplicitAny: false` in `tsconfig` would remove it. I don't see great value in these TS errors, as the solution for them is just adding `any` everywhere. WDYT?

2023-01-22 08:30 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/server.ts
> +    const port = (https.address() as AddressInfo).port
You are right that `server.listen` doesn't return a Promise, and the `await` keyword that was there is a mistake. But the more important part is that the `port` is set in the callback. So I don't think it's just good measure. I think it's good that you promisify it. Let's keep sending `0` as the port.

2023-01-22 08:33 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/server.ts
>            logger.log('@@@', err)
Yes, that's what I meant. I added this a while back.

2023-01-22 08:34 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress-12.config.ts
> +import {defineConfig} from 'cypress12'
Oh, I didn't notice it. Sorry.

2023-01-22 08:36 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/plugins/index.js
> -module.exports = (_on, _config) => {}
This file was deleted. I guess github just doesn't shows it properly.

2023-01-22 08:39 UTC, amitzur commented on js/packages/eyes-cypress/types/index.d.ts
> +/// <reference types="cypress" />
Do you have a reference for it? (I mean I believe you, I'm just curious to learn more)

2023-01-22 08:39 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/plugins/index.ts
> +export default eyesPlugin
@zamboney :point_up:

2023-01-22 08:39 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.json
> -    "noImplicitAny": true,
@zamboney :point_up:

2023-01-22 08:41 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/server.ts
> +    const managers: {manager: string; socketWithUniversal: SocketWithUniversal}[] = []
@zamboney you changed it to `object`. I think `any` is fine. And shouldn't it be `Object` (uppercase O)?

2023-01-23 17:15 UTC, zamboney commented
@amitzur please take another look 👀 . I added `userGlobalHook` support!

2023-01-23 17:17 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/eyesPlugin.ts
> +}
This idea to check if plugins exist is from [this](https://github.com/Shelex/cypress-allure-plugin/blob/master/writer/checkPluginsFile.js) plugin

@amitzur ☝️

2023-01-30 17:17 UTC, zamboney reviewed
@amitzur the `e2e` test [pass](https://github.com/applitools/eyes.sdk.javascript1/actions/runs/4044339065/jobs/6954394238) `node16` (the other tests just stack) so i thing we are good to go. 

i'm running the `e2e` test again (just in case) once i submit this comment so i think after you refer to my replay we are g2g

2023-01-30 17:17 UTC, zamboney commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.json
> +    "types": ["cypress", "../../../..", "node"],
@amitzur, the `"node"` type is required for using the `NodeJS.Module` type. if you think we could drop this and use custom type instead

2023-01-30 17:17 UTC, zamboney commented on js/packages/eyes-cypress/test/e2e/ts/cypress/plugins/index.ts
> +export default eyesPlugin
this is the syntax for [cypress < 10](https://docs.cypress.io/guides/tooling/typescript-support#Types-for-plugins)

2023-01-30 17:17 UTC, zamboney commented on js/packages/eyes-cypress/types/index.d.ts
> +/// <reference types="cypress" />
No, but I try it in other ways and it would not work...

2023-01-31 09:12 UTC, amitzur commented on js/packages/eyes-cypress/index.js
> +// This is the main entry point of our application
@zamboney why do you still need this file?

2023-01-31 09:13 UTC, amitzur commented on js/packages/eyes-cypress/package.json
> +  "main": "./index",
@zamboney why not `dist/plugin/index.js`? And why not specify the file suffix?

2023-01-31 09:16 UTC, zamboney commented on js/packages/eyes-cypress/index.js
> +// This is the main entry point of our application
only for good measure, i can remove it if you think its unnecessary

2023-01-31 09:16 UTC, zamboney commented on js/packages/eyes-cypress/package.json
> +  "main": "./index",
same as last comment

2023-01-31 09:23 UTC, amitzur commented on js/packages/eyes-cypress/src/expose.ts
> +export * from './plugin'
@zamboney change this to `export {type EyesPluginConfig} from './plugin'`

2023-01-31 09:26 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/errorDigest.ts
> +function stringifyTestResults(testResults: any) {
how is it going to help you? you will search for `: any` in the code and start fixing? anyway, here I don't have a strong opinion so go with however you feel is right.

2023-01-31 09:27 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/index.ts
> +export const eyesPlugin = makeEyesPlugin({
@zamboney You no longer need this in the new proposal

2023-01-31 09:31 UTC, zamboney commented on js/packages/eyes-cypress/src/expose.ts
> +import {type EyesPluginConfig} from './plugin' // eslint-disable-line @typescript-eslint/no-unused-vars
i can remove the `EyesPluginConfig` but `CypressTestResultsSummary` will not work with for `yarn test:ts` it's needed [here](https://github.com/applitools/eyes.sdk.javascript1/blob/ae0eb70937c7a65042057fa1fff7b326324bbf48/js/packages/eyes-cypress/types/index.d.ts#L45)

```
yarn run v1.22.19
$ yarn test:ts:compile && yarn test:ts:run
$ tsc --project test/e2e/ts/cypress
types/index.d.ts:2:65 - error TS2614: Module '"./expose"' has no exported member 'CypressTestResultsSummary'. Did you mean to use 'import CypressTestResultsSummary from "./expose"' instead?

2 import {type CypressCheckSettings, type CypressEyesConfig, type CypressTestResultsSummary} from './expose'
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-01-31 09:32 UTC, amitzur commented on js/packages/eyes-cypress/src/setup/handlePlugin.js
> +${chalk.green.bold('import eyesPlugin from "@appliitools/eyes-cypress"')}
@zamboney typo! `appliitools`. This is user facing, please proof read it 10 times!

2023-01-31 09:37 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/index.ts
> +export const eyesPlugin = makeEyesPlugin({
sure

2023-01-31 09:38 UTC, amitzur commented on js/packages/eyes-cypress/src/setup/handlePlugin.js
> +const {parse, first} = require('abstract-syntax-tree')
@zamboney I think the use of AST here is cool, but you introduce more noise than value, and we really want to converge in this PR.
For example, how does this behave if the user's file is not a valid JS/TS file? Does this library support TS? Is there an advantage to using this library over anything else from https://astexplorer.net/ ?
The usage we need is really basic. You might as well just look for a regex just like we do in commonJS. And detecting commonJS in the plugins file is IMO just a matter of looking for `module.exports`.

I think it's fine to push this route in the future, but if you do, I expect a rich suite of tests.
Please, let's focus on the core functionality in this PR.

2023-01-31 09:39 UTC, amitzur commented on js/packages/eyes-cypress/types/index.d.ts
> +export {eyesPlugin} from './expose'
@zamboney no need for this with the new proposal

2023-01-31 09:39 UTC, amitzur commented on js/packages/eyes-cypress/types/index.d.ts
> +/// <reference types="cypress" />
ok. we need to make sure it doesn't brake in future versions

2023-01-31 09:42 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.json
> +    "esModuleInterop": true
no, no - if this requires the user to add these flags then we need to change how we do things. We can't upgrade a major version.

2023-01-31 09:43 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.json
> +    "types": ["cypress", "../../../..", "node"],
@zamboney This is not good. It means the user needs to do this as well.
Use `import type Module from 'module'` in order to use `Module`, instead of requiring the user to import the node types.

2023-01-31 09:46 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/plugins/index.ts
> +export default eyesPlugin
@zamboney I honesty don't understand where you see this sort of syntax used, including the link you referenced.

2023-01-31 09:47 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/eyesPlugin.ts
> +}
@zamboney I don't undertand

2023-01-31 09:50 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/eyesPlugin.ts
> +export function makeEyesPlugin({startServer, eyesConfig, logger}: any) {
@zamboney I don't know why you didn't touch this file, but it should be completely changed. Now **in the new API** you have access to the `on` method in both ESM and CJS.
The separation I talk about is that `pluginExport` is responsible to find the `on` and `config`, and then pass them to `eyesPlugin`, which should be in this file, and act identically in all cases.
Currently `pluginExport.ts` has a function called `setupNodeEvents` inside, which is essentially the `eyesPlugin`. Please refactor that function out of `pluginExport` and put it in this file.
There is no more need to have a named export called `eyesPlugin`. Only a default export.

2023-01-31 09:51 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/pluginExport.ts
> +  return function pluginExport(pluginInitArgs: Cypress.ConfigOptions | NodeJS.Module) {
```
import type Module from 'module'
//...
return function pluginExport(pluginInitArgs: Cypress.ConfigOptions | Module) {
```

This way you won't require your users to import the node builtin types.

2023-01-31 09:53 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/eyesPlugin.ts
> +export function makeEyesPlugin({startServer, eyesConfig, logger}: any) {
i remove this file... no need it anymore

2023-01-31 09:53 UTC, amitzur commented
@zamboney I think given the magnitude of this PR, we can't settle for "tests are stuck on Node 12 and 14".
We can remove Node 12 since it's end of life. Let's switch that to Node 18. But everything needs to be green in order to release this PR. I would add that we should also safe-proof it with some manual testing :scream:

2023-01-31 09:58 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/pluginExport.ts
> +  return function pluginExport(pluginInitArgs: Cypress.ConfigOptions | NodeJS.Module) {
@amitzur it's not working...

2023-01-31 10:40 UTC, zamboney commented on js/packages/eyes-cypress/src/plugin/pluginExport.ts
> +  return function pluginExport(pluginInitArgs: Cypress.ConfigOptions | NodeJS.Module) {
not working...

2023-01-31 12:55 UTC, zamboney commented
@amitzur after running the "cypress publish" `github` action, i will try to explain why we need `index.js` in the root of the project and how it solves the `"esModuleInterop": true` problem.

once set to  `"esModuleInterop": true` it's try (among other stuff it does) to get the `default` value of an object once `require` it (for example, in the legacy cypress [here](https://github.com/applitools/eyes.sdk.javascript1/blob/1529-cypress-typescript/js/packages/eyes-cypress/test/e2e/ts/cypress/plugins/index.ts)). this works once we remove the root `index.js` and move it to `./dist/plugin/index.js` because there `tsc` (using `ttsc`) expose the code like so:`exports.default = pluginExport;`.

this will all work fine but we **still need to support** the legacy `cypress@9`. and once I run the `e2e` tests it start throwing error because we are `require` it without the `default` like [here](https://github.com/applitools/eyes.sdk.javascript1/blob/fc3467a216ae8b2fbfbbe7dd5319437e595265ce/js/packages/eyes-cypress/test/fixtures/testApp/cypress/plugins/index-run.js#L4).

To fix the `"esModuleInterop": true` and keep the legacy code without breaking changes, i added the `index.js` file that export, by default, the `module.exports = expose.default` also `Object.defineProperty(module.exports, 'default', {value: expose.default})` so that if the client does not set `"esModuleInterop": true` it will work

I hope it's makes sense ✌️

2023-01-31 14:01 UTC, amitzur approved these changes
This is a great milestone!

I'm glad the user doesn't need to add `esModuleInterop` to their TS config.
Please remove the ESM detection with AST part from eyes-setup.

So to recap
- There **is** a requirement to have `"node"` types in tsconfig. But we are fine with it since it's also documented by Cypress itself: https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfigjson
- There **is** a requirement to have `moduleResolution` set to `node` or `node16`, and we are fine with it since `node` is a recommended practice in Cypress. We will have motivation to solve this only if we hear about it from a customer/PoC.
- This PR adds the ability to test Cypress with the `Test packages` workflow.
- Leftovers:
  a) Reduce test time
  b) Refactor `eyesPlugin` out of `pluginExport`
  c) Improve setup script with AST analysis
  d) Test on future version of Cypress
  e) Add proper types everywhere there's `any`
 
Anything I forgot?

Great work @zamboney ! This was a long one :)

2023-01-31 16:08 UTC, kyryloonufriiev commented on .gitignore
> +js/packages/@applitools/
If you need something like that, you should add it in js' `.gitignore`

2023-01-31 16:59 UTC, merged