check that we get a real shadowRoot in add and cleanup ElementIds
applitools/eyes.sdk.javascript1 pull request #1182
Opened 2022-12-01 19:12 UTC by SophieDePaula

[Trello card](https://trello.com/c/kQT5e0SL/1607-mfs-java-error-when-taking-region-screenshot-or-using-coded-region)

2022-12-01 20:57 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Handle fake shadowRoot with UFG
@benbabayoff8

2022-12-01 21:18 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Handle fake shadowRoot with UFG
@SophieDePaula looks good to me.

2022-12-03 07:24 UTC, kyryloonufriiev commented on js/packages/snippets/src/browser/addElementIds.js
> +      element.getRootNode().constructor.name === 'ShadowRoot'
You do this check twice. In this if-statemen and in the for-loop. I would remove the one in if-statement, since here you just need to check that this method even exists, it will not exist in ie or other old browsers.

2022-12-03 07:26 UTC, kyryloonufriiev requested changes

2022-12-06 07:48 UTC, merged