[eyes-universal] add support to `node14-linux-arm64`
applitools/eyes.sdk.javascript1 pull request #1196
Opened 2022-12-08 15:20 UTC by zamboney

2022-12-12 07:58 UTC, kyryloonufriiev approved these changes

2022-12-12 08:03 UTC, kyryloonufriiev requested changes
I did approve it. But on second thought I understand that we don't have a test for that. We usually test new binaries with a gh action matrix, I'm not sure if you can run arm + Linux there, but worth an investigation. Also, I don't get how the newly generated file will be named. `eyes-universal-linux-arm64`?

2022-12-12 10:34 UTC, zamboney commented
About the name, it's generated by `pkg` and it's `eyes-universal-linux-arm64` under the `bin` folder. I will check the `gh action` and get back to you. Thanks for the feedback.

2022-12-12 11:27 UTC, zamboney commented
@kyrylo 

there are no `arm64` image as part of the [running-images](https://github.com/actions/runner-images) that `github action` support, so as far as i can see it there are 2 options to add the test you want:

  1. add a new ["self-hosted" runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) that will run on `os: arm64`
  2. add a new `gh action` that will run on `os: ubuntu-latest` and `container: amd64/node` [link](https://hub.docker.com/r/amd64/node/)

The first options not recommenced as they write in there docs:
> Warning: We recommend that you only use self-hosted runners with private repositories. This is because forks of your public repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.

The second options is more workaround as it will require to build the docker image with the `arm64` binary and run it on **none** `amd64` machine. This is exactly what `pkg` done so i think is fine

WDYT?

2022-12-12 14:05 UTC, kyryloonufriiev commented
So the second option looks like exactly what we are doing today with alpine test, no? If so please add it to the workflow

2022-12-14 13:18 UTC, zamboney commented
So the second options not working, `github action` [not supporting](https://github.community/t/running-docker-container-on-arm64-host/128624/2) running `amd64` container on `arm64` host. I will try to find another way to test it. Thanks for the feedback.

2022-12-14 16:00 UTC, kyryloonufriiev commented
I don't think you need to spend any more time on that. We can skip the testing for now. The assumption was that it might be very easy to add a test but since it takes more time that I was expecting we can skip the testing

2022-12-14 16:03 UTC, zamboney commented
i finally figured out how to run the tests! If you take a look at the `github action` `workflow` i change and let me know if this is a good fit...

2022-12-21 09:32 UTC, kyryloonufriiev requested changes
Well done. I wrote some small comments, but I like the idea, I would love to reuse our action for testing but this solution is also good enough.

2022-12-21 09:32 UTC, kyryloonufriiev commented on js/packages/eyes-universal/package.json
> +    "build:bin:arm64": "pkg -t node14-linux-arm64 -o bin/eyes-universal-linux-arm64 .",
I think we should re-name stuff here. `yarn build` is always should be something complete. It was dist + bin before, but now you cannot get complete build of binaries at all. So I would recommend `yarn build` being simply `yarn build:dist`, then you have `yarn build:bin:x64` and `yarn build:bin:arm64` that build binaries for specific platforms (BTW you can remove config for `pkg`, since there two build modes it is just confusing at this point), then you can have `yarn build:x64` and `yarn build:arm64` just to combine dist + bin:{arch}.

2022-12-21 09:32 UTC, kyryloonufriiev commented on .github/workflows/publish-universal.yml
> +          tar -czf ./bin/eyes-universal.tar.gz $(find ./bin -type f -not -name '*.zip' -not -name '*.tar.gz' | xargs)
why you don't use `yarn` commands? The point of this job is also lost to me. Why you cannot create archives at the point you really need them, in publish job?

2022-12-21 09:32 UTC, kyryloonufriiev commented on .github/workflows/publish-universal.yml
> +        if: ${{env.arch == ''}}
Isn't it possible to simply check for `matrix.arch` in `if`?

2022-12-21 09:32 UTC, kyryloonufriiev commented on .github/workflows/publish-universal.yml
> +        if: ${{env.arch == ''}}
Also `whatever.arch == ''` is a bit confusing you can simply add `x64` where you use this arch, so it will be more self-explanatory.

2022-12-21 09:32 UTC, kyryloonufriiev commented on .github/workflows/publish-universal.yml
> +            esac
I understand you copied it from the example for that action, but can we simplify this thing for our use? I don't think we care about anything that is not ubuntu.

2022-12-21 09:32 UTC, kyryloonufriiev commented on .github/workflows/publish-universal.yml
> +        if: ${{env.arch == ''}}
Also if you have `arch` for everything you will be able to avoid having `arch-group` since it basically always should be the same.

2022-12-21 09:32 UTC, kyryloonufriiev commented on .github/workflows/publish-universal.yml
> +            artifact_name: universal-${{ matrix.distro }}_${{ matrix.arch }}
Do you use it?

2022-12-21 09:55 UTC, zamboney commented on .github/workflows/publish-universal.yml
> +            artifact_name: universal-${{ matrix.distro }}_${{ matrix.arch }}
yes...

2022-12-21 09:55 UTC, zamboney commented on .github/workflows/publish-universal.yml
> +            esac
np i will

2022-12-21 09:55 UTC, zamboney commented on .github/workflows/publish-universal.yml
> +          tar -czf ./bin/eyes-universal.tar.gz $(find ./bin -type f -not -name '*.zip' -not -name '*.tar.gz' | xargs)
i don't want to have a long command in the `package.json` `scripts` but i can move it to `sh` file in the `workflow` if it's suite your need

2022-12-21 09:55 UTC, zamboney commented on js/packages/eyes-universal/package.json
> +    "build:bin:arm64": "pkg -t node14-linux-arm64 -o bin/eyes-universal-linux-arm64 .",
i don't understand what you are want me to do here please write it as snippet

2022-12-21 09:55 UTC, zamboney commented on js/packages/eyes-universal/package.json
> -    "postversion": "bongo postversion --skip-release-notification"
my bad i will revert it

2022-12-21 09:56 UTC, zamboney commented on .github/workflows/publish-universal.yml
> +            shell: bash
no reason i will change it back

2022-12-21 10:41 UTC, zamboney commented on .github/workflows/publish-universal.yml
> +          tar -czf ./bin/eyes-universal.tar.gz $(find ./bin -type f -not -name '*.zip' -not -name '*.tar.gz' | xargs)
you need to unify the `x64` and the `arch64` artifact into one artifact and i want to keep the `publish` step as it was. I think of the "publish" step as a step to publish resources to create or modify them...

2022-12-21 10:42 UTC, zamboney commented on .github/workflows/publish-universal.yml
> -          test-type: it
?

2022-12-21 11:05 UTC, kyryloonufriiev commented on .github/workflows/publish-universal.yml
> +          tar -czf ./bin/eyes-universal.tar.gz $(find ./bin -type f -not -name '*.zip' -not -name '*.tar.gz' | xargs)
You already have yarn commands to create archives, and 1st and 2nd commands are looks redundant to me. I understand the intent to separate bundling from publishing, it would be nice if it cost us nothing, but in this case, it causes another job to spin up for no actual reason. I don't see anything wrong with creating archives from artifacts in the separate step of the publishing job.

2022-12-21 11:31 UTC, zamboney commented on .github/workflows/publish-universal.yml
> +          tar -czf ./bin/eyes-universal.tar.gz $(find ./bin -type f -not -name '*.zip' -not -name '*.tar.gz' | xargs)
i need the first line to move the `arm64` artifact to the `x64` files and the 2nd line to clean old `zip` and `tar.gz` files that were created in the `x64` bundle.

About the time it takes, take a look [here](https://github.com/applitools/eyes.sdk.javascript1/actions/runs/3706224633/jobs/6281322052) it took 1s to set up the job. all of the steps, if it is done on `bundle` or in `publish`, will take the same time, so i don't see any reason to change its location

2022-12-21 11:47 UTC, kyryloonufriiev commented on js/packages/eyes-universal/package.json
> +    "build:bin:arm64": "pkg -t node14-linux-arm64 -o bin/eyes-universal-linux-arm64 .",
something like that
```suggestion
    "build": "yarn build:dist",
    "build:dist": "tsc",
    "build:x64": "yarn build:dist && yarn build:bin:x64",
    "build:arm64": "yarn build:dist && yarn build:bin:arm64",
    "build:bin:x64": "pkg . --target node14-linux-x64,node14-alpine-x64,node14-macos-x64,node14-win-x64",
    "build:bin:arm64": "pkg . --target node14-linux-arm64 --output ./bin/eyes-universal-linux-arm64",
```

2022-12-21 12:18 UTC, zamboney commented on js/packages/eyes-universal/package.json
> +    "build:bin:arm64": "pkg -t node14-linux-arm64 -o bin/eyes-universal-linux-arm64 .",
i don't see any reason to change it this way... i think that the old way (a.k.a. using the `pkg` section) still more straight forward

2022-12-27 12:19 UTC, kyryloonufriiev commented on js/packages/eyes-universal/package.json
> +    "build:bin:arm64": "pkg -t node14-linux-arm64 -o bin/eyes-universal-linux-arm64 .",
I think it is confusing. When someone will find pkg config that has `targets` by default you are thinking that this is all of the targets we are going to use.

2022-12-27 12:21 UTC, zamboney commented on js/packages/eyes-universal/package.json
> +    "build:bin:arm64": "pkg -t node14-linux-arm64 -o bin/eyes-universal-linux-arm64 .",
i don't think so... i think that this is the `x64` config and you can understand it by the naming of the script

2022-12-27 13:39 UTC, merged