[eyes-webdriverio-5] bad version `webdriverio@7`
applitools/eyes.sdk.javascript1 pull request #1206
Opened 2022-12-18 11:42 UTC by zamboney

`webdriverio@7.28.0` [version](https://github.com/webdriverio/webdriverio/releases/tag/v7.28.0) throw an `tsc` error ([diff](https://github.com/webdriverio/webdriverio/compare/v7.27.0...v7.28.0))

once downgrade to `7.27.0` version the `tsc`  work as expected

This change will allow to fix version for `webdriverio`

2022-12-18 11:54 UTC, kyryloonufriiev commented
Why do this and not fix whatever doesn't work in the latest version?

2022-12-18 13:20 UTC, zamboney commented
This is an internal issue in webdriberio.

2022-12-18 16:12 UTC, kyryloonufriiev commented
@zamboney Ok. Wdio has a buggy version, I still don't think it is worth a separate script to maintain. I think that instead of testing on latest 7, we should test on 7.27, this should be specified in the workflow. Take a look at how we already doing something similar for playwright.

2022-12-18 17:05 UTC, zamboney commented
@kyryloonufriiev can you please show me where you doing it in playwright?

2022-12-18 17:16 UTC, kyryloonufriiev commented
@zamboney please check out publish -playwright.yml workflow file. You will see that for node 12 we testing it on a specific minor version of the framework, since this is the last version that supports node 12. You will see that this version (major.minor) set in PLAYWRIGHT_VERSION env variable. Then this env variable used in the package.json to upgrade the framework. In wdio WEBDRIVERIO_MAJOR_VERSION used not only  to install framework, so some additional work should be done

2022-12-19 09:16 UTC, zamboney commented
@kyryloonufriiev i done what you ask, please review again 10x

2022-12-19 09:22 UTC, kyryloonufriiev requested changes
@zamboney This is not a complete solution. Please take a better look at how and where `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION` is used.

You also should change the name of the variable you provide with an action to `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION`, no `MAJOR` word since it is simply not true anymore.

I would recommend calculating `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION` from `APPLITOOLS_WEBDRIVERIO_VERSION` in the same place we are extracting the actual major version today.

BTW the same thing should be done for `spec-driver-wdio` package as well.

2022-12-19 09:22 UTC, kyryloonufriiev commented on .github/workflows/publish-webdriverio.yml
> +    if: true
I'm not sure what is that

2022-12-19 12:38 UTC, zamboney commented on .github/workflows/publish-webdriverio.yml
> +    if: true
for testing

2022-12-19 12:40 UTC, zamboney commented
@kyryloonufriiev i will change the name of the it, but can you explain why you think this is not a complete solution?

2022-12-19 14:36 UTC, kyryloonufriiev requested changes

2022-12-19 14:36 UTC, kyryloonufriiev commented on .github/workflows/publish-spec-webdriverio.yml
> +      APPLITOOLS_WEBDRIVERIO_VERSION: ${{matrix.framework-version}}
This is not the only thing to change in this file. Take a look at line 35, it says `framework-version: 7`

2022-12-19 14:36 UTC, kyryloonufriiev commented on js/packages/bongo/test/tree/fixtures/packages/eyes-webdriverio-5/package.json
> +    "build": "ttsc --project tsconfig$([ ! -z $APPLITOOLS_WEBDRIVERIO_VERSION ] && echo .v${APPLITOOLS_WEBDRIVERIO_VERSION%%.*}).json",
No need for the change in `bongo/test/tree`

2022-12-19 14:36 UTC, kyryloonufriiev commented on js/packages/eyes-webdriverio-5/src/service.ts
>    }
I would prefer to leave the calculated name as `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION`, but in case `APPLITOOLS_WEBDRIVERIO_VERSION` is specified we can take a major from there.

2022-12-19 14:36 UTC, kyryloonufriiev commented on js/packages/spec-driver-webdriverio/src/index.ts
>    }
Same here

2022-12-19 14:42 UTC, zamboney commented on .github/workflows/publish-spec-webdriverio.yml
> +      APPLITOOLS_WEBDRIVERIO_VERSION: ${{matrix.framework-version}}
why do we need to change it?

2022-12-19 14:54 UTC, zamboney commented on js/packages/spec-driver-webdriverio/test/e2e/spec-driver.spec.ts
> +      if (typeof version === 'undefined' || version < 7) this.skip()
can you explain what you want me to do?

2022-12-19 14:55 UTC, zamboney commented on js/packages/eyes-webdriverio-5/src/service.ts
>    }
can you explain what you want me to do?

2022-12-19 16:01 UTC, kyryloonufriiev commented on js/packages/eyes-webdriverio-5/src/service.ts
>    }
I think you should not simply rename the env var here. But extend a logic like this:
 - if there is nor `APPLITOOLS_WEBDRIVERIO_VERSION`, nor `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION` then extract the major version of the framework and put it in `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION`
 - if there is `APPLITOOLS_WEBDRIVERIO_VERSION` and no `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION` then extract the major version from `APPLITOOLS_WEBDRIVERIO_VERSION` and put it in `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION`
 - if there is `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION` do nothing

2022-12-19 16:03 UTC, kyryloonufriiev commented on js/packages/spec-driver-webdriverio/test/e2e/spec-driver.spec.ts
> +      if (typeof version === 'undefined' || version < 7) this.skip()
You should not do any change here if you populate `APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION` as I wrote above

2022-12-19 16:03 UTC, zamboney commented on js/packages/eyes-webdriverio-5/src/service.ts
>    }
not sure i understand

2022-12-19 19:29 UTC, kyryloonufriiev approved these changes
@zamboney I did pushed what I tried to explain about the major version.

2022-12-19 19:29 UTC, kyryloonufriiev commented on js/packages/eyes-webdriverio-5/package.json
> +    "build": "ttsc --project tsconfig$([ ! -z $APPLITOOLS_WEBDRIVERIO_VERSION ] && echo .v${APPLITOOLS_WEBDRIVERIO_VERSION%%.*}).json",
BTW This is super nice. Didn't know you we can do that!

2022-12-19 19:30 UTC, merged