Add lab provider and CI name to logEvents
applitools/eyes.sdk.javascript1 pull request #1208
Opened 2022-12-20 00:14 UTC by SophieDePaula

[Trello card](https://trello.com/c/ZSN0uuiR/85-splunk-add-lab-provider-url)

notes:
 - currently, this is only added to universal and wdio spec-driver

2022-12-20 08:17 UTC, kyryloonufriiev requested changes

2022-12-20 08:17 UTC, kyryloonufriiev commented on js/packages/core-base/src/types.ts
> +  labProvider?: string
You don't add it here. You add it to `event` object. That has a free structure so no need to declare anything. Also do not call the field `labProvider`, because it is not a lab provider, but a simple URL that may or may not reference a lab provider.

2022-12-20 08:17 UTC, kyryloonufriiev commented on js/packages/core/src/open-eyes.ts
> +        labProvider: spec.extractHostName ? spec.extractHostName(target) : undefined,
You can simply do that `spec?.extractHostName?.(target)`. This way you also handle the case when there is no spec at all (it could happen).

2022-12-20 08:17 UTC, kyryloonufriiev commented on js/packages/driver/src/spec-driver.ts
> +  extractHostName?(driver: TDriver): string
This is a utility method please put it in the proper place, along with other utility methods

2022-12-20 08:17 UTC, kyryloonufriiev commented on js/packages/eyes-universal/src/types.ts
> +  extractHostName?(options: {driver: TDriver}): string
it should not go there at all. This is a sync method, it could not be done through the web sockets

2022-12-20 18:05 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Additional internal event logs
@benbabayoff8

2022-12-20 18:20 UTC, SophieDePaula commented
Here is an example for `driverUrl` when running against saucelabs from splunk:

```
{
  "data": {
    "Site": "Public",
    "Service": "Eyes",
    "HostName": "SDK000002",
    "Timestamp": "2022-12-20T18:16:51.0485027+00:00",
    "Logger": "eyes.client.sessions",
    "Level": "NOTICE",
    "Context": {
      "EyesRequestId": "6fa7bdea-4595-446f-9833-e39a80953de0",
      "EyesClient": "eyes-webdriverio/5.38.2",
      "EyesClientRequestId": "0--47e41e3e-57b0-4913-989f-2b1bc7fb80a8",
      "CallerIP": "73.189.112.142",
      "RequestUrl": "https://eyesapi.applitools.com/api/sessions/log?apiKey=***",
      "RequestMethod": "POST",
      "UserName": null,
      "AccountId": "xIpd7EWjhU6cjJzDGrMcUw~~",
      "AccessKey": "***",
      "IsImpersonated": false,
      "Permissions": [
        "execute"
      ],
      "CreatedAt": "2022-12-20T18:16:51.0329287+00:00"
    },
    "Text": null,
    "Info": {
      "timestamp": "2022-12-20T18:16:50.7720000+00:00",
      "Event": {
        "type": "runnerStarted",
        "node": {
          "version": "v16.1.0",
          "platform": "darwin",
          "arch": "x64"
        },
        "driverUrl": "ondemand.us-west-1.saucelabs.com"
      }
    },
    "Exception": null,
    "ExceptionType": null,
    "ExceptionStackTrace": null
  }
}
```

@benbabayoff8 , @kyryloonufriiev fyi

2022-12-20 18:36 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Additional internal event logs
@SophieDePaula amazing

2022-12-20 20:07 UTC, kyryloonufriiev requested changes

2022-12-20 20:07 UTC, kyryloonufriiev commented on js/packages/core-base/src/types.ts
> -  event: {type: string} & Record<string, any>
as I wrote in my previous comment. `even` could be any object, this is done on purpose so we can log any events. This is why you don't need to add your property here.

2022-12-20 20:07 UTC, kyryloonufriiev commented on js/packages/core/src/open-eyes.ts
> +          CIProvider: spec?.extractCIProvider(),
do not call properties with leading uppercase latter. Also `extractCIProvider` has no relation to the driver so it shouldn’t be there.

2022-12-20 20:07 UTC, kyryloonufriiev commented on js/packages/core/src/open-eyes.ts
> +          driverUrl: spec?.extractHostName?.(target),
It is also worth checking for the target is not undefined
```suggestion
          driverUrl: target && spec?.extractHostName?.(target),
```

2022-12-20 21:18 UTC, SophieDePaula commented on js/packages/core-base/src/types.ts
> -  event: {type: string} & Record<string, any>
@kyryloonufriiev I did change it but forgot to push in that commit so I pushed it in the commit after.

2022-12-20 21:40 UTC, SophieDePaula commented
@kyryloonufriiev I addressed all your comments.

2022-12-20 21:59 UTC, SophieDePaula commented on js/packages/core/src/utils/extract-CI-provider.ts
> +  if (process.env.BUILD_ID) {
I don't think that `JENKINS_URL` env var is mandatory, and I read that `Jenkins` is a continuation of `Hudson`, so I decided to put them together.
@kyryloonufriiev , @benbabayoff8 lmk if that is a problem.

2022-12-21 09:10 UTC, benbabayoff8 commented on js/packages/core/src/utils/extract-CI-provider.ts
> +  if (process.env.BUILD_ID) {
@SophieDePaula I would consider Hudson as Jenkins as well. I think that is better than letting the field guess.

2022-12-21 16:40 UTC, kyryloonufriiev requested changes
Great work! I just have some minor comments, feel free to address them and merge.
About the file names, you should change:
extract-CI-provider.ts -> extract-ci-provider.ts
extract-CI-provider.spec.ts -> extract-ci-provider.spec.ts

2022-12-21 16:40 UTC, kyryloonufriiev commented on js/packages/core-base/src/types.ts
> +  event: {type: string; driverUrl?: string; extractedCIProvider?: string} & Record<string, any>
Did you understand from my previous message that it should not be here?

2022-12-21 16:40 UTC, kyryloonufriiev commented on js/packages/core/src/open-eyes.ts
> +import {extractCIProvider} from './utils/extract-CI-provider'
The naming convention for the file is all lowercase + dashes instead of spaces. Please align your file name.

2022-12-21 16:40 UTC, kyryloonufriiev commented on js/packages/driver/src/spec-driver.ts
> +  extractHostName?(driver: TDriver): string
The proper typing here would be:
```suggestion
  extractHostName?(driver: TDriver): string | null
```

2022-12-21 16:40 UTC, kyryloonufriiev commented on js/packages/spec-driver-webdriverio/test/e2e/spec-driver.spec.ts
> +  })
What is the point of running a separate browser just to extract a URL. We already run a bunch of browsers you can test this function there.

2022-12-21 16:40 UTC, kyryloonufriiev commented on pending-changes.yaml
> +    - Additional internal event logs
This should go to every sdk

2022-12-21 16:40 UTC, kyryloonufriiev commented on js/packages/core/src/utils/extract-CI-provider.ts
> +export function extractCIProvider(): string {
the CI is not always there, I think we should return null if we were not able to find one.
```suggestion
export function extractCIProvider(): string | null {
```

2022-12-21 16:52 UTC, SophieDePaula commented on js/packages/spec-driver-webdriverio/test/e2e/spec-driver.spec.ts
> +  })
But then I have a test that tests two unrelated things. I thought it would be cleaner and less confusing if I just add a test for this method.

2022-12-21 16:53 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Additional internal event logs
But I only added it to wdio and universal

2022-12-21 16:53 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Additional internal event logs
I guess the CI provider was added to all

2022-12-21 17:18 UTC, merged