Storybook external http headers
applitools/eyes.sdk.javascript1 pull request #1271
Opened 2023-02-02 21:06 UTC by SophieDePaula

2023-02-05 13:24 UTC, amitzur requested changes
I agree with the new config parameter and the readme addition. There is only one change I would make, to pass this configuration to `initPage` instead of `renderStories`.

2023-02-05 13:24 UTC, amitzur commented on js/packages/eyes-storybook/src/eyesStorybook.js
> +      puppeteerExtraHTTPHeaders: config.puppeteerExtraHTTPHeaders,
I would pass this to `initPage` rather than to `renderStories`. That's where new pages are created.

2023-02-07 01:30 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Add the option to send external http headers to Puppeteer Page object
@benbabayoff8

2023-02-08 18:46 UTC, amitzur requested changes
1. inline comment about the weird API parameter `puppeteerExtraHTTPHeader`.
2. Need to run `yarn lint --fix`
3. Consider avoiding a whole new storybook app, since you actually just need a new test server middleware to serve it. I see that there is `singleStorybook` being used by e2e tests. It's not a big deal, but I was confused why does this test need a storybook app of its own to test the functionality.

2023-02-08 18:46 UTC, amitzur commented on js/packages/eyes-storybook/src/initPage.js
> +function makeInitPage({iframeUrl, config, browser, logger, getTransitiongIntoIE, getRenderIE, puppeteerExtraHTTPHeader}) {
why do you need this extra parameter when you have `config.puppeteerExtraHTTPHeaders` ?

2023-02-08 18:55 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/initPage.js
> +function makeInitPage({iframeUrl, config, browser, logger, getTransitiongIntoIE, getRenderIE, puppeteerExtraHTTPHeader}) {
You are right, I missed it

2023-02-08 21:41 UTC, SophieDePaula commented
@amitzur I actually can't use `singleStorybook` in this case. I need my story to include a page that is hosted by `testServerInProcess` so that I use the middleware between the page and Puppeteer to check the headers

2023-02-08 21:51 UTC, merged