[core-base] crop image base on 'renderinfo'
applitools/eyes.sdk.javascript1 pull request #1281
Opened 2023-02-06 13:19 UTC by zamboney

This is the first stage to crop the image base on `renderinfo`

In this stage we are cropping the snapshot base on the `renderinfo` `maxImageHeight` and `maxImageArea`

The logic is as follow

[![](https://mermaid.ink/img/pako:eNpdkU1uwyAQha-CZp1cwKoi1T-yuukm3tleTALBqMFEeKwqIr57wFAJlRUz73szT-DgariAAqTFx8S6cpiZP5-9FMSURikYofXFyI7HEyvdV-h9XOyJDJuEkhNt0VIG4HXD-yJerHLRi1Zggi9KJrLKyTZ3k119q-4Xv5ys0ilB3DNGst6DVPmoaGv-234Vpym5mt3VOrVEwqMpTZuN6Pogjrlwu2OI2XX9bFimdvvA5rtOZVbDAbSwGhX37-qCPgBNQosBCn_laH8GGObNc-uDI4mGKzIWiv1JDoArmfNzvkIRUv1BtUL_RzpR2xsLOIvg?type=png)](https://mermaid.live/edit#pako:eNpdkU1uwyAQha-CZp1cwKoi1T-yuukm3tleTALBqMFEeKwqIr57wFAJlRUz73szT-DgariAAqTFx8S6cpiZP5-9FMSURikYofXFyI7HEyvdV-h9XOyJDJuEkhNt0VIG4HXD-yJerHLRi1Zggi9KJrLKyTZ3k119q-4Xv5ys0ilB3DNGst6DVPmoaGv-234Vpym5mt3VOrVEwqMpTZuN6Pogjrlwu2OI2XX9bFimdvvA5rtOZVbDAbSwGhX37-qCPgBNQosBCn_laH8GGObNc-uDI4mGKzIWiv1JDoArmfNzvkIRUv1BtUL_RzpR2xsLOIvg)

2023-02-06 13:20 UTC, zamboney commented
## few comment on this pr

is feel better for me to create a new property `limit?: ImageServerLimit` i can move it as part of the `setting` but it's not really a "user" setting so it's feels better to use `limit`. i can use `serverSetting` or inside `setting` add `server` but still is feels like twisting my arm

i can remove the `cropToLimit` function and use it on the `transformTarget` if it's not look good to you

need to logic in `cropToLimit` we want to make sure that the `maxHight` limit first before the `maxArea` limit

i liked the `describe('limit')` but i can drop this if it's not look good

2023-02-06 16:00 UTC, kyryloonufriiev requested changes

2023-02-06 17:00 UTC, zamboney commented on js/packages/core-base/src/types.ts
> +}
This is what I wrote in my first comment on this pr, my original thought was the way you suggested but it seems (to me) that the `ImageSettings` is more of a _"user setting"_ and not a _"internal setting"_. If you think this isn't the right place for it, then i will move it as you suggested.

2023-02-06 17:00 UTC, zamboney commented on js/packages/core-base/src/utils/transform-target.ts
> +    crop.width = maxImageArea / crop.height
I didn't check what the backend was doing. I will check, but i don't think there is any other way to check this...

2023-02-06 17:00 UTC, zamboney commented on js/packages/core-base/src/utils/transform-target.ts
> +  if (crop.width < image.width || crop.height < image.height) {
Again my thought was to do it so i would not call to `image.corp` if it was not needed. But if you think this is unnecessary, i can remove it.

2023-02-07 08:24 UTC, kyryloonufriiev commented on js/packages/core-base/src/utils/transform-target.ts
> +  if (crop.width < image.width || crop.height < image.height) {
It is unnecessary because it is already optimized in this function so you don't have to think too much about the optimization when you work with images.

2023-02-07 08:30 UTC, kyryloonufriiev commented on js/packages/core-base/src/utils/transform-target.ts
> +    crop.width = maxImageArea / crop.height
I was under the impression (after talking to Amit) that we have to check the backend's behavior first. Because there obviously two ways to reduce the area of a rectangle - cut a width, or cut a height.
You are trying to reduce it by cutting a width.
I personally think that the better way to do it is to cut a height. But as we already understood we should preserve the server behavior.

2023-02-07 08:33 UTC, kyryloonufriiev commented on js/packages/core-base/src/utils/transform-target.ts
> +  }
The thing is that you should not call it if the limit is `undefined` in the first place, if it would be something that the user can call then, of course, we have to do the validation. But in this case, you call it, and you don't need that reach api.

2023-02-07 08:39 UTC, kyryloonufriiev commented on js/packages/core-base/src/types.ts
> +}
I think we should not have any behavior that could not be overridden. This means if a user (I am talking user of `core-base`) wants a different image `maxHeight` or `maxArea` and they are not interfering with whatever the server provides (means we would always choose the smallest limit for height/area) we will use the provided values. The server just helps us to get defaults for some of the values, but never dictates something that could not be otherwise configured.

2023-02-07 08:42 UTC, zamboney commented on js/packages/core-base/src/utils/transform-target.ts
> +    crop.width = maxImageArea / crop.height
good point i miss this, after a talk with backend i will do what they are doing 10x

2023-02-07 08:52 UTC, zamboney commented on js/packages/core-base/src/types.ts
> +}
@kyryloonufriiev just to clarify, what you want is to be part of the `ImageSetting`. taking the minimum of `accountinfo` and `ImageSettings.normalization.cut` provide and place it on `imageSetting.normalization.cut`? is that make sense to you?

2023-02-07 12:21 UTC, kyryloonufriiev commented
@zamboney I noticed you committed `NO_CHANGELOG`, I think this feature worth a mention in the changelog

2023-02-07 18:46 UTC, zamboney commented on pending-changes.yaml
> +    - Crop screenshot image base on account info before upload
@benbabayoff8 ☝️

2023-02-09 09:34 UTC, kyryloonufriiev requested changes
This also should be added to `extractText` and `locate`

2023-02-09 09:34 UTC, kyryloonufriiev commented on js/packages/core-base/src/check-and-close.ts
> +    }
better use a new nullish coalescing operator
```suggestion
    settings ??= {}
    settings.normalization ??= {}
    settings.normalization.limit ??= {}
    settings.normalization.limit.maxImageHeight = Math.min(
      settings.normalization.limit.maxImageHeight ?? Infinity,
      requests.test.account.maxImageHeight,
    )
    settings.normalization.limit.maxImageArea = Math.min(
      settings.normalization.limit.maxImageArea ?? Infinity,
      requests.test.account.maxImageArea,
    )
```

2023-02-09 13:37 UTC, kyryloonufriiev commented on js/packages/core-base/src/locate-text.ts
> +    }
Since `locate`, `extractText` and `locateText` are part of the `Core` now, you don't have a test started there. The way to get account info will be:
```suggestion
    const account = await requests.getAccountInfo({settings, logger})
    settings.normalization ??= {}
    settings.normalization.limit = {
      maxImageHeight: Math.min(
        settings.normalization.limit?.maxImageHeight ?? Infinity,
        account.maxImageHeight,
      ),
      maxImageArea: Math.min(
        settings.normalization.limit?.maxImageArea ?? Infinity,
        account.maxImageArea,
      ),
    }
```

2023-02-09 14:08 UTC, kyryloonufriiev requested changes

2023-02-09 14:08 UTC, kyryloonufriiev commented on js/packages/core-base/src/utils/transform-target.ts
> +      }
Shouldn't it happen after we will take the region from the screenshot? The initial image could be gigantic, but the region could be a small portion of it. I think the limits validation should happen after all other manipulations.

2023-02-09 14:08 UTC, kyryloonufriiev commented on js/packages/core-base/test/it/check.spec.ts
> +  it('crop image base on "renderinfo" "maxImageHeight" and "maxImageArea"', async () => {
Please don't use "renderinfo", it is outdated terminology. In our code base, this is called account info.

2023-02-09 14:08 UTC, kyryloonufriiev commented on js/packages/core-base/test/it/transform-target.spec.ts
>  import {makeImage} from '@applitools/image'
```suggestion
import {readFileSync} from 'fs'
import {makeImage, type Image} from '@applitools/image'
```

2023-02-09 14:11 UTC, kyryloonufriiev commented on .github/actions/parser/main.js
> +      return changedFilePath.startsWith(changedPackage.path + '/')
👍🏼

2023-02-09 14:17 UTC, zamboney commented on js/packages/core-base/src/utils/transform-target.ts
> +      }
isn't it what happen now? am i missing something?

2023-02-09 14:24 UTC, kyryloonufriiev commented on js/packages/core-base/src/utils/transform-target.ts
> +      }
I understand the confusion. There is `normalization.cut` and `region` they are doing basically the same but serve different purposes. So you apply the limits after `normalization.cut`, but before `region`.
Check out line 37

2023-02-09 14:51 UTC, merged

2023-02-20 07:13 UTC, amitzur commented on js/packages/core-base/src/extract-text.ts
> +        const account = await requests.getAccountInfo({settings, logger})
@zamboney @kyrylodolynskyi from a user perspective, they should be able to run `extractText` only after calling `open`. So I think in the normal case, we should already have the account info available somewhere. We can avoid sending this request.

2023-02-20 11:35 UTC, zamboney commented on js/packages/core-base/src/extract-text.ts
> +        const account = await requests.getAccountInfo({settings, logger})
@amitzur I understand what you are saying, and indeed it seems from the code like a waste of request, but this call came from the same [getAccountInfoWithCache](https://github.com/applitools/eyes.sdk.javascript1/blob/2e843f9ba6b0abe9ddb614793d47fc6e30f1aa01/js/packages/core-base/src/server/requests.ts#L54-L56)