[js] try to fix `eslint` issue on `git commit`
applitools/eyes.sdk.javascript1 pull request #1283
Opened 2023-02-08 09:13 UTC by zamboney

2023-02-08 09:15 UTC, kyryloonufriiev commented
@zamboney What does it do?

2023-02-08 10:18 UTC, zamboney commented
> Ah, you just absolutize the path of staged files, right?

yep 🎉

2023-02-08 11:00 UTC, kyryloonufriiev commented
I think you should not change the hook file, but instead, simply change the script in `package.json`. The idea is to be able to run exactly the same command manually as the git hook will run.

2023-02-08 12:44 UTC, zamboney commented
> I think you should not change the hook file, but instead, simply change the script in `package.json`. The idea is to be able to run exactly the same command manually as the git hook will run.

i was able to fix it by passing '../' to the `--line-prefix`

2023-02-08 14:35 UTC, kyryloonufriiev commented
I can agree with the absolute path. But I don't understand what `../` solves.
Whatever we have now works fine for me. Are you sure it will continue working after this pr?

2023-02-08 15:05 UTC, zamboney commented
The absolute path was just a symptom of the real problem, which is that the combination of using `npm script` and `git diff` added a duplication of `js` in the path. this solution fixes that by changing the path to one directory up

2023-02-08 20:35 UTC, kyryloonufriiev commented
Why don't I have this problem then?

2023-02-08 20:58 UTC, zamboney commented
@kyryloonufriiev this is strange, can you check with my changes and see if you have an issue? Because I think that @SophieDePaula and I getting the same issue.

2023-02-08 22:03 UTC, SophieDePaula commented
My issue was that I merged `master` into my branch because I had conflicts which brought many changes from master that eslint checked. Then I had to run `yarn` in one of the packages that was changed because I got an error that one of the `eslint` packages was not found there, but I couldn't install all the dependencies in that package because that package had a dependency that was not published yet.

2023-02-09 09:18 UTC, kyryloonufriiev requested changes

2023-02-09 10:45 UTC, zamboney commented on js/package.json
> +    "eslint-plugin-mocha-no-only": "^1.1.1",
`eyes-cypress` use it

2023-02-09 11:48 UTC, kyryloonufriiev commented on js/package.json
> +    "eslint-plugin-mocha-no-only": "^1.1.1",
So it is not related to the repo level modules/configs

2023-02-09 12:13 UTC, zamboney commented on js/package.json
> +    "eslint-plugin-mocha-no-only": "^1.1.1",
nope.

2023-02-09 12:42 UTC, zamboney commented
after i clone a new repo and test it on (without `git worktree`) all work as expected so this is a `git worktree` issue. i will try to solve it on my end but i'm closing this pr

2023-02-09 12:42 UTC, closed without merging