[core-base] add density metrics
applitools/eyes.sdk.javascript1 pull request #1302
Opened 2023-02-20 17:21 UTC by zamboney

in order to support `PPI` this pr add to the `api/session/running` the `densityMetrics` property

[trello](https://trello.com/c/6HYzeSfz/1707-dfin-poc-regular-text-classified-as-large-text-for-pdfs)

- [x] tests
- [x] documentation

2023-02-20 17:26 UTC, zamboney reviewed
@kyrylodolynskyi, i added some comment on the PR please take a look before read 10x

2023-02-20 17:26 UTC, zamboney commented on js/packages/core-base/test/e2e/images.spec.ts
> +          // @ts-ignore
This is so i can use the `core.openEyes` and add a `testName` if you think it's not necessary i will remove it

2023-02-20 17:26 UTC, zamboney commented on js/packages/core-base/test/e2e/images.spec.ts
> +  describe('works with densityMetrics', () => {
i have to do 2 `openEyes` because the `accessibilityStatus` is per test and not per `check`

2023-02-20 17:26 UTC, zamboney commented on js/packages/core-base/test/unit/requests.spec.ts
> +        densityMetrics: {
not sure if this is mandatory but a added it any way

2023-02-21 13:04 UTC, kyrylodolynskyi requested changes

2023-02-21 13:04 UTC, kyrylodolynskyi commented on js/packages/core-base/test/e2e/images.spec.ts
> +    })
I doubt there is a reason for the test without property at all, but even if there is. I don't think this is a reasonable way to write a test. The test should be self-contained, so we can easily understand what it does and maintain it (means if you need to open eyes do it in `it`).

2023-02-21 13:04 UTC, kyrylodolynskyi commented on js/packages/core-base/test/e2e/images.spec.ts
> +    it('with densityMetrics accessibilityStatus', async () => {
The name is very artificial, please write a more readable name for the test that describes what you are doing or what should happen.

2023-02-21 15:02 UTC, zamboney commented on js/packages/core-base/test/e2e/images.spec.ts
> +  })
This test ensures that once there is no `densityMetrics`, the `result.accessibilityStatus.status` `'Passed"` because. it's making sure that the reason for the change is due to the removal of the `densityMetrics`. i get what you are saying that it does not make sense at first glance, so i will add a very low `densityMetrics` to make the `result.accessibilityStatus.status` `'Passed"`  so it will be clear for the future reader this test

2023-02-21 15:02 UTC, zamboney commented on pending-changes.yaml
> +    - Passing density metric for PPI support in the sdk
@benbabayoff8 ☝️

2023-02-22 07:21 UTC, kyrylodolynskyi commented on js/packages/core-base/test/e2e/images.spec.ts
> +  })
I don't think this test is needed. If something should change status due to the fact that we successfully sent `dencityMetrics` it is already enough to prevent future regressions. The test that demonstrates that something works differently without it is pointless. I mean if you want this demonstration it should be a part of one test, not two different tests.

2023-02-22 07:23 UTC, kyrylodolynskyi commented
@zamboney Are you going to add user-facing for this feature? I think we definitely should have it.

2023-02-22 07:39 UTC, zamboney commented
@kyrylodolynskyi what do you mean by "user-facing"?

2023-02-22 08:05 UTC, kyrylodolynskyi commented
@zamboney I mean something in `eyes-api` package. You can see in the trello card that we decided to add `.ppi(...)` method to `CheckSettings`

2023-02-22 11:06 UTC, zamboney commented on js/packages/core-base/test/e2e/images.spec.ts
> +  })
i changed the test so that it's now it is setting the pixel ratio of the screen to `10x10` so all of the texts are now large, and the accessibility status is `'Passed'`, i still think we should keep it because if this test failed, and the other test is pass, for example, both of the `accessibiltyStatus` is `"Fail"`, it's giving as a clue that the PPI isn't set right (could be our end or the backend).
If, after that explanation, you still think that this test is pointless, i will remove it

2023-02-22 11:18 UTC, zamboney commented
@kyrylodolynskyi i added user interface

2023-02-22 11:37 UTC, kyrylodolynskyi requested changes

2023-02-22 11:37 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/input/CheckSettings.ts
> +  }
It shouldn't go to the `CheckSettingAutomation`, but to the `CheckSettingsImage` a.k.a. `CheckSettingsBase`. Also The api we decided on is `.ppi(...)`, not `.densityMetrics(...)`

2023-02-22 11:37 UTC, kyrylodolynskyi commented on js/packages/eyes-api/tsconfig.json
> +  "ts-node": {"transpileOnly": false}
why?

2023-02-22 11:37 UTC, kyrylodolynskyi commented on js/packages/eyes-cypress/README.md
> +```
Cypress doesn't have this api. In cypress, users do not use `Target.window()`, they have an even worse thing, the custom object of a shape that only cypress supports.

2023-02-22 11:37 UTC, kyrylodolynskyi commented on js/packages/eyes-nightwatch/README.md
> +```js
I beliave this don't even worth maintaining since it is going to be removed soon

2023-02-22 11:37 UTC, kyrylodolynskyi commented on js/packages/core-base/test/e2e/images.spec.ts
> +  it('should passing the accessibility when the density metrics xdpi and ydpi set to 10 and not the same as the viewportSize width and height', async () => {
I still don't understand this test. Wouldn't it work without `densityMetrics`?

2023-02-22 11:37 UTC, kyrylodolynskyi commented on js/packages/core-base/test/e2e/images.spec.ts
> +    result.accessibilityStatus
```suggestion
```

2023-02-22 11:46 UTC, kyrylodolynskyi commented on js/packages/core-base/test/e2e/images.spec.ts
> +  })
I understand what you mean. The first test could fail for a different reason than the presence of `densityMetrics`, so in this case, the second test would fail as well, so it should bring our attention. I think it is clear that this is not the ideal way, no one would ever understand (without) additional information that we have to look at in those two tests together. This is why I think we should have only one test since this is one case that should be checked and demonstrated together.
The ideal test of course would be just an image that could pass only with `densityMetrics` then you don't need these two steps. If it is possible to get/create such an image this will be the preferable way to proceed, if not then just merging two tests in one will work for me.

2023-02-22 12:16 UTC, zamboney commented on js/packages/core-base/test/e2e/images.spec.ts
> +  })
yes of course this is what I want to have an image that could only "Pass" only with `dinsityMetrics` but the issue that this PR is fixing is actually the problem that all of the images "Pass" the `accessibiltyStatus` without `dinsityMetrics`.

good point about merging these two tests, that's what i will do 👍

2023-02-22 12:26 UTC, zamboney commented on js/packages/eyes-api/src/input/CheckSettings.ts
> +  }
> It shouldn't go to the `CheckSettingAutomation`, but to the `CheckSettingsImage` a.k.a. `CheckSettingsBase`. 
np i will fix the

> Also The api we decided on is `.ppi(...)`, not `.densityMetrics(...)`

`densityMetrics` is more general than `PPI`, and the unit that the server is currently using is `DPI` ([read more](https://99designs.com/blog/tips/ppi-vs-dpi-whats-the-difference/#:~:text=What%20is%20the%20difference%20between%20PPI%20and%20DPI%3F&text=PPI%20describes%20the%20resolution%20in,the%20quality%20of%20the%20output.)) so I thought that making it more general is a good practice and not misleading. Furthermore i API is not in use so I think the naming can be changed

2023-02-22 12:28 UTC, zamboney commented on js/packages/eyes-api/tsconfig.json
> +  "ts-node": {"transpileOnly": false}
if not then the test is passing, although the `tsc` `typecheck` is failing [here](https://github.com/applitools/eyes.sdk.javascript1/blob/universal-densityMetrics/js/packages/eyes-api/test/unit/CheckSettings.spec.ts) so i thought it a good idea to do a `typecheck` as well, if you think it's unnecessary i will remove it

2023-02-22 15:53 UTC, kyrylodolynskyi requested changes
Other than one small comment about the casing, it looks good to me. Let's wait for the sync to finally decide on the user-facing api.

2023-02-22 15:53 UTC, kyrylodolynskyi commented on js/packages/eyes-api/tsconfig.json
> +  "ts-node": {"transpileOnly": false}
I know that the test may have some bad typescript, but the reason I added it to all of the ts configs is that with the test we often do some experiments and at this point, it is just annoying to handle the types. Of course, I try to have a valid typescript at the end, but not being able to run the test due to types is not what I would want.

2023-02-22 15:53 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/input/CheckSettings.ts
> +  }
Ok, I see your point. But we don't want to publish an api and then change it in the next iteration. Let's talk about it on today's sync

2023-02-22 16:30 UTC, merged