use timeout when fetching resource
applitools/eyes.sdk.javascript1 pull request #1305
Opened 2023-02-23 23:26 UTC by SophieDePaula

[Trello card](https://trello.com/c/oLyE17zj/1758-bokksu-cypress-poc-resources-missing-with-504)

In this PR I added a `timeout` to `fetch` requests in case we don't get a response.
I saw that in `dom-snapshot` we have timeout of 10 seconds, so I thought it's safe to set the timeout to 20 seconds.

Notice, that in the customer's case, we still see missing resources because in some cases even after 5 retries, we are still not getting a response

2023-02-24 08:03 UTC, kyrylodolynskyi requested changes

2023-02-24 08:03 UTC, kyrylodolynskyi commented on js/packages/req/src/req.ts
> +    timeout: options?.timeout,
This is not the timeout you need. Take a better look at the code and where `options.timeout` is used. `req` already supports `timeout` functionality.

2023-02-24 08:03 UTC, kyrylodolynskyi commented on js/packages/ufg-client/src/resources/fetch-resource.ts
> +  timeout?: number
I don't think there is a point in making it configurable per request. It should be a global config same as we already have for `streamingTimeout`

2023-02-28 13:19 UTC, SophieDePaula commented on js/packages/ufg-client/test/it/fetch-resource.spec.ts
> +      ...authority,
@kyrylodolynskyi when I don't send that, I get an `ssl` error when trying to fetch the resource.

2023-02-28 13:54 UTC, kyrylodolynskyi requested changes

2023-02-28 13:54 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/it/fetch-resource.spec.ts
> +      },
This is also not how you do it. You should simply return a `true` if the error is the one you expected.

2023-02-28 13:54 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/it/fetch-resource.spec.ts
> +      ],
There is already a middleware that may fit your need. Will it work for you?
```suggestion
      middlewares: ['slow'],
```

2023-02-28 13:55 UTC, kyrylodolynskyi commented on js/packages/req/src/req.ts
> +  fetchTimeout?: number
How is it different from the `timeout` property?

2023-02-28 14:05 UTC, SophieDePaula commented on js/packages/ufg-client/test/it/fetch-resource.spec.ts
> +      ...authority,
Got it, I missed it.

2023-02-28 14:14 UTC, SophieDePaula commented on js/packages/req/src/req.ts
> +  fetchTimeout?: number
@kyrylodolynskyi I thought the `timeout` property is used for something different and therefore I created a dedicated property for fetch timeout.

2023-02-28 14:18 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Add a timeout for fetching resources
@benbabayoff8

2023-02-28 15:37 UTC, kyrylodolynskyi requested changes

2023-02-28 15:37 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/it/fetch-resource.spec.ts
> +    authority = await generateCertificate({days: 1})
You don't need the global `authority`, since you are going to use it only in one test

2023-03-01 08:04 UTC, SophieDePaula commented on js/packages/req/src/req.ts
> +  fetchTimeout?: number
@kyrylodolynskyi , If I don't send `fetchTimeout` to `fetch`, I get a generic error `user aborted test` instead on `network timeout`, and I think it's confusing and in such a case it's harder to understand what is going on. 
To me it's much clearer, to have a `fetchTimeout` property and get the relevant error message.

2023-03-01 08:40 UTC, kyrylodolynskyi commented on js/packages/req/src/req.ts
> +  fetchTimeout?: number
@SophieDePaula If your problem is with an error message you can work to change that. I 100% with you on that. But this is not the way to do it. `fetch` api doesn't support `timeout`, and the right way to abort requests on timeout is the way that is already implemented.
I also don't like the fact that we cannot specify a custom error when aborting requests. We can change that, let's sync

2023-03-14 14:56 UTC, kyrylodolynskyi requested changes

2023-03-14 14:56 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/it/fetch-resource.spec.ts
> +      err => err.message.includes('The user aborted a request'),
You would better check that this is `AbortError`, the message could change.

2023-03-14 14:56 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +      const fetchResource = makeFetchResource({streamingTimeout: 80, fetchTimeout: 0})
Why do you need it here?

2023-03-14 14:56 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +    await Promise.all(resources)
Use `map` instead of `for` loop
```suggestion
    await Promise.all(mockResources.map(resource => fetchResource({resource})))
```

2023-03-14 14:56 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +          value: Buffer.from('bla'),
It should have no value or content type. To create url resource you need just `url`.

2023-03-14 14:56 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +  })
I see what you are doing. It is fine, but I think we should emulate the behavior we see on the customer side.
If there is more than X request in the queue right now respond immediately with an error status code.

2023-03-14 21:19 UTC, SophieDePaula commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +  })
@kyrylodolynskyi That's what I wanted to do in the first place, but with `nock` you can't send a `callback` as a status, that's the reason I took this approach.

2023-03-14 21:48 UTC, SophieDePaula commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +      const fetchResource = makeFetchResource({streamingTimeout: 80, fetchTimeout: 0})
@kyrylodolynskyi we don't , I removed it

2023-03-15 10:20 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +  })
Of course, you can. Here is example from our code.
```
    nock('https://fonts.googleapis.com')
      .get('/some-font')
      .once()
      .reply(function () {
        return [200, 'font', {'Content-Type': `application/${this.req.headers['user-agent']}`}]
      })
```

2023-03-17 09:21 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +    )
Using filter + length is not the best way to get a number of elements that match your condition, but in this case, this is also not what you need. You actually want to know if there are any failed resources in the array. So I recommend
```suggestion
    assert.strictEqual(resResources.some(resource => utils.types.has(resource, `errorStatusCode`)), false)
```

2023-03-17 09:21 UTC, kyrylodolynskyi commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +    }
A am still kinda skeptical about this `for` loop. I understand what you tried to do, but I would like us to avoid such usage in general, maybe it is fine for the tests.
Anyway, I want to recommend this, just to not give chance for this practice.

```suggestion
    const mockResources = Array({length: 10}, (_, index) => makeResource({url: `http://something/${index}`}))
    let count = 0
     nock('http://something').get(/\d+/).times(mockResources.length).reply(limitServerParallelRequests)
```

2023-03-17 17:47 UTC, SophieDePaula commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +    }
Thank you for taking the time to mention that

2023-03-17 18:08 UTC, SophieDePaula commented on js/packages/ufg-client/test/unit/fetch-resources.spec.ts
> +    }
That actually, doesn't work, let's talk about it.

2023-03-29 07:46 UTC, kyrylodolynskyi requested changes
I think an e2e test on the core level would help us to not regress in the future.

2023-03-29 07:46 UTC, kyrylodolynskyi commented on js/packages/core/src/ufg/get-base-eyes.ts
in this file, you should not care about `fetchConcurrency`. This is conceptually wrong.

2023-03-29 07:46 UTC, kyrylodolynskyi commented on js/packages/ufg-client/src/client.ts
> +  fetchConcurrency?: number
I think it should go in the `config` object.

2023-03-29 07:46 UTC, kyrylodolynskyi commented on js/packages/ufg-client/src/resources/fetch-resource.ts
> +  fetchTimeout?: number
At this point, you better call it `concurrency` and `timeout`. It will create nice symmetry with other commands (e.g. `render`)

2023-03-29 07:46 UTC, kyrylodolynskyi commented on js/packages/core/src/ufg/core.ts
> +  fetchConcurrency?: number
This property should not exist on the core level. Because it could be configured only through the manager.

2023-03-29 07:46 UTC, kyrylodolynskyi commented on js/packages/core/src/ufg/get-ufg-client.ts
> +export function makeGetUFGClient({client, fetchConcurrency, logger: defaultLogger}: Options) {
This property should not be predefined, it should be provided in `getUFGClient`

2023-03-29 23:00 UTC, SophieDePaula commented on js/packages/ufg-client/src/resources/fetch-resource.ts
> +  fetchTimeout?: number
@kyrylodolynskyi I prefer to keep these names for better readability of the code.

2023-03-29 23:18 UTC, SophieDePaula commented on js/packages/core/src/ufg/core.ts
> +  fetchConcurrency?: number
@kyrylodolynskyi How should I pass it then?

2023-04-14 07:25 UTC, kyrylodolynskyi requested changes
You also should add a test that will verify that even two eyes under the same manager will not fetch more than X resources in parallel.

2023-04-14 16:45 UTC, SophieDePaula commented on js/packages/core/test/fixtures/browser-fetching-fetchConcurrency/app.ts
@kyrylodolynskyi notice that I created several endpoints to the same resources so it won't be cached, can I do that with test server?

```
 app.get('/image1', (_req: any, res: any) => {
  res.sendFile(path.join(__dirname, '/smurfs.jpg'));
});
app.get('/image2', (_req: any, res: any) => {
  res.sendFile(path.join(__dirname, '/smurfs.jpg'));
});
app.get('/image3', (_req: any, res: any) => {
  res.sendFile(path.join(__dirname, '/smurfs.jpg'));
});
app.get('/image4', (_req: any, res: any) => {
  res.sendFile(path.join(__dirname, '/smurfs.jpg'));
});
   ```

2023-04-18 07:01 UTC, kyrylodolynskyi commented on js/packages/core/test/fixtures/browser-fetching-fetchConcurrency/app.ts
You just create a folder for your page where you put as much resources as you need (you can copy the same file N times as well)

2023-04-18 12:53 UTC, kyrylodolynskyi requested changes

2023-04-18 12:53 UTC, kyrylodolynskyi commented on js/packages/core/test/e2e/ufg/Resource-fetching-concurrency.spec.ts
The file name shouldn't be uppercased

2023-04-18 12:53 UTC, kyrylodolynskyi commented on js/packages/core/src/ufg/get-ufg-client.ts
>    )
Hmmm. I think you should exclude fetchConcurrency from the cache key.

2023-04-18 12:53 UTC, kyrylodolynskyi commented on js/packages/core/test/e2e/ufg/Resource-fetching-concurrency.spec.ts
> +    await page.goto(`${baseUrl}/browser-fetching-fetchConcurrency/index.html`)
please call the page properly. It has nothing to do with "browser fetching", also you should not use kebab and camel case together.
But even better would be to use the page that we already have, as far as I understand the only requirement for the page is to have multiple resources, we already have a page called `page` that has a bunch of different resources. I think it should work just fine for you.

2023-04-18 17:05 UTC, SophieDePaula commented on js/packages/core/test/e2e/ufg/Resource-fetching-concurrency.spec.ts
> +    await page.goto(`${baseUrl}/browser-fetching-fetchConcurrency/index.html`)
@kyrylodolynskyi the page points to a the resources that are hosted under the `app` I wrote so that every time a resource is fetched, we count the request and can respond with the right status code

2023-04-18 17:34 UTC, SophieDePaula commented on js/packages/core/test/e2e/ufg/Resource-fetching-concurrency.spec.ts
> +    await page.goto(`${baseUrl}/browser-fetching-fetchConcurrency/index.html`)
I also changed the name as you requested

2023-04-18 19:07 UTC, kyrylodolynskyi commented on js/packages/core/src/ufg/get-ufg-client.ts
>    )
It should. The fact that it uses the old type is another mistake that should be fixed.

2023-04-18 20:45 UTC, SophieDePaula commented on js/packages/core/test/e2e/ufg/Resource-fetching-concurrency.spec.ts
I changed it

2023-04-19 06:53 UTC, kyrylodolynskyi commented on js/packages/core/src/ufg/get-ufg-client.ts
>    )
It gets `UFGRequestsConfig` because at the time it was created `UFGClientConfig` type didn't exist. And since you introduced a better type, it is a mistake that it isn't used here as well.

2023-04-20 16:36 UTC, merged