[eyes] Create eyes package on top of core
applitools/eyes.sdk.javascript1 pull request #1308
Opened 2023-02-28 12:38 UTC by kyrylodolynskyi

2023-03-01 11:58 UTC, zamboney commented on js/packages/eyes-api/test/unit/enums.spec.ts
> +  describe('AndroidDeviceName', () => {
👍

2023-03-02 15:49 UTC, amitzur commented
@kyrylodolynskyi while I'm reviewing this, a quick comment -
I love the simple name `@applitools/eyes` on one hand. But on the other hand I already see how it's going to be trouble communicating around it. The word `eyes` is so loaded with multiple meaning already. WDYT about it?
Other possible options I can think of - (a) keep the name `eyes-api` and just do a major version, (b) `eyes-sdk`, (c) `sdk-api`.

2023-03-02 16:11 UTC, kyrylodolynskyi commented
@amitzur I don't like the `eyes-api`, because it is not just about an api anymore, it is a fully functional SDK. And traditionally all our SDK packages were called `eyes-*`, so it was only logical for me to call it `eyes` because it is everything.
Here are my pro-`eyes` arguments:
1. I would say that the `Eyes` class is the central entity in this package, so `eyes` is the perfect name.
2. This package going to be a user-facing package for integrators, so it should have a "cool" name - `eyes` is cool 😎.
3. It would make sense for integrators, they will see `eyes-selenium`, `eyes-webdriverio`, etc. and naturally they want `eyes-<their product>`, so they use the `eyes` package as a base for that.

2023-03-07 13:11 UTC, amitzur commented
@kyrylodolynskyi fair enough, I agree with your reasoning. So when we refer to it we'll just say "the eyes package, you know the one that was eyes-api but now it's also core. Yeah, the eyes package" :)

2023-03-07 14:02 UTC, amitzur requested changes
I think this is great in simplifying things. The small inline comments I have are about the ability to understand the code for anyone who is new to it.
There are lots of variables like `sdk`, `core`, `eyes`, which have different meaning in different places. While TS helps, it's still hard to easily understand the code. I'd be happy if we adopted a convention that for example `Core.Eyes` variables would be called `coreEyes` or something like that. Same goes to `sdkOptions` like in my inline comment.

2023-03-07 16:19 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/SDK.ts
> +  return (options.makeCore ?? makeCore)({agentId: `js/eyes/${require('../package.json')}`, ...options})
I want to keep a way to have a custom core implementation specified, for testing purposes. Also by default, we are using normal js core, but nothing should prevent us from using universal client instead.

2023-03-07 16:19 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/Eyes.ts
> +    if (this._spec?.isDriver?.(driverOrConfigOrAppName)) {
In images

2023-03-07 16:20 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/Eyes.ts
> +  protected static readonly _sdk: SDKOptions<Core.SpecType>
I will change it

2023-03-10 08:37 UTC, kyrylodolynskyi commented on .github/workflows/publish.yml
> +    needs: [ setup, core, test-utils ]
fixed

2023-03-10 12:22 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/SDK.ts
> +  return (options.makeCore ?? makeCore)({agentId: `js/eyes/${require('../package.json')}`, ...options})
I don't want to specify every property specifically, what I want is to pass `options` through and give agentId a default value. I made a change to make it more obvious and avoid passing `makeCore` to `makeCore`.

2023-03-10 12:23 UTC, merged