bongo: consolidate test reporting and release notifications
applitools/eyes.sdk.javascript1 pull request #1321
Opened 2023-03-07 15:23 UTC by tourdedave

### Objective

- to enable all SDK languages to use the same mechanism for sending both test reports and release notifications
- to enable the JS core (non-generic tests) to report and send release notifications in the same manner as the SDKs

### Before

```
coverage-tests generate ./configuration --name 'sdk-name'
// run tests...
coverage-tests report ./configuration --name 'sdk-name' --reportId $GITHUB_SHA
// send notification (custom for each language)
```

### After

```
coverage-tests generate ./configuration --name 'sdk-name'
// run tests...
bongo report ./configuration --name 'sdk-name' --reportId $GITHUB_SHA
bongo send-release-notification --name 'sdk name' --version 'sdk version'
```

2023-03-07 16:34 UTC, kyrylodolynskyi requested changes
Looks nice and clean to me. There are a few questions in the comments.
There is also a small request, I would love to get rid of `convertSdkNameToReportName`. We should simply specify the names that @Yarden-Ingber wants to receive, or even better @Yarden-Ingber will accept the real SDK names (maybe with language-specific prefixes), instead of made-up keys.

2023-03-07 16:34 UTC, kyrylodolynskyi commented on node_modules/.yarn-integrity
> +}
what is that?

2023-03-07 16:34 UTC, kyrylodolynskyi commented on js/packages/bongo/src/cli/index.js
>      ['send-release-notification', 'hello-world'],
Why is there an alias `hello-world`?

2023-03-07 18:25 UTC, tourdedave commented on node_modules/.yarn-integrity
> +}
🤔 I don't know.

2023-03-07 18:45 UTC, tourdedave commented
> I would love to get rid of `convertSdkNameToReportName`. We should simply specify the names that @Yarden-Ingber wants to receive, or even better @Yarden-Ingber will accept the real SDK names (maybe with language-specific prefixes), instead of made-up keys.

I'm a fan of the first part, not sure about the second. So I propose we break it into two steps.

1. The first thing is to get rid of this function and update the SDKs in our monorepo to specify the name Bongo's service expects (and let the languages not in the mono know of this breaking change). This would remove us from being a gatekeeper in the report/notification process since we won't need to handle the name translation anymore.

2. Talk with Bongo (separate from this PR) to see if he has an appetite to update his service to accept the names of the SDKs as they are.

2023-03-07 18:53 UTC, kyrylodolynskyi commented
@tourdedave Makes perfect sense. 👍🏼 BTW we need to talk to Bongo anyway because there should be a custom endpoint to send the release notif for the core.

2023-03-07 18:57 UTC, kyrylodolynskyi commented
@tourdedave Also I would expect this PR to update all of the JS packages to send reports using bongo.

2023-03-07 19:00 UTC, tourdedave commented
> BTW we need to talk to Bongo anyway because there should be a custom endpoint to send the release notif for the core.

Oh, really? I thought we would just be able to use the same route, change the group, and it would just work ™️. Why do we need a custom endpoint?

> @tourdedave Also I would expect this PR to update all of the JS packages to send reports using bongo.

Yes, of course.

2023-03-08 08:33 UTC, kyrylodolynskyi commented
@tourdedave I believe the release notification doesn't have a `group` property. The `group` property exists in the test report and there we don't need a custom endpoint. Basically, the "custom endpoint" thing is what I heard from Bongo during our sync about it. What we actually need is any way to differentiate core notifications from sdks notifications.

2023-03-08 13:33 UTC, tourdedave commented
> @tourdedave I believe the release notification doesn't have a `group` property. The `group` property exists in the test report and there we don't need a custom endpoint. Basically, the "custom endpoint" thing is what I heard from Bongo during our sync about it. What we actually need is any way to differentiate core notifications from sdks notifications.

Got it. Thanks

2023-03-09 15:35 UTC, tourdedave commented
I talked to @Yarden-Ingber, he will add a new route for us. It will be `/send_mail/core_sdk`

2023-03-10 07:58 UTC, kyrylodolynskyi approved these changes
Looks great!

2023-03-10 18:03 UTC, merged