add splitStoriesByConfig method
applitools/eyes.sdk.javascript1 pull request #1338
Opened 2023-03-15 23:44 UTC by SophieDePaula

[Trello card](https://trello.com/b/JsFvGu0s/sdk-dev)

2023-03-27 19:35 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Add support for configuration per subset of stories
@benbabayoff8

2023-03-28 20:39 UTC, amitzur requested changes
This is good, I think the structure simplifies things.

About terminology - you call "subset of stories" for 2 different things: subset of fakeIE/non-fakeIE (in the log in eyesStorybook.js), and subsets of stories per their configurations.
I don't think we should use "subset of stories". The name of the feature is "configuration per story". So the e2e test should be called `config-per-story.e2e.test.js` etc.

The `getStoriesWithConfig` function needs to be improved. See inline comments.

2023-03-28 20:39 UTC, amitzur commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
Oh, it does have it. I was confused by the name. I think the test file name should be with the same name as the source.

2023-03-28 20:39 UTC, amitzur commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +      let remainingStories = Object.assign([], storiesWithTitle);
This is not how you create an array with initial value from another array. Did you mean `[...storiesWithTitle]`?

2023-03-28 20:39 UTC, amitzur commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +    basicConfig = Object.assign([], config);
But better to do `basicConfig = {...config}`.

2023-03-28 20:39 UTC, amitzur commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +  let basicConfig;
I don't understand the point of this variable. It is updated with every call to `getStoriesWithConfig`. I assume you want to hold the global, or "basic", config outside the `getStoriesWithConfig` function. If so, then pass it in `makeGetStoriesWithConfig`. Otherwise, it's just not correct to use it like this.

2023-03-28 21:11 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/generateConfig.js
> +  if (!result.browser && !result.renderers) {
@amitzur since this method is also called from `getStoriesWithConfig`, we can already have a renderers in the base configuration.

2023-03-28 21:13 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/unit/renderStory.test.js
> +      target: 'region',
@amitzur just because it didn't make sense for me, `target` can either be `window` which is the default or `region`. Also, `target` will not end up in the expected config, only the `region` property.

2023-03-28 21:15 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/fixtures/applitools.config.js
> +  storybookUrl: 'http://localhost:9001',
@amitzur this was done by mistake, I'll revert it back

2023-03-28 21:17 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +    basicConfig = Object.assign([], config);
@amitzur I meant to send an object not an array. In any case, I changed it to what you suggested in your second comment.

2023-03-28 21:23 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +        ...storiesToUpdate.get(story.baselineName)?.config,
@amitzur the reason I decided to go with a `Map` structor, is that if we have multiple configurations that includes the same story we need to merge them. That way, I can easily find if the current story was already included in a different config and merge all.

2023-03-28 21:28 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +  function handleBrowser({config}) {
@amitzur I added `handleBrowser` method only to for the sake of `shouldRenderIE`. I have to check that before merging all configs as I need to know if I should add this to `storiesWithConfig` or to `storiesWithConfigIE`.
Since `shouldRenderIE` check for `renderers` and not `browser`, I had to make this transformation here as well but on the other hand didn't want to copy the logic of adding `name` and transforming `chromeEmulationInfo`

2023-03-28 21:44 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
done

2023-03-28 21:46 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +      let remainingStories = Object.assign([], storiesWithTitle);
done

2023-03-28 21:47 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +      delete basicConfig['storyConfiguration'];
done

2023-03-28 21:47 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +  let basicConfig;
done

2023-03-29 05:29 UTC, amitzur commented on js/packages/eyes-storybook/test/unit/renderStory.test.js
> +      target: 'region',
Well you can say that about all other properties in this test that don't get a value that makes sense. But that just makes it all the more explicit - the test says _"see how I put just strange values here? it's because they don't have any meaning besides being populated in the expected output"_.

2023-03-29 05:30 UTC, amitzur commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +      storyConfigurations.forEach(storyConfig => {
https://github.com/github/eslint-plugin-github/blob/main/docs/rules/array-foreach.md
For me it feels cleaner. No need for an inner function.
We can consider using this eslint rule from github

2023-03-29 06:39 UTC, amitzur commented
@SophieDePaula I made some changes:
- remove instances of "story subsets"
- make logging in eyesStorybook more understandable
- refactor getStoriesWithConfig unit test
- remove batchName from subConfig (because it doesn't make sense)
- add `waitBeforeCapture` property to "merge multiple subsets" test, in order to actually test overriding of properties

Please go over the way I rewrote tests for `getStoriesWithConfig`. I think it's more readable now.
Also, note that 1 test is failing - it's a case of `fakeIE` where the story needs to be split into 2 - there is one normal and one fake IE.

Lastly, now that I dive deeper into `getStoriesWithConfig` I think there is a way to remove `handleBrowser`, and also address the case that there is already `renderers` property in `transformBrowser`. You don't need to pass the entire config into it. Only the local one which was returned from `storyConfiguration`.

2023-03-29 06:40 UTC, amitzur commented
@SophieDePaula overall I was happy to see the test coverage :)

2023-03-29 17:29 UTC, SophieDePaula commented
@amitzur 
1) I fixed the failing unit test. 
2) If I send only the local config to `transformBrowser` then if I don't have browser in my local config but I do have it in the basic of another previous sub config, then I'll get the default value of `browserInfo`.
3) I am not sure why sending `config: {...expectedConfig, ...expectedSubConfig2}` to every story is better than adding the config with a `map`. My thought was that I wanted to do less copy pasting. 

Im glad you like the coverage :tada:

2023-03-29 17:33 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +      storyConfigurations.forEach(storyConfig => {
Ok, I updated the for loop

2023-03-29 22:00 UTC, SophieDePaula commented
@amitzur I did not change the logic around `shouldRenderIE` because it does not align with a scenario that we only have a `fakeIE` environment.
In that case, I'll also get an array with one entry, but I don't know if it's a fakeIE config or not and again, I'll have to create some logic to check that, so I left it the way it was.

2023-03-29 22:06 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Add support for configuration per subsets of stories
@benbabayoff8

2023-03-30 15:21 UTC, merged