WIP - remove duplicate tests
applitools/eyes.sdk.javascript1 pull request #1348
Opened 2023-03-20 18:04 UTC by tourdedave

re: [Trello](https://trello.com/c/dUGbA7TW/84-support-cypress-retry-mechanism)

(a.k.a. support test framework retries)

2023-03-20 18:25 UTC, kyrylodolynskyi reviewed
I understand it is a draft. Just wanna leave here a few comments.

2023-03-20 18:25 UTC, kyrylodolynskyi commented on js/packages/core/src/separate-duplicate-results.ts
This file should go to the utils folder, the root level is just for the actual commands that will be user-facing.

2023-03-20 18:25 UTC, kyrylodolynskyi commented on js/packages/core/src/separate-duplicate-results.ts
> +            new Date(b?.result?.startedAt as Date).valueOf() - new Date(a?.result?.startedAt as Date).valueOf(),
instead on `new Date(startedAt).valueOf()` I recommend `Date.parse(startedAt)`

2023-03-21 13:03 UTC, tourdedave commented on js/packages/core/src/separate-duplicate-results.ts
> +            new Date(b?.result?.startedAt as Date).valueOf() - new Date(a?.result?.startedAt as Date).valueOf(),
💯

2023-03-23 10:19 UTC, kyrylodolynskyi requested changes

2023-03-23 10:19 UTC, kyrylodolynskyi commented on js/packages/core/src/get-manager-results.ts
> +        const {serverUrl, apiKey, proxy} = storage[0]?.test?.server
This couldn't be right... There might be different server urls and api keys.

2023-03-23 10:19 UTC, kyrylodolynskyi commented on js/packages/core/src/get-manager-results.ts
> +          }
Why not delete tests in parallel?

2023-03-23 10:19 UTC, kyrylodolynskyi commented on js/packages/core-base/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
This is the wrong place for this property. `core-base` doesn't know anything about managers, this type is used in `eyes.getResults()` not `manager.getResults()`

2023-03-23 10:19 UTC, kyrylodolynskyi commented on js/packages/core/src/make-manager.ts
> +  removeDuplicateTestsPerBatch?: boolean
As we decided. This is unnecessary here.

2023-03-23 10:19 UTC, kyrylodolynskyi commented on js/packages/core/src/get-manager-results.ts
> +    const {keepDuplicateTests} = storage[0]?.test
This property could be different for every test

2023-03-23 10:19 UTC, kyrylodolynskyi commented on js/packages/core/src/get-manager-results.ts
> +                secretToken: dup?.result?.secretToken as string,
No need for type casting here.

2023-03-23 13:03 UTC, tourdedave commented on js/packages/core/src/get-manager-results.ts
> +    const {keepDuplicateTests} = storage[0]?.test
Okay. So, what do you recommend?

2023-03-23 13:10 UTC, tourdedave commented on js/packages/core-base/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
So where does it need to go?

```
src/get-manager-results.ts:54:20 - error TS2339: Property 'removeDuplicateTestsPerBatch' does not exist on type 'GetResultsSettings<TType>'.

54     if ((settings?.removeDuplicateTestsPerBatch, !keepDuplicateTests)) {
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/get-manager-results.ts:54
```

2023-03-23 13:22 UTC, kyrylodolynskyi commented on js/packages/core-base/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
To the core's (not `core-base`) type - `GetResultsSettings`

2023-03-23 13:25 UTC, tourdedave commented on js/packages/core/src/get-manager-results.ts
> +                secretToken: dup?.result?.secretToken as string,
```
src/get-manager-results.ts:63:17 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

63                 testId: dup?.result?.id,
                   ~~~~~~

src/get-manager-results.ts:64:17 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

64                 batchId: dup?.result?.batchId,
                   ~~~~~~~

src/get-manager-results.ts:65:17 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

65                 secretToken: dup?.result?.secretToken,
                   ~~~~~~~~~~~


Found 3 errors in the same file, starting at: src/get-manager-results.ts:63
```

2023-03-23 13:32 UTC, tourdedave commented on js/packages/core-base/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
But the way core's `GetResultsSettings` are written derive their values from what is in `core-base` through a ternary operator. It's unclear to me what action I should take.

```
export type GetResultsSettings<TType extends 'classic' | 'ufg'> = (TType extends 'ufg'
  ? UFGCore.GetResultsSettings
  : ClassicCore.GetResultsSettings) & {throwErr?: boolean}
```

2023-03-24 07:11 UTC, kyrylodolynskyi commented on js/packages/core-base/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
You can see that core's `GetResultsSettings` extends ufg's `GetResultsSettings` or classic's `GetResultsSettings` with `throwErr` property, you should simply add also your property allong the declaration of `throwErr`.

2023-03-27 10:54 UTC, kyrylodolynskyi commented on js/packages/core/src/get-manager-results.ts
> +    const {keepDuplicateTests} = storage[0]?.test
I recommend marking the test results with this flag, so you can understand what to do with the result object (remove or not)

2023-03-27 11:08 UTC, kyrylodolynskyi commented on js/packages/core/src/get-manager-results.ts
> +                secretToken: dup?.result?.secretToken as string,
Ah, I admit it. The `TestResult` type has a shitty declaration where every property is optional.

2023-03-27 16:22 UTC, tourdedave commented on js/packages/core-base/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
Okay, thanks for the explanation. But just so you know, this declaration is not easy to read. It wasn't clear until you pointed it out that the `throwErr` property was being applied to either of the `GetResultSettings`. At a glance, it looks like the property is only applied to classic's given the way the ternary operator is laid out. Only after reading it a few times did I see the parens enclosing the ternary.

2023-03-27 16:35 UTC, tourdedave commented on js/packages/core/src/utils/separate-duplicate-results.ts
> +  ]
My understanding of the requirement is to 1) find uniques so we can delete them from eyes, and 2) remove the uniques from the results returned to the user.

I don't want to mutate date in place, but rather, return a modified copy. And I want to unit test the behavior not just to exercise it but to make it clear what the contract of the function is to anyone who needs to maintain it later. I also don't want to add additional code to an already large function for someone to reason about when it can easily be abstracted.

The argument of utility versus business case doesn't make sense to me because the utility is the business case. And we currently only need to do it in one place. If we needed to reuse this in additional places and customize it based on different contexts, then I would agree with you that what you're recommending would be a better direction.

2023-03-27 17:51 UTC, tourdedave commented on js/packages/core/src/get-manager-results.ts
> +    const {keepDuplicateTests} = storage[0]?.test
Okay. But before I get to that, seeing a situation when running a GCT where core-base completes `openEyes` and sets `keepDuplicateTests` to `true`, but when core/`getManagerResults` is called, `keepDuplicateTests` is not included in any of the tests. Thoughts on what would cause that?

2023-03-28 11:19 UTC, kyrylodolynskyi commented on js/packages/core-base/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
This is prettier formatting. I agree it is not the best way to write this expression, but the parenthesis should give a hint.

2023-03-28 14:26 UTC, tourdedave commented on js/packages/core/src/get-manager-results.ts
> +        const {serverUrl, apiKey, proxy} = storage[0]?.test?.server
What do you recommend?

2023-03-28 18:27 UTC, tourdedave commented
@benbabayoff8 I've added `removeDuplicateTestsPerBatch` as the RunnerOption users can use to enable this behavior. Please let me know if you'd prefer a different name for this.

2023-03-29 07:18 UTC, kyrylodolynskyi requested changes
I have one more request, can you update `js/core/docs/universal.md` with the new feature you added?

2023-03-29 07:18 UTC, kyrylodolynskyi commented on js/packages/core-base/src/types.ts
> +  keepDuplicateTests?: boolean
This is always defined, so should not be optional.
I think the name is a little bit misleading, it should not be plural, also you keep the result and not the test, so I would say `keepDuplicate(d?)Result`

2023-03-29 07:18 UTC, kyrylodolynskyi commented on js/packages/core/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
We decided that we don't need it here.

2023-03-29 07:18 UTC, kyrylodolynskyi commented on js/packages/eyes-api/test/unit/Eyes.spec.ts
>    })
Actually, we don't need this. We want to pass it only in `manager.getResults`

2023-03-29 07:18 UTC, kyrylodolynskyi commented on js/packages/core/test/it/get-manager-results.spec.ts
> +    assert.deepStrictEqual(summary.results.length, 1)
What kind of duplicate is that? It is just a two-step test, we need to open other eyes to create a pseudo-duplicate.
Also, we agreed that `removeDuplicateTestsPerBatch` should go in `getResults`.

2023-03-29 07:18 UTC, kyrylodolynskyi commented on js/packages/core/test/utils/fake-base-core.ts
> +                })
This is wrong. Steps are not test results, they are steps in the test result, so basically, the way it was before.
This explains the integration test that I also commented on.

2023-03-29 07:18 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/Runners.ts
> +      removeDuplicateTestsPerBatch: this._removeDuplicateTestsPerBatch,
I understand that we don't need it in the settings because we decided to put it in `getResults`.

2023-03-29 09:16 UTC, benbabayoff8 commented on js/packages/eyes-api/src/Runners.ts
> +      removeDuplicateTestsPerBatch: this._removeDuplicateTestsPerBatch,
@kyrylodolynskyi How would you imagine it within the getAllTestResults (user API)?

2023-03-29 09:29 UTC, kyrylodolynskyi commented on js/packages/eyes-api/src/Runners.ts
> +      removeDuplicateTestsPerBatch: this._removeDuplicateTestsPerBatch,
We are not talking about user-facing api. This is an internal api on which we decided since it is the most flexible one.

2023-03-29 14:23 UTC, tourdedave commented on js/packages/core/test/it/get-manager-results.spec.ts
> +    assert.deepStrictEqual(summary.results.length, 1)
Nice catch. I never revisited this test once I got the e2e test working. I'll take a look.

2023-03-29 14:30 UTC, tourdedave commented on js/packages/core/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
Put another way - if I remove this declaration, then `eyes-api` will throw a build error

```
src/Runners.ts:53:74 - error TS2339: Property 'removeDuplicateTestsPerBatch' does not exist on type 'EyesManagerSettings'.

53         settings: {throwErr, removeDuplicateTestsPerBatch: this.settings.removeDuplicateTestsPerBatch},
```

2023-03-29 14:30 UTC, tourdedave commented on js/packages/eyes-api/test/unit/Eyes.spec.ts
>    })
I'm not sure I agree. Waiting on feedback to my comment above.

2023-03-29 17:10 UTC, tourdedave commented on js/packages/core-base/src/types.ts
> +  keepDuplicateTests?: boolean
Thinking about this more, why should it not be plural? There could be more than one duplicate result. And why is it misleading? The usage of "test" as the object of interest is consistent with what we expose at the user level. Which is better in the long term and less confusing - to be precise (e.g., specific to the implementation detail) or accurate (e.g., consistent with the naming convention of the feature that is exposed to the user)?

2023-03-29 17:18 UTC, kyrylodolynskyi commented on js/packages/core/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
`eyes` package will get a build error because it is wrong as well. We decided that `removeDuplicateTestsPerBatch` will be passed in `.getResults()`, this means it should go in `GetResultSettings` (you already added it there). `EyesManagerSettings` applied to `makeManager`, passing new property there was our first idea that we throw away during our discussion.

2023-03-29 17:25 UTC, kyrylodolynskyi commented on js/packages/core-base/src/types.ts
> +  keepDuplicateTests?: boolean
I hear your reasoning about `test` vs. `result`. But about plural vs. singular, I have to point out that you specify it per test, so there could not be multiple tests within a test. This flag answers the question - "should I remove this test (singular) if it is considered a duplicate?"

2023-03-29 17:31 UTC, tourdedave commented on js/packages/core/src/types.ts
> +  removeDuplicateTestsPerBatch?: boolean
We clearly have a misunderstanding and need to sync to discuss. Because yesterday we reviewed my changes in eyes-api on our sync call and you said it aligned with what we discussed. So I am confused, and find this back and forth surprising and frustrating.

2023-03-29 22:50 UTC, tourdedave commented on js/packages/core-base/src/types.ts
> +  keepDuplicateTests?: boolean
Depends on your definition of `test`, because the property that is exposed for the user to opt-in to this behavior is `removeDuplicateTestsPerBatch`. Again - I was going for consistency that would (in my mind, at least) make this code easier to reason about long term.

2023-03-29 22:57 UTC, tourdedave commented
Functionally, everything works as needed for both cypress and all core/universal based SDKs. However, based on the last round of feedback from @kyrylodolynskyi there are some changes that need to be addressed. I'm off tomorrow but back on Friday. If this can wait until Friday, then I will finalize the PR and work on releasing by end-of-the-day then. But - if you (@benbabayoff8, @amitzur, @kyrylodolynskyi) would like to err on the side of caution and ship something sooner, then feel free to make the necessary changes to finalize this PR and ship while I'm away.

2023-03-30 11:21 UTC, amitzur commented on js/packages/core/src/get-manager-results.ts
> +            const {serverUrl, apiKey, proxy} = dup?.result?.server!
@kyrylodolynskyi there's a typescript error on this line because `Property 'server' does not exist on type 'TestResult'`. Where should these values be taken from then?

2023-03-30 11:30 UTC, amitzur commented on js/packages/core/src/utils/separate-duplicate-results.ts
> +    const batchBaselines = new Set(containers.map(r => r.result?.baselineId))
@kyrylodolynskyi there is a TS error here `Property 'baselineId' does not exist on type 'TestResult'.`
From what I see, `baselineId` is not defined on `TestResult` in `core`, but it is defined on `TestResult` in `core-base`. How do you suggest I mitigate this situation?
In general, would we want to define `core`'s `TestResult` as `extends CoreBase.TestResult` ?

2023-03-30 11:35 UTC, amitzur commented on js/packages/core/src/get-manager-results.ts
> +            const {serverUrl, apiKey, proxy} = dup?.result?.server!
Sorry, it was my bad for not linking the packages.

2023-03-31 11:25 UTC, kyrylodolynskyi commented
@amitzur @tourdedave I applied some changes to the types in the `core` and implementation in the `eyes`, also finalized e2e test in cypress.

2023-03-31 11:25 UTC, merged

2023-03-31 13:00 UTC, tourdedave commented
Thanks @amitzur & @kyrylodolynskyi for taking this PR the rest of the way!