Non-visual tests
applitools/eyes.sdk.javascript1 pull request #1426
Opened 2023-04-11 14:35 UTC by kyrylodolynskyi

Description coming soon...

2023-04-14 14:57 UTC, tourdedave requested changes
Looks great! The distinction between visual and functional tests is clear, the refactoring in the ec-client makes it easier to follow, the executeScript implementation support looks solid, and it's a nice touch that you made it so that we can get the metadata for self-healing out of executeScript.

I saw a TODO comment in core/universal and it wasn't clear to me what needed to be done and if it was necessary for this PR. And as for the execute script e2e test - it seems like we should add an assertion to make sure the desired result was achieved (or else how would we know that it's working as we expect?)

2023-04-14 14:57 UTC, tourdedave commented on js/packages/core/src/universal/core.ts
> +      // TODO
What needs to happen here?

2023-04-14 14:57 UTC, tourdedave commented on js/packages/execution-grid-client/test/e2e/client.spec.ts
> +    await driver.executeScript('applitools:endTest', {status: 'Failed'})
This test is just checking that the command completes, we should also check that the intended result happened in Eyes, no?

2023-04-18 06:33 UTC, kyrylodolynskyi commented on js/packages/core/src/universal/core.ts
> +      // TODO
This is not necessary. It is here just because of the types. Because the universal core should be an exact mapping of the regular core, we don't need it here.

2023-04-18 06:33 UTC, kyrylodolynskyi commented on js/packages/execution-grid-client/test/e2e/client.spec.ts
> +    await driver.executeScript('applitools:endTest', {status: 'Failed'})
I agree! But the problem is that this is basically `closeAsync`, so there are no test results in the response, so we don't have the info to check it on the back-end. Maybe we should introduce another command `applitools:getResults` to use it for debugging at least.

2023-04-18 12:01 UTC, merged