consider params from story
applitools/eyes.sdk.javascript1 pull request #1502
Opened 2023-04-28 18:25 UTC by SophieDePaula

2023-05-01 10:37 UTC, amitzur commented
@SophieDePaula There is some cleanup to do, and I would like the e2e test to contain more cases.
By "cleanup" I mean that I would like `story.parameters.eyes` to be merged into `story.config`. So that it would be done one time at the beginning, and then in `getStoryData` and `renderStory`, and generally any place that reads the config of a story, will not care where it came from. `story.config` should be the place to read from.
Makes sense?

2023-05-01 10:39 UTC, amitzur requested changes
See my comment above. I will continue to review this and provide more feedback, but my comment should already provide you with some work, and it's the main part of my feedback.

2023-05-02 00:25 UTC, SophieDePaula commented
@amitzur lmk what you think

2023-05-02 00:25 UTC, SophieDePaula commented on pending-changes.yaml
> +    - Add the options to send a list of browsers from the component configuration
@benbabayoff8

2023-05-02 07:58 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Add the options to send a list of browsers from the component configuration
Shouldn't it be "Add the option"?

2023-05-02 13:56 UTC, amitzur requested changes

2023-05-02 16:42 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/renderStory.js
> -    const eyesParameters = (parameters && parameters.eyes) || {};
@amitzur I am merging `eyesParameters` in `getStoriesWithConfig` in `addConfigToStoy`

2023-05-02 17:09 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/getStoriesWithConfig.js
> +          ...new Set([
@amitzur I agree, the reason I did that is because I unnecessarily merge the config with itself when there was no use in `storyConfiguration`. But I have fixed it now.

2023-05-02 17:15 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/unit/getStoriesWithConfig.test.js
@amitzur there is an `e2e` test for `renderers`, `layoutBreakpoints` and `waitBeforeCapture` properties from `parameters.eyes`.
There are also `unit` tests in `renderStory.test.js` where we check that the story config includes the values from `parameters.eyes`

2023-05-02 17:20 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/generateConfig.js
> +  if (!result) return;
@amitzur I call this function on `story.parameters.eyes`, so in case someone set an empty object there we don't want to crash.

2023-05-03 17:39 UTC, kyrylodolynskyi commented on js/packages/eyes-storybook/src/generateConfig.js
> +  if (!result) return;
@SophieDePaula I think `transfromBrowser` is a very poor naming. You basically transform check settings or config (it is not clear what is the type of `result`).
Back to the topic, an empty object is not going to match the condition (means `!{} === false`). if you want to ensure that the `result` is not `null` or `undefined`, then I think you should do it before calling the function.
Also, I see that you actually can this function this way `transformBrowser({...story.parameters.eyes})`, so it is never gonna be `null` or `undefined`.

I recommend addressing it before merging and also giving a function a proper name.

2023-05-03 17:41 UTC, kyrylodolynskyi requested changes
I like the fact that you cleaned up a bit around the feature! I left one small comment, feel free to address and merge without an additional approvement.

2023-05-03 17:42 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/generateConfig.js
> +  if (!result) return;
@kyrylodolynskyi I see you are right. Why is `tranformBrowser` a bad name? I only address the browser in that method.

2023-05-03 18:43 UTC, kyrylodolynskyi commented on js/packages/eyes-storybook/src/generateConfig.js
> +  if (!result) return;
It just happened that you transform the browser **_field_** but the object of other types. You could as well transform other properties of the object. You should think about the types first, it would be a good name if the function would accept an object of type `Browser` and return `Renderer`. So in your case, the function accepts something like `StorybookConfig` type and returns something like `TransformedStorybookConfig` (I don't fully understand hypothetical types in storybook SDK).
I hope it is clear

2023-05-03 22:55 UTC, merged