[java, bongo] support pending changes
applitools/eyes.sdk.javascript1 pull request #1519
Opened 2023-05-02 09:29 UTC by IdosApplitools

Updated `bongo` to support non-js SDKs in the `version` command in order to integrate with `pending-changes.yml`.

Java example usage: 

```
../js/packages/bongo/src/cli/index.js version --with-pending-changes -sa --non-js --pending-changes-file-path ../pending-changes.yaml -p "Java" --verbose
```

2023-05-03 13:01 UTC, IdosApplitools commented on js/packages/bongo/src/changelog/update.js
> +    case 'Java':
@tourdedave While implementing it in a way it would consider a manifest type (JSON, XML, etc) I realized this might (but probably won't) cause problems if we have overlapping types between different SDKs, and instead of relying on a type, it would be simpler get the version directly from the input. `bongo version` is used when publishing so we already have access to the new version there. Let me know what you think

2023-05-03 13:59 UTC, tourdedave commented on js/packages/bongo/src/cli/index.js
> +      packageName: {alias: 'p', type: 'string'},
That's right. A nice touch though none-the-less.

2023-05-03 14:06 UTC, tourdedave commented on js/packages/bongo/src/changelog/update.js
> +    releaseVersion === undefined ? require(path.resolve(targetFolder, 'package.json')).version : releaseVersion
Yes, that is a confusing concept. The JSON file gets read when calling `require` and turned into an object with keys (e.g., `{version: '1.2.3'}`). Using `{version}` means that you want to extract just the version property and store it in a variable of the same name. Calling `.version` on the return of `require` works because `.require` is a property on the object that gets created.

We shouldn't need to explicitly check for undefined. A slightly cleaner way to achieve the same thing would be something like this:

```js
const version = releaseVersion ? releaseVersion : require(path.resolve(targetFolder, 'package.json')).version
```

2023-05-03 15:37 UTC, IdosApplitools commented on js/packages/bongo/src/changelog/update.js
> +    case 'Java':
Yep thats correct, I already updated the implementation and it looks cleaner.

2023-05-23 06:47 UTC, IdosApplitools commented
@kyrylodolynskyi @tourdedave can you please take a look at the updated changes?
Java & Python will require a release of `bongo` after the merge for us to use.

2023-05-25 01:23 UTC, tourdedave commented
@IdosApplitools I'm off tomorrow but hoping to look at this PR on Friday.

2023-05-26 15:44 UTC, tourdedave requested changes
Looks great! Just one recommendation for tweaking the API for updating pending changes (and updating the test). Once you change that and resolve the merge conflicts feel free to merge. You should also be able to release it yourself from the Actions tab (e.g., `Publish - bongo`). You can ship it as a minor version.

Also, it's worth noting that I updated `send-release-notification` to fix a bug when specifying the version. The argument used to be `--version` but now it's `--release-version` just like you did in this PR. So the arguments are aligned. Mentioning it here in case you might need to update your GitHub action for sending release notifications.

2023-05-26 15:44 UTC, tourdedave commented on js/packages/bongo/test/changelog/pending-changes.spec.js
> +      let releaseVersion // default is undefined
No need to specify this here. We can just pass it only if needed.

2023-05-26 15:44 UTC, tourdedave commented on js/packages/bongo/src/changelog/update.js
> +function writeReleaseEntryToChangelog(targetFolder, releaseVersion, {withDate = true} = {}) {
It's probably better to put `releaseVersion` in with `withDate`, rather than add an additional argument (especially since the release version is optional).

2023-05-26 15:44 UTC, tourdedave commented on js/packages/bongo/test/changelog/pending-changes.spec.js
> +        writeReleaseEntryToChangelog(cwd, releaseVersion, {withDate: false})
With the API change I mentioned for `writeReleaseEntryToChangelog` this would just be `writeReleaseEntryToChangelog(cwd, {withDate: false})`

2023-05-26 15:44 UTC, tourdedave commented on js/packages/bongo/test/changelog/pending-changes.spec.js
> +        writeReleaseEntryToChangelog(cwd, releaseVersion, {withDate: false})
And then this would be `writeReleaseEntryToChangelog(cwd, {releaseVersion, withDate: false})`. Or you could just inline the version: `writeReleaseEntryToChangelog(cwd, {releaseVersion: '4.58.4', withDate: false})`

2023-07-11 06:07 UTC, IdosApplitools commented
Closing this PR since these changes are no longer relevant with the new release-please flow.

2023-07-11 06:07 UTC, closed without merging