fix: wait for play
applitools/eyes.sdk.javascript1 pull request #1628
Opened 2023-05-30 17:37 UTC by SophieDePaula

[Trello card](https://trello.com/c/Ww0h1hQV/1884-storybook-race-condition-leading-to-failed-tests)

2023-07-06 11:33 UTC, amitzur requested changes
Did you manage to reproduce this?
There is another direction of using the channel to actually emit the `SET_CURRENT_STORY` event to render the story:
https://github.com/storybookjs/storybook/blob/97a2b8940112dd62c2775feb1fe9bafb93bf0bd2/code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx#L101
But that's a bigger change that requires more investigation. The solution in this PR is good enough IMO

2023-07-06 11:33 UTC, amitzur commented on js/packages/eyes-storybook/src/browser/getClientAPI.js
> +  if (/iframe/.test(window.location.href)) {
this is unrelated to the current PR, why is it here?

2023-07-06 11:33 UTC, amitzur commented on js/packages/eyes-storybook/src/browser/getClientAPI.js
> +      return /\/iframe/.test(frame.location.href);
same as last comment

2023-07-06 11:33 UTC, amitzur commented on js/packages/eyes-storybook/test/fixtures/storybook-versions/latest/package.json
> +    "storybook": "STORYBOOK_VERSION=latest sb dev -p 9010",
I don't understand. Did latest not run Storybook 7 before? Also, `STORYBOOK_VERSION` is not read anywhere. And `APPLITOOLS_FRAMEWORK_VERSION` is the way to set storybook version now. So what is this change?

2023-07-06 16:53 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/browser/getClientAPI.js
> +  if (/iframe/.test(window.location.href)) {
Yes, this is a different issue. I removed it and will address it in a different PR.

2023-07-06 16:53 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/browser/getClientAPI.js
> +      return /\/iframe/.test(frame.location.href);
I responded on the last comment

2023-07-06 18:11 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/fixtures/storybook-versions/latest/package.json
> +    "storybook": "STORYBOOK_VERSION=latest sb dev -p 9010",
@amitzur I changed it to `APPLITOOLS_FRAMEWORK_VERSION`, and not it didn't use 7 I had to manually update some dependencies to make this run on 7

2023-07-06 20:15 UTC, SophieDePaula commented
> Did you manage to reproduce this? There is another direction of using the channel to actually emit the `SET_CURRENT_STORY` event to render the story: https://github.com/storybookjs/storybook/blob/97a2b8940112dd62c2775feb1fe9bafb93bf0bd2/code/lib/preview-api/src/modules/preview-web/PreviewWithSelection.tsx#L101 But that's a bigger change that requires more investigation. The solution in this PR is good enough IMO

I was not able to reproduce this, can I merge this?

2023-07-11 17:45 UTC, SophieDePaula commented
@kyrylodolynskyi I added you as a reviewer as I see that Amit is on PTO

2023-07-24 19:59 UTC, amitzur approved these changes

2023-07-24 21:15 UTC, merged