feat: add getResults api to Cypress
applitools/eyes.sdk.javascript1 pull request #1663
Opened 2023-06-20 00:16 UTC by SophieDePaula

TODO:

- [ ] Add a test

2023-06-27 04:35 UTC, kyrylodolynskyi commented on js/packages/eyes-cypress/test/components/.yarnrc.yml
> +globalFolder: ../../../../.yarn/cache
```suggestion
cacheFolder: ../../../../.yarn/cache
```

2023-06-27 04:35 UTC, kyrylodolynskyi commented on js/packages/eyes-cypress/test/e2e/cypress-run-disableBrowserFetching.test.js
> +const {describe, it, before, after} = require('mocha') // eslint-disable-line
why?

2023-06-27 04:35 UTC, kyrylodolynskyi commented on js/packages/eyes-cypress/test/e2e/cypress-run-disableBrowserFetching.test.js
> +    await pexec('npm install cypress@latest')
why not yarn?
It's no surprise that our test takes an eternity to run if we perform installations in them (just an observation)

2023-06-27 17:49 UTC, SophieDePaula commented on js/packages/eyes-cypress/test/e2e/cypress-run-disableBrowserFetching.test.js
> +    await pexec('npm install cypress@latest')
@kyrylodolynskyi I updated all tests to use `yarn`

2023-06-27 17:52 UTC, SophieDePaula commented on js/packages/eyes-cypress/test/e2e/cypress-run-disableBrowserFetching.test.js
> +const {describe, it, before, after} = require('mocha') // eslint-disable-line
@kyrylodolynskyi I added `mocha` to `eyes-cypress` devDependencies.
I thought since this dependency is in the devDependencies of the root project it should recognize it, but I get an error message that this package is extraneous

2023-06-27 18:23 UTC, kyrylodolynskyi commented on js/packages/eyes-cypress/test/e2e/cypress-run-disableBrowserFetching.test.js
> +const {describe, it, before, after} = require('mocha') // eslint-disable-line
I don't understand.
Why do we even need to import those functions if they should be globally accessible when we running with mocha?

2023-06-27 18:26 UTC, SophieDePaula commented on js/packages/eyes-cypress/test/e2e/cypress-run-disableBrowserFetching.test.js
> +const {describe, it, before, after} = require('mocha') // eslint-disable-line
@kyrylodolynskyi I didn't realize that mocha is globally accessible

2023-06-28 07:03 UTC, amitzur requested changes
Overall this is done.
Most important is not to remove the `test:ts` tests. Otherwise I would approve it since I only have comments about style.

Please add those tests, even if not with matrix, then with what it was running before this PR.

I see in many places you have `.gitignore`, `.yarnrc.yml`, and `yarn.lock`. I assume it's an attempt to improve test performance anywhere we run `yarn`, right? Did it work?
Seems a bit verbose to have it in so many places, and it seems to me most of these folders don't even need it. Am I right?

2023-06-28 07:03 UTC, amitzur commented on js/packages/eyes-cypress/.gitignore
> -test/coverage/generic/yarn.lock
also, you already added a `.gitignore` file in `test/coverage/generic`

2023-06-28 07:09 UTC, kyrylodolynskyi commented on js/packages/eyes-cypress/package.json
> +    "test": "yarn test:unit && yarn test:it && yarn test:e2e && yarn test:components && yarn test:coverage",
You need to check the `/release-please-config.json` file. It contains the matrix that runs this test with different cypress versions.

2023-06-28 07:18 UTC, amitzur commented on js/packages/eyes-cypress/package.json
> +    "test": "yarn test:unit && yarn test:it && yarn test:e2e && yarn test:components && yarn test:coverage",
Ahhh ok. That's good. Then just need to readd `test:ts:compile`.

2023-06-28 07:19 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.build.json
@SophieDePaula this file is not needed AFAICT

2023-06-28 17:10 UTC, SophieDePaula commented on js/packages/eyes-cypress/.gitignore
> -test/coverage/generic/yarn.lock
@amitzur we need `yarn` as part of `test:coverage` command because this suite is running with cypress version > 10 which uses `cypress.config.js` rather than `cypress.json` (which exists in the root) so we need to isolate it from the root `eyes-cypress` dir. So we install all the dependencies separately in the target folder.

2023-06-28 17:17 UTC, SophieDePaula commented on js/packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/getResults.js
> +      cy.task('log', `@@START@@${JSON.stringify(result)}@@END@@ `)
@amitzur the thought behind it was that this is a dedicated test to getResults and  `get-test-results-for-checkSettings.js` is part of a different test and if we change it in the future it might affect this test.

2023-06-28 17:20 UTC, SophieDePaula commented on js/packages/eyes-cypress/src/browser/commands.js
> +    const throwErr = args.throwErr !== false ? true : false
right...

2023-06-28 17:20 UTC, SophieDePaula commented on js/packages/eyes-cypress/src/browser/commands.js
> +  Cypress.config('getResultsArgs', args)
I suppose you are referring to `Cypress.config` , we don't I'll remove it

2023-06-28 17:54 UTC, SophieDePaula commented on js/packages/eyes-cypress/package.json
> +    "test": "yarn test:unit && yarn test:it && yarn test:e2e && yarn test:components && yarn test:coverage",
Done

2023-06-28 17:59 UTC, SophieDePaula commented on js/packages/eyes-cypress/test/e2e/ts/cypress/tsconfig.build.json
removed

2023-06-29 08:36 UTC, amitzur commented on js/packages/eyes-cypress/.gitignore
> -test/coverage/generic/yarn.lock
I think the solution is to move `cypress.json` out of that place instead of installing cypress in every folder we run. But we can sort it out later.

2023-06-29 11:28 UTC, merged