Python release please integration test PR
applitools/eyes.sdk.javascript1 pull request #1719
Opened 2023-07-06 20:39 UTC by ikseek

2023-07-07 11:43 UTC, kyrylodolynskyi requested changes

2023-07-07 11:43 UTC, kyrylodolynskyi commented on release-please-config.json
> +        {"runner": "linux", "artifacts": ["./dist"], "key": "{{component}}/{{package-version}}/{{hash}}"}
no need to specify `runner` if this is a default one.

2023-07-07 11:43 UTC, kyrylodolynskyi commented on release-please-config.json
> +      "skip-snapshot": true,
this is a java-only property

2023-07-07 11:43 UTC, kyrylodolynskyi commented on .github/actions/setup/main.ts
> +          let [_, version] = versionModule.match(/__version__\s+=\s+"([0-9.]+)"/) as RegExpMatchArray
This seems like a very complicated way to get the version. So many variations, isn't it the same in all python packages?

2023-07-07 11:43 UTC, kyrylodolynskyi commented on .github/actions/setup/main.ts
> +              packages["core-universal"] = {
The package name has to be a key here.

2023-07-07 11:43 UTC, kyrylodolynskyi commented on .github/actions/python/tests/action.yml
> +    required: false
What does it mean? If this is just a pattern string to decide what test to run, then we already have a "standard" name for this - `grep`. It is not required for us to have the same naming here, but I think this will really nice.

2023-07-07 12:24 UTC, ikseek commented on .github/actions/setup/main.ts
> +          let [_, version] = versionModule.match(/__version__\s+=\s+"([0-9.]+)"/) as RegExpMatchArray
This variation is for historical/compatibility reasons. There is a change in code structure not merged yet that makes all packages have version in applitools/pkg_name/__init__.py. But robot will be different, it has their own naming convention.

2023-07-07 13:08 UTC, kyrylodolynskyi commented on .github/actions/setup/main.ts
> +          let [_, version] = versionModule.match(/__version__\s+=\s+"([0-9.]+)"/) as RegExpMatchArray
What about the version in `setup.cfg`? Isn't in what we need?

2023-07-18 12:15 UTC, kyrylodolynskyi requested changes
Looks good to me. But you will have to add `"builds": ["js/core/x64/{{environment}}", "js/core/arm64/{{environment}}"]` to your build jobs that need to have binaries to create a proper build.

2023-07-18 12:15 UTC, kyrylodolynskyi commented on .github/workflows/ci.yml
> +        if: ${{matrix.builds}}
it is always an array so it never be falsy
```suggestion
        if: ${{join(matrix.builds)}}
```

2023-07-19 08:40 UTC, kyrylodolynskyi reviewed
Few more questions:
1. Do you use any tools for reporting / sending notifications to the qa server other than the action called `bongo` (this one https://github.com/applitools/eyes.sdk.javascript1/blob/master/.github/actions/bongo/action.yml)? 
2. Did you integrate linting into `python/build` action as we discussed so we can avoid running `pre-commit` workflow separately? 
3. Are you planning to remove `py-tests` workflow once fully migrated to the new release flow?

2023-07-19 08:40 UTC, kyrylodolynskyi commented on .github/actions/python/tests/action.yml
Can you call this action `test` instead of `tests`? It is a small thing, I just want to keep the terminology the same across languages at least for central actions.

2023-07-19 13:45 UTC, ikseek commented
> Few more questions:
> 
> 1. Do you use any tools for reporting / sending notifications to the qa server other than the action called `bongo` (this one https://github.com/applitools/eyes.sdk.javascript1/blob/master/.github/actions/bongo/action.yml)?
Not anymore, i removed all other reporting calls. But this bongo action will need a change addressing the issue @Artem-applitools was solving by a smart report merge
> 2. Did you integrate linting into `python/build` action as we discussed so we can avoid running `pre-commit` workflow separately?
Not yet, I don't remember that was needed. I will do it in separate PR, this one is big enough already.
> 3. Are you planning to remove `py-tests` workflow once fully migrated to the new release flow?
Sure, together with py-publish.

2023-07-19 14:29 UTC, Artem-applitools commented on python/Makefile
> +install_selenium_generated_tests_requirements: install_functional_tests_requirements
How it generate tests now without node_modules install?

2023-07-25 18:05 UTC, merged