fix(js/req,ufg-client): support retries on AbortError
applitools/eyes.sdk.javascript1 pull request #1773
Opened 2023-07-13 18:10 UTC by tourdedave

[Trello](https://trello.com/c/A704uHVc)

In some customer networks, a request to check the render status of a job in the UFG can exceed the allotted timeout of 60 seconds. When this happens the SDK aborts the job rather than retrying the request (since no response has been received for the request -- so, no HTTP status or error codes to potentially trigger a reply). This PR attempts to remedy that by enabling retries on `AbortError` to be done, opt-in by specifying it in `codes` (see [my test](https://github.com/applitools/eyes.sdk.javascript1/blob/fa6dc81342c8afd168ed137ebb0fa72f83bde3cc/js/packages/req/test/it/req.spec.ts#L188) for an example).

In order to support this behavior, a new `AbortController` needed to be created for each `req` (e.g., inside of the inner `req` function instead of the outer `req` function). I'm open to suggestions if you see a cleaner way to approach this.

I've also adjusted the timeout for the `/render-status` request to reduce it from 60 seconds down to 20 seconds based on feedback in the Trello ticket.

2023-07-13 18:44 UTC, kyrylodolynskyi reviewed
This makes no sense to me, first of all, I intentionally put timeout higher than retries, because this is what we want to limit the amount of time per whole operation, not just for one request, this way there is less sense to set timeout because you will still don't know how many time it will take with all of the retries.
But an even more critical point is that AbortError !== timeout, there are other reasons for the request to about. Obviously, when you intentionally abort a request it should not be retried.

2023-07-17 09:41 UTC, kyrylodolynskyi requested changes
One more thing I would like to request is since we already tracking the reasons for abortions we can throw better errors from req, by replacing the `AbortError` thrown from fetch.

2023-07-17 09:41 UTC, kyrylodolynskyi commented on js/packages/req/test/it/req.spec.ts
>    })
Why do you remove this test? Didn't we decide to preserve the functionality we already have?

2023-07-17 09:41 UTC, kyrylodolynskyi commented on js/packages/ufg-client/src/server/requests.ts
> +      stuckTimeout: 15000,
I understand that this number is coming from Or perception of how much time this request should take. But I think we should be slightly less optimistic here because we don't know the customers' network condition and other client-side crap. I think the original timeout was written without an understanding of the separation between stuck timeout and overall request timeout, which means the 1-minute timeout should be used as a stuck timeout and the overall timeout should be set to a higher number. But maybe you would argue that this is  "too safe", so I suggest timeout = 90_000 and stuckTiomeout = 30_000

2023-07-17 09:41 UTC, kyrylodolynskyi commented on js/packages/req/src/types.ts
> +  stuckTimeout?: number
I like the name, but I think in terms of api it should be done a little bit differently. I will try to explain, by looking at this api it seems like I can interchange stuck and overall timeouts and the difference is in semantics. But, as your implementation proves, the only reason to use `stuckTimeout` is to retry when it happens. And I think that the api should reflect it, this is why I suggest putting this property in the `Retry` type, this will also allow configuring amount of attempts and an interval.
I would like to discuss it today over zoom to hear your arguments.

2023-07-17 13:22 UTC, tourdedave commented on js/packages/req/test/it/req.spec.ts
>    })
My mistake - I thought I was modifying a test I had added. I'll fix it.

2023-07-17 17:20 UTC, kyrylodolynskyi requested changes

2023-07-17 17:20 UTC, kyrylodolynskyi commented on js/packages/req/src/req.ts
> +  const timeout = options.connectionTimeout
Can you use the same prefix for both, so it will be clear that they are connected? I mean rename `timeout` to `connectionTimeoutTimer` or to `connectionTimer`, but then `connectionTimeoutController` to `connectionController`.

2023-07-17 17:20 UTC, kyrylodolynskyi commented on js/packages/req/src/req.ts
> +      }
This is a remote scenario, but I think you should check if the error cached is AbortError, because what if we will have some other error happening between calling `controller.abort()` and the actual error thrown?

2023-07-17 17:20 UTC, kyrylodolynskyi commented on js/packages/req/src/req-errors.ts
> +}
You should use an enum for that.

2023-07-17 18:47 UTC, tourdedave commented on js/packages/req/src/req.ts
> +          if (!abortReason) AbortReasons.requestTimeout
Right! I didn't update the test correctly, so this went unnoticed. Nice catch!

2023-07-17 18:50 UTC, tourdedave commented on js/packages/req/src/req.ts
>      if (options.signal) options.signal.onabort = () => controller.abort()
If both are set *and* the `code` `STUCK_REQUEST` is specified in the retry options, then it will respect the `connectionTimeout`. But if the `code` is not provided, then yes, it seems like something else will happen.

2023-07-17 20:26 UTC, tourdedave commented on js/packages/req/src/req.ts
>      if (options.signal) options.signal.onabort = () => controller.abort()
I've fixed it so it will only retry on stuck requests with both the `requestTimeout` and retry.codes includes `STUCK_TIMEOUT` is specified. In either case, the `connectionTimeout` will be respected.

2023-07-17 20:35 UTC, tourdedave commented on js/packages/req/src/req.ts
> +      }
Wouldn't we only get an `AbortError` if we call `controller.abort()`? If there is some other error, then the error would be untouched and pass through as-is. If you can think of a concrete example then we can add a test for it to try and expose/fix this scenario. I'll leave it as-is for now.

2023-07-17 21:49 UTC, merged