feat: add the option to fail on diffs in global hooks
applitools/eyes.sdk.javascript1 pull request #1844
Opened 2023-08-03 23:35 UTC by SophieDePaula

[Trello card](https://trello.com/c/dTlEpkgc/1978-fujitsu-cypress-tests-taking-too-long)

2023-08-04 17:35 UTC, SophieDePaula commented
@amitzur @benbabayoff8 ,

here is the PR re the Cypress execution time we were talking about.
I named the flag `failCypressOnDiffAfterAll` as it aligns with the current flag we have `failCypressOnDiff` and it is clear from the name what's the functionality.
@amitzur I think the name you suggested `failCypressAfterAllSpecs` is also very informative but a bit too long, I am ok with using it if you think what I suggested is not clear enough.

2023-08-09 22:50 UTC, amitzur requested changes
@SophieDePaula I left some inline comments. 2 general points:
1. We keep making patches in the Cypress codebase. We can't continue to do this. There are so many confusing and things I cannot explain in the code, that I don't know where to start providing feedback.
2. Not sure about the naming. `failCypressOnDiffAfterAll` sounds too verbose and too similar to `failCypressOnDiff`. There is a difference between them. `failCypressOnDiff` is responsible for the switch fail-->non-fail. `failCypressOnDiffAfterAll` is responsible to make the failure happen at a specific point. This begs the question - what happens if you set `failCypressOnDiff` to false, and `failCypressOnDiffAfterAll` to true? IMO there should be no failure, since it's set to false. This is why I think it should be called `failCypressAfterAllSpecs` or `waitForAllSpecs`, to emphasize that it's talking about **when** to do the thing.

2023-08-09 22:50 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/hooks.ts
> +        showLogs?: boolean
where did this pop up?

2023-08-09 22:50 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/hooks.ts
> +        let testResults = []
wow, the code before this change was really doing nonesense.
I think you should use more functional code style here:
```
const testResults = summaries.map(
  ({results}) => results.map(({result}) => result)
).flat()
```

2023-08-09 22:50 UTC, amitzur commented on js/packages/eyes-cypress/src/plugin/hooks.ts
> +          eyesFailCypressOnDiff: config.appliConfFile.failCypressOnDiffAfterAll,
This way to write code leads to confusing code IMO. Renaming a parameter like that, I mean.
We should be aware to make changes to parameter names to make them be more sensible. In this case, for example, the parameter to `printTestResults` makes sense to call `shouldThrowError`.
I'm sorry to say, this is just a drop in an ocean of spaghetti unmaintained code.

2023-08-09 22:50 UTC, amitzur commented on js/packages/eyes-cypress/src/browser/commands.js
> +  !Cypress.config('appliConfFile').failCypressOnDiffAfterAll
How do you feel about this condition? Does it look like it would be easy to maintain?

2023-08-10 00:50 UTC, SophieDePaula commented on js/packages/eyes-cypress/src/plugin/hooks.ts
> +        showLogs?: boolean
@amitzur I suppose that this type was created to address the current needs of this file and does not reflect all the properties that can be added to the configuration file (`applitools.config.js`) I modified it to be closer to reality.

2023-08-10 00:51 UTC, SophieDePaula commented on js/packages/eyes-cypress/src/plugin/hooks.ts
> +        let testResults = []
@amitzur yes, we had a bug there , I used your code instead of mine and added a test to make sure we include all test results in the tap file.

2023-08-10 00:52 UTC, SophieDePaula commented on js/packages/eyes-cypress/src/plugin/hooks.ts
> +          eyesFailCypressOnDiff: config.appliConfFile.failCypressOnDiffAfterAll,
@amitzur I took your advice and now we check for `shouldThrowError` rather than `eyesFailCypressOnDiff`.
Let's talk about this SDK in more details in our next meeting.

2023-08-10 00:53 UTC, SophieDePaula commented on js/packages/eyes-cypress/src/browser/commands.js
> +  !Cypress.config('appliConfFile').failCypressOnDiffAfterAll
@amitzur I now use a variable for this condition instead.

2023-08-10 00:59 UTC, SophieDePaula commented
@amitzur I addressed your inline comments, as for your general comments:

1) I changed the name of the new flag to `failCypressAfterAllSpecs`.  The logic is if `failCypressOnDiff: false` and `failCypressAfterAllSpecs: true` then we check for diffs only after all specs are done
2) As I mentioned in one of my previous comments, let's discuss the state of this SDK in our next meeting.

2023-08-14 20:03 UTC, amitzur reviewed
Much much better :)

2023-08-14 20:03 UTC, amitzur commented on js/packages/eyes-cypress/test/e2e/cypress-run-CypressFailOnDiffAfterAllSpecs.test.js
> +    const normalizedStdout = err.stdout.replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])/g, '')
`strip-ansi`

2023-08-15 20:45 UTC, merged