feat: show aborted tests in Eyes dashboard
applitools/eyes.sdk.javascript1 pull request #1877
Opened 2023-08-15 21:50 UTC by SophieDePaula

TODO:

- [ ] Add test

2023-08-21 06:02 UTC, amitzur requested changes
@SophieDePaula See inline comments. There is missing/wrong implementation.
In general, I would like to see unit tests for the new code in `renderStory` and `processResults`.

2023-08-21 06:02 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +  const resultsOrErr = results.results
What use case is this solving? Did we miss some errors until now? Why is a variable that holds only errors called `resultsOrErr`? Is `.stack` really the way to identify errors in this array? Why do all other places in this function process `results.summary.results` and only this place processes `results.results`?

2023-08-21 16:07 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/renderStory.js
> +              target: snapshots ?? {},
@amitzur the reason I was calling `check` with an empty `snapshot` was because the `storage` was empty otherwise.
Where would you call `baseEyes = await eyes.getBaseEyes()` ? I don't have an `eyes` instance.

2023-08-21 16:11 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +    r => (r.result.status === 'Passed' || r.result.isNew) && !r.result.isAborted,
@amitzur no, but we check here if it's `Passed` or `New`, I can make this condition clearer.

2023-08-21 16:41 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/renderStory.js
> +              target: snapshots ?? {},
@amitzur re the `API` change, I was thinking about the use experience here, if they see that some of their tests are aborted than it's a better experience to see the error immediately in the console and not start looking for the error in the probably huge logs, or even worse , not having logs enable in the first place, rerunning the test and then maybe or maybe not reproducing the same issue.

2023-08-21 17:58 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +    r => (r.result.status === 'Passed' || r.result.isNew) && !r.result.isAborted,
That's where I was aiming :)

2023-08-22 23:34 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/renderStory.js
> +              target: snapshots ?? {},
@amitzur I spoke with Kyrylo and now we only call `open` and `abort` with additional logic in `abort`

2023-08-22 23:39 UTC, SophieDePaula commented on js/packages/core/src/ufg/abort.ts
> +      })
@kyrylodolynskyi this is what we discussed plus some additions and changes. When I called `eyes.abort` from line 61, `fetch` crashes.
Also, I had to add the test to the storage as I need to the `testResults` and I need to know which test was aborted.

2023-08-22 23:40 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/renderStory.js
> +              target: snapshots ?? {},
Re the second point, I removed it even though I think it can only be beneficial for the user, I suppose it's not super important.

2023-08-23 00:11 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +  const resultsOrErr = results.results
@amitzur I changed this condition to check for the logic around our `TestResults`object structure rather than the error object structure.
[Type](https://github.com/applitools/eyes.sdk.javascript1/blob/master/js/packages/core/src/ufg/types.ts#L64) and [returned value](https://github.com/applitools/eyes.sdk.javascript1/blob/master/js/packages/core/src/ufg/get-results.ts#L19)

2023-08-23 04:47 UTC, amitzur requested changes
See inline comments

2023-08-23 04:47 UTC, amitzur commented on js/packages/core/src/ufg/abort.ts
> +          const {eyes} = await Promise.race(promises)
@SophieDePaula don't duplicate this code. Try to organize the code to write it once.

2023-08-23 04:47 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +        !err.message.includes('is failed! See details at'),
we should really try to find another way to do this.

2023-08-23 04:47 UTC, amitzur commented on js/packages/eyes-storybook/test/e2e/snapshots/storybook-aborted.e2e.test.json
> +    "Single category: Single story - Failed Failed to get story data for Single category: Single story, test was aborted",
This `Failed Failed` output doesn't look good. Let's try to get a better result.

2023-08-23 04:47 UTC, amitzur commented on js/packages/eyes-storybook/test/unit/renderStory.test.js
> +        abort: async () => {
@SophieDePaula I wrote a comment about this code style already in this PR. Either do `return Promise.reject(...)` or better yet `throw new Error(...)`.

2023-08-23 18:04 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/e2e/snapshots/storybook-aborted.e2e.test.json
> +    "Single category: Single story - Failed Failed to get story data for Single category: Single story, test was aborted",
@amitzur I added a `.` after the first `Failed`, so now it's `Single category: Single story - Failed. Failed to get ...`

2023-08-23 18:06 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +        !err.message.includes('is failed! See details at'),
@amitzur I rearranged that to :

```
  const errMessagesToExclude = [
    'detected differences',
    'Please approve the new baseline',
    'is failed! See details at',
  ];
  errors = flatten(errors)
    .filter(({err}) => err && !errMessagesToExclude.some(msg => err.message.includes(msg)))
    .concat(flatten(resultsErr));
```

2023-08-23 22:25 UTC, SophieDePaula commented on js/packages/core/src/ufg/abort.ts
> +          const {eyes} = await Promise.race(promises)
fixed

2023-08-23 22:25 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/unit/renderStory.test.js
> +        abort: async () => {
Fixed

2023-08-24 14:42 UTC, amitzur commented on js/packages/core/src/ufg/abort.ts
> +        const [baseEyes] = await eyes.getBaseEyes({settings: {renderer, properties}, logger: logger})
@kyrylodolynskyi why does `getBaseEyes` return an array?
@SophieDePaula please change `logger: logger` to just `logger`.

2023-08-24 15:52 UTC, SophieDePaula commented on js/packages/core/src/ufg/abort.ts
> +        storage.set(key, [new Promise(resolve => resolve({renderer, eyes: baseEyes}))])
Ah yes, we discussed this

2023-08-24 15:58 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +        !(Array.isArray(result.resultsOrErr) && utils.types.has(result.resultsOrErr[0], 'renderer'))
@amitzur it can either be an `error` or [an Array](https://github.com/applitools/eyes.sdk.javascript1/blob/master/js/packages/core/src/ufg/get-results.ts#L19) of [TestResult](https://github.com/applitools/eyes.sdk.javascript1/blob/master/js/packages/core/src/ufg/types.ts#L64)

2023-08-24 15:59 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +    if (result.result.isAborted) {
Sure, I guess it make sense

2023-08-24 16:16 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +    if (result.result.isAborted) {
@amitzur actually when I look at the code I see that if `isAborted` is not the first one, then I'll have to add ` && !result.result.isAborted` to `isNew` and `!result.result.isDifferent`.
So leaving it as is make more sense to me.

2023-08-25 05:54 UTC, kyrylodolynskyi commented on js/packages/core/src/ufg/abort.ts
> +        const [baseEyes] = await eyes.getBaseEyes({settings: {renderer, properties}, logger: logger})
Because there maybe many eyes if it was started like this, when you open automation eyes you can pass it an array of base eyes, then when you call `getBaseEyes` you will get them back.

2023-08-27 12:02 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +    if (result.result.isAborted) {
But the output to the user is more important than the code, won't you agree?

2023-08-27 12:02 UTC, amitzur commented on js/packages/core/src/ufg/abort.ts
> +        const [baseEyes] = await eyes.getBaseEyes({settings: {renderer, properties}, logger})
@kyrylodolynskyi why does `getBaseEyes` return an array?

2023-08-28 19:51 UTC, SophieDePaula commented
@amitzur I addressed the scenario where all test fails and we don't have test results (AKA ` Cannot read properties of undefined (reading 'isDifferent')`).
Please let me know if you have any additional comments.

2023-08-29 09:19 UTC, amitzur requested changes
See inline comments. I'm not 100% done yet, I still need to go over `processResults.js`

2023-08-29 17:45 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/e2e/snapshots/storybook-aborted.e2e.test.json
> +    "Single category: Single story - Failed. Failed to get story data for Single category: Single story, test was aborted",
@amitzur I have a [test in `it`](https://github.com/applitools/eyes.sdk.javascript1/blob/storybook-abort-failed-stories/js/packages/eyes-storybook/test/it/snapshots/processResults.test.json#L147) that shows the output of two tests, one `Passed` and on `Aborted`.

As for the second part of your question, it is showed twice, once with the status (`Passed` / `Unresolved` / `Aborted`) and we also specify the `browserInfo` as we can have some stories that have different statuses on different environments. The second time with show the `title` and the reason for the failure.

2023-08-29 17:47 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/unit/renderStory.test.js
> +  it('should throw an error when openEyes fails', async () => {
@amitzur it is not , but I didn't see a test for it and I wanted to make sure this woks properly as it is related to the [second trello card](https://trello.com/c/KXs3dW5O/2013-canvaeditor-build-failures) fix that is included in this PR.

2023-08-29 18:31 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/unit/renderStory.test.js
> +    const baseStory = {
@amitzur I only need the `baselineName` and an empty `config`, I'll remove everything else.

2023-08-29 21:40 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/it/processResults.test.js
> +        resultsOrErr: [new Error('another error messgae !')],
@amitzur I done what we spoke about , I threw an exception for one of the renderers in `render.ts` in `checkRenderResults` and the result was that we fail all environments. Therefore, the scenario that we have an array with one entry of `TestResult` and one with error is not possible.

2023-08-30 15:45 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +        !(Array.isArray(result.resultsOrErr) && utils.types.has(result.resultsOrErr[0], 'renderer'))
@SophieDePaula if `result.resultsOrErr` is an array, then it cannot be an error, right? So why `utils.types.has(result.resultsOrErr[0], 'renderer')`?

2023-08-30 15:46 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
@SophieDePaula in this `concat` aren't you probably creating duplicates?

2023-08-30 18:38 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +        !(Array.isArray(result.resultsOrErr) && utils.types.has(result.resultsOrErr[0], 'renderer'))
@amitzur that's correct, I removed it.

2023-08-30 18:44 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
@amitzur while looking into this I found, that if we get an error in the `TestResult` (for example when a render fails), the structure is different than what we expected. First, we might not have `result` anymore, also we can only get the `testName` from [`userTestId`](https://github.com/applitools/eyes.sdk.javascript1/blob/master/js/packages/core/src/open-eyes.ts#L55) in `eyes` so I fixed that . As for dups, we use `uniq` on `title` which is `baselineName` in both cases so we don't print dup errors per story.

2023-08-30 18:53 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
Ok, `userTestId` is 100% not a good way to get the test name. Please try to find another way.

2023-08-30 18:56 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
@SophieDePaula I don't understand. What does `eyes.getResults` return in the case of a render failure?

2023-08-30 19:00 UTC, amitzur commented on js/packages/eyes-storybook/test/it/snapshots/processResults.test.json
> +    "My Component | Button1 - Failed. some error messgae !",
@SophieDePaula what caused this change in the output?

2023-08-30 19:44 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
@amitzur when we fail to render it seems we add `info` to the `Error` object, [see this](https://github.com/applitools/eyes.sdk.javascript1/blob/master/js/packages/core/src/ufg/check-and-close.ts#L310).

Also, why is `userTestId` is 100% not a good way to get the test name? I don't have the test name unfortunatly if the render fails and I see that in `open-eyes` that `userTestId` is  `settings.userTestId ??= ${settings.testName}--${utils.general.guid()}`. If this is not good enough I am afraid that I'll have to make changes to `core` to include the test name in the returned object.

2023-08-30 20:02 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
@SophieDePaula the reason it's not good is because it's not an API, it's an implementation detail. Changing that line in core will break your code and there is no way to detect it.

2023-08-30 20:09 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +  const unresolved = testResults.filter(
@amitzur I now filter results that doesn't have `result` property. However, I needed to create another var for testResultsWithErrors as they are no longer included in `testResults`.

2023-08-30 20:18 UTC, amitzur commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
I think we should make `eyes.test` available in `error.info`, and `VisualTest` should have all the OpenSettings.
@kyrylodolynskyi does that sound right?

2023-08-30 20:31 UTC, SophieDePaula commented on js/packages/eyes-storybook/test/it/snapshots/processResults.test.json
> +    "My Component | Button1 - Failed. some error messgae !",
@amitzur because now that the `Error` is not in an Array (as it should be) , then we have `.message` and we don't just  stringify the error object, [see this](https://github.com/applitools/eyes.sdk.javascript1/blob/master/js/packages/eyes-storybook/src/processResults.js#L53)

2023-08-30 21:32 UTC, SophieDePaula commented on js/packages/eyes-storybook/src/processResults.js
> +    .concat(flatten(resultsErr));
@amitzur I added `testName` to `VisualTest` type and now I use it in `processResults`.
I didn't add all `OpenSettings` as it includes many properties and I didn't want to start mapping everything before we get to a final decision  
https://github.com/applitools/eyes.sdk.javascript1/blob/storybook-abort-failed-stories/js/packages/core-base/src/server/requests.ts#L171

2023-09-04 21:27 UTC, merged