feat: change cache to support distributed cache
applitools/eyes.sdk.javascript1 pull request #1913
Opened 2023-09-06 11:48 UTC by zamboney

2023-09-06 11:49 UTC, zamboney commented on js/packages/ufg-client/.mocharc.js
> +  timeout: 3000,
no reason for more the 3sec waiting for test in this pacakge

2023-09-06 11:59 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +  KnownResource,
@zamboney it's still a type

2023-09-07 06:47 UTC, amitzur requested changes
Inline comments mainly about code style and some questions.
But the main point is that I don't get this solution.
Why are you calling `getCachedResource` inside `processContentfulResource`?
Now I'm ready to get an explanation about this solution

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/types.ts
> +type KnownResourceWithoutValue = KnownResource & {value?: never}
This doesn't make sense. `value` is not in `KnownResource`.

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/types.ts
> +) => Promise<KnownResourceWithoutValue | FailedResource | null>
Why not `Promise<KnownResource | FailedResource | null>`? `KnownResource` already doesn't have the `value` property.

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/types.ts
> +  getValueFromCache?: CacheFunctionWithCallback
I think this is leftovers that you forgot to remove

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/client.ts
>    cache = defaultResourceCache,
Why are you still receiving the cache? You replaced it with `getCachedResource`.

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +        .then(() => (waitUploadResources = []))
I assume you reset this array for the same reason we suspect `ready` was turned from promise to boolean? In order to not keep a reference for this promise forever?

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +      resource: ContentfulResource | FailedResource | null
why can it be null?

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +    skipCache = false, // if the callback cache is called form another callback, we don't want to cache it
Not good coding convention to have this as a second parameter. The function is already receiving a single destructured parameter.

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +    async function callback(): ReturnType<CacheFunctionWithCallback> {
Put inner functions at the end so that it's clear what the body of the function is.

2023-09-07 06:47 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +    async function callback(): ReturnType<CacheFunctionWithCallback> {
inner functions at the end

2023-09-07 08:04 UTC, zamboney commented
@amitzur

About the inline comments i will address them inline 😄.

> Why are you calling `getCachedResource` inside `processContentfulResource`?

The way things work (as far as my narrow understanding) is that we want to **"handles prefilled resources with dependencies"**

I think it's easier to understand it by the tests that are failing if you comment `getCachedResource` [here](https://github.com/applitools/eyes.sdk.javascript1/blob/bfecc76ec798db66ef31cd8e5e6f1de0a7184062/js/packages/ufg-client/src/resources/process-resources.ts#L115-L116) and just return the `callback`

```diff
       }
       return resource
     }
-    if (skipCache) return callback()
-    return getCachedResource(resource?.id || (resource?.hash as {hash: string}).hash, callback)
+    return callback()
   }
 
   async function processUrlResource({
```

Once done 3, tests failed

```
yarn test:unit --reporter tap | grep 'not ok'

not ok 54 processResources handles the case when the same resource appears as prefilled resource and as a dependency of another url resource
not ok 62 processResources handles resources with errorStatusCode (non-200 resources) from cache
not ok 63 processResources handles prefilled resources with dependencies
```


Before, this issue did not occur, but we changed the cache mechanism and no longer can update the dependencies of a resource in the cache. You can see the changes [here](https://github.com/applitools/eyes.sdk.javascript1/blob/f8a36db1f5359491b1f71e8221997824bd2ed7e6/js/packages/ufg-client/src/resources/process-resources.ts#L177-L180) and [here](https://github.com/applitools/eyes.sdk.javascript1/blob/f8a36db1f5359491b1f71e8221997824bd2ed7e6/js/packages/ufg-client/src/resources/process-resources.ts#L195).


This is what I currently understand about the topic. I can delve deeper to gain a better understanding of "prefilled" resources and their dependencies, but it goes beyond the scope of this task (i think).

2023-09-08 08:36 UTC, amitzur requested changes

2023-09-08 08:36 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +  function getResourceId({
I don't like this function. I don't understand why it's needed. We saw yesterday that a resource should always has an `id`. The only case we saw it doesn't is for the dom resource, which could and should be fixed.

2023-09-08 08:36 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +    resource: {value?: Buffer; hash?: HashedResource | {errorStatusCode: number}; id?: string}
I don't like this usage of some ad-hoc type for a resource.

2023-09-08 08:36 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +  const getCachedResource = (
Why make it complicated? You can just use `getCachedResource` and pass it `resource.id`.

2023-09-08 08:36 UTC, amitzur commented on js/packages/ufg-client/src/resources/process-resources.ts
> +          const processedResource = await getCachedResource(resource, () =>
No. `getCachedResource` is only meant to be used for fetching resources that you don't have the value for.
There is no need to set anything in the cache if it wasn't fetched in this operation.
Why did you add it?

2023-09-08 08:36 UTC, amitzur commented on js/packages/ufg-client/src/resources/resource.ts
> +export function isHashedResource(resource: unknown): resource is HashedResource {
There is no need for this function.

2023-09-08 14:43 UTC, zamboney reviewed
@amitzur in general you need to make a decision:
1. we are keeping the tests and logic intact and push this change faster and agree to deal with the issue about the change in logic later
2. we are understanding what the author did and fix the logic issue that raise when we change the cache to support in a distributed way

2023-09-08 14:43 UTC, zamboney commented on js/packages/ufg-client/src/client.ts
>    cache = defaultResourceCache,
i want to keep the existing flow, also it's not really in use. if you think this is unnecessary i will remove it

2023-09-13 07:38 UTC, merged