fix: add support to shadow dom iframe
applitools/eyes.sdk.javascript1 pull request #1925
Opened 2023-09-14 08:15 UTC by zamboney

2023-09-18 09:11 UTC, kyrylodolynskyi requested changes

2023-09-18 09:11 UTC, kyrylodolynskyi commented on js/packages/snippets/src/browser/getChildFramesInfo.js
>  }
Shouldn't it be the recursive implementation? I mean calling the same function repeatedly inside every shadow root? This will also cover the case when the iframe is located in a nested shadow root document (the one that is already inside a shadow root)

2023-09-18 09:15 UTC, zamboney commented on js/packages/snippets/src/browser/getChildFramesInfo.js
>  }
sure i will do that

2023-09-19 14:39 UTC, zamboney commented
@kyrylodolynskyi changed as requested please take anther look, 10x!

2023-09-19 18:24 UTC, kyrylodolynskyi commented on js/packages/snippets/src/browser/getChildFramesInfo.js
> +  root = root || document
@zamboney Pay attention to the convention among all snippets, it always accepts only one (or none) argument and this argument is an array. So I recommend this

```suggestion
function getChildFramesInfo([root = document] = []) {
```

2023-09-19 18:56 UTC, zamboney commented
I try your suggestion but when I do I get a `null` as an argument and it's over writing the default value, I will give it a try tomorrow...

2023-09-19 20:48 UTC, zamboney commented on js/packages/snippets/src/browser/getChildFramesInfo.js
> +  root = root || document
I try your suggestion but when I do I get a `null` as an argument and it's over writing the default value, I will give it a try tomorrow...

2023-09-20 06:07 UTC, kyrylodolynskyi commented on js/packages/snippets/src/browser/getChildFramesInfo.js
> +  root = root || document
This is how it works everywhere else (you can check yourself), so I will be surprised if this isn't going to work

2023-09-20 07:57 UTC, zamboney reviewed
@kyrylodolynskyi made some changes please take a look again 10x

2023-09-20 07:58 UTC, zamboney commented on js/packages/snippets/src/browser/getChildFramesInfo.js
> +  root = root || document
@kyrylodolynskyi, your suggestion didn't work because the parameter that is supplied by the driver is `null`, but I made some changes by moving the recursive function inside. I hope this better meets your needs

2023-09-20 08:07 UTC, kyrylodolynskyi approved these changes

2023-09-20 08:51 UTC, merged