fix: set environment in reset
applitools/eyes.sdk.javascript1 pull request #1939
Opened 2023-09-27 10:33 UTC by zamboney

force `isNative` based on the name of the `switchWorld` variable.

2023-09-27 10:34 UTC, zamboney commented on js/packages/driver/src/driver.ts
> +            'getDriverInfo' | 'getEnvironment' | 'getViewport' | 'getFeatures' | 'getHelper' // I'm not sure if we need all of these options
I'm not sure if we need all of these options

2023-09-27 10:34 UTC, zamboney commented on js/packages/driver/src/driver.ts
> +  reset?: Extract<Parameters<typeof Driver.prototype.refresh>[0], 'reset'> | boolean // TODO: WDYT about this? if this is unnecessary, i an remove it IMO we need to remove the boolean option
WDYT about this? If this is unnecessary, I can remove it IMO we need to remove the boolean option

2023-09-27 13:35 UTC, kyrylodolynskyi reviewed
I am not sure what you are trying to achieve. We are detecting exactly this when extracting the environment. Are you trying to do an optimization?
In other words, is there any other reason, except optimization, to know that this is a native context before the call to `getEnvironment`?

2023-09-27 14:19 UTC, zamboney commented
@kyrylodolynskyi take a look at the test. If the user changes the context to `NATIVE_APP` and then `check`, the test throws an error of `Method not implemented` because the `switchWorld` change to native while the caps are set to `web`. This is an issue because it's trying to get the `userAgent` using `executeScript` which is not supported in `NATIVE_APP`.  🤷‍♂️ 
anyway, I'm trying to fix it from the `spec-driver`... I think it's make more sense

2023-09-27 14:22 UTC, kyrylodolynskyi commented
@zamboney It wasn't clear from the test. So basically you are saying that the problem is that we do not reset capabilities. Right?
I don't see how you can fix it from spec-driver side 🤔

2023-09-27 14:25 UTC, zamboney commented on js/packages/spec-driver-webdriver/src/spec-driver.ts
> +  return {sessionId: driver.sessionId, environment: {isNative}}
@kyrylodolynskyi ☝️

2023-09-27 14:29 UTC, kyrylodolynskyi commented on js/packages/spec-driver-webdriver/src/spec-driver.ts
> +  return {sessionId: driver.sessionId, environment: {isNative}}
So you would have to do it in every spec-driver. The spec-driver is meant to be minimal, and everything that could be implemented elsewhere should be implemented elsewhere. This has already been implemented in `getEnvironment` method of the `Driver`

2023-09-27 14:31 UTC, zamboney commented on js/packages/spec-driver-webdriver/src/spec-driver.ts
> +  return {sessionId: driver.sessionId, environment: {isNative}}
Sure makes sense I will change it...

2023-09-27 14:42 UTC, kyrylodolynskyi commented on js/packages/spec-driver-webdriver/src/spec-driver.ts
> +  return {sessionId: driver.sessionId, environment: {isNative}}
Doing it in spec-driver isn't the right way, and I told you the reason why in my previous message. This is not required to be there. Spec-driver already provides instruments to extract this information, this is basically the definition of "not required" for the spec-driver. What is really important for spec driver is to be minimal

2023-09-27 15:03 UTC, kyrylodolynskyi commented on js/packages/driver/src/driver.ts
> +      this._environment.isNative = (await this.getCurrentWorld()) === 'NATIVE_APP'
Just above this line, we are basically doing the same with some reasonable optimizations. As I understand from our conversation the `!this._environment.browserName` statement is not `true` in this case. Right?
So my question is why it is not `true`? Isn't it happening because even after reset we still have capabilities cached?

2023-09-27 15:19 UTC, zamboney commented on js/packages/driver/src/driver.ts
> +      this._environment.isNative = (await this.getCurrentWorld()) === 'NATIVE_APP'
not in the cache in caps. the user supply `app` as `chrome`/`safari` but switch to `NATIVE_APP`

2023-09-27 16:29 UTC, kyrylodolynskyi commented on js/packages/driver/src/driver.ts
> +      this._environment.isNative = (await this.getCurrentWorld()) === 'NATIVE_APP'
Ok. Now I see it in the repro in the ticket. Anyway, you have to consolidate, the old way to extract this info and the new way.
With the requirement to support this, it means that we just always have to extract the current context, no matter whether we are in the browser or not.

2023-09-27 16:42 UTC, zamboney commented on js/packages/driver/src/driver.ts
> +      this._environment.isNative = (await this.getCurrentWorld()) === 'NATIVE_APP'
Not sure if I understand what you mean...

2023-09-28 06:02 UTC, kyrylodolynskyi requested changes

2023-09-28 06:02 UTC, kyrylodolynskyi commented on js/packages/driver/src/driver.ts
> +      this._environment.isNative = (await this.getCurrentWorld()) === 'NATIVE_APP'
My point is you should consolidate the line you added with the `if` statement on line 269. Otherwise, you extract the current world twice, also do it only when `this._environment.isMobile` is `true` seems reasonable.

2023-09-28 08:59 UTC, kyrylodolynskyi requested changes
LGTM now 👍🏼 , but please use the same name for the test and the fixture.

2023-09-28 10:27 UTC, kyrylodolynskyi approved these changes

2023-09-28 11:44 UTC, merged