feat: cross origin iframes
applitools/eyes.sdk.javascript1 pull request #259
Opened 2020-09-10 13:42 UTC by tool3

2020-09-13 11:29 UTC, amitzur reviewed
Very nice work.
I think that for cleanness sake, `crossFramesXpaths` property should be deleted after it's consumed.
The most outstanding issue right now is that original arguments are not preserved.
I think the way to solve it is to have the cross-origin frames functions **inside** `_takeDomSnapshot` so that the parameters are accessible in the closure.

2020-09-13 11:29 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +  return await _takeDomSnapshot({driver})
original arguments are not preserved: browser, disableBrowserFetching and startTime.

Regarding `startTime`: current behavior times out after 5 minutes. I don't think we ever hit this limit, but I think we should preserve this behavior, and the 5 minutes limit (or whatever we set it to in the future) should be on the overall operation, including all the cross origin frames work.

2020-09-13 11:46 UTC, tool3 commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +async function getFrame(driver, xpath) {
I agree !

2020-09-14 20:28 UTC, kyryloonufriiev requested changes
Well done. I leave some comments for you

2020-09-14 20:28 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
>  async function takeDomSnapshot({driver, startTime = Date.now(), browser, disableBrowserFetching}) {
I would love to not pass a `browser` property here. But extract the information we need from a `driver`.

2020-09-14 20:28 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +        : await getScript({disableBrowserFetching})
I think you need to do it once at the start of the whole `takeDomSnapshot` function. Otherwise, you will read from file N times.

2020-09-14 20:28 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    delete snapshot.crossFramesXPaths
What if you have a frame (not cors) with cors frame inside?

2020-09-15 06:53 UTC, tool3 commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    delete snapshot.crossFramesXPaths
all frames are handled by the `processPage` script so when we get here we already have the structure of all frames in the page (including any nested and\or cors frames)

2020-09-15 07:20 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    delete snapshot.crossFramesXPaths
Let's say you have a page like this
```html
<!-- localhost:3000 -->
<iframe src="localhost:3000/frame">
<iframe src="localhost:3001">
```
This is a frame with cors
```html
<!-- localhost:3000/frame -->
<iframe src="localhost:3002">
```

As far as I understand `processPage` scrip will return you a structure like this
```js
{
  // ...
  frames: [{
    // ...
    frames: [],
    crossFramesXPaths: ['/IFRAME[1]']
    // ...
  }],
  crossFramesXPaths: ['/IFRAME[2]']
  // ...
}
```

2020-09-15 07:21 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    delete snapshot.crossFramesXPaths
Am I right? If so, will you go to the nested frame to get information about nested cors frame?

2020-09-15 07:25 UTC, tool3 commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    delete snapshot.crossFramesXPaths
I understand what you mean now... no I am not doing that ! great catch !

2020-09-23 08:19 UTC, amitzur requested changes
Reviewed everything except `takeDomSnapshot.js` :)
I will submit a PR to explain my suggestions for `takeDomSnapshot.spec.js`

2020-09-23 08:45 UTC, tool3 commented on packages/sdk-shared/coverage-tests/custom/TestCheckDomSnapshotCrossOriginFrames_VG.spec.js
> +        title: 'Hello, I have a designer cross origin frame',
just a joke.. the inner frame says: 'Made by Michael CORS'

2020-09-23 08:46 UTC, tool3 commented on packages/sdk-shared/coverage-tests/util/cors-snapshot-middleware.js
> +  return `${staticPath}${url.replace('/handles', '')}`
we actually don't need `path.resolve` as I am getting the `staticPath` as a parameter.. so I literally just append `url` to `staticPath`

2020-09-23 08:47 UTC, tool3 commented on packages/sdk-shared/src/test-server.js
> +    const middleWare = hbData ? require(middlewareFile)(argv) : require(middlewareFile)
yeah I have been trying to resolve that issue - this works and is straightforward

2020-09-23 09:07 UTC, amitzur requested changes
I added to the other PR also suggested changes for `takeDomSnapshot.js`

2020-09-23 11:25 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +        return {reference, parent}
I would like to explain what does it do. Actualy it converts an array of selectors to a backward linked list. This is a structure supported by `EyesContext#context` to get a nested context.
So if you have `['a', 'b', 'c']`
You will get
```
{
  reference: 'c',
  parent: {
    reference: 'b',
    parent: {
      reference: 'c',
      parent: null
    }
  }
}
```

2020-09-23 14:52 UTC, merged