fix: multi region selectors
applitools/eyes.sdk.javascript1 pull request #275
Opened 2020-10-11 08:11 UTC by tool3

# multi region selectors
passing `enableMultipleResultsPerSelector: true,` in `RenderRequest`
enabling the return of `selectorRegions` as an array of arrays.

2020-10-11 11:28 UTC, amitzur reviewed
WIP review. Haven't looked at `calculateMatchRegions` and its test yet

2020-10-11 11:42 UTC, tool3 commented on packages/eyes-sdk-core/lib/renderer/RenderStatusResults.js
> +      selectorRegions = selectorRegions.map(region => {
do you mean change the constructor signature ?

selectorRegions is deconstructed from the response object before instantiating the `RenderStatusResults` class

2020-10-11 11:43 UTC, amitzur commented on packages/eyes-sdk-core/lib/renderer/RenderStatusResults.js
> +      selectorRegions = selectorRegions.map(region => {
correct. which is why it would never be instantiated with a `Region` instance in `selectorRegions`

2020-10-11 11:44 UTC, amitzur commented on packages/eyes-sdk-core/lib/renderer/RenderStatusResults.js
> +      selectorRegions = selectorRegions.map(region => {
```
selectorRegions.map(regions => {
```

2020-10-14 05:51 UTC, amitzur requested changes
review is WIP.
There's a bug in `calculateSelectorsToFindRegionsFor`, which also caused an undesired change in its unit tests.
Other than that, the general implementation is exactly how I envisioned it.

2020-10-14 05:51 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateMatchRegions.test.js
> +    expect(regions[0]).to.be.undefined
why not `expect(regions).to.eql([undefined, undefined, undefined, undefined, undefined, undefined])`?

2020-10-14 05:54 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/createRenderRequests.test.js
> +          {type: 'css', selector: 'bla5', accessibilityType: 'RegularText'},
This is not good - it's exactly the outcome of the bug in `calculateSelectorsToFindRegionsFor`

2020-10-14 05:57 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateMatchRegions.test.js
> +    expect(calculateMatchRegions({codedRegions, selectorRegions: []})).to.eql([
you could remove `selectorRegions:[]` because of the default value you gave it in the function

2020-10-14 05:58 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateMatchRegions.test.js
> +    const codedRegions = [[ignore], undefined, undefined, undefined, undefined, undefined]
This is not the same test. The original test checked a single ignore, not an array.

2020-10-14 06:03 UTC, amitzur commented on packages/visual-grid-client/src/sdk/checkWindow.js
> +      const regions = calculateMatchRegions({
for readability purposes you can also do:
```
const [
  ignoreRegions,
  layoutRegions,
  strictRegions,
  contentRegions,
  accessibilityRegions,
  floatingRegions,
] = calculateMatchRegions({
  codedRegions,
  selectorRegions,
  imageLocationRegion,
})
```

2020-10-14 07:01 UTC, amitzur commented
@tool3 there's a deeper issue. Here are the details:

Suppose this:

```
checkWindow({
  floating: [
    {selector: '.flo', maxUpOffset, maxDownOffset}
  ]
})
```

So:
```
codedRegions[5] = [
  {selector: '.flo', maxUpOffset, maxDownOffset}
]
```

Then:
```
selectorsToFindRegionsFor: ['.flo-1']
```

Suppose there are 3 elements with `.flo`
```
selectorRegions === [[region1, region2, region3]]
```

Now you want to assign these 3 regions with the user input of maxUpOffset and maxDownOffset.

You return this from calculateMatchRegions:
```
regions === [undefined, undefined, undefined, undefined, [region1, region2, region3]]
```

You are doing this:
```
Object.assign(regions[5][0], codedRegions[5][0])
Object.assign(regions[5][1], codedRegions[5][1])
Object.assign(regions[5][2], codedRegions[5][2])
```

But this is wrong. And you get an exception because codedRegions[5] has length 1.

You have no corresponding array to map from the selector regions to the user input.
You need an array that is exactly the size of `selectorsToFindRegionsFor`, but with user input. So that there will be no data loss:
```
userRegionsCorrespodingToVGSelector: [{selector: '.flo', maxUpOffset, maxDownOffset}]
```

---
It becomes more obvious in this case:
```
checkWindow({
  floating: [
    {selector: '.flo-1', maxUpOffset1, maxDownOffset1},
    {selector: '.flo-2', maxUpOffset2, maxDownOffset2}
  ]
})
```

I am pushing an addition to the e2e test that will fail until this is fixed. So you can debug that and see what's going on.

2020-10-14 07:05 UTC, amitzur commented
@tool3 run `test/e2e/openEyes.e2e.test.js` to reproduce the bug

2020-10-15 12:08 UTC, kyryloonufriiev commented on packages/visual-grid-client/src/sdk/calculateSelectorsToFindRegionsFor.js
>    sizeMode,
Why do you need `sizeMode` here? As for me, this is unnecessary. I would rather pass `selector` in this function only in case `sizeMode === 'selector'`.

2020-10-15 12:08 UTC, kyryloonufriiev commented on packages/visual-grid-client/src/sdk/calculateSelectorsToFindRegionsFor.js
> +    let selectorRegionIndex = imageLocationRegion ? 1 : 0
How do you know from the outside what is `imageLocationRegion`. I this code is based on the assumption that in case `sizeMode === 'selector'` the first element is `imageLocationRegion`. I see this function as a correct place to extract imageLocationRegion

2020-10-18 04:40 UTC, amitzur approved these changes
Looks like this is ready! :clap: 
I added some comments which aren't showstoppers. Some conditions seem to be able to be simplified. And I suggested a few name changes to tests.

2020-10-18 04:40 UTC, amitzur commented on packages/eyes-sdk-core/lib/renderer/RenderStatusResults.js
> +   * @param {Region[][]} selectorRegions
It's not `Region[][]`. It's a "region plain object".

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/e2e/openEyes.e2e.test.js
> +      ignore: {selector: 'div[class*="bg-"]'},
I added more validations to this test, why did you remove them?

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/createRenderRequests.test.js
> -    const ignore = ['kuku', {type: 'css', selector: 'bla'}]
Does this test still mean anything?

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/src/sdk/calculateSelectorsToFindRegionsFor.js
>    sizeMode,
I'm not sure about that. I think the role of this function is to construct `selectorsToFindRegionsFor` out of user input.

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/src/sdk/calculateSelectorsToFindRegionsFor.js
> +          if (codedRegions && codedRegions.length > 0) {
why do you need this condition? `codedRegions` is expected to hold an array at this point. If it doesn't, there's a bug or VG didn't return the correct structure. Am I missing anything?

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/src/sdk/checkWindow.js
> +    // const userRegions = [ignore, layout, strict, content, accessibility, floating]
no need to leave this comment

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/src/sdk/createCheckSettings.js
> +      if (region) {
why is this needed?

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/src/sdk/createCheckSettings.js
> +      if (region) {
why is this needed?

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateSelectorsToFindRegionsFor.test.js
> +    it('handles sizeMode with selector, but no selectors', () => {
`handles sizeMode with selector, but no regions` - i think that's a clearer name

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateSelectorsToFindRegionsFor.test.js
> +    it('handles no sizeMode with selector', () => {
`handles no sizeMode with selector region` - otherwise the name is confusing as `selector` is also an argument

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateSelectorsToFindRegionsFor.test.js
> +    it('handles only selectors without sizeMode or selector', () => {
`handles mixed ignore regions with selectors and other region types`

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateSelectorsToFindRegionsFor.test.js
> +    it('handles sizeMode = selector, without selector', () => {
basically that's invalid input, but ok

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateSelectorsToFindRegionsFor.test.js
> +      const floating = {type: 'link text', selector: 'kuku1'}
this is invalid input. I think it's confusing to have this case, since it should never happen. And if it does, then some other piece of our code had a bug.

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateSelectorsToFindRegionsFor.test.js
> +      expect(regions.accessibility[0])
why not also do `expect(regions).to.eql(...)` here? to validate the entire array of regions?

2020-10-18 04:40 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/calculateSelectorsToFindRegionsFor.test.js
> +    })
You can also validate `imageRegionLocation` is returned from `getMatchRegions` here

2020-10-18 04:42 UTC, amitzur commented
@tool3 The most substantial point in the review is the validations of regions in the e2e test. I added those, then commented them out because of the bug. And now instead of uncommenting them, you removed them.

2020-10-18 05:25 UTC, tool3 commented on packages/visual-grid-client/test/e2e/openEyes.e2e.test.js
> +      ignore: {selector: 'div[class*="bg-"]'},
I didn't... I separated it into it's own test

2020-10-18 09:18 UTC, merged