eyes-puppeteer
applitools/eyes.sdk.javascript1 pull request #293
Opened 2020-11-06 18:39 UTC by tourdedave

Here is an initial pass on eyes-puppeteer.

Since it is so similar to Playwright, it went surprisingly quick.

The main difference between Playwright and Puppeteer is how it supports arguments for evaluating JS snippets. Puppeteer accepts one or more arguments and an element reference **cannot** be sent inside of a collection -- it can only be sent as its own argument. This was worked about by creating a wrapper function for the script that can handle deserializing/serializing the arguments. It's still a work in progress -- still need to add support for elements in nested collections.

After that, need to run the remainder of the coverage tests to verify everything else works.

2020-11-16 10:25 UTC, amitzur reviewed
Very nice!
I like the docker-first approach. It makes it easier to make it run in GH actions.
You can delete `scripts/output` file.
I didn't go thoroughly into the spec-driver yet, only to the peripherals.
The main open point is knowing what versions of puppeteer we support.

2020-11-16 10:25 UTC, amitzur commented on packages/eyes-puppeteer/CHANGELOG.md
> +- updated to @applitools/eyes-sdk-core@12.5.7 (from 12.5.5)
can remove this

2020-11-16 10:25 UTC, amitzur commented on packages/eyes-puppeteer/.mocharc.cvg.js
> +    'node_modules/@applitools/sdk-shared/coverage-tests/custom/**/*.spec.js',
aha! You use `node_modules` so this can be used from GitHub Actions!

2020-11-16 10:25 UTC, amitzur commented on packages/eyes-puppeteer/.mocharc.cvg.js
> +  //require: ['../sdk-shared/coverage-tests/util/mocha-hooks.js'],
can remove this comment

2020-11-16 10:25 UTC, amitzur commented on packages/eyes-puppeteer/package.json
> +    "puppeteer": ">=5.3.0"
We haven't discussed this. Can we check what versions of Puppeteer we support?
How hard is it to use an earlier version of puppeteer in the docker container?

2020-11-16 10:25 UTC, amitzur commented on packages/eyes-puppeteer/package.json
> +    "preversion": "bongo preversion && yarn coverage:prod",
not running `yarn test` on purpose?

2020-11-16 10:59 UTC, tourdedave commented on packages/eyes-puppeteer/package.json
> +    "puppeteer": ">=5.3.0"
We can support different versions of Puppeteer. We just need to map it to the correct version of Chrome/Chromium.

https://github.com/puppeteer/puppeteer/blob/main/versions.js

2020-11-16 11:00 UTC, tourdedave commented on packages/eyes-puppeteer/package.json
> +    "preversion": "bongo preversion && yarn coverage:prod",
No reason. I'll add it.

2020-11-16 11:02 UTC, tourdedave commented on packages/eyes-puppeteer/package.json
> +    "preversion": "bongo preversion && yarn coverage:prod",
FYI - that's how it is in eyes-playwright.

2020-11-16 12:03 UTC, amitzur commented on packages/eyes-puppeteer/package.json
> +    "preversion": "bongo preversion && yarn coverage:prod",
thanks for the heads up. I'll fix it

2020-11-17 11:34 UTC, tourdedave commented on packages/eyes-puppeteer/package.json
> +    "puppeteer": ">=5.3.0"
So, effectively, different containers running different version of Chrome and Puppeteer that are compatible. Running on GitHub actions means we'd be running latest Chrome, so we'd run latest Puppeteer.

Is this a use case we need to consider?

2020-11-18 14:02 UTC, kyryloonufriiev requested changes
Looks pretty great. I'm really glad we can build a new sdk in that straightforward way.

2020-11-18 15:47 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +    ? frame.$x(transformedSelector.replace(/^xpath=/, ''))
👍

2020-11-18 15:50 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +  return frame.$$(transformSelector(selector))
👍

2020-11-18 17:19 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +  } else if (TypeUtils.isObject) {
💯

2020-11-18 17:25 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +    : await script(deserializedArgs) // e.g., dom-snapshot can be invoked directly
👏

2020-11-18 17:31 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
Something like this 840f22304f2bf8f3d3a0b0c1edc84b036bc1e3f4?

2020-11-19 14:58 UTC, kyryloonufriiev approved these changes
👍 
I left only one extra comment. But this is not a dealbreaker.

2020-11-19 14:58 UTC, kyryloonufriiev commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
The only reason why we need to know `stale element error` is to try to re-find an element. In case of these errors, I don't think it will be possible. I would say even more `stale element error` is not something that might happen in cdp.
In playwright, I check in this function for some specific case when the page is reloaded and element reference doesn't exist anymore.

2020-11-19 15:00 UTC, kyryloonufriiev commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
Actually, I just get that this is (`Execution context was destroyed`) might be an error puppeteer throws in case of the page was reloaded. In this case first one makes sense, but the second still not.

2020-11-19 15:07 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
The second error comes from execute script. If you remove it and run test/generic/ShouldNotFailIfScrollRootIsStale.spec.js you will see it.

2020-11-19 15:11 UTC, kyryloonufriiev commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
Hmmm. I thought this is where the first error will be thrown. So in which case the first error is thrown?

2020-11-19 15:15 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
On a call to the element that is no longer in scope is one case.

Something like this: https://github.com/applitools/eyes.sdk.javascript1/blob/puppeteer/packages/eyes-puppeteer/test/it/spec-driver.spec.js#L93

2020-11-19 15:17 UTC, merged

2020-11-19 15:21 UTC, kyryloonufriiev commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
Ah. If so it's good. By the way, I don't understand what you mean under "scope". In CDP even if you entirely remove an element from the dom you still have a reference on the detached `Node` instance.

2020-11-19 15:24 UTC, tourdedave commented on packages/eyes-puppeteer/src/spec-driver.js
> +}
That's true, but it's not something you can interact with. By scope I mean it's in context or "is alive"