add streaming resource timeout
applitools/eyes.sdk.javascript1 pull request #328
Opened 2020-12-22 11:00 UTC by yarden-wieder

2021-01-04 11:54 UTC, tourdedave requested changes
Looks good! Just a couple of small things to address.

2021-01-04 11:54 UTC, tourdedave commented on packages/visual-grid-client/src/sdk/fetchResource.js
> +
This function would be more readable wrapped in brackets (at first glance I was thrown off why it wasn't since it was a function w/ a multi-line body)

2021-01-04 11:54 UTC, tourdedave commented on packages/visual-grid-client/src/sdk/fetchResource.js
> +  const canBeStreaming =
I vote for more crisp wording, like `isStreaming`

2021-01-04 11:54 UTC, tourdedave commented on packages/visual-grid-client/test/unit/sdk/fetchResources.test.js
> +        expect.fail,
I'm confused by this line. Why is it here? It seems to contradict the test.

2021-01-04 11:54 UTC, tourdedave commented on packages/visual-grid-client/test/unit/sdk/fetchResources.test.js
> +        expect.fail,
Same here too. Why is it here? It seems to contradict the test.

2021-01-04 12:32 UTC, amitzur reviewed
WIP review

2021-01-05 16:57 UTC, amitzur commented on packages/visual-grid-client/src/sdk/fetchResource.js
> +  const canBeStreaming =
I think because it's a heuristic then it's more like `possiblyStreaming`, `mightBeStreaming`, `probablyStreaming`, `couldBeStreaming`, `maybeStreaming` or any variation of them.... I could go on :)

2021-01-05 20:26 UTC, tourdedave commented on packages/visual-grid-client/test/unit/sdk/fetchResources.test.js
> +        expect.fail,
Then perhaps it's the name I find confusing. If it doesn't apply to requests with a content length, then why would we expect this test to fail?

2021-01-05 22:33 UTC, amitzur commented on packages/visual-grid-client/src/sdk/fetchResource.js
> +    ['audio/', 'video/'].some(prefix => response.headers.get('Content-Type').startsWith(prefix))
@yarden-wieder I find this style more readable. what do you think?
```
/^(audio|video)\//.test(response.headers.get('Content-Type'))
```

2021-01-05 22:44 UTC, amitzur requested changes
There are 3 main issues here:
1. We are now retrying only on the initial response and not on the buffer. I think network conditions might cause the download to fail, and then we would like the retry. In case we time out on streaming we should not retry because it's not considered a failure.
2. We should return an `errorStatusCode` when timing out. Not throw an exception. Otherwise the URL will not be mapped. I suggest `599` so it's clear that it's something we made up and not coming from the webapp itself.
3. Using `Promise.race` when there isn't really a race seems like bad practice. The better way IMO is to use it conditionally if indeed streaming is suspected.

2021-01-05 22:44 UTC, amitzur commented on packages/visual-grid-client/src/sdk/fetchResource.js
> +    const buffer = await Promise.race([
I think it makes more sense not to use `Promise.race` if this isn't streaming. Then you will not need the weird `noTimeout` promise above

2021-01-05 22:44 UTC, amitzur commented on packages/visual-grid-client/src/sdk/fetchResource.js
> +    return psetTimeout(timeout).then(() =>
why not use `await` here?

2021-01-05 23:12 UTC, amitzur commented on packages/visual-grid-client/test/unit/sdk/fetchResources.test.js
> +        expect.fail,
The `expect.fail` is in the second parameter to `.then`. So essentially he's saying - fail the test if `fetchResource(url)` throws.
I agree this is redundant and confusing.

2021-01-06 00:59 UTC, amitzur commented
@yarden-wieder I fixed the 3 items mentioned above :point_up: https://github.com/applitools/eyes.sdk.javascript1/pull/328#pullrequestreview-562188010
And then when running it against the customer's page I saw that the request also needs to be aborted with AbortController. So I added it as well.
There is one flow I couldn't get to test properly, so I'm adding a draft PR for my attempt.
I believe this is ready for merge.

2021-01-06 17:28 UTC, merged