wip: feat support js layouts
applitools/eyes.sdk.javascript1 pull request #329
Opened 2020-12-27 20:32 UTC by tool3

2020-12-28 14:10 UTC, amitzur reviewed
Initial pass at the PR. I will continue to review today/tomorrow

2020-12-28 14:10 UTC, amitzur commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/breakpoints.js
> +      browser: [
The generic test we have uses different browsers. Let's be consistent with it:
https://github.com/applitools/sdk.coverage.tests/blob/master/coverage-tests.js#L112

2020-12-28 14:10 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +        return takeDomSnapshot(options).then(snapshot => Array(browsers.length).fill(snapshot));
I think it's better to still support passing a single snapshot over the wire to the Node.js side. If you have 10 browser configuration and no layout breakpoints, and a large snapshot, then it would be serialized 10 times, which is a shame.

2020-12-28 14:10 UTC, amitzur commented on packages/eyes-cypress/src/plugin/handlers.js
> +      snapshots = [],
I think it still makes sense to support getting a single snapshot. See my comment in eyesCheckWindow line 31

2020-12-28 14:14 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +const makeEyesCheckWindow = require('./eyesCheckWindow.js');
😱 sorry about that

2020-12-28 14:25 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +        if (!!getGlobalConfigProperty('eyesFailCypressOnDiff')) {
yes. previously it was set to be `true` if user provided it or if it's `undefined`.
today I set `eyesFailCypressOnDiff` explicitly to `true` in `pluginExport` unless provided by user.
even if user sets `eyesCypressOnDiff: undefined` this clause will work.

2020-12-28 14:35 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +    Object.assign(checkArgs, {...args, eyesOpenArgs, browser, layoutBreakpoints});
`args` do take precedence over `eyesOpenArgs` - but only for layout breakpoints.
for `browser` - you cannot set `browser` in `check` as far as I understood.

2020-12-28 14:37 UTC, tool3 commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/breakpoints.js
> +      browser: [
👍🏼

2020-12-28 14:50 UTC, tool3 commented on packages/eyes-cypress/src/plugin/handlers.js
> +    getIosDevicesSizes: async () => {
👍🏼

2020-12-28 14:58 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +  const defaultBrowser = {width: 800, height: 600, name: 'chrome'};
to be perfectly honest I wasn't sure what I should use.
in cypress we take the default width and height which is `1000x660`, but in every other sdk we use the default from vgc which is `800x600`.

2020-12-28 15:20 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +        return takeDomSnapshot(options).then(snapshot => Array(browsers.length).fill(snapshot));
this was something I thought about but preferred concentrating on the core concept. now that we have that down I agree that this optimization is required.

I wasn't sure about the prop name so I left it as plural: `snapshots` - even though it can be both an array and a single object.

2020-12-29 12:13 UTC, amitzur commented on packages/eyes-cypress/src/browser/commands.js
> +    Object.assign(checkArgs, {...args, eyesOpenArgs, browser, layoutBreakpoints});
But `args` are first, and then `eyesOpenArgs` overrides it

2020-12-29 12:14 UTC, amitzur commented on packages/eyes-cypress/src/browser/commands.js
> +    Object.assign(checkArgs, {...args, eyesOpenArgs, browser, layoutBreakpoints});
ah, sorry. I see you fixed that

2020-12-29 12:22 UTC, amitzur commented on packages/eyes-cypress/src/browser/commands.js
> +  const defaultBrowser = {width: 800, height: 600, name: 'chrome'};
1. vgc default is 1024x768, not 800x600.
2. in Cypress if `browser` is not specified by the user, we use the viewport size from Cypress' configuration. It's not necessarily 1000x660. This makes sense because then the visual test will be at the same viewport size of the local browser.

2020-12-31 01:43 UTC, amitzur requested changes
1. Config changes in pluginExports feel a bit risky and unrelated.

2. Tests for handlers shouldn't be changed to receive array of snapshots, since this scenario still happens and is actually the happy path. So in order to have tests for multiple snapshots you can add to the existing test suite. In general - **tests should not be removed or altered unless their use case is no longer relevant**. Especially if they are very fast unit tests.

3. saving `openEyesArgs` on the Config is essentially putting them in global scope. I think this would turn out ok just because Cypress handles each file in a separate process, and each file runs the tests serially. I think it would be better if we found a way to scope it, like having a `this` object from Cypress which has context of the current test. But then we need to account for open commands being inside before/beforeEach. So I think the global scope solution simplifies it a lot, and as I said I believe it should be fine. But we should be aware of it, since polluting this global scope might be dangerous. We also don't do any cleanup. I hope Cypress doesn't pass configuration defined in one file to another file.

4. No support for `layoutBreakpoints: true` (crash on exception in `.sort`). Maybe this requirement wasn't communicated clearly. Need to add e2e test to this (see (6) below). In core this is unit tested, but here in Cypress this feature is only tested e2e.

5. Passing args in `eyesCheckWindow` still isn't correct. See comment below.

6. e2e tests should have also:
  a. define `layoutBreakpoints` in global config
  b. define `layoutBreakpoints` in check args
  c. define `layoutBreakpoints` as `true` (in one of the 3 methods)

7. Readme. See what I did for Storybook.

2020-12-31 01:43 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +            .viewport(width, height)
missing `{log: false}`

2020-12-31 01:43 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +        return takeDomSnapshot(options).then(snapshot => snapshot);
I think it's not needed to do `.then(snapshot => snapshot)`

2020-12-31 01:43 UTC, amitzur commented on packages/eyes-cypress/src/browser/commands.js
> +  const checkArgs = Object.assign(globalArgs, eyesOpenArgs, args);
What will happen now is that because you removed the white list from `eyesCheckWindow`, and you mass assign all `eyesOpenArgs` onto the `checkArgs` - then all the arguments from open will be sent to the handler of `checkWindow`. I don't think that's a good thing.

I think maybe your initial implementation was closer to correct. You only need `browser` and `layoutBreakpoints` from open/global args. So I think you should just remove this line.

2020-12-31 01:43 UTC, amitzur commented on packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js
> +    await eyesCheckWindow(fakeDoc, tag, cypress);
If you used `doc.defaultView` only when it's needed, then you could still leave this test untouched.

2020-12-31 01:43 UTC, amitzur commented on packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js
> +    Promise.resolve(data);
What is this line for?

2020-12-31 01:43 UTC, amitzur commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/breakpoints.js
> +/* global cy */
makes sense to call this file `layout-breakpoints.js`

2020-12-31 06:40 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +    const sendArgs = typeof args === 'string' ? {tag: args} : args;
removing this.
this creates a problem with a test that checks for string input.
essentially I am no longer accepting string input because I handle all of that in `commands`

2020-12-31 06:41 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +    const browser = args.browser;
👍🏼

2020-12-31 06:42 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      const browserInfo = !!browser.name;
👍🏼

2020-12-31 06:42 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +        const command = iosDevice ? 'getIosDevicesSizes' : 'getEmulatedDevicesSizes';
👍🏼

2020-12-31 06:42 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +            .viewport(width, height)
👍🏼

2020-12-31 06:43 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +        return takeDomSnapshot(options).then(snapshot => snapshot);
yes, remnants from battling cypress promises

2020-12-31 07:15 UTC, tool3 commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/breakpoints.js
> +/* global cy */
👍🏼

2020-12-31 07:15 UTC, tool3 commented on packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js
> +    Promise.resolve(data);
I was trying to mimic cypress but I understand this is not needed. removing.

2020-12-31 07:17 UTC, tool3 commented on packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js
> +    await eyesCheckWindow(fakeDoc, tag, cypress);
I have completely reverted the test and no longer using fake doc. 
however, the string input test was altered to `await eyesCheckWindow('bla doc', {tag});`  since `eyesCheckWindow` does not accept a string **directly** (handled in `commands.js`)

2020-12-31 07:25 UTC, tool3 commented on packages/eyes-cypress/test/unit/plugin/handlers.test.js
> +    const result = await handlers.checkWindow({snapshots: [{blobData}]});
👍🏼

2020-12-31 07:29 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +  const checkArgs = Object.assign(globalArgs, eyesOpenArgs, args);
I want to make sure this code is maintainable and readable.. but i'm afraid "maybe closer to correct" doesn't sound like it's there...
is there anything else I can do here that will make this code more robust and understandable ? 

this came from trying to follow your suggestion in a previous comment:
https://github.com/applitools/eyes.sdk.javascript1/pull/329#discussion_r549356268

currently, I have reverted this to my original implementation:
```javascript
const checkArgs = {};
```

2020-12-31 07:34 UTC, tool3 commented
1. config in `pluginExport` - reverted.
2. all altered tests were reverted and only slightly tweaked to account for some new changes.
3. verified cypress is not passing configurations between tests  (https://docs.cypress.io/guides/references/configuration.html#Test-Configuration)
4. in progress.
5. fixed.
6. in progress.

2020-12-31 11:08 UTC, amitzur approved these changes
:100:

2020-12-31 11:08 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      const width = doc.defaultView && doc.defaultView.innerWidth;
no need for this check. You want to require `doc` to have the `defaultView` property. But to avoid the problem in tests, use `doc` only when you need it, meaning in line 50.

2020-12-31 11:10 UTC, amitzur commented
This looks great.
There's one small thing about when the user specifies a browser without a name. We currently detect that as device emulation or iOS. But this is wrong. Probably we should use the same logic as `isEmulation` from vgc. This is an issue that I spotted only now, in all SDK's not only in this PR.

2020-12-31 12:20 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +  const checkArgs = {layoutBreakpoints, browser};
that's one great shorthand but I feel like the intent is clearer using the more verbose structure.

2020-12-31 12:20 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +  console.log(checkArgs);
🙈

2020-12-31 12:28 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      const width = doc.defaultView && doc.defaultView.innerWidth;
but that would mean `cannot read property innerWidth of undefined` when you pass in a string like we do in the tests right?  or am I missing something here...?

2020-12-31 14:06 UTC, tool3 commented
> This looks great.
> There's one small thing about when the user specifies a browser without a name. We currently detect that as device emulation or iOS. But this is wrong. Probably we should use the same logic as `isEmulation` from vgc. This is an issue that I spotted only now, in all SDK's not only in this PR.

just pointing out here that in cypress I was able to resolve the default browser name in `eyesOpen`, by verifying that no browser name was provided, nor any ios or emulated deviceName were given -> use `chrome`.

2020-12-31 14:07 UTC, merged