chore: adding fancy and snaptdout
applitools/eyes.sdk.javascript1 pull request #330
Opened 2020-12-28 08:57 UTC by tool3

# snaptdout
`snaptdout` is a utility that helps test string output.
it does this by comparing strings line by line and saving the result to a `.json` file with the name of the test file.

this helps save much of the tedious and taxing work of building a string in a test in order to validate that the results is exactly the same.

### current limitations
- global config only: currently `snaptdout` accepts global config via `package.json` - this needs to change to accept all possible config as a second argument as well.

### features
- drop-in and start testing. 
- **should** support basically all testing frameworks (not tested).
- great diffs.

### example
```javascript
const output = myFunctionWhichReturnsAFormattedOutput(someArg);
await snaptdout(output, 'snapshot name');
```

# fancy
`fancy` is a string formatting tool that will allow us to keep a consistent style across all of our sdks.

### features
- template based formatting for structural flexibility.
- DIY formatting - `fancy` accepts a formatting function which will receive the formatter as it's first argument (currently defaults to the cypress format output. see `errorDigest` in `eyes-cypress`) - the formatter object has many methods and colors to format the output.

### example
```javascript
const { output } = fancy({
      header: 'My Header',
      footer: 'My Footer',
      body: {
        passed,
        failed,
        unresolved: diffs,
      },
      indent: 4
});
```
output:
![image](https://user-images.githubusercontent.com/16037265/103200660-9ee69b80-48f6-11eb-9f2d-bf0919e96534.png)

2021-01-19 17:48 UTC, tourdedave requested changes
Great work!

I'm still grokking everything so I'm sure there will be more feedback. But here's my first read of it. I offered some suggestions around the API design, and wanted to discuss some of the uses cases about the information we're returning to the user.

Other than that, there are a couple of points I didn't mention, but will note here:

1. Use of `_` for local variables

Stylistically I don't think we've come to a consensus on our preferred code style when it comes to the use of `_` across our packages. But I do know that we use it for linting to note that a variable is unused. So when I read your code, I kept thinking "why are there so many unused variables?". But on the second pass, it was clear that they were local variables and this was likely the shortest path to avoiding naming collisions with functions of the same name. I don't have anything concrete here, just wanted to surface my initial take when reading your code and to open up the discussion about this.

2. Mutable state

In the `report` function, when the `formatterFunction` is used, it mutates the state of what was passed in. Normally I try to stay away from side-effects, but maybe this mutation is by design to make it easier to implement a custom function? I'm not in love with it, but it is passable since the state is internal to this function. Worth a discussion though.

2021-01-19 17:48 UTC, tourdedave commented on packages/fancy/index.js
> +	formatterFunction = require('./lib/default/formatResults')
`formatterFunction` feels uncomfortable as part of this destructured object. It stands out as different than the rest of the params and the name is both too generic and too specific (it doesn't convey what it does and contains an implementation detail - which matters because the user needs to know this key to use it).

I think it would work better as its own argument. Then the separation is clear and the name becomes less critical.

e.g.,

```js
function formatter({ header, footer, body, indent, dull, template } = {}, formatterFunction) {
```

As for the name, something that's more crisp like `customReportFormatter` would be better about conveying the intent w/o leaking details about the implementation.

wdyt?

2021-01-19 17:48 UTC, tourdedave commented on packages/fancy/index.js
> +		formatter: formatFunction,
What's the case where you need this?

2021-01-19 17:48 UTC, tourdedave commented on packages/fancy/index.js
> +		output: formatFunction.report()
Since `formatterFunction` is only used in `report`, you could just pass it there instead of passing it at the call-site for `formatter`. 

`formatFunction.report(formatterFunction)` - then following the bread crumbs would be a bit easier

2021-01-19 17:48 UTC, tourdedave commented on packages/fancy/lib/formatter.js
> +            formatterFunction(this, templateObj);
This will throw if it's not specified. I know that a default formatter is passed in if one is not provided, so I suspect this is an exceptional case that we would want to throw on, yeah?

2021-01-20 07:47 UTC, tool3 commented on packages/fancy/README.md
> +<img src="https://github.com/applitools/fancy/blob/master/example.png?raw=true" />
yeah i've readded the images and they will be resolved once this is merged back to master

2021-01-20 07:47 UTC, tool3 commented on packages/fancy/index.js
> +	formatterFunction = require('./lib/default/formatResults')
agreed. makes sense

2021-01-20 07:53 UTC, tool3 commented on packages/fancy/index.js
> +	formatterFunction = require('./lib/default/formatResults')
I agree with you that, in this case, it makes more sense to put it as a second argument.

but in general, I think it's fine if you use `key`ed arguments but provide a good documentation and typings.

i'm not sure I follow your conflicts about the name... what implementation detail does it leak ? 
and also, how `customReportFormatter` addresses that point ?

I totally agree that it makes sense to put it as a second argument - so naming **isn't** a thing.

2021-01-20 07:56 UTC, tool3 commented on packages/fancy/index.js
> +		output: formatFunction.report()
yes ! great catch thank you !

2021-01-20 08:15 UTC, tool3 commented on packages/fancy/lib/formatter.js
> +            formatterFunction(this, templateObj);
so are you saying we **should** `trycatch` this ?

2021-01-20 08:49 UTC, tool3 commented on packages/fancy/index.js
> +		formatter: formatFunction,
I wanted to provide a way to use the formatting functions individually.
so you could:
```js
const {formatter} = require('@applitools/fancy')();
console.log(formatter.red('hello'))
```

2021-01-20 11:13 UTC, tourdedave commented on packages/fancy/index.js
> +	formatterFunction = require('./lib/default/formatResults')
I was referring to "function" being in the name. If it's documented/typed that it is a function, then it doesn't need to be in the name.

2021-01-20 11:13 UTC, tourdedave commented on packages/fancy/index.js
> +		formatter: formatFunction,
Makes sense.

2021-01-20 13:59 UTC, tool3 commented on packages/fancy/index.js
> +	formatterFunction = require('./lib/default/formatResults')
`customFormatter` ?

2021-01-20 15:32 UTC, tourdedave commented on packages/fancy/index.js
> +	formatterFunction = require('./lib/default/formatResults')
Perfect.

2021-01-20 15:52 UTC, tool3 commented
once we complete the reviews, prior to merging, i'll add our release boilerplate to each of the packages in this PR (`bongo`, `CHANGELOG`)

2021-03-01 13:37 UTC, merged