fix: fix CORS frames with same `src`
applitools/eyes.sdk.javascript1 pull request #352
Opened 2021-01-13 11:07 UTC by tool3

when we encounter cross origin frames with the same `src` attribute - the resulting image will have inappropriately positioned iframes and therefore will result in a bad image.

[Trello card](https://trello.com/c/qn5glrAD)

2021-01-13 11:15 UTC, tourdedave requested changes
This needs a test.

2021-01-13 11:21 UTC, amitzur commented
@tool3 can't this be done in dom-snapshot? why isn't this covered by the following: https://github.com/applitools/dom-scripts/blob/master/packages/dom-snapshot/src/browser/domNodesToCdt.js#L129 ?

Can you do some order and explain the bug? Because I know you already fixed this previously in the line of code I referenced.

2021-01-13 18:42 UTC, tool3 commented
> @tool3 can't this be done in dom-snapshot? why isn't this covered by the following: https://github.com/applitools/dom-scripts/blob/master/packages/dom-snapshot/src/browser/domNodesToCdt.js#L129 ?
> 
> Can you do some order and explain the bug? Because I know you already fixed this previously in the line of code I referenced.

as we discussed, since this is handling cross origin frames - and historically we found out that we cannot rely on a CORS frame's src attribute - we do this in core.

2021-01-13 19:14 UTC, amitzur commented on packages/eyes-sdk-core/test/it/takeDomSnapshot.spec.js
> +function derandomize(subjects, name, prop, counter = 0) {
These 2 functions confused me a bit. I see it as an over abstraction.
Although it's very generic, it's also doing a lot of implicit (or unexpected) things. Like checking the `value` property on the cdt node, en route to the attribute object. But that property is not part of the shape of the object.

For this sort of operation I prefer something like the following, which:
(A) leverages the API of receiving a snapshot and derandomizing it, since the nested frames have the same shape of the top level snapshot.
(B) has a granular function for doing the actual work, applying the [SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle):
(C) Doesn't have the array checks - I think it's safe to assume cdt and frames are arrays.

```js
function derandomizeUrls(snapshot) {
  snapshot.url = derandomizeValue(snapshot.url)
  for (const node of snapshot.cdt) {
    if (node.attributes) {
      for (const attr of node.attributes) {
        attr.value = derandomizeValue(attr.value)
      }
    }
  }

  for (const frame of snapshot.frames) {
    derandomizeUrls(frame)
  }
}

function derandomizeValue(value) {
  if (value && value.includes('?applitools-iframe')) {
    const randomNumber = value.match(/[^?=]*$/)[0]
    return value.replace(randomNumber, counter++)
  } else {
    return value
  }
}
```

2021-01-14 06:46 UTC, tool3 commented on packages/eyes-sdk-core/test/it/takeDomSnapshot.spec.js
> +function derandomize(subjects, name, prop, counter = 0) {
the array checks were added only to accommodate for the fact that we sometimes pass a string instead of an array.

this is cleaner, but I had to make some modifications to make it work:

```js
function derandomizeUrls(snapshot) {
  let counter = 0
  for (const node of snapshot.cdt) {
    if (node.attributes) {
      for (const attr of node.attributes) {
        attr.value = derandomizeValue(attr.value, counter++)
      }
    }
  }
  // reset counter for frames
  counter = 0

  for (const frame of snapshot.frames) {
    frame.url = derandomizeValue(frame.url, counter++)
    derandomizeUrls(frame)
  }
}

function derandomizeValue(value, counter) {
  if (value && value.includes('?applitools-iframe')) {
    const randomNumber = value.match(/[^?=]*$/)[0]
    return value.replace(randomNumber, counter)
  } else {
    return value
  }
}
```
also note that I am resetting the counter before looping through the frames, just to keep the counter start at 0 for each category - for me this is more intuitive and expectable when writing tests

2021-01-14 14:58 UTC, amitzur approved these changes
This looks great. Another option is to change it as @kyryloonufriiev suggested - to accept a function that generates the unique ID.

2021-01-17 09:00 UTC, tool3 commented
> This looks great. Another option is to change it as @kyryloonufriiev suggested - to accept a function that generates the unique ID.

provided the option to add a `generateUniqueUrl` function that overrides the default one.
### api
but of course you can also decide on behavior:
```js
generateUniqueUrl: ('https://cors.com', 'applitools-iframe') // => https://cors.com?applitools-iframe=123
```
### usage
```js
const snapshot = await takeDomSnapshot(logger, eyesDriver, {
    generateUniqueUrl: () => 'someString'
})
```

2021-01-17 09:39 UTC, tool3 commented
> This looks great. Another option is to change it as @kyryloonufriiev suggested - to accept a function that generates the unique ID.

provided the option to add a `uniqueUrl` function that overrides the default one.
### api
```js
uniqueUrl('https://cors.com', 'applitools-iframe') // => https://cors.com?applitools-iframe=123
```
### usage
```js
const snapshot = await takeDomSnapshot(logger, eyesDriver, {uniqueUrl: () => 'someString'})
```

2021-01-19 14:02 UTC, amitzur reviewed
WIP review

2021-01-19 14:02 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    uniqueUrl,
you are passing a function as an argument to dom snapshot? I don't understand

2021-01-19 14:02 UTC, amitzur commented on packages/eyes-sdk-core/test/unit/utils/GeneralUtils.spec.js
> +    const validGuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i
look for uses of `chai-uuid`

2021-01-19 14:12 UTC, tool3 commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    uniqueUrl,
yes this is what we decided in order to avoid derandomizing the urls.
we simply pass a different function in the tests.
or are you talking about something else ?

2021-01-19 14:20 UTC, tool3 commented on packages/eyes-sdk-core/test/unit/utils/GeneralUtils.spec.js
> +    const validGuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i
updated to use `chai-uuid`

2021-01-19 14:51 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js
> +    uniqueUrl,
oh, sorry. I confused this with `const arg` a few lines later. I thought you were sending this to the browser.

2021-01-19 18:16 UTC, amitzur requested changes
I think the tests should be different. See this PR https://github.com/applitools/eyes.sdk.javascript1/pull/361

2021-01-20 05:20 UTC, amitzur approved these changes

2021-01-20 13:56 UTC, merged