feat: custom batch properties
applitools/eyes.sdk.javascript1 pull request #372
Opened 2021-02-01 11:26 UTC by tool3

this PR introduces support for sending custom batch properties.

[trello](https://trello.com/c/IKTydXLv)
[coverage tests PR](https://github.com/applitools/sdk.coverage.tests/pull/50)

2021-02-01 11:43 UTC, amitzur reviewed
Looks great

2021-02-01 11:43 UTC, amitzur commented on packages/eyes-sdk-core/test/unit/config/BatchInfo.spec.js
> +    assert.strictEqual(batch.getProperties(), properties)
how come you don't need `deepStrictEqual` here?

2021-02-01 11:43 UTC, amitzur commented on packages/eyes-selenium/CHANGELOG.md
> +- updated to @applitools/eyes-sdk-core@12.14.6 (from 12.14.1)
remove the following 4 lines

2021-02-01 11:43 UTC, amitzur commented on packages/eyes-selenium/package.json
> +    "@applitools/eyes-sdk-core": "12.14.7",
these changes should not be part of the PR

2021-02-01 11:43 UTC, amitzur commented on packages/sdk-shared/CHANGELOG.md
> +- add support for custom batch properties
Not the correct text.
`add support for getting batch info`

2021-02-01 11:43 UTC, amitzur commented on packages/sdk-shared/src/get-batch-info.js
> +    const url = `${sessionUrl.origin}/api/sessions/batches/${testResults.getBatchId()}/batch?accountId=${accountId}&apiKey=${apiKey}`
I think `accountId` is not needed

2021-02-01 11:43 UTC, amitzur commented on packages/sdk-shared/src/test-setup.js
> +const customBatch = typeof BatchInfo === 'undefined';
`isCustomBatch`. But that's not even the meaning of it. I think this check is because of a bug that existed ages ago. Anyhow, it's not a "custom batch". If any, it's `isBatchInfoDefined`

2021-02-01 11:43 UTC, amitzur commented on packages/sdk-shared/src/test-setup.js
> +  if (customBatch && batchInfo) batch.setProperties(batchInfo.properties);
This feels a little dirty. What did you want to support?

2021-02-01 11:59 UTC, tool3 commented on packages/eyes-sdk-core/test/unit/config/BatchInfo.spec.js
> +    assert.strictEqual(batch.getProperties(), properties)
I do need it. updated to `deepStrictEqual`

2021-02-01 11:59 UTC, tool3 commented on packages/eyes-selenium/CHANGELOG.md
> +- updated to @applitools/eyes-sdk-core@12.14.6 (from 12.14.1)
removed

2021-02-01 12:00 UTC, tool3 commented on packages/eyes-selenium/package.json
> +    "@applitools/eyes-sdk-core": "12.14.7",
reverted

2021-02-01 12:00 UTC, tool3 commented on packages/sdk-shared/CHANGELOG.md
> +- add support for custom batch properties
done

2021-02-01 12:00 UTC, tool3 commented on packages/sdk-shared/src/get-batch-info.js
> +    const url = `${sessionUrl.origin}/api/sessions/batches/${testResults.getBatchId()}/batch?accountId=${accountId}&apiKey=${apiKey}`
I used `getTestInfo` as reference, which uses it. why wouldn't it be needed?

2021-02-01 12:02 UTC, tool3 commented on packages/sdk-shared/src/test-setup.js
> +const customBatch = typeof BatchInfo === 'undefined';
I agree on the name, but I feel like `isSomething` and `something` are stylistic choices.
I updated to `isBatchInfoDefined` but I think `batchInfoDefined` would also work just as well.

2021-02-01 12:25 UTC, tool3 commented on packages/sdk-shared/src/test-setup.js
> +  if (customBatch && batchInfo) batch.setProperties(batchInfo.properties);
refactored

2021-02-02 04:08 UTC, amitzur commented on packages/sdk-shared/src/get-batch-info.js
> +    const url = `${sessionUrl.origin}/api/sessions/batches/${testResults.getBatchId()}/batch?accountId=${accountId}&apiKey=${apiKey}`
Well, maybe it does. I think the link I sent you doesn't have accountId and still works. Doesn't matter, we can leave it here.

2021-02-02 04:12 UTC, amitzur requested changes
just the batch in test-setup needs to be reverted. Other than that it's all :100:

2021-02-02 04:12 UTC, amitzur commented on packages/sdk-shared/src/test-setup.js
> +  const batchInfo =  batch ? new BatchInfo({ name: batchName, ...batch }) : batchName;
The point of specifying the batch outside of `getEyes` is so that all tests are batched together. We could have also just defined the batch ID outside with a uuid. If that makes things simpler for you, then you can change it.
I think the export of `batch` is used, but I don't remember for what and if it's still true.

2021-02-02 12:45 UTC, tool3 commented on packages/sdk-shared/src/test-setup.js
> +  const batchInfo =  batch ? new BatchInfo({ name: batchName, ...batch }) : batchName;
updated to a combination of global batch and custom props within `getEyes`

2021-02-04 03:28 UTC, amitzur approved these changes

2021-02-04 06:04 UTC, merged