fix(eyes-cypress): check deviceName over name
applitools/eyes.sdk.javascript1 pull request #377
Opened 2021-02-11 09:57 UTC by tool3

[trello](https://trello.com/c/onmEQzNx)

`eyesCheckWindow` was checking for the `name` property of a provided browser configuration.

unfortunately, we (I) also added a default browser name, that explicitly adds the `name` property to any browser configuration.

2021-02-18 15:23 UTC, tourdedave requested changes
See my comments on the conditional branch.

Also:
- Can you provide a reference to the default name setting that you mention in the PR description?

- Does this PR resolve the issue listed in the ticket? If so, is there already a test reference in the SDK's test set that demonstrates this? If not, we should add one.

2021-02-18 15:23 UTC, tourdedave commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      if (!browser.deviceName) {
If we follow what's listed in [the VG protocol](https://github.com/applitools/mono/blob/master/docs/visual-grid-protocol.md#rendering-api-app-api), it would be possible to hit this code path with a browser object for an iOS simulator. `deviceName` works but it's not what is spec'd.

2021-02-18 15:23 UTC, tourdedave commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      if (!browser.deviceName) {
Also, doing gating on positive conditions would be easier to reason about and likely lead to fewer bugs since you'd be whitelisting instead of blacklisting.

e.g.,

```
if (browser.deviceName) {
  // do the mobile stuff
} else {
  // do the browser stuff
}

2021-02-18 15:39 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      if (!browser.deviceName) {
since we overload any browser object with a default `name` (if it doesn't already have it) than we created a situation where we would treat devices as browsers... 

this negation makes sense because you can't be sure by only checking the name.
I am in favor of non-negated code when possible, but in this case it makes things a little more readable.

2021-02-18 15:42 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      if (!browser.deviceName) {
and sure! i'll add a test !

2021-02-21 10:10 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      if (!browser.deviceName) {
okay so following your comment and our conversation about it I made the following changes:
- extracted the function and its dependencies to a new module
- reversed if for positive condition
- extended the condition to include all known permutations
- added an integration test that checks all of this

2021-02-22 19:08 UTC, tourdedave commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      if (!browser.deviceName) {
Does this PR address the issue referenced in the Trello card? Put another way - do we have a breakpointLayout test that surfaces the issue and does this PR fix it?

2021-02-23 11:04 UTC, tool3 commented on packages/eyes-cypress/src/browser/eyesCheckWindow.js
> +      if (!browser.deviceName) {
not sure I understand the question...
the problem was the customer's usage of `name` inside emulated configuration objects - which we state that we do support (it's even in the examples).
 
this PR fixes the issue and enables us to support all said permutations.

I also added a test that verifies this.

2021-02-23 12:35 UTC, tourdedave commented
It was unclear from reading the Trello ticket that that was the problem. Thanks for clarifying. It might be helpful to include that kind of detail in future Trello tickets (I read both the Trello ticket and the PR when reviewing).

For context into why I asked... the implicit questions I bring to PRs that address a Trello ticket are:
- does it fix the issue that the customer reported? and,
- has it been verified at their level?

We often find and fix things at a lower level. Sometimes we don't verify them at a higher level (e.g., e2e) which can hide the fact that we didn't fully fix their issue, which can lead to more back and forth. It sounds like you're thinking of things in a similar way and did everything you needed to in this PR - it just wasn't clear to me at first glance.

2021-02-23 15:08 UTC, tourdedave approved these changes

2021-02-24 14:23 UTC, merged