feat(eyes-cypress): global hooks
applitools/eyes.sdk.javascript1 pull request #384
Opened 2021-02-19 20:57 UTC by tool3

2021-02-23 08:22 UTC, amitzur requested changes
Almost done with the review. But in the meantime there are many points to address.

2021-02-23 08:22 UTC, amitzur commented on packages/eyes-cypress/src/plugin/handlers.js
> +        concurrency: config.testConcurrency,
I think we should call the property `testConcurrency`, and then inside `waitForBatch` check `testConcurrency === 5`

2021-02-23 08:22 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +      concurrency: config.concurrency,
see comment about `testConcurrency`

2021-02-23 08:22 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +        waitForBatch.bind(null, tests, visualGridClient.closeBatch),
potential bug here - the reference to `tests` is the initial array in `runningTests.js`. But you assume `runningTests.reset` was not called (which is correct in this case, but if that becomes untrue you will have a hard time spotting the bug).
If `reset` was called, the reference would not be correct. This is why in `commands.js` the function `waitForBatch` is binded to the array that was created inside `batchStart`.

2021-02-23 08:22 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +      const pollBatchEnd = pollingHandler(
No need to poll here! This is inside the plugin. Just await `waitForBatch`

2021-02-23 08:22 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/handlers.test.js
> +      expect(_args.enablePatterns).to.be.true;
what is this checking? `enablePatterns` was passed to checkWindow

2021-02-23 08:22 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/handlers.test.js
>        handlers.batchStart({});
No need to call `handlers.batchStart` anymore, since it's not instantiating VGC anymore.

2021-02-23 08:22 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/handlers.test.js
>        handlers.batchStart({});
No need to call `handlers.batchStart` anymore, since it's not instantiating VGC anymore.

2021-02-23 10:08 UTC, tool3 commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/legacy-hooks.js
> +describe('legacy hooks', () => {
went with `hooks.js` and both calling it

2021-02-23 10:09 UTC, tool3 commented on packages/eyes-cypress/src/plugin/waitForBatch.js
> +    if (Number(concurrency) === 1) {
changed to `Number(testConcurrency) === 5` - we need `Number` to support string numbers (env vars)

2021-02-23 10:10 UTC, tool3 commented on packages/eyes-cypress/src/plugin/config.js
> +  if (getProp(vgConfig, 'userAgent')) {
correct, removed.

2021-02-23 10:10 UTC, tool3 commented on packages/eyes-cypress/src/plugin/config.js
> +function makeConfig(baseConfig = {}) {
agreed and removed

2021-02-23 10:11 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +  if (getGlobalConfigProperty('eyesLegacyHooks') || getGlobalConfigProperty('isInteractive')) {
made it more readable to me - if `eyesIsDisabled` no need to check for other conditions.
changed to a single if

2021-02-23 10:11 UTC, tool3 commented on packages/eyes-cypress/src/plugin/pluginExport.js
> +        eyesConfig.eyesLegacyHooks = false;
added cypress version check

2021-02-23 10:11 UTC, tool3 commented on packages/eyes-cypress/src/plugin/handlers.js
> +        concurrency: config.testConcurrency,
changed to `Number(testConcurrency) === 5`

2021-02-23 10:12 UTC, tool3 commented on packages/eyes-cypress/src/plugin/hooks.js
> +      const pollBatchEnd = pollingHandler(
thanks ! done !

2021-02-23 10:17 UTC, tool3 commented on packages/eyes-cypress/src/plugin/config.js
> +    baseConfig.failCypressOnDiff = false;
right, removed.

2021-02-23 10:17 UTC, tool3 commented on packages/eyes-cypress/src/plugin/config.js
> +  if (getProp(vgConfig, 'viewport.height') && getProp(vgConfig, 'viewport.width')) {
I used the same config code that was in `startPlugin` with small modifications - this is the way it was written.
so I should remove this `if` completely?
what should we send in `eyesOpen` ?

2021-02-23 10:19 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +    width: getGlobalConfigProperty('viewportWidth'),
so I am not sure I fully understand.. you want to remove the `defaultBrowser` ? or update it to `innerWidth` and `innerHeight` ?
`viewportWidth` and `viewportHeight` are coming from cypress.. why is this a mistake ? mind you that this is only in the case where customer didn't provide **any** browser in global config or `open`

2021-02-23 10:28 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +  if (!browser.name && !browser.iosDeviceInfo && !browser.chromeEmulationInfo) {
no this is just for filling in the `name` - in #377 I validate the browser in `getBrowserInfo` which is in `eyesCheckWindow` while this runs in `open`

2021-02-23 10:47 UTC, tool3 commented on packages/eyes-cypress/test/it/plugin/handlers.test.js
> +      expect(_args.enablePatterns).to.be.true;
that `eyesCheckWinow` is being run from `visualGridClient`

2021-02-23 10:48 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +      data: Object.assign({testName}, args, {browser}),
updated to be in `eyesOpen`. will think of a test for it.

2021-02-23 10:54 UTC, tool3 commented on packages/eyes-cypress/src/plugin/hooks.js
> +        waitForBatch.bind(null, tests, visualGridClient.closeBatch),
I needed a way for the plugin to access the running tests so we can call `waitForBatch` with them.

I rely on the fact that `reset` wasn't called, do you feel like I shouldn't make that assumption ?

2021-02-23 11:43 UTC, amitzur commented on packages/eyes-cypress/src/plugin/config.js
> +  if (getProp(vgConfig, 'viewport.height') && getProp(vgConfig, 'viewport.width')) {
`startPlugin` doesn't have any reference to the word `viewport`. vgConfig is what gets loaded from applitools.config.js. There should not be an entry called `viewport` in the config file.
In `eyesOpen`, the viewport height and width should be passed (window.innerHeight, window.innerWidth), in order to use it in the plugin in case the user doesn't provide *any* browser configuration.

2021-02-23 11:46 UTC, amitzur commented on packages/eyes-cypress/src/browser/commands.js
> +    width: getGlobalConfigProperty('viewportWidth'),
"coming from cypress" ===> we read it from our configuration file. But nowhere is it documented that there are these properties in the configuration file. Just look them up in the source code - this is the only place you'll find them.
So, of course NOT remove the default browser. Pass the window's innerHeight and innerWidth from the browser to the plugin, then if there is no globalBrowser or eyeOpenBrowser use those values as the default browser.

2021-02-23 11:48 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +        waitForBatch.bind(null, tests, visualGridClient.closeBatch),
I think it's a fair assumption, but I feel it's fragile. So at least mention this assumption in a comment here. For future us.

2021-02-23 12:00 UTC, tool3 commented on packages/eyes-cypress/src/plugin/config.js
> +  if (getProp(vgConfig, 'viewport.height') && getProp(vgConfig, 'viewport.width')) {
gotcha ! thanks !

2021-02-23 12:04 UTC, amitzur reviewed
Another iteration of WIP review

2021-02-23 12:18 UTC, tool3 commented on packages/eyes-cypress/src/plugin/pluginExport.js
> +      if (config.version >= CYPRESS_SUPPORTED_VERSION && config.experimentalRunEvents) {
yeah. I realized that I can transform it to a number and validate that... but in javascript, this works perfectly:
`console.assert('1.2.0' < '1.3.0')`

2021-02-23 12:22 UTC, tool3 commented on packages/eyes-cypress/src/plugin/handlers.js
> -      logger.log(`[handlers] batchEnd`);
by mistake, thanks for catching

2021-02-23 12:23 UTC, tool3 commented on packages/eyes-cypress/src/plugin/hooks.js
> +        waitForBatch.bind(null, tests, visualGridClient.closeBatch),
cool thanks

2021-02-23 12:31 UTC, tool3 commented on packages/eyes-cypress/src/browser/commands.js
> +    width: getGlobalConfigProperty('viewportWidth'),
`viewportWidth` and `viewportHeight` are cypress configuration values - not ours.
we're basically saying: set up a default browser with the default `viewportWidth` and `viewportHeight` as reported by cypress. 
the reason I say that is because these values can be changed by the user - so using these props we will always respect the "true" default.
https://docs.cypress.io/api/commands/viewport.html#Defaults

does that make sense?

2021-02-23 12:50 UTC, amitzur commented on packages/eyes-cypress/src/browser/commands.js
> +    width: getGlobalConfigProperty('viewportWidth'),
ohhhhhh. forgive me, i missed this point

2021-02-23 13:56 UTC, tool3 commented on packages/eyes-cypress/src/plugin/hooks.js
> +      isInteractive: !isTextTerminal,
unfortunately, at the point where I `setGlobalHooks` - the config from cypress doesn't have this property yet.
only inside the events I get the config with `isTextTerminal`.

since I wanted to keep `setGlobalHooks` as minimal as possible, I feel like this will complicate things a bit.

do you agree? or do you still think it's worth it ?

2021-02-23 15:19 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +      isInteractive: !isTextTerminal,
ah, I understand what you're saying. Then I think you chose right

2021-02-23 15:23 UTC, tool3 commented
waiting for the final review iteration.
things I haven't done yet:
1. documentation - I want us to discuss this because we need to have a very clear feature description
1. test for `navigator.userAgent` in `commands.js` - in general we don't have **any** tests for `commands.js`

2021-02-27 23:42 UTC, amitzur reviewed
Where is the test in `pluginExport.test.js` that checks the condition when `eyesLegacyHooks` is false?

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +        return {bla: 'ret', eyesDisableBrowserFetching: true};
You mutate `config` but then return another object. Is that on purpose?
Also, returning `eyesDisableBrowserFetching` from here doesn't make sense - this is the original module, it is the "user's code".

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +  it('works with eyes timeout', async () => {
eyes timeout? wasn't this removed?

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +    __module = {
Every test defines its own `__module`. It should move from here

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +    on = (_event, _callback) => {};
also here the same comment about `noop`

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/startPlugin.test.js
> +  let getCloseServer, __module, on;
`on` doesn't need to be defined separately in `beforeEach` - it doesn't hold data. You can just define a `noop` function in the file and use that.

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js
> +      await pexec(
You could use `simple.js` here. Not sure we need the `hooks.js` file

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js
> +  it('works with experimentalRunEvents flag', async () => {
I think this test is not different in any way from the other e2e tests. Why should it exist?

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +    const {isTextTerminal, testConcurrency} = config;
How come `testConcurrency` is provided here? Isn't it a Cypress object?

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +        return {bla: 'blah'};
You mutate `config` but then return another object. Is that on purpose?

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +        config.version = '6.3.0';
You mutate `config` but then return another object. Is that on purpose?

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +        return {bla: 'ret', eyesIsDisabled: true};
You mutate `config` but then return another object. Is that on purpose?
Also, returning `eyesIsDisabled` from here doesn't make sense - this is the original module, it is the "user's code".

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +        return {bla: 'ret', eyesFailCypressOnDiff: false};
You mutate `config` but then return another object. Is that on purpose?
Also, returning `eyesFailCypressOnDiff` from here doesn't make sense - this is the original module, it is the "user's code".

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/unit/plugin/waitForBatch.test.js
> +      visualGridClient,
But `makeWaitForBatch` doesn't get `visualGridClient` as an argument.

2021-02-27 23:42 UTC, amitzur commented on packages/eyes-cypress/test/unit/plugin/handlers.test.js
> -  it('handles "batchStart"', () => {
Why remove this test? Is there no logic at all in `batchStart`? What about `runningTests.reset()`?

2021-02-28 07:34 UTC, tool3 commented on packages/eyes-cypress/src/plugin/config.js
> +  const config = Object.assign(vgConfig, baseConfig);
👍🏼

2021-02-28 07:34 UTC, tool3 commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +        return {bla: 'ret', eyesDisableBrowserFetching: true};
👍🏼

2021-02-28 07:35 UTC, tool3 commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +  it('works with eyes timeout', async () => {
merge conflicts - will merge from master soon and this will be removed

2021-02-28 07:37 UTC, tool3 commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +    on = (_event, _callback) => {};
👍🏼

2021-02-28 07:45 UTC, tool3 commented on packages/eyes-cypress/src/plugin/hooks.js
> +    const {isTextTerminal, testConcurrency} = config;
no, it is a combined object of both cypress and what we return from the plugin.

since these events run asynchronously, the config here already has what we returned from `pluginExport`.

but this comment made me realize that we didn't set `testConcurrency` properly like other properties (for example `eyesDisableBrowserFetching`) - fixed.

2021-02-28 07:46 UTC, tool3 commented on packages/eyes-cypress/test/it/plugin/pluginExport.test.js
> +        config.version = '6.3.0';
no it's a mistake - I only do this once in the file and that is for testing `eyesLegacyHooks`.

fixed all occurrences of this.

2021-02-28 07:49 UTC, tool3 commented on packages/eyes-cypress/test/unit/plugin/waitForBatch.test.js
> +      visualGridClient,
my bad. no other test in this file used it.

2021-02-28 08:33 UTC, tool3 commented on packages/eyes-cypress/test/unit/plugin/handlers.test.js
> -  it('handles "batchStart"', () => {
readded it to test `runningTests.reset()` is happening as expected

2021-02-28 08:41 UTC, tool3 commented on packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js
> +      await pexec(
used `simple.js`

2021-02-28 08:43 UTC, tool3 commented on packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js
> +  it('works with experimentalRunEvents flag', async () => {
I updated this test to have 2 steps:
1. add the `experimentalRunEvents` flag in the test and verify it's working.
2. remove the `experimentalRunEvents` in the test and verify it's working.

so now, all tests are still running with legacy hooks, and only this one verifies the flag.

2021-02-28 08:45 UTC, tool3 commented
> Where is the test in `pluginExport.test.js` that checks the condition when `eyesLegacyHooks` is false?

`sets eyesLegacyHooks` in `pluginExport.test.js:31`

2021-02-28 11:54 UTC, amitzur commented on packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js
> +  it('works with experimentalRunEvents flag', async () => {
Where is part (2) of what you wrote? (remove `experimentalRunEvents`)

2021-02-28 11:57 UTC, amitzur commented on packages/eyes-cypress/test/unit/plugin/handlers.test.js
> -  it('handles "batchStart"', () => {
where is it?

2021-02-28 12:13 UTC, tool3 commented on packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js
> +  it('works with experimentalRunEvents flag', async () => {
the 2nd `it` in `packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js`:

```javascript
it('does not fail without experimentalRunEvents flag', async () => {
```

2021-02-28 12:14 UTC, tool3 commented on packages/eyes-cypress/test/unit/plugin/handlers.test.js
> -  it('handles "batchStart"', () => {
`packages/eyes-cypress/test/unit/plugin/handlers.test.js` line 389

2021-02-28 14:43 UTC, amitzur approved these changes
We're there!
Only need to merge https://github.com/applitools/eyes.sdk.javascript1/pull/393

2021-02-28 14:43 UTC, amitzur commented on packages/eyes-cypress/test/unit/plugin/config.test.js
> +    expect(config.isDisabled).to.be.true;
why is Cypress configuration affected by `APPLITOOLS_IS_DISABLED` ?

2021-02-28 15:14 UTC, tool3 commented on packages/eyes-cypress/test/unit/plugin/config.test.js
> +    expect(config.isDisabled).to.be.true;
the `config` comes from VG - which takes care of the env side of things.

so the `eyesConfig` is just a reflection of what we got on the `config` object:
```javascript
 eyesIsDisabled: !!config.isDisabled,
```

it's part of the default `configParams` from `visual-grid-client`:
https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/visual-grid-client/src/sdk/configParams.js

2021-03-02 12:55 UTC, merged