Eyes storybook 2021 02 21 12 03
applitools/eyes.sdk.javascript1 pull request #388
Opened 2021-02-22 21:55 UTC by SophieDePaula

Add the option to filter stories using story title by:

1. Function: send story title as a parameter
2. String: add an api that receives a string and checks if the string matches any story title 
3. Regex: uses the string api from #2 and checks if the string starts and end with "/", then uses test method to match stories to the regex received.
4. Add the option to send a string to include from the cli

2021-02-22 22:36 UTC, amitzur requested changes
Great first PR!
I left some comments inside. Mainly - the API for the user should be different:
1. When it's a function, it should still be a single argument, and `storyTitle` is another field in the object.
2. When it's a regex, it's an actual regex.

Other comments are regarding code style and general stuff.
Very well!

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/filterStories.js
> +  const story_title = getStoryTitle(story);
We use camel case for variables, so: `storyTitle`.

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/README.md
> +include: "/Button: */",
I think we should support a regex as is. No special magic here. So: `include: /Button: */,`.
The convention of start and end with a `/` is something we can do **for the cli argument**, since in cli there are only strings. So it's a nice-to-have for letting the user specify a "regex" in the cli.

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/filterStories.js
> +    if (config.include.startsWith('/') && config.include.endsWith('/')) {
If you change to support regex only for cli, then you would have this code in the yargs area and not here. In this file there should be another condition for when `config.include instanceof RegExp` (or better yet `Object.prototype.toString.call(config.include) === '[object RegExp]'`)

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/filterStories.js
> +      let include_input = new RegExp(config.include.substring(1, config.include.length - 1));
general comment - when declaring a variable it is preferred to use `const`. Unless there's a rare case that the variable is re-assigned a different value later.

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/yargsOptions.js
> +      'A string that represents a story titel or a regex (starts and ends with /) to match stories title',
typo in the word titel

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/yargsOptions.js
> +  include: {
you can use the `coerce` field to transform the string to a RegExp here

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/yargsOptions.js
> +    alias: ['include'],
I don't think this is needed. It's the same name. Or did I miss something?

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/test/fixtures/applitools.config.js
> +  include: 'Button: with text',
I think it's important to keep the condition in line 9 for the tests (I don't remember if this file is used by tests or if it's just for playing around).

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/filterStories.js
> +    return config.include(story, story_title);
I think it's better to have `storyTitle` as part of the single argument to `config.include`. So: `return config.include({...story, storyTitle})`.

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    const config = {include: ({name: _name}, story_title) => story_title === 'bbb: aaa'};
You could use the function `getStoryTitle` in the test here. If you look at that function you'll also see that the story title sometimes has a suffix (when there are variations). So that case should be tested as well.

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/README.md
> +| `include`                 | true                        | A predicate function or string specifying which stories should be visually tested.<br/>Visual baselines will be created only for the compon
The structure of the readme creates an awkward situation where there is no place to put examples for the configuration file. But I'm not sure adding the text "and global config using string and regext" is beneficial here. It's a long string and I got a bit confused by what it means.

Also, not `story title` but rather `storyTitle` in the arguments description.

2021-02-22 22:36 UTC, amitzur commented on packages/eyes-storybook/src/defaultConfig.js
> +  include: undefined,
Is this really necessary?

2021-02-22 23:03 UTC, amitzur commented
@SophieDePaula for the readme part - it would be good to integrate with the changes from https://github.com/applitools/eyes.sdk.javascript1/pull/379 which @tool3 wrote.

2021-02-23 23:13 UTC, SophieDePaula commented on packages/eyes-storybook/src/filterStories.js
> +    return config.include(story, story_title);
It is used by other tests, I'll put it back.

2021-02-23 23:45 UTC, SophieDePaula commented on packages/eyes-storybook/test/fixtures/applitools.config.js
> +  include: 'Button: with text',
It is used by some tests, I put it back

2021-02-24 17:58 UTC, SophieDePaula commented on packages/eyes-storybook/src/filterStories.js
> +    return config.include(story, story_title);
I added the story title as part of the story object. That resulted in some tests that are using the function api to fail, so I modified them accordingly.

2021-02-24 22:53 UTC, SophieDePaula commented on packages/eyes-storybook/README.md
> +| `include`                 | true                        | A predicate function or string specifying which stories should be visually tested.<br/>Visual baselines will be created only for the compon
Amit, I created a new paragraph for global configuration examples and added a link to that in a separate line, is that clear enough now?

2021-02-24 23:31 UTC, SophieDePaula commented on packages/eyes-storybook/src/defaultConfig.js
> +  include: undefined,
I noticed that without it, the include that is sent from the cli is ignored.
Under `generateConfig.js `I see this line

` const result = Object.assign({}, defaultConfig, config, argvConfig);`

If I don't add include to the default config it will not be included in the result and will not be considered when I run the test with this parameter.

2021-02-28 14:50 UTC, amitzur commented
@SophieDePaula please merge from `master`. The commit 8d8d5513e51973210c22e6e30007a8d034bd2cd2 would cause you a little merge conflict, since instead of integrating the readme changes "by hand", they should be integrated by merging from master.

2021-02-28 15:08 UTC, amitzur requested changes
We're close!
I think it would be nice to add an e2e test for the cli. But we can do that later.

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    const _res = filterStories({stories, config});
what is this for?

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    stories.forEach(story => (story['storyTitle'] = getStoryTitle(story)));
That's a bit confusing to me. Also, it's just not correct, since you want to test the `filterStories` function with the same object structure as in runtime. And in runtime `filterStories` doesn't receive objects with `storyTitle` property.
Also, this line is just not needed.

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    stories.forEach(story => (story['storyTitle'] = getStoryTitle(story)));
not needed.

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    expect(filterStories({stories, config})).to.eql(stories.splice(0, 1));
since `splice` is mutating the array, I think it's just the same but nicer to call `.slice(0,1)` instead.

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    expect(filterStories({stories, config: {}})).to.eql(stories.splice(0, 1));
since `splice` is mutating the array, I think it's just the same but nicer to call `.slice(0,1)` instead.

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    stories.forEach(story => (story['storyTitle'] = getStoryTitle(story)));
not needed

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/test/unit/filterStories.test.js
> +    expect(filterStories({stories, config})).to.eql(stories.splice(0, 1));
since `splice` is mutating the array, I think it's just the same but nicer to call `.slice(0,1)` instead.

2021-02-28 15:08 UTC, amitzur commented on packages/eyes-storybook/src/yargsOptions.js
> +      ('include',
what is this used for?

2021-02-28 16:54 UTC, SophieDePaula commented on packages/eyes-storybook/src/defaultConfig.js
> +  include: undefined,
No with the tests, I tried to use it via the cli and it didn't work and therefore I added it to the default config.

2021-02-28 17:03 UTC, SophieDePaula commented on packages/eyes-storybook/README.md
> +#### global
I added:
When passing a storyTitle as a string only this story will be tested. For example:
```
module.exports={
...
include: "Button: with text",
...
}
```
When passing a storyTitle as a Regex only matching stories will be tested. For example:
```
module.exports={
...
include: /Button: */,
...
}
```
I think it was in the wrong location though

2021-03-03 05:41 UTC, amitzur approved these changes
Great!
Please fix the readme according the comments below, and then release a **minor** version.

2021-03-03 05:41 UTC, amitzur commented on packages/eyes-storybook/README.md
> +| `include`                 | true                        | A predicate function or a string specifying which stories should be visually tested.<br/>Visual baselines will be created only for the comp
A predicate function or a string **or a regular expression** specifying which stories...

2021-03-03 05:41 UTC, amitzur commented on packages/eyes-storybook/README.md
> +You can filter by `kind`, `name`, `storyTitle`,  `parameters`, a combination of them or any logic that will result in a `boolean`. For example:
double space between storyTitle and parameters

2021-03-03 05:41 UTC, amitzur commented on packages/eyes-storybook/README.md
> +When  passing a `storyTitle` as a  `string` only this story will be tested. For example:
double space after **When** and after **a**

2021-03-03 05:41 UTC, amitzur commented on packages/eyes-storybook/README.md
> +When passing a `storyTitle` as a  `Regex` only matching storis will be tested. For example:
double space after **a**, typo in **storis**

2021-03-03 05:41 UTC, amitzur commented on packages/eyes-storybook/README.md
> +module.exports={
module.exports = {
(spaces)

2021-03-03 05:41 UTC, amitzur commented on packages/eyes-storybook/README.md
> +module.exports={
module.exports = {
(spaces)

2021-03-04 00:38 UTC, merged