Fix/testcafe viewport size
applitools/eyes.sdk.javascript1 pull request #390
Opened 2021-02-25 17:15 UTC by tourdedave

This PR is for a more robust implementation of `getWindowRect` & `setWindowRect` which resolves the issues noted in [Trello 736](https://trello.com/c/xNCZNfPi)

2021-02-26 05:45 UTC, amitzur requested changes
It's the wrong calculation - see comment inline

2021-02-26 05:45 UTC, amitzur commented on packages/eyes-testcafe/test/it/legacy-api.spec.js
> +  await t.resizeWindow(2000, 1000)
what difference does it make in this specific test?

2021-02-26 05:45 UTC, amitzur commented on packages/eyes-testcafe/test/it/spec-driver.spec.js
> +  const expectedRect = {width: 500, height: 500}
we don't care about x,y ?

2021-02-26 05:45 UTC, amitzur commented on packages/eyes-testcafe/src/spec-driver.js
> +// and window.innerWidth are a trustworthy source of truth. From this starting
We also assume
a) `setWindowRect(w, h)` sets it correctly to `w` and `h`
b) the diff between the window and the viewport doesn't change when changing the window size

To remove assumption (b) we do the compensation/verification loop that you mention below.

2021-02-26 05:45 UTC, amitzur commented on packages/eyes-testcafe/src/spec-driver.js
> +    width: initialViewportSize.width - anchorViewportSize.width,
This is not the correct calculation. The diff should be `600 - anchorViewportSize.width`. Then the `windowRect` you set back to should logically be `diff.width = initialViewportSize.width + diff.width`.

2021-02-26 11:51 UTC, tourdedave commented on packages/eyes-testcafe/test/it/legacy-api.spec.js
> +  await t.resizeWindow(2000, 1000)
It made sense with the old implementation (it surfaced the bug) - this test can be removed I think

2021-02-26 11:52 UTC, tourdedave commented on packages/eyes-testcafe/test/it/spec-driver.spec.js
> +  const expectedRect = {width: 500, height: 500}
I think we do (based on what's in other specs) but the SDK is not able to change it w/ setWindowRect so I took it out to see how it behaved - all tests pass w/o it (including coverage)

2021-02-26 11:53 UTC, tourdedave commented on packages/eyes-testcafe/src/spec-driver.js
> +// and window.innerWidth are a trustworthy source of truth. From this starting
👍

2021-02-26 12:07 UTC, tourdedave commented on packages/eyes-testcafe/src/spec-driver.js
> +    width: initialViewportSize.width - anchorViewportSize.width,
Okay, I felt confident in the current calculation since it was getting to the correct size and all of the tests passed with it (including coverage). But I realize now it's creating a window size based on just the viewport sizes - so it would fall down when running a headed browser. I'll see about adding a test to verify, and update the calculation.

2021-02-26 12:17 UTC, amitzur commented on packages/eyes-testcafe/src/spec-driver.js
> +    width: initialViewportSize.width - anchorViewportSize.width,
Exactly.

2021-02-26 17:45 UTC, tourdedave commented on packages/eyes-testcafe/test/it/spec-driver.spec.js
> +  const expectedRect = {width: 500, height: 500}
It looks like screenX and screenY don't get updated as part of a window resize in TestCafe, so there might not be a reliable way to track it

2021-02-26 17:49 UTC, tourdedave commented on packages/eyes-testcafe/test/it/spec-driver.spec.js
> +  const expectedRect = {width: 500, height: 500}
added x, y back to getWindowRect

2021-02-26 18:00 UTC, tourdedave commented on packages/eyes-testcafe/src/spec-driver.js
> +    width: initialViewportSize.width - anchorViewportSize.width,
Running with a headed browser still worked with the existing calculation 🤔. Regardless, I've updated it.

2021-02-26 18:10 UTC, amitzur commented on packages/eyes-testcafe/src/spec-driver.js
> +    width: initialViewportSize.width - anchorViewportSize.width,
that is so weird. did you debug it to see what intermediate values the code produces?

2021-02-26 18:18 UTC, tourdedave commented on packages/eyes-testcafe/src/spec-driver.js
> +    width: initialViewportSize.width - anchorViewportSize.width,
No, I didn't. Do you think it's worth investigating?

2021-02-27 20:39 UTC, amitzur commented on packages/eyes-testcafe/src/spec-driver.js
> +    width: initialViewportSize.width - anchorViewportSize.width,
I think when we get results like this that we cannot explain - we must investigate, especially given how little effort it requires. 

Actually, I was so curious how this could happen that I did the investigation. I added a couple of console logs to `getWindowRect`, and reached a conclusion that TestCafe's `driver.resizeWindow` method actually resizes the browser to the desired **viewport size**, and not window size.
So the reason that tests always passed before your change is because the diff was always 0.
I opened a PR for this: https://github.com/applitools/eyes.sdk.javascript1/pull/392

2021-03-01 15:19 UTC, tourdedave commented
## Results

| browser | result |
| - | - |
| Chrome | ✔ |
| Firefox | ✔|
| Safari | ✔|
| IE 11 | ✘ |
| Edge classic | TBD |
| Edge latest | TBD |

## Stack traces

### IE 11

```sh
 ✖ setViewportSize (width, height)

   1) AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
      + actual - expected

      {
      +   height: 683,
      +   width: 1024
      -   height: 500,
      -   width: 500
      }

      + expected - actual

       {
      -  height: 683
      -  width: 1024
      +  height: 500
      +  width: 500
       }
```

2021-03-02 12:55 UTC, amitzur approved these changes

2021-03-02 12:56 UTC, amitzur commented
@tourdedave :flushed: what a discovery about remote browsers!

2021-03-03 12:37 UTC, merged