Add runAfter hook
applitools/eyes.sdk.javascript1 pull request #398
Opened 2021-03-08 00:45 UTC by SophieDePaula

Added runAfter hook to allow the user to clean up the browser before the next story renders.
This was requested by Wix ([trello card](https://trello.com/c/Y9JyMiIt/653-storybook-add-runafter-method?menu=filter&filter=due:notdue))

2021-03-08 08:29 UTC, amitzur requested changes
Several changes needed, but most importantly:
1) Behavior is not preserved in error handling of client API.
2) Execution of `runAfter` is done from the wrong place.

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/CHANGELOG.md
> + - added after hook
after --> runAfter

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/README.md
> +  eyes: {
I think the better example is what you have in the e2e test - a `runBefore` function that creates dirty state, and a `runAfter` function that cleans it up.
And the text inside the div could say this - `Component with runBefore hook that leaves a background-color style on the html element`.

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/src/renderStories.js
> +          if (eyesParameters && eyesParameters.runAfter) {
I think this should be in `getStoryData`, after `takeDomSnapshots`.

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/test/fixtures/appWithStorybook/index.js
> +  <div style={{fontSize: 'xxx-large'}}>PINK!</div>
`xxx-large` is not really a valid value for fontSize. Even though it doesn't matter, maybe it's confusing? Not sure.

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/test/fixtures/appWithStorybook/index.js
> +     document.querySelector("html").style.backgroundColor = 'pink';
Just FYI that `fuchsia` is also an option :)

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/test/fixtures/appWithStorybook/index.js
> +     document.querySelector("html").style.backgroundColor = '';
If you wanted to be 100% purist, you'd save the original value from the `runBefore` function. Maybe it was red before it was changed to pink?
I don't think it's necessary here, but I'm wondering if it makes sense to add this to the documentation, or as a recipe.

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/src/getStoryIndex.js
> +function getStoryIndex(index) {
`getStoryByIndex`, not `getStoryIndex`.

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/src/getStoryIndex.js
> +const getClientAPI = require('./browser/getClientAPI');
This file should be under `src/browser`, where all files which are intended to be run in the browser are located.

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/src/browser/runRunBeforeScript.js
> +    return {message: ex.message};
returning the api version from this function is important for troubleshooting

2021-03-08 08:29 UTC, amitzur commented on packages/eyes-storybook/src/browser/runRunBeforeScript.js
> +    let story = getStoryIndex(index);
I think this is not preserving existing behavior. It's a problem that we don't have tests for it. Since this is code that runs in the browser and has quite a few dependencies on Storybook, then it's a bit hard to test.
So either we keep it untested or we add tests, but we want to make sure that the same behavior is preserved. Before these changes, this was the behavior:
1. `getClientAPI` may throw, in which case we return `{message: ex.message}`
2. `getClientAPI` may return undefined, in which case we return `{message: ex.message}` but the error is actually `cannot call method getStories of undefined` or something like that.
3. `api.getStories()[index]` may return undefined, in which case we log it and return undefined.
4. Otherwise - run the runBefore function (btw, it's available since the Node.js side verified that it is defined).
5. if `runBefore` throws, we return `{message, version}`

But now, `getStoryIndex` doesn't behave like this at all:
1. if `getClientAPI` throws, `getStoryIndex` returns {message} and runRunBeforeScript will throw `cannot call eyes of undefined`. Which is an irrelevant exception.
2. if `getClientAPI` returns undefined, same problem as (1).
3. if `api.getStories()[index]` returns undefined, similar problem as (1) and (2)

2021-03-08 23:02 UTC, SophieDePaula commented on packages/eyes-storybook/test/fixtures/appWithStorybook/index.js
> +     document.querySelector("html").style.backgroundColor = 'pink';
Done ^_^

2021-03-09 00:25 UTC, SophieDePaula commented on packages/eyes-storybook/test/fixtures/appWithStorybook/index.js
> +     document.querySelector("html").style.backgroundColor = '';
Make sense, I can keep it under the window object. Is there a better way?

```
  eyes: {
    runBefore({rootEl, story}) {
     window.originalBackgoundColor = document.querySelector("html").style.backgroundColor;
     document.querySelector("html").style.backgroundColor = 'fuchsia';
    },
    runAfter({rootEl, story}){
     document.querySelector("html").style.backgroundColor = window.originalBackgoundColor;
    }
  }
```

2021-03-09 00:44 UTC, SophieDePaula commented on packages/eyes-storybook/src/browser/runRunBeforeScript.js
> +    let story = getStoryIndex(index);
To resolve this (and the previous comment), I throw the exception from `getStoryByIndex.js` instead of returning so that runBefore/After is not called and the relevant info is returned. 
I also added a check in both before and after hooks for #3.

`if (!story) return;`

2021-03-09 19:55 UTC, amitzur commented on packages/eyes-storybook/README.md
> +     document.querySelector("html").style.backgroundColor = window.originalBackgoundColor;
and `delete window.originalBackgroundColor`

2021-03-16 21:03 UTC, amitzur approved these changes
:100:

2021-03-16 21:13 UTC, merged