chore(deps): adding dependabot
applitools/eyes.sdk.javascript1 pull request #413
Opened 2021-03-22 09:07 UTC by tool3

[trello](https://trello.com/c/e3cea3jO/833-fix-all-dependabot-and-audit-alerts)

this PR was created to handle the security and `npm audit` alerts that are triggered for our repo.
it introduces 2 files: 

1. `dependabot.yml` - initial dependabot config (under the `.github` directory).
2.  `generate-dependabot-config` - dependabot config generator in `sdk-shared` so we can better control what packages we want to continuously update.

since the dependabot UI doesn't offer much flexibility - and their monorepo detection is not working so well, I decided to create an entry per package (not only SDKs) in the `dependabot.yml` file, and have a single script that can generate this file with a skip list.

it is important to understand that once we enable this, we should expect a short period of many PRs as our initial "ramp-up".

2021-03-24 08:09 UTC, amitzur commented
@tool3 what workflow do you expect to have with the generator script?

2021-03-24 08:17 UTC, tool3 commented
> @tool3 what workflow do you expect to have with the generator script?

it was created so we don't forget to add new packages to the audit/dependency checks.
so we can run it periodically (and update master if there were changes) - possibly with a scheduled job - or simply run it as a part of our release procedure to make sure it is always up to date.

2021-03-24 08:17 UTC, amitzur requested changes
See my question about workflow.
I want to work on coding style. Mainly, be more functional. But also not do things like try/catch and just rethrow. Or use `exec` for a standard filesystem operation. This is important. When reading code, a standard way of thinking makes it easy to understand the author's intent.

2021-03-24 08:17 UTC, amitzur commented on packages/sdk-shared/src/generate-dependabot-config.js
> +    const {stdout: items} = await exec('ls packages')
I expect to use `fs.readdir` here

2021-03-24 08:17 UTC, amitzur commented on packages/sdk-shared/src/generate-dependabot-config.js
> +    for (const package of packages) {
A note on coding style. I prefer we choose more functional style. This is important for readability and consistency.
In this case it is very clear:
1. filter out skip list from packages array
2. map filtered array with inline string template (no need for string replace)
3. join with `\n`

2021-03-24 08:17 UTC, amitzur commented on packages/sdk-shared/src/generate-dependabot-config.js
> +  } catch (error) {
why try and catch an error if you just throw it?

2021-03-24 10:10 UTC, amitzur commented
> it was created so we don't forget to add new packages to the audit/dependency checks.
so we can run it periodically (and update master if there were changes) - possibly with a scheduled job - or simply run it as a part of our release procedure to make sure it is always up to date.

@tool3 @kyryloonufriiev @tourdedave do you think we should start having a generator for packages? If so, I think that generator can add the new package to the yml file.

2021-03-24 10:34 UTC, amitzur commented on packages/sdk-shared/src/generate-dependabot-config.js
> +    for (const package of packages) {
What do you think about the following?
```
const packagesStr = items
  .filter(package => !skipList.includes(package) && !package.startsWith('.'))
  .map(package => `- package-ecosystem: "npm"
    directory: "/packages/${package}"
    schedule:
      interval: "daily"`)
  .join('\n')
const fileContent = `version: 2\n updates:\n${packagesStr}`
```

2021-03-24 10:53 UTC, kyryloonufriiev commented
> @tool3 @kyryloonufriiev @tourdedave do you think we should start having a generator for packages? If so, I think that generator can add the new package to the yml file.

@amitzur I absolutely agree that package generation script is a nice thing to have. Because we have a really similar structure of packages and all our tools rely on we keeping this structure. I just felt it by publishing a bunch of new packages.

2021-03-24 12:38 UTC, tool3 commented on packages/sdk-shared/src/generate-dependabot-config.js
> +    for (const package of packages) {
this was changed to reflect something similar.
I say similar, because we don't really need to `map` it again and `join`.

since after `filter` I already have a list of packages to run on - I don't need to `join` it or do anything special with it, just run something per item :)

2021-03-24 12:39 UTC, tool3 commented on packages/sdk-shared/src/generate-dependabot-config.js
> +  } catch (error) {
removed

2021-03-24 13:00 UTC, amitzur commented on packages/sdk-shared/src/generate-dependabot-config.js
> +    for (const package of packages) {
This `for` loop is exactly what I suggested to get rid of :)
It doesn't convey any meaning. There's no perf overhead in this case for doing `map` and `join`. And it passes a clear message what you are doing.
The `for` loop is imperative code. `map` and `join` is functional. In most cases we want to favor functional style since it's more semantic.

2021-03-24 14:29 UTC, tool3 commented on packages/sdk-shared/src/generate-dependabot-config.js
> +    for (const package of packages) {
done!

2021-03-24 14:30 UTC, tool3 commented on packages/sdk-shared/src/generate-dependabot-config.js
> +    for (const package of packages) {
done :)

2021-04-26 09:26 UTC, amitzur commented on packages/sdk-shared/src/generate-dependabot-config.js
> +const skipList = ['eyes-universal-poc', 'eyes-leanft', 'eyes-images-legacy', 'eyes-sdk-core-legacy'];
eyes-common-legacy and eyes-selenium-3 should be skipped as well

2021-04-26 11:03 UTC, tool3 commented on packages/sdk-shared/src/generate-dependabot-config.js
> +const skipList = ['eyes-universal-poc', 'eyes-leanft', 'eyes-images-legacy', 'eyes-sdk-core-legacy'];
done

2021-04-26 11:11 UTC, merged