fix: fixing custom coverage tests in report
applitools/eyes.sdk.javascript1 pull request #419
Opened 2021-04-01 13:18 UTC by tool3

our coverage report was consistently missing the custom coverage tests.

the `convertJunitXmlToResultSchema` function in `sdk-coverage-tests` used to iterate over the json metadata file, which by definition does not contain any information about custom tests.

with this PR, we are running on *all* test results in the xml file - mapping any generic test to it's own object as before, but this time, including the custom coverage tests as well.

2021-04-01 13:52 UTC, kyryloonufriiev requested changes
I think now we will miss tests that exist in metadata, but not in xunit xml.

2021-04-01 13:54 UTC, kyryloonufriiev commented on packages/sdk-coverage-tests/src/report/xml.js
> +      if (!testMeta && !isSkipped) return
How `testMeta` could be falsy if you explicitly set it two lines before.

2021-04-01 13:57 UTC, kyryloonufriiev commented on packages/sdk-coverage-tests/src/report/xml.js
>        const isSkipped = testMeta.skip || testMeta.skipEmit || false // we explicitly set false to preserve backwards compatibility
I think here we need to try to extract `skip` from XML as well. I know that our reporter doesn't add it, but I have a creative solution to understand that test was skipped. Skipped test in XML result has `time` property equals to `0`.

2021-04-22 12:30 UTC, kyryloonufriiev commented on packages/sdk-coverage-tests/src/report/xml.js
> +  return Object.entries(allTests).reduce((acc, [testName, testMeta]) => {
You don't really need `reduce` here, just use `map` instead.

2021-04-22 12:33 UTC, kyryloonufriiev commented on packages/sdk-coverage-tests/src/report/xml.js
> +        mode: testMeta.executionMode,
what will be here for custom tests? `undefined`? Is it allowed?

2021-04-22 13:02 UTC, tool3 commented on packages/sdk-coverage-tests/src/report/xml.js
> +  return Object.entries(allTests).reduce((acc, [testName, testMeta]) => {
done thanks !

2021-04-22 13:03 UTC, merged