feat(eyes-storybook): fake ie
applitools/eyes.sdk.javascript1 pull request #421
Opened 2021-04-13 13:25 UTC by tool3

[trello](https://trello.com/c/P0SeWKRO)

this PR introduces a way to fake IE11 in storybook.

2021-04-22 10:56 UTC, amitzur reviewed
Review is WIP.
I went over most of the things. There are some issues that need addressing.
I expect the second part of the review to contain more requests for change than this one (I started from the easier things :) ).

2021-04-22 10:56 UTC, amitzur commented on packages/eyes-storybook/test/e2e/snapshots/eyes-storybook.e2e.test.json
> +    "Using @applitools/eyes-storybook version 3.20.2.",
so with every release we will need to update this file?
Maybe snaptdout should support not only `.json` but also dynamic `.js`?

2021-04-22 10:56 UTC, amitzur commented on packages/eyes-storybook/test/e2e/TestAccessibility.e2e.test.js
> +        browser: [{name: 'chrome', width: 800, height: 600}],
is this added because it's now mandatory? I don't mind it being here, just making sure no existing user API got broken

2021-04-22 10:56 UTC, amitzur commented on packages/eyes-storybook/src/validateAndPopulateConfig.js
> +  if (config.fakeIE) {
no need for nested `if`. Better to use `&&`.

2021-04-22 10:56 UTC, amitzur commented on packages/eyes-storybook/src/renderStories.js
> +      return `Done ${number} stories out of ${length} ${hasIE(config) ? '(IE)' : ''}`;
this is not correct logic. `hasIE` doesn't check if config has `fakeIE`. I don't think you need `hasIE` at all. Only `shouldRenderIE`, which is what should be used in this line as well.
How come no test failed because of this?

2021-04-22 11:16 UTC, tool3 commented on packages/eyes-storybook/src/fakeIE.js
> +  logger.verbose('[fakeIE] - faking IE');
I don't have access to the full page object from `initPage`, but I can pass in the `pageId`

2021-04-22 11:20 UTC, tool3 commented on packages/eyes-storybook/src/initPage.js
> +    if (!getRenderIE()) {
no, it only means that for IE it's handled elsewhere ... in `pagePool.drain` as explained the in PR description.

2021-04-22 11:26 UTC, tool3 commented on packages/eyes-storybook/src/renderStories.js
> +      return `Done ${number} stories out of ${length} ${hasIE(config) ? '(IE)' : ''}`;
I am not sure I understand. `renderStories` always gets called with separated configs.
`hasIE` checks for the existence of `IE` in your config browsers.
`shouldRenderIE` also validates the flag. which is being handled in `executeRenders`

2021-04-22 11:30 UTC, tool3 commented on packages/eyes-storybook/src/validateAndPopulateConfig.js
> +  if (config.fakeIE) {
done

2021-04-22 11:35 UTC, tool3 commented on packages/eyes-storybook/test/e2e/snapshots/eyes-storybook.e2e.test.json
> +    "Using @applitools/eyes-storybook version 3.20.2.",
I will replace it with current version from `package.json` - maybe worth adding this to `snaptdout` later on

2021-04-22 12:25 UTC, tool3 commented on packages/eyes-storybook/test/e2e/TestAccessibility.e2e.test.js
> +        browser: [{name: 'chrome', width: 800, height: 600}],
yup, it's mandatory

2021-04-26 06:28 UTC, amitzur commented on packages/eyes-storybook/src/renderStories.js
> +      return `Done ${number} stories out of ${length} ${hasIE(config) ? '(IE)' : ''}`;
Consider just a regular case of executing the SDK with IE in the browser configuration, but without the fakeIE flag. What will the output be?

2021-04-26 06:29 UTC, tool3 commented on packages/eyes-storybook/src/renderStories.js
> +      return `Done ${number} stories out of ${length} ${hasIE(config) ? '(IE)' : ''}`;
gotcha! fixing !

2021-04-27 09:59 UTC, amitzur commented on packages/eyes-storybook/src/initPage.js
> +    if (!getRenderIE()) {
but in `pagePool.drain` you are not listening on `close` event of the page.

2021-04-27 10:01 UTC, amitzur commented on packages/eyes-storybook/test/e2e/TestAccessibility.e2e.test.js
> +        browser: [{name: 'chrome', width: 800, height: 600}],
but until now it wasn't mandatory. So an API broke

2021-04-27 10:36 UTC, amitzur requested changes
Only thing left in the review is a deeper look at the tests for `executeRenders`.

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/src/initPage.js
> +      if (!getRenderIE() && pagePool.isInPool(pageId)) {
In continuation to another thread on this line - can you explain why this is needed?

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/src/pagePool.js
> +  let fullPageObjs = [];
where do you reassign this variable that it needs to be `let`?

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/src/shouldRenderIE.js
> +module.exports = {splitConfigsByBrowser, hasIE, shouldRenderIE};
no need to export `hasIE`. it's not used outside so it's confusing

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/test/e2e/TestAccessibility.e2e.test.js
> +    await closeStorybook();
there were 2 before/after blocks, each one responsible for a different thing. If you think it makes sense to merge them - please do it symmetrically also to the `before` block.

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/test/unit/shouldRenderIE.test.js
> +  describe('splitConfigsByBrowser', () => {
I think it's also worth having a test for a config that has only IE. I was looking for this test to see what the output would be.

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/test/unit/shouldRenderIE.test.js
> +  describe('hasIE', () => {
if you stop exporting this function then you can remove its tests as well (see comment above)

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/test/e2e/snapshots/fake-ie.e2e.test.json
> +    "Fake IE: Fake IE Page [Chrome 90.0] [800x600] - Passed",
is this order deterministic?

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/src/eyesStorybook.js
> +    const results = await executeRenders(configs);
there is a big bug here. if there is an error you throw it from `executeRenders`, and will not reach the `closeBatch` call below. Better return the result of `presult` from `executeRenders` and handle the exception throwing here like it was before.

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/src/executeRenders.js
> +function makeExecuteRenders({timeItAsync, renderStories, pagePool, stories, logger, setRenderIE}) {
I don't think the `makeExecuteRenders` function should receive `stories`. It makes more sense to be passed to `executeRenders`.
Actually, why do you need to have a `makeExecuteRenders` at all? You "make" the function just one line before calling it. You might as well have just a `executeRenders` function with the union of arguments.

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/test/unit/executeRenders.test.js
> +          counter++;
this is super fragile. your test will brake if a log entry is added to `executeRenders`!

2021-04-27 10:36 UTC, amitzur commented on packages/eyes-storybook/test/unit/executeRenders.test.js
> +      setRenderIE: {},
this should be a function, for clarity

2021-04-27 13:39 UTC, tool3 commented on packages/eyes-storybook/src/pagePool.js
> +  let fullPageObjs = [];
at some point we thought about simply overriding the `fullPageObjs` array, but I never set it back to `const` - fixing.

2021-04-27 13:42 UTC, tool3 commented on packages/eyes-storybook/src/shouldRenderIE.js
> +module.exports = {splitConfigsByBrowser, hasIE, shouldRenderIE};
removing thanks

2021-04-27 13:43 UTC, tool3 commented on packages/eyes-storybook/test/e2e/TestAccessibility.e2e.test.js
> +    await closeStorybook();
sorry ! didn't notice that other before at all (temporary blindness - is that a thing ?) - fixing

2021-04-27 13:43 UTC, tool3 commented on packages/eyes-storybook/test/unit/shouldRenderIE.test.js
> +  describe('splitConfigsByBrowser', () => {
added

2021-04-27 13:43 UTC, tool3 commented on packages/eyes-storybook/test/unit/shouldRenderIE.test.js
> +  describe('hasIE', () => {
removed this test case

2021-04-27 13:44 UTC, tool3 commented on packages/eyes-storybook/test/e2e/snapshots/fake-ie.e2e.test.json
> +    "Fake IE: Fake IE Page [Chrome 90.0] [800x600] - Passed",
yes - we separate the config specifically to have the fake IE pages last - because of what we discussed of avoiding the need to reset the useragent and document mode.

2021-04-27 13:44 UTC, tool3 commented on packages/eyes-storybook/src/eyesStorybook.js
> +    const results = await executeRenders(configs);
extracted to `eyesStorybook` - great catch ! thank you !

2021-04-27 13:45 UTC, tool3 commented on packages/eyes-storybook/test/unit/executeRenders.test.js
> +      setRenderIE: {},
updated

2021-04-27 14:12 UTC, tool3 commented on packages/eyes-storybook/src/executeRenders.js
> +function makeExecuteRenders({timeItAsync, renderStories, pagePool, stories, logger, setRenderIE}) {
I removed the `makeExecuteRender` and consolidated it to a single function

2021-04-27 14:29 UTC, tool3 commented on packages/eyes-storybook/test/unit/executeRenders.test.js
> +          counter++;
updated the test to contain an array of logs, and updated the test to match the new single function design

2021-04-27 14:29 UTC, tool3 commented on packages/eyes-storybook/src/initPage.js
> +      if (!getRenderIE() && pagePool.isInPool(pageId)) {
we want to retain the option to still run the logic for when a page closes unexpectedly - but at the same time - we don't want to do that when running the IE stories - because we handle it differently when it's a fake IE page.

when the page is set to be IE - we do `page.close` before running the logic of removing and readding the page to the pool - otherwise we will only create new pages and the run will just hang.

2021-04-28 06:44 UTC, amitzur commented on packages/eyes-storybook/src/eyesStorybook.js
> +    const results = await executeRenders(configs);
I don't see it extracted back there

2021-04-28 06:45 UTC, amitzur commented on packages/eyes-storybook/src/initPage.js
> +      if (!getRenderIE() && pagePool.isInPool(pageId)) {
we **do** want to have the listener when running IE stories. We just want to remove it (or just not perform the recovery) while draining the pool.

2021-04-28 06:47 UTC, amitzur requested changes
1. Still not fixed calling `closeBatch` event in case of error in `renderStories`.
2. Need to listen to `close` event on page also while running IE stories.

2021-05-02 06:39 UTC, merged