Browser extension update
applitools/eyes.sdk.javascript1 pull request #671
Opened 2021-08-11 12:41 UTC by kyryloonufriiev

1. Fix the bug in `setWindowSize` spec driver method when the window is maximized.
2. Fix bug with accessing cross-origin frame context.
3. Return array of TestResults from `close`.
4. Add capability of throwing errors from `close` and `closeAllEyes`, it is `false` by default (usage `eyees.close({throwErr: true})`)

I have used a chance to refactor the core a bit, so I have removed some redundant abstractions around test results (`TestResultsSumary` and `TestResultContainer`). Also, I have changed a base class `EyesError` to implement a generic error structure for the core which includes all of the needed metadata, such as `reason`. I use `reason` to create a user-facing representation of this error.

2021-08-11 17:14 UTC, amitzur requested changes
1. `close.js` seems buggy.
2. I think documenting the various reasons for errors (perhaps with a TS type?) makes sense, to make it easy to consume it.

2021-08-11 17:14 UTC, amitzur commented on packages/eyes-sdk-core/lib/new/close-all-eyes.js
> +      result = result instanceof TestResults ? result.toJSON() : null
result would never be `instanceof TestResults`

2021-08-12 14:27 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/new/close.js
> +    else if (!Array.isArray(results)) results = [results]
Yeah, doesn't make sense anymore

2021-08-12 14:31 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          if (!error.info || !error.info.result) throw error
I didn't understand am I should add undefined or you say that I'm doing it already. Before I start touching it, we were throwing an error in case it is an actual error and not a diff/new/failed test error. This is what I have preserved here

2021-08-12 16:11 UTC, kyryloonufriiev commented
Works fine with the browser extension. I also have run coverage tests for wido to verify that other SDKs are still working as before.
![image](https://user-images.githubusercontent.com/59825365/129230616-d6dff40c-51ac-4a2c-9f8a-a52e6be6de3e.png)

2021-08-13 07:00 UTC, merged