separate local server to it's own process
applitools/eyes.sdk.javascript1 pull request #731
Opened 2022-01-08 00:26 UTC by SophieDePaula

In order to better understand what happens when presumably our local server crashes, we now start the local server in a separate process (relates to this [trello card](https://trello.com/b/ECya7n3i/js-sdks?filter=due:notdue)).

In `pluginExport.js` we now `fork` a new process that gets `server.js` file and does:

1) Create `logger`
2) Create `visualGridClient`
3) Create `handlers`
4) Create the `app`
5) Start the local server
6) Add a new endpoint to `app`

`server.js` now listen to messages from `pluginExport` to perform the functionalty mentioned above.
In addition, a new endpoint was created for `app`. This endpoint (`eyes/waitForBatch`) will be called from the `after:run` of the global hooks instead of calling `waitForBatch` directly.

TODO:
Add a test to crash the server and make sure we are getting an informative error message

2022-01-08 00:33 UTC, SophieDePaula commented on packages/eyes-cypress/test/it/plugin/server.test.js
> +  it.skip('starts at a random port', async () => {
I skipped this test as we start the server from other places, we get the port and are able to connect. Therefore, I don't believe doing the same thing here will benefit us.

2022-01-10 12:29 UTC, amitzur requested changes
Review is WIP. My main concerns are around when and how to stop the process, how to pass the config to it, and the way `waitForBatch` is implemented.

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
>  function makeGlobalRunHooks({visualGridClient, logger}) {
No more need to `makeGlobalRunHooks` since both `visualGridClient` and `logger` are no longer used

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +      const response = await axios.get(
I think the right way to do it is `axios.get(url, {params, headers})`. But are you sure that `config` is serializable? You are sending a `GET` request here, and `params` will become query params on the URL. Is that the intention?

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/hooks.js
> +      if (response.data.message && response.data.message.includes('Eyes-Cypress detected diffs')) {
Throwing an error here should be done based on the `success` value of the response. The server should respond with a `{success, error}` object, and the logic of the message should be in the server. The code here should just check if `success` is `false` then throw the `error`

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/pluginExport.js
> +function makePluginExport({eyesConfig, globalHooks, basicConfig = ''}) {
why is the default value for `baseConfig` an empty string? Its "type" is actually an object, according to what is passed from `startPlugin`

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/server.js
> +    closeServer();
missing `await`

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/server.js
> +    app.get('/eyes/waitForBatch', express.json({limit: '100mb'}), async (req, res) => {
Could this not be done in `handlers`? We already listen to `/eyes/:command`, I would expect it to work normally just like any other handler. What you will get from doing that is the ability to just throw an error from the handler (or return a value from it), and the server will respond with a response of the shape `{success, result}` or `{success, error}`.

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/server.js
> +        process.exit(0);
I don't think it's good to stop the process from here. The fact that the batch ended isn't coupled with the logic to end the process.

2022-01-10 12:29 UTC, amitzur commented on packages/eyes-cypress/src/plugin/server.js
> +  createAppAndStartServer.then(res => {
I'm not sure this is more readable than using async/await.
What about doing something like `const {closeServer, eyesPort} = await new Promise(...)` ?

2022-01-10 18:25 UTC, SophieDePaula commented on packages/eyes-cypress/src/plugin/hooks.js
>  function makeGlobalRunHooks({visualGridClient, logger}) {
@amitzur we still pass the hooks to `makePluginExport` so I kept the `function` just removed the parameter it's getting. I support that's what you meant :)

2022-01-10 19:48 UTC, SophieDePaula commented on packages/eyes-cypress/src/plugin/hooks.js
> +      const response = await axios.get(
Good point. I replaced `params` with `data` so that the `config` passes in the `body`.
When I send the `body` and `header` in an object like you suggested, I don't see the `headers` and `body` in the `request`

2022-01-10 23:14 UTC, SophieDePaula commented on packages/eyes-cypress/src/plugin/hooks.js
> +      const response = await axios.get(
Please ignore my previous comment, I switched to `post` to take advantage of the endpoint we already have as you mentioned below

2022-02-28 22:48 UTC, closed without merging