Support lazy loading as part of CheckSettings
applitools/eyes.sdk.javascript1 pull request #738
Opened 2022-01-13 16:58 UTC by tourdedave

[Trello](https://trello.com/c/BIHFMhVk)

- [x] eyes-api
- [ ] snippets
- [ ] eyes-sdk-core (classic)
- [ ] eyes-sdk-core (VG)
- [ ] coverage tests
- [ ] update readmes

2022-01-14 07:25 UTC, kyryloonufriiev commented on packages/eyes-api/src/input/CheckSettings.ts
> +      pageHeight: options && options.pageHeight || 15000
Just a suggestion. You can use modern syntax here since this is a type script and we will compile it anyway.
```suggestion
      scrollLength: options?.scrollLength ?? 300,
      waitingTime: options?.waitingTime ?? 2000,
      pageHeight: options?.pageHeight ?? 15000
```

2022-01-14 07:28 UTC, kyryloonufriiev commented
You also should update `types` package, it declares types for internal API, at the moment it looks like a copypasting, but it allows us completely unbind internal API from user-facing API.

2022-01-17 09:07 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +function lazyLoad([{scrollLength, waitingTime, pageHeight} = {}] = []) {
I think this function should accept also an element to scroll. But pay attention that this should be a separate item in the array and not the one in an object, because of some sdks limitations.

2022-01-17 09:11 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +  let p = Promise.resolve()
Looking at this I have understood that if we wanna call this function and wait until it is really done, we will have to implement a new method in all of the spec drivers (!). Because `executeAsyncScript` is a different method in wd protocol. But we can avoid it with a polling approach.

2022-01-17 09:12 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +      window.scrollTo({top: scrollLength * (i + 1)})
This function signature is not supported in IE. But do we need to support it in the first place?

2022-01-18 14:31 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +function lazyLoad([{scrollLength, waitingTime, pageHeight} = {}] = []) {
The initial requirements for this feature didn't say anything about an element. But I'll ask for clarification. Understood about the array arguments/limitations.

2022-01-18 14:33 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +      window.scrollTo({top: scrollLength * (i + 1)})
Ah, good point. I just thought it was more declarative. I'll switch it.

2022-01-18 14:34 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +  let p = Promise.resolve()
🤯 okay.

2022-01-18 15:03 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +      window.scrollTo({top: scrollLength * (i + 1)})
You can use our scrollTo snippet which accepts object with x and y, supports element scrolling, and handles different behavior in browsers.

2022-01-18 15:09 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +function lazyLoad([{scrollLength, waitingTime, pageHeight} = {}] = []) {
I don't see a reason to limit functionality on a default scrolling element only. There is no overhead to do so, because when you will execute this script you will already have scrollingElement in our driver.

2022-01-18 20:24 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +function lazyLoad([{scrollLength, waitingTime, pageHeight} = {}] = []) {
Sure, but I checked with the business owner and they said it is not required right now.

2022-01-18 20:26 UTC, tourdedave commented
@kyryloonufriiev I'm having trouble getting a bundle that works with IE and promises. Maybe we can sync up on this tomorrow?

2022-01-19 14:05 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +function lazyLoad([{scrollLength, waitingTime, pageHeight} = {}] = []) {
I misunderstood your initial comment. I thought you meant accept an element to scroll *to*. Not accept an element to scroll *with*. That seems important to include. I'll follow up with the business.

2022-01-19 15:13 UTC, tourdedave commented
> @kyryloonufriiev I'm having trouble getting a bundle that works with IE and promises. Maybe we can sync up on this tomorrow?

Going to switch the implementation to polling/sync, which removes the need to polyfill to support promises or regeneratorRuntime (which also side-steps the challenges I've been running into getting a build that works for IE)

2022-01-31 15:19 UTC, kyryloonufriiev reviewed
I still have a concern about the fact that we are going to support only window scrolling and don't have support for `scrollRootElement`. If a user is going to specify an SRE + lazeLoad, then he definitely wants an SRE to be the element we gonna scroll.

Also, Amit has convinced me that polling is the correct way to go, but I still think that we should adjust `executePollScript`, because it was initially designed for dom scripts only, so the default value for `pollTimeout` was chosen depend on that. I don't believe that `200ms` makes any sense if `waitingTimeout` is set to `5s`.

2022-01-31 15:27 UTC, tourdedave commented on packages/snippets/rollup/commands.js
> +      resolve(),
To use dom-shared. See `lazyLoadPollResult`

2022-01-31 15:58 UTC, tourdedave commented on packages/eyes-api/test/unit/CheckSettings.spec.ts
> +    })
I'm glad you say so. The duplication between eyes-api and core felt like a mis-step. And supporting a boolean felt like a natural direction to take things.

2022-01-31 15:59 UTC, tourdedave commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          },
Where would you recommend putting it?

2022-01-31 16:01 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +}
Great idea! Didn't know we already had this specified elsewhere.

2022-01-31 16:05 UTC, tourdedave commented
> I still have a concern about the fact that we are going to support only window scrolling and don't have support for `scrollRootElement`. If a user is going to specify an SRE + lazeLoad, then he definitely wants an SRE to be the element we gonna scroll.
> 
> Also, Amit has convinced me that polling is the correct way to go, but I still think that we should adjust `executePollScript`, because it was initially designed for dom scripts only, so the default value for `pollTimeout` was chosen depend on that. I don't believe that `200ms` makes any sense if `waitingTimeout` is set to `5s`.

I don't know what to tell you about the SRE. I agree with you, but as far as I know we presented this to the business and they said it's a good idea but it's not something we're going to do right now. As for polling time, makes sense. What do you recommend?

2022-01-31 16:14 UTC, kyryloonufriiev commented on packages/snippets/rollup/commands.js
> +      resolve(),
Ah. Didn't notice that you use it. This is overhead because the biggest part of this script is supposed to splint the response into chunks, this is never gonna be needed for this script. I also don't really see a reason to create a dedicated poll script. We have it for dom-snapshot because the script itself is so big that it was nice to have a small one for polling.

2022-01-31 16:15 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          },
I would do it just before taking dom snapshot.

2022-01-31 16:21 UTC, kyryloonufriiev commented
Regarding SRE, okay if someone told you that we don't have to do it then it is fine. I think `pollTimeout` should be not less than `waitingTime`. Maybe you have a better juristic in mind.

2022-01-31 16:31 UTC, tourdedave commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          },
Can you elaborate? `prepareBeforeCapture` is called just before `takeDomSnapshot` in `takeDomSnapshots`.

2022-01-31 16:41 UTC, tourdedave commented on packages/snippets/rollup/commands.js
> +      resolve(),
If we're mapping the snippet to a result object structure used throughout the code base then I figured it would be easier to leverage the existing polling script which handles this (even though there's functionality re: chunking that we'd never use here). I was initially hoping to use both `pollify` and `poll` from dom-shared (which is why I initially implemented it), but couldn't use `pollify` because it's async, . Once I realized I could only use 1/2 of the solution I still thought its was good enough to keep. I'm not opposed to backing it out if you feel strongly about this.

2022-01-31 18:11 UTC, tourdedave commented
> I think `pollTimeout` should be not less than `waitingTime`. Maybe you have a better juristic in mind.
> 
> Regarding SRE, okay if someone told you that we don't have to do it then it is fine.

A `pollTimeout` of `waitingTime` seems like a good place to start.

2022-02-01 07:54 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          },
Ah. You are right. But should we do it before each of the snapshots? or only once before all of them. Also by changing `waitBeforeCapture` to `prepareBeforeCapture` you broke the storybook, just something to keep in mind.

2022-02-01 14:54 UTC, tourdedave commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          },
That's good to know about storybook since we aren't planning to update it as part of this. Probably better to separate them into two functions then. I'm not sure which is better (before each snapshot or once before all). Which do you think makes more sense?

2022-02-01 14:58 UTC, tourdedave commented on packages/snippets/rollup/commands.js
> +      resolve(),
Also, re: having a dedicated polling script, I see value in it.

Specifically:
1. it follows a precedent that's used elsewhere (e.g., dom-snapshot)
2. it's easier to reason about as a result
3. it maintains encapsulation (e.g., we don't need to reference window variables in core)

2022-02-02 08:49 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          },
If you use `layoutBreakpoints` with `lazyLoad`, it doesn't make a lot of sense for you to load content again and again once you resize a window, because the content is already loaded after the first time, I believe this is the case in 99%. This is why I think we should load content once before all dom snapshots. Also, it might be a reason for screenshots with a different number of elements loaded on different screen sizes. So I'm voting for the "once before all" option.

2022-02-02 09:37 UTC, kyryloonufriiev commented on packages/snippets/rollup/commands.js
> +      resolve(),
I see your point and it makes sense. It just doesn't feel right to me to use dom-shared in snippets. But maybe this is just because they are located in different repositories and dom-shared mostly associated with dom-scripts.
But my other point is that having a separate script to poll results doesn't really serve the purpose it serves in dom-scripts. We have a `pollResult` script there to make requests to the browser smaller. But in this case, we make them bigger with no good reason for that.

| Script | Chars |
|-------|------------|
| `lazyLoad` | 2948 |
| `lazyLoadPollResult` | 1760 |

`lazyLoadPollResult` script is more than half the size of the `lazyLoad` script, in fact, it is even bigger than the actual business logic of `lazyLoad` because the `lazyLoadPollResult` script is called inside `lazyLoad`.

So I propose to smush together `lazyLoad` and `lazyLoadPollResult`, avoid using `poll` from `dom-shared` because it is too fat for such a small script. But you can still use the same protocol as well as the `executePollScript` utility from the core.

2022-02-02 09:43 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +    )
Hmm. I understand the motivation, but I think this contradicts the idea of snippets, they should be minimalistic and pure logical units we execute to do a specific task. I don't think that input validation is something it should include, if you need to validate such a thing it should be done before you execute a snippet.

2022-02-02 09:47 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +  }
If you are going to handle errors here you also should catch them inside the `setTimeout` callback, because this is where all of the logic happens.

2022-02-02 09:50 UTC, kyryloonufriiev commented on packages/snippets/src/browser/lazyLoad.js
> +        const {x, y} = currentScrollPosition()
consider using the `scrollTo` snippet, because it was already written to return the current scroll position after scroll. Also, it handles `scroll-behavior: smooth` style property (it will break your logic here).

2022-02-02 15:15 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +  }
Okay. Will do. I added error handling like this so it matched what is expected by the polling script in EyesUtils in core

2022-02-02 18:24 UTC, tourdedave commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          },
@amitzur thoughts? ☝️

2022-02-09 21:06 UTC, tourdedave commented
Updated the snippet and readme. Need to revisit the infinite scroll test in IE since the test is failing. I added details as to what's happening in the comments of the test.

2022-02-11 18:21 UTC, tourdedave commented
I'm having trouble getting a build on an SDK with everything wired up.

I've gone to each package (in the following order) `types`, `eyes-api`, `eyes-sdk-core`, `eyes-selenium` and done the following.

1. Linked deps (with `file:../path/to/package`) when appropriate
2. `rm -rf node_modules; yarn`
3. `yarn build` when available

Everything works until I get to `eyes-selenium`. I get the following when trying to build.

```
/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/typescript/lib/typescript.js:114713
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'length')
    at createTypeMembers (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:446:122)
    at createTypeLiteralNode (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:339:25)
    at createTypeNode (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:311:20)
    at createPropertyDeclaration (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:575:26)
    at createTypeMembers (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:453:33)
    at createTypeLiteralNode (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:339:25)
    at createTypeNode (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:311:20)
    at createPropertyDeclaration (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:575:26)
    at createTypeMembers (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:453:33)
    at createTypeLiteralNode (/Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-selenium/node_modules/@applitools/api-extractor/dist/transformer.js:339:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm running Node 16.13.1.

2022-02-11 18:35 UTC, tourdedave commented
Actually, I'm getting the same error when trying to build `eyes-selenium` with `eyes-api@1.1.7`. It works with `eyes-api@1.1.6`.

2022-02-12 01:16 UTC, kyryloonufriiev commented
@tourdedave Works for me. Verify if you have the latest version of the `api-extractor` in this package.

2022-02-14 14:34 UTC, tourdedave commented
> @tourdedave Works for me. Verify if you have the latest version of the `api-extractor` in this package.

That works, thanks!

2022-02-23 10:56 UTC, amitzur requested changes
Great and clean!
I love the readme, it's very well structured.
What happens if the driver is already focused on an inner iframe? Should we focus on the main context before the snippet? And if we do, do we need to explicitly focus it back? Or will that be managed by core+driver? cc @kyryloonufriiev 

Requested changes mainly because of the boolean parameter in eyes-api.

Dave, what did you mean by the following question?
> decide on when to run the snippet as part of grid execution in eyes-sdk-core

2022-02-23 10:56 UTC, amitzur commented on packages/eyes-api/src/input/CheckSettings.ts
> +  lazyLoad(options: boolean | LazyLoadOptions = true): this {
I spoke with Ben. Neither of us think that it makes sense to support `boolean` at the user API level.
So the default value IMO should just remain undefined (i.e. `options` is optional), and if it's undefined then `this._settings.lazyLoad = true`

2022-02-23 10:56 UTC, amitzur commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          waitBeforeCapture: async () => {
was it not readable the way it was?

2022-02-23 10:56 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshots.js
> +  lazyLoadBeforeCapture,
I think I would not create another option. It's defined and used exactly like `waitBeforeCapture`. So I think a cleaner API for `takeDomSnapshots` would be to change `waitBeforeCapture` option to `beforeCapture` and the consumer should provide the functionality that they want to run before each capture. WDYT?

2022-02-23 10:56 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshots.js
> +      console.log(err)
probably you want to use `logger` here

2022-02-23 10:56 UTC, amitzur commented on packages/types/src/setting.ts
> +    lazyLoad?: boolean | LazyLoadOptions
As mentioned in the comment in `CheckSettings.ts`, need to remove `boolean`

2022-02-23 10:56 UTC, amitzur commented on packages/snippets/src/browser/lazyLoad.js
> +        setTimeout(() => {
do you intentionally wait before the first iteration? It's no biggy. I was just expecting the function to immediately perform the operation, and then call `setTimeout(() => scrollAndWait(...), waitingTime)`.

2022-02-23 10:56 UTC, amitzur commented on packages/snippets/src/browser/lazyLoad.js
> +              const {x, y} = scrollTo([undefined, startingScrollPosition])
This means setting `scroll-behavior` to 'auto' and then reverting it on each iteration. Of course, if it was already `auto` then that's a non-issue.
Ok, I'm fine with it. But let's add a comment that states that this is the behavior.

2022-02-23 10:56 UTC, amitzur commented on packages/eyes-sdk-core/test/e2e/lazyLoad.spec.js
> +    manager.closeAllEyes()
`await` ?

2022-02-23 10:56 UTC, amitzur commented on packages/eyes-sdk-core/test/e2e/lazyLoad.spec.js
> +      ;[driver, destroyDriver] = await spec.build({browser: 'chrome'})
I would move this to a `beforeEach` outside of `describe`. Actually, since each describe has only 1 test, I thinks all `it`s can be flat under the main `describe`. I don't like nested suites unless it's absolutely necessary :)

2022-02-23 15:48 UTC, tourdedave commented on packages/eyes-api/CHANGELOG.md
> +- initial implementation of API layer for js eyes SDKs
I removed a trailing new line

```
-- initial implementation of API layer for js eyes SDKs
\ No newline at end of file
+- initial implementation of API layer for js eyes SDKs
```

2022-02-23 16:01 UTC, tourdedave commented on packages/eyes-nightwatch/README.md
> +- `undefined` - the UFG's default
Looks like same as the other one. Removed newline at the end of the file.

```
-- `undefined` - the UFG's default
\ No newline at end of file
+- `undefined` - the UFG's default
```

2022-02-23 16:13 UTC, tourdedave commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshots.js
> +  lazyLoadBeforeCapture,
This was the original direction taken, but Kyrylo pointed out that this would have been a breaking change for eyes-storybook. Since we weren't planning to update eyes-storybook as part of this work, I reverted the change and implemented it as a new option.

2022-02-23 16:15 UTC, tourdedave commented on packages/snippets/src/browser/lazyLoad.js
> +        setTimeout(() => {
I guess I interpreted it differently and didn't give it a whole lot of thought.

2022-02-23 17:31 UTC, tourdedave commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshots.js
> +  lazyLoadBeforeCapture,
A choose-your-own-adventure moment:

a) leave it as-is and update it later or b) change it now and update eyes-storybook

WDYT?

2022-06-01 06:59 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +    const lazyLoadOptions = CheckSettingsUtils.makeLazyLoadOptions(this._checkSettings.lazyLoad)
I don't think input validation should happen in `makeLazyLoadOptions` at all. You are right that this happens very deep in our business logic. This is why I believe that validation should happen once we get data from the user, which means in `check` function (the one in `new` folder). There is also another direction - validate on api level.

2022-06-01 07:11 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshots.js
> +  lazyLoadBeforeCapture,
@amitzur @tourdedave I don't think my point was about the storybook. The update would cost us just to rename the function in the storybook SDK. 
I was concerned about the fact we will run it before each `takeDomSnapshot` because in the case of `layoutBreakpoints` it could be lots of snapshots, so lots of scrolling and waiting through the same content again and again.

2022-06-09 15:32 UTC, tourdedave commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +    const lazyLoadOptions = CheckSettingsUtils.makeLazyLoadOptions(this._checkSettings.lazyLoad)
I'll take a look at both. Thanks!

2022-06-09 17:48 UTC, tourdedave commented on packages/eyes-sdk-core/lib/utils/takeDomSnapshots.js
> +  lazyLoadBeforeCapture,
I discussed this offline with Kyrylo. Since the behavior for `waitBeforeCapture` and lazy load need to happen at different times, we will keep them as separate functions.

2022-06-09 19:01 UTC, tourdedave commented on pending-changes.yaml
> +    - Add the ability for the SDK to lazy load the page prior to performing a check window
@benbabayoff8

2022-06-13 18:25 UTC, tourdedave commented
@kyryloonufriiev Please review when you get a chance. Thanks!

2022-06-14 14:15 UTC, merged