Storybook
applitools/eyes.sdk.javascript1 pull request #758
Opened 2022-01-24 13:42 UTC by chaim-aharonson-applitools

2022-02-02 10:27 UTC, amitzur requested changes
Great job!
There are just a few minor comments, and I asked for more opinions on `isMany`. But the code is good and to the point.

2022-02-02 10:27 UTC, amitzur commented on packages/eyes-storybook/src/processResults.js
> +  } else if (passedOrNew.length && !warnForUnsavedNewTests) {
I would simplify the condition a bit:

```
} else if (warnForUnsavedNewTests) {
...
} else if (passedOrNew.length) {
...
}
```

2022-02-02 10:27 UTC, amitzur commented on packages/eyes-storybook/src/processResults.js
> +      `\n'SaveNewTests' was set as false and there ${countText}. Please approve ${_toMany(
Nice output! Text correction:
```
`\n'saveNewTests' was set to false and there ${countText}. Please approve ${_toMany(
```

2022-02-02 10:27 UTC, amitzur commented on packages/eyes-storybook/src/processResults.js
> +      )} baseline${_toMany(newTestsSize)} in Eyes.\n`,
I would say `in Eyes` --> `in the Eyes dashboard`. Actually, could you consult with Ben about it? We use the term "Test manager" in our formal documentation (but nowhere in the SDK readme's. There we use the term "Eyes dashboard")

2022-02-02 10:27 UTC, amitzur commented on packages/eyes-storybook/src/processResults.js
> +  const _toMany = utils.general.toMany;
variable names that start with `_` are considered unused. This is how to avoid an eslint error for intentional cases of not using a variable. In this case it's not needed because the variable is used.

2022-02-02 10:27 UTC, amitzur commented on packages/utils/src/general.ts
> +export function toMany(object: [] | number, config?: [manyCase: string, singleCase: string]): string {
I initially thought this isn't really needed. And I thought `pluralize` would be a better name.
TBH it's a bit weird to return only the suffix. But after seeing how it's used in `processResults` I'm fine with it.

Regarding the configuration, I also thought a better practice would be an object `{manyCase, singleCase}`. It would be better both for understanding, and for specifying only a `singleCase` if that's really a use case. But it's very verbose for the caller, especially since it's likely to be used inside a template literal.

@kyryloonufriiev @SophieDePaula @tourdedave let's hear your opinion as well?

2022-02-02 10:27 UTC, amitzur commented on packages/eyes-storybook/test/it/processResults.test.js
> +      saveNewTests: true,
you can also not send anything and this way you will also check the default value

2022-02-03 11:40 UTC, chaim-aharonson-applitools commented on packages/utils/src/general.ts
> +  const count = types.isArray(object) ? object.length : types.isNumber(object) ? object : 0;
the '0' case is a fallback, maybe in ts we don't need that.
I think it's more 'developer friendly' and shorter to avoid ```length``` and send to the method 'what u have'

2022-02-03 11:45 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/src/processResults.js
> +      )} baseline${_toMany(newTestsSize)} in Eyes.\n`,
added 'dashboard' seams clearer (will update the ticket)

2022-02-03 12:01 UTC, chaim-aharonson-applitools commented on packages/utils/src/general.ts
> +export function toMany(object: [] | number, config?: [manyCase: string, singleCase: string]): string {
```pluralize``` it is from now.
Config was defined as an Array for shorter code and due to the fact that if 'config' is used it **must** send the two values. additionally, ```manyCase``` is first because I saw that all places which this was used, the first case handled many, aka: ```err.length>0?'s':''```

2022-02-09 10:42 UTC, amitzur approved these changes
Great! See only 1 comment inline, and you can publish:
1) utils
2) storybook

2022-02-09 10:42 UTC, amitzur commented on packages/eyes-storybook/src/processResults.js
> +  } else if (passedOrNew.length && !warnForUnsavedNewTests) {
no need for `!warnForUnsavedNewTests` since it's already in the previous `if/else`

2022-02-09 11:16 UTC, merged