Set cut provider
applitools/eyes.sdk.javascript1 pull request #764
Opened 2022-02-02 16:32 UTC by chaim-aharonson-applitools

2022-02-02 17:05 UTC, kyryloonufriiev requested changes

2022-02-02 17:05 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/test/unit/new/MakeCheck.spec.js
> +    })
This is not exactly what I was envisioning. Why would you need `getCut` and `setCut` in the core api. What you really need is to read the cut value directly from your "fake eyes" object that you should pass to the `makeCheck` function. I also don't think that `EyesMockWithCutFunc` in `testUtils` makes sense, since this kind of mock object is valid only for this test.

2022-02-07 10:02 UTC, chaim-aharonson-applitools commented on packages/eyes-sdk-core/test/unit/new/MakeCheck.spec.js
> +    })
get and set cut as functions and not directly: IMHO it is more 'elegant', readable and consist with real **eyes** API, but, if you think I should remove and call directly I will do so.
Moved the relevant functions from ```testUtils```

2022-02-09 10:37 UTC, amitzur approved these changes
:100: @chaim-aharonson-applitools you can merge this into master and publish:
1) eyes-sdk-core
2) eyes-webdriverio

(basically all SDK's should be released with this fix, but only 1 customer is waiting for it, and they are using webdriverio)

2022-02-09 11:27 UTC, merged