Support batchId, batchName and batchSequenceName
applitools/eyes.sdk.javascript1 pull request #809
Opened 2022-03-17 00:04 UTC by SophieDePaula

Support batchId, batchName and batchSequenceName from the config file, eyesOpen and environment variables.
This is to fix [this issue](https://trello.com/c/H5xJSTsD/1271-cypress-batchid-configuration-not-being-honored-in-new-cypress-version).
I initially thought that we should only support sending an object with the above properties.

2022-03-17 07:59 UTC, amitzur requested changes
- Missing handling of `cy.eyesOpen({batch: {id,name,sequenceName}})` (plus a test for it)
- Missing a test in `eyesOpenMapping.test.js` for having `batchId`, `batchName`, `batchSequenceName` in the applitools.config.js file.
- Missing tests for the logic in `config.js`

2022-03-17 07:59 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesOpenMapping.js
> +    id: args.batchId || appliConfFile.batch.id,
what about `args.batch.id` ?

2022-03-17 07:59 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesOpenMapping.js
> +    name: args.batchName || appliConfFile.batch.name,
what about `args.batch.name`?

2022-03-17 07:59 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesOpenMapping.js
> +    sequenceName: args.batchSequenceName || appliConfFile.batch.sequenceName,
what about `args.batch.sequenceName`?

2022-03-17 07:59 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesOpenMapping.js
> +  let batch = {
why not `const`?

2022-03-17 07:59 UTC, amitzur commented on packages/eyes-cypress/test/unit/browser/eyesOpenMapping.test.js
> +      batchId: '1234',
I would do this in a separate test

2022-03-17 07:59 UTC, amitzur commented on packages/eyes-cypress/src/plugin/config.js
> +      name: config.batchName,
you are overriding `name` with `undefined` in case there is `config.batch.name` but not `config.batchName`

2022-03-17 07:59 UTC, amitzur commented on packages/eyes-cypress/src/plugin/config.js
> +    config.batch = {
no reason for this `else` block. The only purpose of the code here is to create a single batch with an ID in case the user didn't specify the batch ID. If they **did** specify a batch ID, then this would be handled in `eyesOpenMapping.js`.
Alternatively, handle everything related to the batch here, and do nothing about it in `eyesOpenMapping.js`. But don't spread the logic across multiple places.

2022-03-17 08:00 UTC, amitzur commented on pending-changes.yaml
> +    - Support batchId, batchName and batchSequenceName from the config file, eyesOpen and environment variables
@benbabayoff8 :point_up:

2022-03-17 08:51 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Support batchId, batchName and batchSequenceName from the config file, eyesOpen and environment variables
@amitzur Awesome.

2022-03-17 18:12 UTC, SophieDePaula commented
Thanks @amitzur ready for review again.

2022-03-19 21:56 UTC, amitzur requested changes

2022-03-19 21:56 UTC, amitzur commented on packages/eyes-cypress/src/browser/eyesOpenMapping.js
> +    id: args.batchId || args.batch?.id || appliConfFile.batchId || appliConfFile.batch?.id,
optional chaining might not be supported in the user's browser (it's supported from [Chrome 80](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility), and Cypress supports Chrome from [version 64](https://docs.cypress.io/guides/guides/launching-browsers#Browser-versions-supported))

Our eslint catches this, since we have `ecmaVersion:2018` in `.eslintrc.json`. Also this code should go through prettier.

2022-03-19 21:56 UTC, amitzur commented on packages/eyes-cypress/test/unit/plugin/config.test.js
> +    expect(config.batch.id).not.undefined;
I didn't know you could write it this way..
Another way is `expect(config.batch.id).not.to.be.undefined;`
(just for correct english, but actually the shorter way seems clearer to me)

2022-03-19 21:56 UTC, amitzur commented on packages/eyes-cypress/test/unit/plugin/config.test.js
> +    expect(config.batch.id).to.be.equal('1234');
no need for `.be`:
`expect(config.batch.id).to.equal('1234');`

2022-03-19 21:56 UTC, amitzur commented on packages/eyes-cypress/test/unit/plugin/config.test.js
> +  it('should not overwrite bach id from config file when passed in an object', () => {
bach --> batch

2022-03-19 21:56 UTC, amitzur commented on packages/eyes-cypress/test/unit/browser/eyesOpenMapping.test.js
> +      batch: {id: undefined, name: undefined, sequenceName: undefined},
hmmm, is this how you would like `eyesOpenMapping` to behave? I'm not even sure this leads to correct behavior when sent to the server.
Since `config.js` will populate `batch.id`, it will never have only undefined values. But I think it's still not a good behavior of `eyesOpenMapping`.

2022-03-19 21:56 UTC, amitzur commented on packages/eyes-cypress/test/unit/browser/eyesOpenMapping.test.js
> +    expect(coreConfig).to.be.deep.equal(expected);
This can be written like this: `expect(coreConfig).to.eql(expected);` (eql is like .deep.equal).

2022-03-19 23:58 UTC, SophieDePaula commented on packages/eyes-cypress/test/unit/plugin/config.test.js
> +    expect(config.batch.id).not.undefined;
So I'm sticking with the shorter way

2022-03-20 00:27 UTC, SophieDePaula commented on packages/eyes-cypress/test/unit/browser/eyesOpenMapping.test.js
> +      batch: {id: undefined, name: undefined, sequenceName: undefined},
That's right, the batchId will always have a value. In regards to `name` and `sequenceName`, I now delete the property from the object in case it's undefined.
I updated the test accordingly.

2022-03-22 20:16 UTC, amitzur approved these changes

2022-03-22 20:21 UTC, merged