Support data urls in iframes
applitools/eyes.sdk.javascript1 pull request #855
Opened 2022-04-11 02:43 UTC by amitzur

[Trello](https://trello.com/c/XfWUEGRS)

The issue was a tricky one, but the solution is only 3 lines of code.

When there is a data url iframe in a page, e.g. `<iframe src="data:text/html,<img src='something.png'/>"></iframe>`, then this iframe is considered cross origin. This is because, well, it's really cross origin (its [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin) is different than the host document), and we detect this by seeing that `frameEl.contentDocument` is null ([here](https://github.com/applitools/dom-scripts/blob/ff5f7ce837d23976a28f939deceb9e6890c53978/packages/dom-shared/src/browser/isAccessibleFrame.js#L5)).

So far there's no problem. Because we handle cross origin iframes. But the issue happens when we switch to this frame and take its dom snapshot. The URL we get for the frame is `data:text/html,...` which is a correct value "on paper". **But** this URL would be used in the resource mapping for UFG, as the key for the frame's contents resource. And that's bad.

*(This is the mechanism for frames in the UFG - we upload the frame's contents (dom and resource mapping) **as a resource**, and then include that resource in the general resource mapping of the page. What URL do we use? the frame's `src` usually. Unless it's special cases, **like data urls**. It doesn't really matter what the URL is. As long as the resource is mapped.)*

The UFG doesn't like data urls as keys in resource maps, and righteously so. See this (`vg-cli view-rendering UAujt6tHnEKUivQXIz7G6A~~/8e123795-3f58-4c1d-a644-71e5d682fa1c`):
![Screenshot from 2022-04-11 05-32-37](https://user-images.githubusercontent.com/394320/162656022-8d19ffeb-e559-4991-acb8-13b6a89b4b8e.png)

What we would like to have is this (`vg-cli view-rendering UAujt6tHnEKUivQXIz7G6A~~/2b8b54db-36fe-4631-ba1d-5fde1e96eba9`):
![Screenshot from 2022-04-11 05-33-47](https://user-images.githubusercontent.com/394320/162656165-5fbdaf4d-72d1-4605-8f35-f3da3257a0a3.png)

There are 2 new tests here:
1. unit test for takeDomSnapshot with a mock of a page with data url iframe.
2. e2e test that shows this solution works (see this result - baseline is with the fix, and checkpoint is without the fix: https://eyes.applitools.com/app/test-results/00000251752657141257/00000251752657141101/steps/1?accountId=UAujt6tHnEKUivQXIz7G6A~~&mode=step-editor)

2022-04-11 06:56 UTC, chaim-aharonson-applitools commented
@amitzur cool !!!
The original ticket mentioned 'HTML' (not 'IMG') as the iframe src:  
`<iframe src="data:text/html,<html><body><img style='width:170px;height:250px;' src='${location.origin}/smurfs.jpg'></body></html>"></iframe>`
Additionally, it appears as **encoded** in ticket, something like:
`<iframe src="data:text/html;charset=utf-8,%3Chtml%3E%3Cbody%3E%3Cimg%20style='width:170px;height:250px;'%20src='${location.origin}/smurfs.jpg'%3E%3C/body%3E%3C/html%3E"></iframe>`
**Glad to say that I tested both with your code and it works** :-)
So, _with your permission_, I added another test for data url as encoded html and moved the test html files to 'fixtures/frames' directory

2022-04-11 07:27 UTC, amitzur commented
@chaim-aharonson-applitools I don't think that makes a difference, but it's always good to validate as much a possible the actual issue we intend to solve. So great!
I'll ship this later today once @SophieDePaula and @tourdedave take a look

2022-04-11 13:28 UTC, tourdedave requested changes
Nice!

A couple of small tweaks requested.

2022-04-11 13:28 UTC, tourdedave commented on pending-changes.yaml
> +    - Support data urls in iframes
There should be an entry for eyes-universal too, no?

2022-04-11 13:28 UTC, tourdedave commented on packages/eyes-sdk-core/test/e2e/check.e2e.spec.js
> +describe('check e2e', () => {
I've actually been relying on this file as a starting point for authoring new tests or debugging issues reported in the universal-server. Can we keep it or add this test as a new file with a more descriptive name?

2022-04-11 20:54 UTC, SophieDePaula approved these changes
:100:

2022-04-12 06:25 UTC, chaim-aharonson-applitools commented on pending-changes.yaml
> +    - Support data urls in iframes
@tourdedave 
Sure, it's me :-)

2022-04-12 17:55 UTC, amitzur commented on pending-changes.yaml
> +    - Support data urls in iframes
yes, thanks

2022-04-12 17:57 UTC, amitzur commented on packages/eyes-sdk-core/test/e2e/check.e2e.spec.js
> +describe('check e2e', () => {
:+1:

2022-04-12 21:07 UTC, tourdedave approved these changes

2022-04-13 05:04 UTC, amitzur commented
@tourdedave I made the requested changes. Merging.

2022-04-13 05:04 UTC, merged

2022-04-13 05:08 UTC, amitzur commented on pending-changes.yaml
> +    - Support data urls in iframes
And also:
1. storybook
2. cypress
3. wdio5-service

I'm adding that post-merge directly to master.
The original ticket was for storybook

2022-04-13 05:09 UTC, amitzur commented on pending-changes.yaml
> +    - Support data urls in iframes
@benbabayoff8 I merged before getting your approval. Please see this entry