Native viewport size
applitools/eyes.sdk.javascript1 pull request #857
Opened 2022-04-12 10:18 UTC by chaim-aharonson-applitools

add geometry.ceil for region

2022-04-13 06:58 UTC, amitzur requested changes

2022-04-13 06:58 UTC, amitzur commented on packages/driver/src/driver.ts
> +    const envUniversalConfig = process.env.UNIVERSAL_VIEWPORT_SIZE_CALCULATION
let's call this `useCeilForViewportSize` and make it be passed in config for `manager.openEyes` and then propagated to driver

2022-04-13 06:58 UTC, amitzur commented on packages/driver/src/driver.ts
> +        //if (viewportSizeCalculation && typeof utils.geometry[viewportSizeCalculation] === 'function') {
Not recommended, this is harder to track and find in the code. It's just being "smart" :)
I'd prefer it to be
```
if (this.useCeilForViewprotSize) {
...
} else {
...
}
```

2022-04-13 06:58 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeVHSes.js
> +      url: serverUrl || '',
why not `serverUrl`? No biggy, I just think it's better if we use the same terminology with the NMG team

2022-04-13 06:58 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeVHSes.js
> +    if (proxyObject) {
what about username and password? and `isHttpOnly`?
I spoke with Roy about them supporting it

2022-04-13 06:58 UTC, amitzur commented on packages/types/src/data.ts
> +  wrapperType?: string
what is this?

2022-04-13 06:58 UTC, amitzur commented on pending-changes.yaml
> +    - Internal 'takeVHSes' extend the sent data
Support passing `serverUrl` and `proxy` to VHS.

2022-04-13 06:58 UTC, amitzur commented on pending-changes.yaml
> +    - Native viewport size calculation changed from round to ceil
Use `Math.ceil` instead of `Math.round` for viewportSize calculation when passed `useCeilForViewportSize:true`

2022-04-13 06:58 UTC, amitzur commented on packages/utils/src/geometry.ts
> +    result.x = Math.round(target.x)
Oh, this is very confusing. I realize it might make sense, but from first look it's unexpected.
Not sure what to do about it.
Oh well...
I would add a comment here saying:
> intentionally using Math.round and not Math.ceil here, because the point is that for width and height it makes sense to use ceil, but not for x and y

2022-04-13 10:44 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeVHSes.js
> +      logger.log('apiKeyInput was skipped')
Use the term `UFG_Apikey` instead of `apiKeyInput`, to be consistent with the other places in this file which throw exception.

2022-04-13 12:00 UTC, chaim-aharonson-applitools commented on packages/eyes-sdk-core/lib/utils/takeVHSes.js
> +      logger.log('apiKeyInput was skipped')
done

2022-04-13 12:01 UTC, chaim-aharonson-applitools commented on packages/utils/src/geometry.ts
> +    result.x = Math.round(target.x)
done

2022-04-13 13:13 UTC, amitzur approved these changes
See inline comments. But generally it's approved.

2022-04-13 13:13 UTC, amitzur commented on packages/driver/src/driver.ts
> +    this._customConfig = options.customConfig || {}
you can do this with a default value in the parameter list

2022-04-13 13:13 UTC, amitzur commented on packages/eyes-api/src/input/Configuration.ts
> +  /** @undocumented */
no need for changes in eyes-api at all

2022-04-13 13:13 UTC, amitzur commented on packages/eyes-sdk-core/lib/utils/takeVHSes.js
> +    const UFG_Apikey = await context.element({type: 'accessibility id', selector: 'UFG_Apikey'})
I didn't mean the variable name in my previous comment. I meant the message to the log. No biggy.

2022-04-13 13:13 UTC, amitzur commented on packages/eyes-sdk-core/test/e2e/universal-overrides.e2e.spec.js
> +  process.env.UNIVERSAL_VIEWPORT_SIZE_CALCULATION = true
you can remove this test

2022-04-14 05:19 UTC, amitzur approved these changes

2022-04-14 17:28 UTC, merged