fix capturing window and region screenshots in android native landscape
applitools/eyes.sdk.javascript1 pull request #858
Opened 2022-04-12 22:24 UTC by SophieDePaula

This PR attempts to solve the issues that were raised in [this Trello card](https://trello.com/c/Xsv4v0UK/1303-android-native-landscape-unable-to-check)

I found two main problems that caused the error we see in the Trello card above:

1) We crop out the button navigation bar, however, in landscape mode, we need to crop it from the left.
2) We use `Appium` API to get the dimensions of the system bars, however, I see that this API is buggy and in landscape mode, it returns the wrong value, therefore, I check if we are in landscape mode, then I flip to portrait to get the correct dimensions and then flip back to landscape.

As a result of this change, I also had to make adjustment to `normalizeRegion` in `driver` to adjust `x` offest in case we are in landscape mode.

### TODO
- [ ] check if all test pass on the packages that were changed ( `driver`, `screenshoter` `spec-driver-selenium`)
- [ ] write tests

2022-04-12 23:12 UTC, SophieDePaula commented on pending-changes.yaml
> +    - native android, when fetching the dimensions of system bars in landscape mode, webdriver returns the wrong deminetion, to workaround it, we now flip to portrait to capture these demiensions and
@benbabayoff8 let me know if you think the comment about the dimensions is unnecessary for the user. I wasn't sure.

2022-04-13 06:33 UTC, amitzur requested changes
I think this is very good.
A bit concerned about the orientation flip, but I have no other suggestion.
Just a few minor changes requested

2022-04-13 06:33 UTC, amitzur commented on packages/spec-driver-selenium/src/spec-driver.ts
> +async function setOrientation(driver: Driver, orientation: string) {
type of `orientation` parameter should be `'PORTRAIT' | 'LANDSCAPE'` and there should be a default value of `PORTRAIT` IMO.

2022-04-13 06:33 UTC, amitzur commented on packages/spec-driver-selenium/src/spec-driver.ts
> +  if (orientation.toLocaleLowerCase() === 'landscape') {
`toLowerCase` is just fine :) we're not handling special chars here

2022-04-13 06:33 UTC, amitzur commented on pending-changes.yaml
> +    - native android, in case we test a device in ladscape mode, make sure to account for the navigation bar on the left and not at the button of the image.
My suggestion + a few typo fixes:
When running a native app on Android, in case we test a device in landscape mode, make sure to account for the navigation bar on the left and not at the bottom of the image. Also account for an Appium bug when calculating system bars height.

2022-04-13 06:33 UTC, amitzur commented on pending-changes.yaml
> +    - native android, when fetching the dimensions of system bars in landscape mode, webdriver returns the wrong deminetion, to workaround it, we now flip to portrait to capture these demiensions and
see my suggestion above

2022-04-13 06:33 UTC, amitzur commented on pending-changes.yaml
> +    - native iOS, allow capturing NavigationBar and TabBar regions
Guideline is to use proper capitalization and grammar as much as possible.

2022-04-13 07:24 UTC, benbabayoff8 commented
@amitzur @SophieDePaula I wouldn't describe the "how" part (that we flip and flip back).
Only what is the scenario and that it is improved/fixed.

2022-04-13 20:12 UTC, SophieDePaula commented on pending-changes.yaml
> +    - native iOS, allow capturing NavigationBar and TabBar regions
@amitzur I am not entirely sure what I need to change here.
I changed `Native` to `native` as I see all the other comments start with lowercase.

2022-04-13 20:19 UTC, SophieDePaula commented on pending-changes.yaml
> +    - native iOS, allow capturing NavigationBar and TabBar regions
I updated this entry, hopefully, this was your intention.

2022-04-13 20:20 UTC, SophieDePaula commented on packages/spec-driver-selenium/src/spec-driver.ts
> +async function setOrientation(driver: Driver, orientation: string) {
I used `ScreenOrientation` type under `types`, I didn't set any default value to this type as it's probably used in other places.

2022-04-13 20:27 UTC, merged