change exception property in testResultsSummary to be of type TestResultsException
applitools/eyes.sdk.javascript1 pull request #878
Opened 2022-04-25 16:42 UTC by SophieDePaula

[Trello](https://trello.com/c/WV7ixoDy/1325-universal-sdk-runtime-errors-in-closemanager-results-returned-as-empty-dicts)

Then property `exception` in testResultsSummary is of type `Error` and therefore the content of this object is lost when sending it in the response to the universal clients.

I created a new type `TestResultsException` that contains only `stack` and `message` properties as `strings` so resolve that.

2022-04-25 19:43 UTC, SophieDePaula commented on packages/eyes-universal/src/socket.ts
>        }
@kyryloonufriiev I see that in `eyes-selenium-universal` we need to map `reason` property value on the [receiving `socket` as well](https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-selenium-universal/src/socket.ts#L95).
Do you think that this is something we need to add to our [docs](https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-universal/README.md#eyesmanagerclosemanager)?

2022-04-25 23:30 UTC, SophieDePaula commented on pending-changes.yaml
> +     exception in TestResultsSummary now should be accepted properly by universal clients, and we now also map `reason` when emitting an error for Eyes exceptions.
@benbabayoff8 fyi

2022-04-25 23:39 UTC, SophieDePaula commented
adjusted [this](https://github.com/applitools/sdk.coverage.tests/pull/150) generic test to make sure we get the relevant exception in `TestResultsSummary`

2022-04-26 19:03 UTC, tourdedave requested changes
Looks great! Just a small tweak to the test in `eyes-selenium-universal`

2022-04-26 22:20 UTC, SophieDePaula commented on packages/eyes-selenium-universal/test/play/play.js
> +describe('play', () => {
good idea!

2022-04-27 06:06 UTC, amitzur commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +          else return {exception: results ? {stack: results.stack, message: results.message} : null}
In the previous line we verify `results.info`. So you can be sure that in this line `results` is defined.

2022-04-27 06:09 UTC, amitzur commented on packages/eyes-api/src/output/TestResultContainer.ts
> +  get exception(): types.TestResultsException {
Isn't this PR an internal detail? Why should it propagate to the user? This is essentially a breaking change. In `eyes-api` we should still hold an Error

2022-04-27 06:11 UTC, amitzur commented on packages/types/src/data.ts
> +export type TestResultsException = {stack?: string; message?: string}
Should these fields really be optional?

2022-04-27 20:48 UTC, SophieDePaula commented on packages/eyes-api/src/output/TestResultContainer.ts
> +  get exception(): types.TestResultsException {
@amitzur I can undo the type changes from here are `data.ts` in `types`, but isn't it a misrepresentation of the type we use in `TestResultContainer`?

2022-05-10 06:37 UTC, amitzur commented on packages/eyes-api/src/output/TestResultContainer.ts
> +  get exception(): types.TestResultsException {
@SophieDePaula Here's what I mean:
Currently the user API is like this - `summary.getAllResults()[0].exception` is an Error instance (if there was an exception).
This means our users know they can do the following:
```
const summary = await runner.getAllTestResults()
const err = summary.getAllResults()[0].exception
if (err instanceof Error) {
  // handle error
}
```
I'm not saying this is the encouraged way to write user code, but **it works**.

What you do in this PR is change the Error to be a plain object. That's a breaking change. So either you knowingly do this and then ask for approval from Product, or you avoid doing it.

Once you realize you don't want to break the user API, you have an anchor - TestResultContainer in eyes-api should have an `Error` instance and nothing else.
The requirement is that in universal the exception field should be serializable. Then this means that either (a) core should not return an Error instance, since it would pass as an empty object in the websocket, or (b) core should still return an Error instance, but the universal-server should serialize it.
I would go with (a) which is what you chose as well. But then you must create an Error instance out of this object on the eyes-api side.
Another way to do it is have a property of `originalError` on the plain object. It would probably not serialize for the universal, but it could serve as an API between core and eyes-api, so that eyes-api would take the `originalError` into the `exception` field of `TestResultContainer` (instead of creating a new one).

2022-05-10 22:55 UTC, SophieDePaula commented on packages/eyes-api/src/output/TestResultContainer.ts
> +  get exception(): types.TestResultsException {
@amitzur universal users are also getting the same `summary` object so I won't be able to keep the type of `exception` in `TestResultContainer` and fix this problem. Therefore I actually think option `b` is the only option we can go with here.
Regarding serialization, it seems that the only place to do it is in `socket.ts`. Let me know what you think.

2022-05-11 07:25 UTC, kyryloonufriiev requested changes
I don't agree with the approach that was chosen here. This will brake cores behavior just to solve serialization problems in a different package. I think the right approach would be to wrap an error with a class with the `.toJSON()` method. Since all of the errors we expect to have are already custom errors it means that we can just add a method to the `EyesError`/`TestFailedError` implementation.

2022-05-11 07:25 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js
> +          const exception = testResults ? null : {stack: result.stack, message: result.message}
I don't think this is right because later we are trying to throw this exception. And this is just wrong to throw something that is not an instance of Error.

2022-05-11 07:25 UTC, kyryloonufriiev commented on packages/types/src/data.ts
> +export type TestResultsException = {stack?: string; message?: string}
Errors name doesn't make sense, there is nothing about tests or results. It is basically just a normal js error type - https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts#L972-L976.

2022-05-13 22:52 UTC, SophieDePaula commented
@kyryloonufriiev I created a new type `SerializedError` which has `toJSON` method and extends `Error` and reverted back the changes I did.
Lmk what you think.
@amitzur fyi

2022-05-16 12:59 UTC, kyryloonufriiev requested changes

2022-05-16 12:59 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +          else return {exception: new SerializedError(results)}
hmmm. Tell me if I'm wrong, we will find ourselves at this line of code only if the error is not an ordinary error object, but the one extended from EyesError. If this is true, isn't it easier to add `toJSON` method to the already created error?

2022-05-16 17:20 UTC, SophieDePaula commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +          else return {exception: new SerializedError(results)}
@kyryloonufriiev from what I understand this could be any error that is thrown from `close`.

2022-05-16 18:31 UTC, SophieDePaula commented on packages/types/src/data.ts
> +}
I removed this type.

2022-05-16 18:32 UTC, SophieDePaula commented on packages/eyes-api/src/errors/SerializedError.ts
> +export class SerializedError extends Error {
Yes, that's correct, I removed this form `eyes-api` and kept it only in `core`.

2022-05-18 06:05 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +          else return {exception: new SerializedError(results)}
Ah, ok I see. We have a completely different logic in `EyesVisualGrid`. Then I think you are right errors should be wrapped, but only those which are not `EyesError`'s. I also believe that the better place to do it would be `closeManager`.

2022-05-19 16:26 UTC, SophieDePaula commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +          else return {exception: new SerializedError(results)}
@kyryloonufriiev `exception` is `readonly` so I had to do it in `EyesVisualGrid` and `EyesClassic`

2022-05-20 05:24 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/sdk/EyesClassic.js
> +          else return {exception: new SerializedError(results)}
I think you didn't understand what I meant. In closeManager you will have access to all the same data. The fact that something is readonly in types is irrelevant, because you can do whatever you want at this point.

2022-05-20 22:12 UTC, SophieDePaula commented on packages/eyes-sdk-core/lib/new/close-manager.js
> +        container.exception = new SerializedError(container.exception)
@kyryloonufriiev I took your advice and now I cast `exception` here. Lmk what you think.

2022-05-23 19:49 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/errors/EyesError.js
> +    return utils.general.toJSON({message: this.message, stack: this.stack, reason: this.reason, info: this.info})
Why do we need `utils.general.toJSON`?

2022-05-23 19:54 UTC, kyryloonufriiev commented on packages/eyes-sdk-core/lib/new/close-manager.js
>        }
Why not?

```
if (throwErr && container.exception) throw exception
```

2022-05-23 19:56 UTC, kyryloonufriiev approved these changes
Looks good. You can merge it. Also this is another card you probably fixed with this PR - https://trello.com/c/wvosVkhj

2022-05-24 22:31 UTC, merged