Cypress -support element as target region
applitools/eyes.sdk.javascript1 pull request #902
Opened 2022-05-12 22:35 UTC by SophieDePaula

2022-05-15 18:10 UTC, kyryloonufriiev commented on packages/eyes-cypress/src/browser/eyesCheckMapping.js
> +          region: {selector: config.element.selector},
isn't there a case when an element doesn't have a selector?

2022-05-17 23:08 UTC, SophieDePaula commented
@amitzur , @kyryloonufriiev this is ready for review

2022-05-18 04:32 UTC, amitzur commented on pending-changes.yaml
> +    - add support to send elements as Target, ignore, floating, accessability and match regions.
My proposal:

`cy.eyesCheckWindow` now supports passing DOM elements and jQuery objects (which are the result value of `cy.get` and similar Cypress DOM queries) for target and regions (ignore, floating, accessibility, and match regions).

Happy to hear feedback @SophieDePaula @benbabayoff8

2022-05-18 05:34 UTC, kyryloonufriiev requested changes
I'm glad you decide to go with a ref representation of elements instead of selectors. I think the next step should be to decide with which one of the two (native and jQ) supported element types you want to work with. I think it should be native elements, so in the very beginning, you will convert jQ objects to normal dom and continue wor from there. I suggest this [jQuery#toArray()](https://api.jquery.com/toArray/#toArray).

2022-05-18 05:34 UTC, kyryloonufriiev commented on packages/eyes-cypress/src/browser/eyesCheckMapping.js
> +      } else if (region.constructor.name === 'jQuery') {
What if I did `jQuery([1,2,3,4])`? This also will have constructor name `jQuery`.

2022-05-18 05:46 UTC, amitzur commented
@SophieDePaula I'm going to push a few changes to reflect my thoughts, and to avoid some ping-pong in the review. I'll indicate what I've done

2022-05-18 06:11 UTC, kyryloonufriiev commented on packages/eyes-cypress/src/browser/eyesCheckMapping.js
> +  return element.nodeType && element.nodeType === Node.ELEMENT_NODE;
Ah, nice observation.

2022-05-18 06:19 UTC, amitzur requested changes
1. This is the first time I notice the custom coverage tests code style. Check out my changes in `ShouldSendAccessibilityRegionsByDomElementWithVg.spec.js`. We can change the existing tests in another PR, but I'd like the new tests to be written like that for simplicity. No reason to copy the code style of emitted code. They are over complicated because it's generated code.
Specifically:
  - not using `assert` since there's no need, and also **this is code in the browser**. Cypress already provides assertions, and there is no builtin `assert` module in the browser.
  - accessing properties not as string accessors.
  - add display name to test
  - map jQuery using `.toArray` and not specifying each element manually.

3. Why are tests for ignore regions separate from the tests for accessibility and floating? You are also not checking the output of the regions in those tests.

4. If I understand correctly, you noticed that we were missing support for accessibility regions by coordinates and fixed it. So please add a test for that.

5. I reorganized `eyesCheckMapping`.
  - The default of `{}` now sits at the top in the custom command. That makes it easier to reason about. 
  - No need for the inner function `toCheckWindowConfiguration`
  - Change logic to detect HTMLElement and jQuery
  - Change `.map` to `for/of` loop. Don't use `map` if you are not mapping.


Lastly, I don't know if you noticed, but `cy.get` returns elements inside iframe. That was surprising to me. But it works! See the accessibility test that I changed - the first region is actually an element inside iframe

2022-05-18 15:25 UTC, SophieDePaula commented on packages/eyes-cypress/src/browser/commands.js
> +const {makeEyesCheckMapping} = require('./eyesCheckMapping');
@amitzur I was doing that to not sent the refer for every `check` call, but only once at the beginning of the file.

2022-05-18 15:34 UTC, SophieDePaula commented on pending-changes.yaml
> +    - add support to send elements as Target, ignore, floating, accessability and match regions.
@amitzur I think it's great, I would only leave out `(which are the result value of cy.get and similar Cypress DOM queries)` as I feel it's a bit too long, and also we have examples in the `README`

2022-05-18 15:59 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - add support to send elements as Target, ignore, floating, accessability and match regions.
Agree with Sophie. I'd recommend: "cy.eyesCheckWindow now supports passing DOM elements and jQuery object for target and regions". We will explain further in the ReadMe

2022-05-19 09:45 UTC, amitzur commented on packages/eyes-cypress/README.md
> +Pass an element as the target
@SophieDePaula this is misplaced. I will make the necessary changes

2022-05-19 09:45 UTC, amitzur commented on packages/eyes-cypress/README.md
> +Pass an element as the target
@SophieDePaula this is misplaced. I will make the necessary changes

2022-05-19 10:05 UTC, amitzur commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/region.js
> +  it('region by JQuery element', () => {
So you kept these tests even though you wrote new ones?

2022-05-19 10:05 UTC, amitzur commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/region.js
> +  it('region by JQuery element', () => {
So you kept these tests even though you wrote new ones?

2022-05-19 10:05 UTC, amitzur commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/region.js
> +  it('region by JQuery element', () => {
@SophieDePaula :point_up:

2022-05-19 10:05 UTC, amitzur commented on packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/region.js
> +  it('region by JQuery element', () => {
@SophieDePaula :point_up:

2022-05-19 20:26 UTC, merged