Storybook play
applitools/eyes.sdk.javascript1 pull request #913
Opened 2022-05-19 08:56 UTC by chaim-aharonson-applitools

2022-05-19 09:17 UTC, amitzur requested changes
The test should also run as part of `test:e2e`. See all the other e2e tests for reference

2022-05-19 09:17 UTC, amitzur commented on packages/eyes-storybook/dist/getClientAPI.js
> +        setTimeout(() => callback(), 0);
setTimeout(callback, 0)

2022-05-19 09:17 UTC, amitzur commented on packages/eyes-storybook/dist/getClientAPI.js
> +              /*  onStoryRendered: callback => {
remove comment

2022-05-19 09:17 UTC, amitzur commented on packages/eyes-storybook/test/e2e/happy-config/single-with-play.config.js
> +  appName: 'Multi browser version',
Irrelevant app name

2022-05-19 09:17 UTC, amitzur commented on packages/eyes-storybook/test/e2e/happy-config/single-with-play.config.js
> +    {width: 640, height: 480, name: 'chrome-one-version-back'},
no need for complicated browser info IMO. Just 2 browsers, chrome latest on 2 viewport sizes is good enough.

2022-05-19 09:17 UTC, amitzur commented on pending-changes.yaml
> +    - add support for `storybook play interaction`
@benbabayoff8 please review

2022-05-19 09:24 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/dist/getClientAPI.js
> +        setTimeout(() => callback(), 0);
done

2022-05-19 09:24 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/dist/getClientAPI.js
> +              /*  onStoryRendered: callback => {
done

2022-05-19 09:26 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/e2e/happy-config/single-with-play.config.js
> +  appName: 'Multi browser version',
fixed

2022-05-23 03:33 UTC, amitzur requested changes
See comments inline.

General notes:
1. I think you didn't notice but I wrote in the card the following versions:
- test/fixtures/storybook-versions/4.1.18
- test/fixtures/storybook-versions/5.3.21
- test/fixtures/storybook-versions/6.3.12
- test/fixtures/storybook-versions/latest
- test/fixtures/storybook-versions/next

Since those are the latest versions of those major/minor versions. So I would prefer to test on those. Unless you think it's needless.

2. I get diffs when running `STORYBOOK_VERSION="6.4.0" moca test/e2e/storybook-csf.e2e.test.js`: https://eyes.applitools.com/app/test-results/00000251749024326771/?accountId=UAujt6tHnEKUivQXIz7G6A~~
Does the string with the storybook version need to appear there or not?

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/fixtures/storybookCSF/stories/LoginFormForOldVersions.js
> +storiesOf('Login', module).add('EmptyForm', () => <LoginForm sbVersion={process.env.STORYBOOK_VERSION}/>);
why do we need the old version under the CSF format?

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/snapshots/storybook-csf.e2e.test.json
> +{
Please run the test without `showLogs` so that the expected output doesn't contain the verbose log

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/happy-config/storybook-csf.config.js
> +if (!process.env.STORYBOOK_VERSION) {
This condition already appears in the test. Is it needed to be written twice?

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    getConfigFilesListByVersion(storybookVersion).forEach(function(fileName) {
prefer `for (const ... of ...)` over `.forEach`

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    closeStorybook = await testStorybook({
This is not needed. If you copied it from `layout-breakpoints` or `wait-before-capture` then it's wrong there too. I just noticed it now.
The reason is - `eyes-storybook` already starts its own storybook (that's what your test is all about). Running a storybook externally is useful only if you provide a `storybookUrl` to `eyes-storybook`. Then `eyes-storybook` doesn't start its own storybook, but rather uses the url provided.

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    delete process.env.STORYBOOK_VERSION;
Why is this needed? It looks like a mistake. What about the day we want to run another test with a specific storybook version?

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/package.json
> +    "storybook:csf": "start-storybook -c test/fixtures/storybookCSF/.storybook -p 9001",
this will now fail because of the double `config.js`/`main.js` files

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    /* .replace(/Total time\: \d+ seconds/, 'Total time: <some_time> seconds')
This will be needed. You will see it if you run without `APPLITOOLS_SHOW_LOGS`

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +// SB older versions (aka: 5.0.0) expect to have 'config.js' as the config file,
Good observation.

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    await pexec(`npm install`, {
It still might be a long operation even if node_modules are installed.
Preferably we would do this in a `beforeAll` global mocha hook (via a mocharc file)

2022-05-23 03:33 UTC, amitzur commented on packages/eyes-storybook/src/cli.js
> +    const packagePath = process.env.STORYBOOK_VERSION
I didn't mean to do this. When I wrote in the card:
> Actually, packagePath is undocumented and I found it just by looking at the code and trying to see if it's possible to run eyes-storybook and provide a specific path to start-storybook.

What I meant was we don't need to do any changes in the code. You can provide the following in `storybook-csf.config.js` and it would work:
```
  packagePath: path.resolve(
    __dirname,
    `../../fixtures/storybook-versions/${process.env.STORYBOOK_VERSION}`,
  )
```

2022-05-23 06:08 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybook-versions/5.0.0/package.json
> +{
1. not sure it's critical but versions are changeable... 6.3.x does not support 'play' in case we change the versions, need to add 6.4.x as well
2. the diffs due to non approved new baseline (now approved)
3. removed some dependencies, everything works (crossing fingers)

2022-05-23 06:08 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybook-versions/6.0.0/package.json
> +    "@applitools/eyes-storybook": "^3.27.6",
removed

2022-05-23 06:08 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybook-versions/5.0.0/package.json
> +    "@applitools/eyes-storybook": "latest",
removed

2022-05-23 06:11 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybook-versions/6.4.0/package.json
> +    "@applitools/eyes-storybook": "latest",
removed

2022-05-23 06:11 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybook-versions/latest/package.json
> +    "@applitools/eyes-storybook": "latest",
removed

2022-05-23 06:12 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/package.json
> +    "storybook:csf": "start-storybook -c test/fixtures/storybookCSF/.storybook -p 9001",
I am aware to that, these are leftovers from prev version, checking whether it's fixable or should be removed

2022-05-23 06:14 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    /* .replace(/Total time\: \d+ seconds/, 'Total time: <some_time> seconds')
I'm aware to the importance of this, but how can it handle 5 different tests running on same .test file which should result a single 'snapshot .json' file?

2022-05-23 06:56 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybookCSF/stories/LoginFormForOldVersions.js
> +storiesOf('Login', module).add('EmptyForm', () => <LoginForm sbVersion={process.env.STORYBOOK_VERSION}/>);
these tests are a mixture, we wanted to test the `play` functionality and verify that old versions not getting any side effects due to the usage of `storyRendered` in our code, so it's not a CSF file but it does verify everything is working properly in spite of `storyRendered`

2022-05-23 06:59 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/e2e/happy-config/storybook-csf.config.js
> +if (!process.env.STORYBOOK_VERSION) {
it is needed twice to handle cases running the test directly, as the script in 'package.json' (which might be updated or removed), in case I find that one of the appearances is deprecated - I will remove

2022-05-23 07:28 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    getConfigFilesListByVersion(storybookVersion).forEach(function(fileName) {
done

2022-05-23 09:56 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    /* .replace(/Total time\: \d+ seconds/, 'Total time: <some_time> seconds')
done using `process.env.INIT_CWD` as the 'storybook-versions/<version_number>' directory and adding a property to package.json
`"snaptdout": {
    "snapshotsPrefix": "v_<version_number>_"
  }
  `

2022-05-23 09:56 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/e2e/storybook-csf.e2e.test.js
> +    await pexec(`npm install`, {
done

2022-05-23 09:59 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/package.json
> +    "storybook:csf": "start-storybook -c test/fixtures/storybookCSF/.storybook -p 9001",
fixed the the ability to run `storybook:csf` by adding a service script to handle

2022-05-26 07:53 UTC, merged