Storybook play gh actions
applitools/eyes.sdk.javascript1 pull request #920
Opened 2022-05-24 13:09 UTC by chaim-aharonson-applitools

2022-05-25 10:29 UTC, amitzur requested changes
1. There is a lot of seemingly unnecessary code here. See inline comments.
2. The config file `storybook-csf.config.js` doesn't have to be renamed. It's not a test file that requires the `.versions.js` suffix. Did you rename it intentionally?
3. Why do we need both 5.0.0 and 5.3.21?

2022-05-25 10:29 UTC, amitzur commented on packages/eyes-storybook/package.json
> +    "test:versions": "yarn build && yarn test:e2e:versions && yarn lint",
Not sure that I like it that it's not included in `yarn test`

2022-05-25 10:29 UTC, amitzur commented on packages/eyes-storybook/src/browser/getClientAPI.js
> +    if (addons && addons.channel && addons.channel.once) {
in what version is there no `addons.channel.once`?

2022-05-25 10:29 UTC, amitzur commented on packages/eyes-storybook/src/browser/getClientAPI.js
> +    } else {
I think there's no need for `setTimeout` if it's not from the `storyRendered` event.

2022-05-25 10:29 UTC, amitzur commented on packages/eyes-storybook/src/browser/getClientAPI.js
> +    if (typeof clientAPI.raw === 'function') {
You already have this information, there is no need for this function.

2022-05-25 10:29 UTC, amitzur commented on packages/eyes-storybook/src/renderStories.js
> +            hasPlayFunction: storyData.hasPlayFunction,
You should already have this on the `story` variable

2022-05-25 10:29 UTC, amitzur commented on packages/eyes-storybook/test/e2e/snapshots/v_5.3.21_storybook-csf.e2e.versions.test.json
> +    "Examples/Login: Empty Form [Chrome <browser_version>] [640x480] - \u001b[38;5;21mNew\u001b[39m",
The status should be `Passed`, not `New`.

2022-05-25 10:34 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/package.json
> +    "test:versions": "yarn build && yarn test:e2e:versions && yarn lint",
not including this is the 'hack' that allows us to run once on the node versions matrix without this test and then run on this test with the storybook versions matrix, both are included in `gh-action` for publishing Storybook

2022-05-25 10:45 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/src/browser/getClientAPI.js
> +    if (addons && addons.channel && addons.channel.once) {
Applitools defined versions as `v4` and `v5`, these are some of the failures I fixed last night

2022-05-25 10:46 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/src/browser/getClientAPI.js
> +    } else {
done

2022-05-25 10:54 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/e2e/snapshots/v_5.3.21_storybook-csf.e2e.versions.test.json
> +    "Examples/Login: Empty Form [Chrome <browser_version>] [640x480] - \u001b[38;5;21mNew\u001b[39m",
fixed

2022-05-25 11:36 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/src/renderStories.js
> +            hasPlayFunction: storyData.hasPlayFunction,
it has it now

2022-05-25 11:49 UTC, amitzur commented on .github/workflows/publish-storybook.yml
> +      max-parallel: 3
why only 3?

2022-05-25 11:51 UTC, amitzur commented on .github/workflows/publish-storybook.yml
> +        storybook-version: ["latest", "6.4.0", "6.0.0", "5.3.21", "5.0.0", "next"]
@chaim-aharonson-applitools in my note here https://trello.com/c/sVuN6MFM/25-support-storybook-play-function#comment-6289d24ba582692300f614a8

I proposed:
- 4.1.18
- 5.3.21
- 6.3.12
- latest
- next

Do you think otherwise?

2022-05-25 11:52 UTC, amitzur commented on .github/workflows/publish-storybook.yml
> +        storybook-version: ["latest", "6.4.0", "6.0.0", "5.3.21", "5.0.0", "next"]
So I propose `["4.1.8", "5.3.21", "6.3.12", "latest", "next"]`

2022-05-25 11:58 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybook-versions/5.0.0/.env
> +SKIP_PREFLIGHT_CHECK=true
once running locally each storybook-version, the compiler detects there is a newer version of X in root of the project and refuses to continue, this file prevents this issue

2022-05-25 12:02 UTC, chaim-aharonson-applitools commented on .github/workflows/publish-storybook.yml
> +      max-parallel: 3
3 is what there was for 'normal' tests of Storybook, I assumed it was there for a reason, will change to the six version we currently support

2022-05-25 12:10 UTC, chaim-aharonson-applitools commented on .github/workflows/publish-storybook.yml
> +        storybook-version: ["latest", "6.4.0", "6.0.0", "5.3.21", "5.0.0", "next"]
I already responded in Slack, I believe that 6.4.0 is needed, it the version that 'play' is initially supported, 5.3.21 was is different from 5.0.0 and both are different from 4.0.0  (in various ways)
I will add 4.1.18 although it's more irrelevant for the scenarios of 'play' then 5.0.0 is, but.. it should support the event of 'onStoryRendered'

2022-05-25 12:14 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/test/fixtures/storybook-versions/6.0.0/package.json
> +    "storybook": "STORYBOOK_VERSION=6.0.0 start-storybook -p 9010 -s public",
it's relevant fir running locally by version, I used that during the development

2022-05-25 12:14 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/src/browser/getClientAPI.js
> +    if (typeof clientAPI.raw === 'function') {
removed

2022-05-25 21:17 UTC, amitzur commented on packages/eyes-storybook/package.json
> +    "test:versions": "yarn build && yarn test:e2e:versions && yarn lint",
You answered on an inline comment for the entire review. Took me a few seconds to realize that.

I'll address:
> - Not including this in yarn test is the 'hack' that allows us to run once on the node versions matrix without this test and then run on this test with the storybook versions matrix, both are included in gh-action for publishing Storybook.
> - I renamed to file storybook-csf.config.js to keep the consistency with .versions, these 'config' and 'test' should run separately, this will also work for any future tests which should be tested with several storybook versions

The fact that they run separately now is just temporary. I would ideally like `yarn test` to run on all storybook versions. I wrote it here: https://trello.com/c/sVuN6MFM/25-support-storybook-play-function#comment-6289d24ba582692300f614a8

> There is a different between 5.0 and 5.3: 5.0 uses the old convention of config.js as the configuration but 5.3 uses the advanced option: main.js and preview.js

Ah, good that we notice it. Then it does make sense. But I think once you make version 4 work, then you won't need 5.0.0.

2022-05-25 21:20 UTC, amitzur commented on packages/eyes-storybook/test/fixtures/storybook-versions/5.0.0/.env
> +SKIP_PREFLIGHT_CHECK=true
oh, nice!

2022-05-25 21:22 UTC, amitzur commented on .github/workflows/publish-storybook.yml
> +      max-parallel: 3
it was 3 because we run on 3 Node.js versions

2022-05-25 21:24 UTC, amitzur commented on .github/workflows/publish-storybook.yml
> +        storybook-version: ["latest", "6.4.0", "6.0.0", "5.3.21", "5.0.0", "next"]
I don't correlate what Slack message you are referring to.
I don't think 6.4.0 is important on its own. Because you already test 6.5.x when you do latest. When they release 7 then we will keep the latest 6. Sounds good?

2022-05-25 21:31 UTC, amitzur commented on packages/eyes-storybook/README.md
> +Since version 3.27.7, there is a support for Storybooks’ Interactions Play functionality: Stories who use ‘Play’, screenshot will be taken _automatically_ after the ‘Play’ flow is done.
@chaim-aharonson-applitools can you fix the quotes to be normal characters?

2022-05-25 21:32 UTC, amitzur commented on packages/eyes-storybook/README.md
> +<https://storybook.js.org/docs/react/essentials/interactions>
@chaim-aharonson-applitools no need for the `<>`

2022-05-25 21:35 UTC, amitzur commented on packages/eyes-storybook/dist/getStories.js
> +        const hasPlayFunction = !!(
@chaim-aharonson-applitools no reason for `!!`. The `&&` already makes it a boolean.

2022-05-25 21:39 UTC, amitzur commented on packages/eyes-storybook/src/browser/getStories.js
> +        hasPlayFunction,
@chaim-aharonson-applitools exactly what I meant

2022-05-25 21:39 UTC, amitzur commented on packages/eyes-storybook/src/renderStory.js
> +    const {name, kind, parameters, hasPlayFunction = false} = story;
@chaim-aharonson-applitools no need to initialize to `false`.

2022-05-25 21:41 UTC, amitzur commented on packages/eyes-storybook/src/renderStory.js
> +      storyProperties.push({name: 'Storybook play function', value: hasPlayFunction});
@chaim-aharonson-applitools I assume that it works. But basically the value should be a string so I would just write here `'true'`

2022-05-26 06:18 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/README.md
> +<https://storybook.js.org/docs/react/essentials/interactions>
fixed

2022-05-26 06:21 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/README.md
> +Since version 3.27.7, there is a support for Storybooks’ Interactions Play functionality: Stories who use ‘Play’, screenshot will be taken _automatically_ after the ‘Play’ flow is done.
done

2022-05-26 06:26 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/dist/getStories.js
> +        const hasPlayFunction = !!(
try this:
`x = {a:'1',b:'2'}`
then
`console.log(x && x.b)`
result will be '**2**' and not true.
Am I wrong?

2022-05-26 06:34 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/dist/getStories.js
> +          story.originalStoryFn &&
I guess it is two ways for same reference, can't say it's redundant for 100%... but will remove it

2022-05-26 06:36 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/src/renderStory.js
> +    const {name, kind, parameters, hasPlayFunction = false} = story;
done

2022-05-26 06:38 UTC, chaim-aharonson-applitools commented on packages/eyes-storybook/src/renderStory.js
> +      storyProperties.push({name: 'Storybook play function', value: hasPlayFunction});
it works. updated to be a string

2022-05-26 07:47 UTC, merged