user API addMobileDevice
applitools/eyes.sdk.javascript1 pull request #977
Opened 2022-06-20 16:18 UTC by chaim-aharonson-applitools

support addMobileDevice in user API
1. I was not sure whether 'visual-grid-client` should be updated as well, for example:
`visual-grid-client/src/sdk/getDeviceInfoFromBrowserConfig.js` (there are more cases in VGC)
2. in `Configuration.ts` line 1054, once replacing the 'any' with proper types: `AndroidVersion | IosVersion` it results an error in line 1060 regarding to `iosVersion` vs. `version` - is there another way to solve this besides what was done? 
3. idea regarding the place the test for this should be added?
I found this `/eyes-api/test/unit/enums.spec.ts` it tests the emulated devices and ios devices sizes, I might add one test here (need to add a new service/api as well) but it will not test 'addMobileDevice'

2022-06-20 19:32 UTC, kyryloonufriiev requested changes

2022-06-20 19:32 UTC, kyryloonufriiev commented on packages/eyes-api/src/input/Configuration.ts
> +import {AndroidDeviceName, AndroidVersion, IosDeviceName, IosVersion} from '..'
Use the actual file path instead of this. It creates circular dependencies

2022-06-21 07:03 UTC, chaim-aharonson-applitools commented on packages/eyes-api/src/input/Configuration.ts
> +import {AndroidDeviceName, AndroidVersion, IosDeviceName, IosVersion} from '..'
sure

2022-06-21 07:05 UTC, chaim-aharonson-applitools commented on packages/eyes-api/src/input/Configuration.ts
> +    version?: any,
this is exactly what I mentioned as the problem, did exactly that but got error, I will use your commit and will see if it still happens, maybe I missed something

2022-06-21 07:10 UTC, chaim-aharonson-applitools commented on packages/eyes-api/src/input/Configuration.ts
> +    screenOrientation: ScreenOrientation,
by the card I understood that `screenOrientation` is not optional, in case it is I think that default should be added (aka: portrait)

2022-06-21 07:20 UTC, kyryloonufriiev commented on packages/eyes-api/src/input/Configuration.ts
> +    version?: any,
Ah. Sorry. I didn't read your description just jump to the review. I will check it out

2022-06-21 07:22 UTC, kyryloonufriiev commented on packages/eyes-api/src/input/Configuration.ts
> +    screenOrientation: ScreenOrientation,
I don't think it is required, because it is not required in `AndroidDeviceInfo`. No need to pass default here, let the server or at least core decide what default should be.

2022-06-21 07:23 UTC, chaim-aharonson-applitools commented on packages/eyes-api/src/enums/AndroidDeviceName.ts
> +}
> I found this /eyes-api/test/unit/enums.spec.ts it tests the emulated devices and ios devices sizes, I might add one test here (need to add a new service/api as well) but it will not test 'addMobileDevice'
- this is what I asked... do you know how I may add script to be available like in: 'https://render-wus.applitools.com/emulated-devices'

2022-06-21 07:40 UTC, kyryloonufriiev commented on packages/eyes-api/src/enums/AndroidDeviceName.ts
> +}
Here is an endpoint for android devices
https://render-wus.applitools.com/public/android-devices, you should use this to test if 
the enum has all the values.

2022-06-21 08:01 UTC, chaim-aharonson-applitools commented
@benbabayoff8 please review the change-log record

2022-06-21 08:02 UTC, kyryloonufriiev commented on pending-changes.yaml
> +    - Support `addMobileDevice` in user API for NMG
This should go to every sdk that supports it. protractor, nightwatch, wdio service

2022-06-21 08:07 UTC, kyryloonufriiev commented on packages/eyes-api/src/enums/AndroidDeviceName.ts
> +  Galaxy_S20_PLUS = 'Galaxy S20 Plus',
I think this is something historical and we should be consistent since it is a new feature for us. I will talk to Ben.

2022-06-21 09:31 UTC, benbabayoff8 commented on pending-changes.yaml
> +    - Support `addMobileDevice` in user API for NMG
@kyryloonufriiev As far as I know we added this API only for WDIO at the moment, so the Changelog is correct. We shouldn't invest time on Protractor / Nightwatch for now.

2022-06-21 09:41 UTC, kyryloonufriiev commented on pending-changes.yaml
> +    - Support `addMobileDevice` in user API for NMG
No. We added API to every framework, even to the playwright and testcafe, but there is no reason to use it, so I'm not recommending adding it there. But in all other frameworks we can use it.

2022-06-21 09:42 UTC, kyryloonufriiev commented on pending-changes.yaml
> +    - Support `addMobileDevice` in user API for NMG
Not in puppeteer

2022-06-21 10:46 UTC, chaim-aharonson-applitools commented on packages/eyes-api/src/enums/AndroidDeviceName.ts
> +  Galaxy_S20_PLUS = 'Galaxy S20 Plus',
done

2022-06-21 10:51 UTC, kyryloonufriiev approved these changes
👍🏼

2022-06-21 10:53 UTC, merged