Update emit.js
applitools/eyes.sdk.javascript1 pull request #987
Opened 2022-06-22 11:50 UTC by chaim-aharonson-applitools

following CR, since there currently no consumers for `config.visualgrid` its the best time to fix it  (GCTs which support/consume the parameter in PR)

2022-06-22 12:23 UTC, kyryloonufriiev requested changes
```
test.test.call(utils, {...sdk, config: test.config, env: test.env, meta: test.meta})
```
I think you just need to pass everything from the test object to the test function.

2022-06-22 12:23 UTC, kyryloonufriiev commented on packages/sdk-coverage-tests/src/generate/emit.js
> +  test.vg && (test.config.vg = true)
On a second thought about that, I think this is not right to add custom stuff in the config object.

2022-06-22 18:09 UTC, kyryloonufriiev commented on packages/sdk-coverage-tests/src/generate/emit.js
> +  test.test.call(utils, {...test, ...sdk})
@chaim-aharonson-applitools What do you think? this is what I propose.

2022-06-23 07:43 UTC, chaim-aharonson-applitools commented on packages/sdk-coverage-tests/src/generate/emit.js
> +  test.test.call(utils, {...test, ...sdk})
great, it works perfectly

2022-06-26 07:31 UTC, merged